### ISSUE TITLE
[APP SUBMITTED]: (SyntaxError) invalid syntax (<unknown>, line 1) (u'curUpdate = "<input type=\\"checkbox\\" class=\\"upda') in file '/Applications/SickRage/gui/slick/views/manage.mako' at line: 70 char: 9

### ISSUE THREAD

**Issue by scott451** [SickRage/sickrage-issues#100]
### INFO
Python Version: **2.7.10 (default, Aug 22 2015, 20:33:39) [GCC 4.2.1 Compatible Apple LLVM 7.0.0 (clang-700.0.59.1)]**
Operating System: **Darwin-15.0.0-x86_64-i386-64bit**
Locale: unknown
Branch: **master**
Commit: SickRage/SickRage@1a78faacd22a7eb2e9562ab60e4dc7c50c5f91f0
Link to Log: https://gist.github.com/ccea0dc82a7ae1abb414
### ERROR
```
Thread-56 :: Failed doing webui callback: Traceback (most recent call last):
  File "/Applications/SickRage/sickbeard/webserve.py", line 265, in async_call
    result = function(**kwargs)
  File "/Applications/SickRage/sickbeard/webserve.py", line 2825, in index
    t = PageTemplate(rh=self, filename="manage.mako")
  File "/Applications/SickRage/sickbeard/webserve.py", line 114, in __init__
    self.template = lookup.get_template(filename)
  File "/Applications/SickRage/lib/mako/lookup.py", line 256, in get_template
    return self._load(srcfile, uri)
  File "/Applications/SickRage/lib/mako/lookup.py", line 321, in _load
    **self.template_args)
  File "/Applications/SickRage/lib/mako/template.py", line 322, in __init__
    module = self._compile_from_file(path, filename)
  File "/Applications/SickRage/lib/mako/template.py", line 378, in _compile_from_file
    self.module_writer)
  File "/Applications/SickRage/lib/mako/template.py", line 692, in _compile_module_file
    generate_magic_comment=True)
  File "/Applications/SickRage/lib/mako/template.py", line 657, in _compile
    node = lexer.parse()
  File "/Applications/SickRage/lib/mako/lexer.py", line 245, in parse
    if self.match_python_block():
  File "/Applications/SickRage/lib/mako/lexer.py", line 378, in match_python_block
    match.group(1) == '!', lineno=line, pos=pos)
  File "/Applications/SickRage/lib/mako/lexer.py", line 134, in append_node
    node = nodecls(*args, **kwargs)
  File "/Applications/SickRage/lib/mako/parsetree.py", line 149, in __init__
    self.code = ast.PythonCode(text, **self.exception_kwargs)
  File "/Applications/SickRage/lib/mako/ast.py", line 40, in __init__
    expr = pyparser.parse(code.lstrip(), "exec", **exception_kwargs)
  File "/Applications/SickRage/lib/mako/pyparser.py", line 48, in parse
    ), **exception_kwargs)
SyntaxException: (SyntaxError) invalid syntax (<unknown>, line 1) (u'curUpdate = "<input type=\\"checkbox\\" class=\\"upda') in file '/Applications/SickRage/gui/slick/views/manage.mako' at line: 70 char: 9

```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by scott451** [comment]
### INFO
Python Version: **2.7.10 (default, Aug 22 2015, 20:33:39) [GCC 4.2.1 Compatible Apple LLVM 7.0.0 (clang-700.0.59.1)]**
Operating System: **Darwin-15.0.0-x86_64-i386-64bit**
Locale: unknown
Branch: **master**
Commit: SickRage/SickRage@1a78faacd22a7eb2e9562ab60e4dc7c50c5f91f0
Link to Log: https://gist.github.com/0728c7dc54c469f1f50f
### ERROR
```
Thread-41 :: Failed doing webui callback: Traceback (most recent call last):
  File "/Applications/SickRage/sickbeard/webserve.py", line 265, in async_call
    result = function(**kwargs)
  File "/Applications/SickRage/sickbeard/webserve.py", line 2825, in index
    t = PageTemplate(rh=self, filename="manage.mako")
  File "/Applications/SickRage/sickbeard/webserve.py", line 114, in __init__
    self.template = lookup.get_template(filename)
  File "/Applications/SickRage/lib/mako/lookup.py", line 256, in get_template
    return self._load(srcfile, uri)
  File "/Applications/SickRage/lib/mako/lookup.py", line 321, in _load
    **self.template_args)
  File "/Applications/SickRage/lib/mako/template.py", line 322, in __init__
    module = self._compile_from_file(path, filename)
  File "/Applications/SickRage/lib/mako/template.py", line 378, in _compile_from_file
    self.module_writer)
  File "/Applications/SickRage/lib/mako/template.py", line 692, in _compile_module_file
    generate_magic_comment=True)
  File "/Applications/SickRage/lib/mako/template.py", line 657, in _compile
    node = lexer.parse()
  File "/Applications/SickRage/lib/mako/lexer.py", line 245, in parse
    if self.match_python_block():
  File "/Applications/SickRage/lib/mako/lexer.py", line 378, in match_python_block
    match.group(1) == '!', lineno=line, pos=pos)
  File "/Applications/SickRage/lib/mako/lexer.py", line 134, in append_node
    node = nodecls(*args, **kwargs)
  File "/Applications/SickRage/lib/mako/parsetree.py", line 149, in __init__
    self.code = ast.PythonCode(text, **self.exception_kwargs)
  File "/Applications/SickRage/lib/mako/ast.py", line 40, in __init__
    expr = pyparser.parse(code.lstrip(), "exec", **exception_kwargs)
  File "/Applications/SickRage/lib/mako/pyparser.py", line 48, in parse
    ), **exception_kwargs)
SyntaxException: (SyntaxError) invalid syntax (<unknown>, line 1) (u'curUpdate = "<input type=\\"checkbox\\" class=\\"upda') in file '/Applications/SickRage/gui/slick/views/manage.mako' at line: 70 char: 9

```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by scott451** [comment]
### INFO
Python Version: **2.7.10 (default, Aug 22 2015, 20:33:39) [GCC 4.2.1 Compatible Apple LLVM 7.0.0 (clang-700.0.59.1)]**
Operating System: **Darwin-15.0.0-x86_64-i386-64bit**
Locale: unknown
Branch: **master**
Commit: SickRage/SickRage@1a78faacd22a7eb2e9562ab60e4dc7c50c5f91f0
Link to Log: https://gist.github.com/7dc7a1374f2c300f0114
### ERROR
```
Thread-51 :: Failed doing webui callback: Traceback (most recent call last):
  File "/Applications/SickRage/sickbeard/webserve.py", line 265, in async_call
    result = function(**kwargs)
  File "/Applications/SickRage/sickbeard/webserve.py", line 2825, in index
    t = PageTemplate(rh=self, filename="manage.mako")
  File "/Applications/SickRage/sickbeard/webserve.py", line 114, in __init__
    self.template = lookup.get_template(filename)
  File "/Applications/SickRage/lib/mako/lookup.py", line 256, in get_template
    return self._load(srcfile, uri)
  File "/Applications/SickRage/lib/mako/lookup.py", line 321, in _load
    **self.template_args)
  File "/Applications/SickRage/lib/mako/template.py", line 322, in __init__
    module = self._compile_from_file(path, filename)
  File "/Applications/SickRage/lib/mako/template.py", line 378, in _compile_from_file
    self.module_writer)
  File "/Applications/SickRage/lib/mako/template.py", line 692, in _compile_module_file
    generate_magic_comment=True)
  File "/Applications/SickRage/lib/mako/template.py", line 657, in _compile
    node = lexer.parse()
  File "/Applications/SickRage/lib/mako/lexer.py", line 245, in parse
    if self.match_python_block():
  File "/Applications/SickRage/lib/mako/lexer.py", line 378, in match_python_block
    match.group(1) == '!', lineno=line, pos=pos)
  File "/Applications/SickRage/lib/mako/lexer.py", line 134, in append_node
    node = nodecls(*args, **kwargs)
  File "/Applications/SickRage/lib/mako/parsetree.py", line 149, in __init__
    self.code = ast.PythonCode(text, **self.exception_kwargs)
  File "/Applications/SickRage/lib/mako/ast.py", line 40, in __init__
    expr = pyparser.parse(code.lstrip(), "exec", **exception_kwargs)
  File "/Applications/SickRage/lib/mako/pyparser.py", line 48, in parse
    ), **exception_kwargs)
SyntaxException: (SyntaxError) invalid syntax (<unknown>, line 1) (u'curUpdate = "<input type=\\"checkbox\\" class=\\"upda') in file '/Applications/SickRage/gui/slick/views/manage.mako' at line: 70 char: 9

```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by miigotu** [comment]
Reverted for now, autocapitalize patch will be reapplied after it is fixed. Closing
