### ISSUE TITLE
Unicode issues when snatching and processing

### ISSUE THREAD

**Issue by weevis** [SickRage/sickrage-issues#101]
When searching:
```
Traceback (most recent call last):
  File "/mnt/array1/tmp/SickRage/sickbeard/webserve.py", line 264, in async_call
    result = function(**kwargs)
  File "/mnt/array1/tmp/SickRage/sickbeard/webserve.py", line 2120, in retryEpisode
    ep_obj = self._getEpisode(show, season, episode)
  File "/mnt/array1/tmp/SickRage/sickbeard/webserve.py", line 661, in _getEpisode
    epObj = showObj.getEpisode(int(season), int(episode))
  File "/mnt/array1/tmp/SickRage/sickbeard/tv.py", line 284, in getEpisode
    ep = TVEpisode(self, season, episode)
  File "/mnt/array1/tmp/SickRage/sickbeard/tv.py", line 1371, in __init__
    self.checkForMetaFiles()
  File "/mnt/array1/tmp/SickRage/sickbeard/tv.py", line 1459, in checkForMetaFiles
    new_result = cur_provider._has_episode_metadata(self)
  File "/mnt/array1/tmp/SickRage/sickbeard/metadata/generic.py", line 130, in _has_episode_metadata
    return self._check_exists(self.get_episode_file_path(ep_obj))
  File "/mnt/array1/tmp/SickRage/sickbeard/metadata/generic.py", line 121, in _check_exists
    result = os.path.isfile(location)
  File "/opt/lib/python2.7/genericpath.py", line 37, in isfile
    st = os.stat(path)
UnicodeEncodeError: 'ascii' codec can't encode character u'\u2019' in position 80: ordinal not in range(128)
```

```
When Post Processing:
ERROR    Thread-22 :: Failed doing webui callback: Traceback (most recent call last):
  File "/mnt/array1/tmp/SickRage/sickbeard/webserve.py", line 263, in async_call
    result = function(**kwargs)
  File "/mnt/array1/tmp/SickRage/sickbeard/webserve.py", line 2211, in processEpisode
    is_priority=argToBool(is_priority), delete_on=argToBool(delete_on), failed=argToBool(failed), proc_type=type
  File "/mnt/array1/tmp/SickRage/sickbeard/processTV.py", line 271, in processDir
    process_media(processPath, videoFiles, nzbName, process_method, force, is_priority, result)
  File "/mnt/array1/tmp/SickRage/sickbeard/processTV.py", line 550, in process_media
    result.result = processor.process()
  File "/mnt/array1/tmp/SickRage/sickbeard/postProcessor.py", line 1073, in process
    sickbeard.USE_SUBTITLES and ep_obj.show.subtitles)
  File "/mnt/array1/tmp/SickRage/sickbeard/postProcessor.py", line 361, in _move
    subtitles=subtitles)
  File "/mnt/array1/tmp/SickRage/sickbeard/postProcessor.py", line 338, in _combined_file_operation
    action(cur_file_path, new_file_path)
  File "/mnt/array1/tmp/SickRage/sickbeard/postProcessor.py", line 355, in _int_move
    helpers.chmodAsParent(new_file_path)
  File "/mnt/array1/tmp/SickRage/sickbeard/helpers.py", line 750, in chmodAsParent
    childPathStat = os.stat(childPath)
UnicodeEncodeError: 'ascii' codec can't encode character u'\u2019' in position 74: ordinal not in range(128)
```

**Comment by OmgImAlexis** [comment]
Duplicate: https://github.com/SickRage/sickrage-issues/issues/12

Please use the submit issue button within SickRage next time.
