### ISSUE TITLE
Found but no download.

### ISSUE THREAD

**Issue by lmctheboss** [SickRage/sickrage-issues#1014]
Suddenly, my SR doesnt download anything. I try manual search and this is the log:
```
2016-02-18 02:09:21 INFO     SEARCHQUEUE-MANUAL-292147 :: Downloading Bajo.Sospecha.-.Temporada.2.720p.HDTV.x264[Cap.206]SPANISH.AUDIO-NEWPCT from Newpct
2016-02-18 02:09:21 INFO     SEARCHQUEUE-MANUAL-292147 :: [Newpct] :: Quality of Bajo.Sospecha.-.Temporada.2.720p.HDTV.x264[Cap.206]SPANISH.AUDIO-NEWPCT is 720p HDTV
2016-02-18 02:09:08 INFO     SEARCHQUEUE-MANUAL-292147 :: [Newpct] :: Performing episode search for Bajo Sospecha
2016-02-18 02:09:08 INFO     SEARCHQUEUE-MANUAL-292147 :: Beginning manual search for: [Bajo Sospecha - S02E06 - La cartera]
```
But nothing download.

Thanks.

**Comment by SickRage2** [comment]
Thanks for the issue report! Before a real human comes by, please make sure your report has all the below criteria checked

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [x] Post debug logs, either inline (for smaller logs) or using gist
- [ ] Please wrap inline logs inside \`\`\` and \`\`\` for readability

Please make sure you also read [how to create an issue](https://github.com/SickRage/sickrage-issues/blob/master/README.md) and followed all of the steps. 

The title should describe your issue. Having "SR not working" or "I get this bug" for 100 issues, isn't really helpful. We will close issues if there isn't enough information.

Sometimes the devs may seem like grunts and respond with short answers. This isn't (always) because the dev hates you, but because he's on mobile or busy fixing bugs. If something isn't clear, please let us know, and this bot may get updated to automatically answer you.

Thanks!

**Comment by duramato** [comment]
Debug logs? And SR commit

**Comment by lmctheboss** [comment]
SickRage Info:	Branch: master
Commit: 8695768ddc77b28c451bcd7b6f2f0fbbc299bd46
Version: 2016.02.16-1
 Python Version:	2.7.10 (default, May 23 2015, 09:44:00) [MSC v.1500 64 bit (AMD64)]
 SSL Version:	OpenSSL 1.0.2a 19 Mar 2015
 OS:	Windows-8-6.2.9200
 Locale:	es_ES.cp1252

**Comment by duramato** [comment]
Can you post the debug logs?

**Comment by lmctheboss** [comment]
Log.


[sickrage.docx](https://github.com/SickRage/sickrage-issues/files/135497/sickrage.docx)

**Comment by lmctheboss** [comment]
Where i can find?

**Comment by duramato** [comment]
```
016-02-18 02:09:21 DEBUG    SEARCHQUEUE-MANUAL-292147 :: [Newpct] :: The highest quality of any match is 720p HDTV
2016-02-18 02:09:21 DEBUG    SEARCHQUEUE-MANUAL-292147 :: [Newpct] :: Picking the best result out of [u'Bajo.Sospecha.-.Temporada.2.720p.HDTV.x264[Cap.206]SPANISH.AUDIO-NEWPCT']
2016-02-18 02:09:21 INFO     SEARCHQUEUE-MANUAL-292147 :: [Newpct] :: Quality of Bajo.Sospecha.-.Temporada.2.720p.HDTV.x264[Cap.206]SPANISH.AUDIO-NEWPCT is 720p HDTV
2016-02-18 02:09:21 DEBUG    SEARCHQUEUE-MANUAL-292147 :: [Newpct] :: Picked Bajo.Sospecha.-.Temporada.2.720p.HDTV.x264[Cap.206]SPANISH.AUDIO-NEWPCT as the best
2016-02-18 02:09:21 DEBUG    SEARCHQUEUE-MANUAL-292147 :: [Newpct] :: Checking if we should keep searching after we've found Bajo.Sospecha.-.Temporada.2.720p.HDTV.x264[Cap.206]SPANISH.AUDIO-NEWPCT
2016-02-18 02:09:21 INFO     SEARCHQUEUE-MANUAL-292147 :: Downloading Bajo.Sospecha.-.Temporada.2.720p.HDTV.x264[Cap.206]SPANISH.AUDIO-NEWPCT from Newpct
2016-02-18 02:09:22 DEBUG    SEARCHQUEUE-MANUAL-292147 :: Traceback (most recent call last):
  File "C:\SickRage\sickbeard\search_queue.py", line 184, in run
    self.success = search.snatchEpisode(searchResult[0])
  File "C:\SickRage\sickbeard\search.py", line 139, in snatchEpisode
    result.content = result.provider.get_url(result.url, need_bytes=True)
  File "C:\SickRage\sickbeard\providers\newpct.py", line 164, in get_url
    data = helpers.getURL(url, headers=self.headers, timeout=timeout, session=self.session, returns='json')
  File "C:\SickRage\sickbeard\helpers.py", line 1481, in getURL
    return resp if response_type == u'response' or response_type is None else resp.json() if response_type == u'json' else getattr(resp, response_type, resp)
  File "C:\SickRage\lib\requests\models.py", line 805, in json
    return complexjson.loads(self.text, **kwargs)
  File "C:\SickRage\lib\simplejson\__init__.py", line 307, in loads
    return _default_decoder.decode(s)
  File "C:\SickRage\lib\simplejson\decoder.py", line 335, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\SickRage\lib\simplejson\decoder.py", line 353, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
```

**Comment by mikerohan** [comment]
Same issue here:

SickRage Info: 	Branch: master
Commit: 8695768ddc77b28c451bcd7b6f2f0fbbc299bd46
Version: 2016.02.16-1
Python Version:	2.7.11 (default, Jan 9 2016, 16:55:40) [GCC 4.8.5]

`2016-02-18 11:00:46 DEBUG    SEARCHQUEUE-MANUAL-292262 :: [Newpct] :: Picking the best result out of [u'El.Ministerio.Del.Tiempo.-.Temporada.2.720p.HDTV.x264[Cap.201]SPANISH.AUDIO-NEWPCT']
2016-02-18 11:00:46 INFO     SEARCHQUEUE-MANUAL-292262 :: [Newpct] :: Quality of El.Ministerio.Del.Tiempo.-.Temporada.2.720p.HDTV.x264[Cap.201]SPANISH.AUDIO-NEWPCT is 720p HDTV
2016-02-18 11:00:46 DEBUG    SEARCHQUEUE-MANUAL-292262 :: [Newpct] :: Picked El.Ministerio.Del.Tiempo.-.Temporada.2.720p.HDTV.x264[Cap.201]SPANISH.AUDIO-NEWPCT as the best
2016-02-18 11:00:46 DEBUG    SEARCHQUEUE-MANUAL-292262 :: [Newpct] :: Checking if we should keep searching after we've found El.Ministerio.Del.Tiempo.-.Temporada.2.720p.HDTV.x264[Cap.201]SPANISH.AUDIO-NEWPCT
2016-02-18 11:00:46 INFO     SEARCHQUEUE-MANUAL-292262 :: Downloading El.Ministerio.Del.Tiempo.-.Temporada.2.720p.HDTV.x264[Cap.201]SPANISH.AUDIO-NEWPCT from Newpct
2016-02-18 11:00:47 DEBUG    SEARCHQUEUE-MANUAL-292262 :: Traceback (most recent call last):
  File "/share/CACHEDEV1_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/sickbeard/search_queue.py", line 184, in run
    self.success = search.snatchEpisode(searchResult[0])
  File "/share/CACHEDEV1_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/sickbeard/search.py", line 139, in snatchEpisode
    result.content = result.provider.get_url(result.url, need_bytes=True)
  File "/share/CACHEDEV1_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/sickbeard/providers/newpct.py", line 164, in get_url
    data = helpers.getURL(url, headers=self.headers, timeout=timeout, session=self.session, returns='json')
  File "/share/CACHEDEV1_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/sickbeard/helpers.py", line 1481, in getURL
    return resp if response_type == u'response' or response_type is None else resp.json() if response_type == u'json' else getattr(resp, response_type, resp)
  File "/share/CACHEDEV1_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/lib/requests/models.py", line 805, in json
    return complexjson.loads(self.text, **kwargs)
  File "/share/CACHEDEV1_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/lib/simplejson/__init__.py", line 307, in loads
    return _default_decoder.decode(s)
  File "/share/CACHEDEV1_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/lib/simplejson/decoder.py", line 335, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/share/CACHEDEV1_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/lib/simplejson/decoder.py", line 353, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded`

**Comment by duramato** [comment]
Can you guys try the newpct branch and see if it fixes it?

**Comment by lmctheboss** [comment]
I dont know what you mean, sorry.

**Comment by mikerohan** [comment]
Switched to newpct branch and it works!

do you need any logs?

**Comment by duramato** [comment]
Cool
And dont need any logs

**Comment by lmctheboss** [comment]
Can you explain me what i have to do?
Sorry.
Thanks a lot.

**Comment by fernandog** [comment]
nothing. just wait

**Comment by lmctheboss** [comment]
Ok. Thanks.

**Comment by fernandog** [comment]
fixed in develop. wait to be on master

**Comment by lmctheboss** [comment]
All is working again!!!!!!
Thanks a lot.
