### ISSUE TITLE
[APP SUBMITTED]: unsupported operand type(s) for +=: 'exceptions.OSError' and 'unicode'

### ISSUE THREAD

**Issue by duramato** [SickRage/sickrage-issues#1042]
### INFO
Python Version: **2.7.6 (default, Jun 22 2015, 18:00:18) [GCC 4.8.2]**
Operating System: **Linux-3.19.0-49-generic-i686-with-Ubuntu-14.04-trusty**
Locale: None
Branch: **you-shall-not-password!**
Commit: SickRage/SickRage@fa5f2854d37552b9f8d98b18b81c71ec0ca113e7
Link to Log: https://gist.github.com/ab5f1eb07509cbb99cef
### ERROR
```
POSTPROCESSER :: Exception generated in thread POSTPROCESSER: unsupported operand type(s) for +=: 'exceptions.OSError' and 'unicode' [fa5f285]
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by SickRage2** [comment]
Thanks for the issue report! Before a real human comes by, please make sure your report has all the below criteria checked

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [x] Post debug logs, either inline (for smaller logs) or using gist

Please make sure you also read [how to create an issue](https://github.com/SickRage/sickrage-issues/blob/master/README.md) and followed all of the steps. 

The title should describe your issue. Having "SR not working" or "I get this bug" for 100 issues, isn't really helpful. We will close issues if there isn't enough information.

Sometimes the devs may seem like grunts and respond with short answers. This isn't (always) because the dev hates you, but because he's on mobile or busy fixing bugs. If something isn't clear, please let us know, and this bot may get updated to automatically answer you.

Thanks!

**Comment by duramato** [comment]
```
AATypeError: unsupported operand type(s) for +=: 'exceptions.OSError' and 'unicode'
AA    msg += ' [%s]' % sickbeard.CUR_COMMIT_HASH[:7]
AA  File "/home/home/SickRage/sickbeard/logger.py", line 200, in log
AA    logger.log(error, logger.ERROR)
AA  File "/home/home/SickRage/sickbeard/helpers.py", line 358, in copyFile
AA    copyFile(srcFile, destFile)
AA  File "/home/home/SickRage/sickbeard/helpers.py", line 412, in hardlinkFile
AA    helpers.hardlinkFile(cur_file_path, new_file_path)
AA  File "/home/home/SickRage/sickbeard/postProcessor.py", line 444, in _int_hard_link
AA    action(cur_file_path, new_file_path)
AA  File "/home/home/SickRage/sickbeard/postProcessor.py", line 382, in _combined_file_operation
AA    self._combined_file_operation(file_path, new_path, new_base_name, associated_files, action=_int_hard_link, subtitles=subtitles)
AA  File "/home/home/SickRage/sickbeard/postProcessor.py", line 450, in _hardlink
AA    sickbeard.USE_SUBTITLES and ep_obj.show.subtitles)
AA  File "/home/home/SickRage/sickbeard/postProcessor.py", line 1135, in process
AA    result.result = processor.process()
AA  File "/home/home/SickRage/sickbeard/processTV.py", line 556, in process_media
AA    process_media(path, [video], nzbName, process_method, force, is_priority, result)
AA  File "/home/home/SickRage/sickbeard/processTV.py", line 230, in processDir
AA    processTV.processDir(sickbeard.TV_DOWNLOAD_DIR, force=force)
AA  File "/home/home/SickRage/sickbeard/auto_postprocessor.py", line 56, in run
AA    self.action.run(self.force)
AA  File "/home/home/SickRage/sickbeard/scheduler.py", line 106, in run
AATraceback (most recent call last):
2016-02-22 13:17:02 ERROR    POSTPROCESSER :: Exception generated in thread POSTPROCESSER: unsupported operand type(s) for +=: 'exceptions.OSError' and 'unicode' [fa5f285]
```
