### ISSUE TITLE
[APP SUBMITTED]: 'NoneType' object has no attribute 'whitelist'

### ISSUE THREAD

**Issue by ejseguinte** [SickRage/sickrage-issues#1043]
### INFO
Python Version: **2.7.10 (default, May 23 2015, 09:40:32) [MSC v.1500 32 bit (Intel)]**
Operating System: **Windows-8-6.2.9200**
Locale: cp1252
Branch: **master**
Commit: SickRage/SickRage@26ddbf4b882c293c187fe3ec88dd6e826eeed7a7
No Log available with ERRORS:
### ERROR
```
Thread-51 :: Failed doing webui callback: Traceback (most recent call last):
  File "C:\SickRage\sickbeard\webserve.py", line 283, in async_call
    result = function(**kwargs)
  File "C:\SickRage\sickbeard\webserve.py", line 1422, in editShow
    whitelist = showObj.release_groups.whitelist
AttributeError: 'NoneType' object has no attribute 'whitelist'
 [26ddbf4]
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by SickRage2** [comment]
Thanks for the issue report! Before a real human comes by, please make sure your report has all the below criteria checked

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [ ] Post debug logs, either inline (for smaller logs) or using gist

Please make sure you also read [how to create an issue](https://github.com/SickRage/sickrage-issues/blob/master/README.md) and followed all of the steps. 

The title should describe your issue. Having "SR not working" or "I get this bug" for 100 issues, isn't really helpful. We will close issues if there isn't enough information.

Sometimes the devs may seem like grunts and respond with short answers. This isn't (always) because the dev hates you, but because he's on mobile or busy fixing bugs. If something isn't clear, please let us know, and this bot may get updated to automatically answer you.

Thanks!

**Comment by neoatomic** [comment]
Could you include a (debug) log.? The error doesn't provide enough info.:(

**Comment by ejseguinte** [comment]
I was able to resolve the issue by forcing an update.
