### ISSUE TITLE
[APP SUBMITTED]: unsupported operand type(s) for +=: 'Error' and 'unicode'

### ISSUE THREAD

**Issue by Tulexi** [SickRage/sickrage-issues#1046]
### INFO
Python Version: **2.7.9 (default, Dec 13 2014, 18:02:08) [GCC]**
Operating System: **Linux-4.1.15-8-default-x86_64-with-SuSE-42.1-x86_64**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@06cc9277398bc1814796f5b5b985b7f5c772f4e6
Link to Log: https://gist.github.com/4dfa9ad7f8a47f22eedc
### ERROR
```
POSTPROCESSER :: Exception generated in thread POSTPROCESSER: unsupported operand type(s) for +=: 'Error' and 'unicode' [06cc927]
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by SickRage2** [comment]
Thanks for the issue report! Before a real human comes by, please make sure your report has all the below criteria checked

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [x] Post debug logs, either inline (for smaller logs) or using gist

Please make sure you also read [how to create an issue](https://github.com/SickRage/sickrage-issues/blob/master/README.md) and followed all of the steps. 

The title should describe your issue. Having "SR not working" or "I get this bug" for 100 issues, isn't really helpful. We will close issues if there isn't enough information.

Sometimes the devs may seem like grunts and respond with short answers. This isn't (always) because the dev hates you, but because he's on mobile or busy fixing bugs. If something isn't clear, please let us know, and this bot may get updated to automatically answer you.

Thanks!

**Comment by miigotu** [comment]
Need the full log that shows the traceback please, thanks

**Comment by Tulexi** [comment]
Ah I assumed it included the complete log, had SickRage send it in before I left for work so didn't check it. My apologies.

This is the debug log when at the point it fails.

```
2016-02-23 19:29:59 DEBUG    POSTPROCESSER :: 'Traceback (most recent call last):\n  File "/home/******/.sickrage/sickbeard/scheduler.py", line 106, in run\n    self.action.run(self.force)\n  File "/home/******/.sickrage/sickbeard/auto_postprocessor.py", line 56, in run\n    processTV.processDir(sickbeard.TV_DOWNLOAD_DIR, force=force)\n  File "/home/******/.sickrage/sickbeard/processTV.py", line 156, in func_wrapper\n    ret = func(*args, **kargs)\n  File "/home/******/.sickrage/sickbeard/processTV.py", line 249, in processDir\n    process_media(path, [video], nzbName, process_method, force, is_priority, result)\n  File "/home/******/.sickrage/sickbeard/processTV.py", line 575, in process_media\n    result.result = processor.process()\n  File "/home/******/.sickrage/sickbeard/postProcessor.py", line 1135, in process\n    sickbeard.USE_SUBTITLES and ep_obj.show.subtitles)\n  File "/home/******/.sickrage/sickbeard/postProcessor.py", line 450, in _hardlink\n    self._combined_file_operation(file_path, new_path, new_base_name, associated_files, action=_int_hard_link, subtitles=subtitles)\n  File "/home/******/.sickrage/sickbeard/postProcessor.py", line 382, in _combined_file_operation\n    action(cur_file_path, new_file_path)\n  File "/home/******/.sickrage/sickbeard/postProcessor.py", line 444, in _int_hard_link\n    helpers.hardlinkFile(cur_file_path, new_file_path)\n  File "/home/******/.sickrage/sickbeard/helpers.py", line 412, in hardlinkFile\n    copyFile(srcFile, destFile)\n  File "/home/******/.sickrage/sickbeard/helpers.py", line 356, in copyFile\n    logger.log(error, logger.WARNING)\n  File "/home/******/.sickrage/sickbeard/logger.py", line 200, in log\n    msg += \' [%s]\' % sickbeard.CUR_COMMIT_HASH[:7]\nTypeError: unsupported operand type(s) for +=: \'Error\' and \'unicode\'\n'
AATypeError: unsupported operand type(s) for +=: 'Error' and 'unicode'
AA    msg += ' [%s]' % sickbeard.CUR_COMMIT_HASH[:7]
AA  File "/home/******/.sickrage/sickbeard/logger.py", line 200, in log
AA    logger.log(error, logger.WARNING)
AA  File "/home/******/.sickrage/sickbeard/helpers.py", line 356, in copyFile
AA    copyFile(srcFile, destFile)
AA  File "/home/******/.sickrage/sickbeard/helpers.py", line 412, in hardlinkFile
AA    helpers.hardlinkFile(cur_file_path, new_file_path)
AA  File "/home/******/.sickrage/sickbeard/postProcessor.py", line 444, in _int_hard_link
AA    action(cur_file_path, new_file_path)
AA  File "/home/******/.sickrage/sickbeard/postProcessor.py", line 382, in _combined_file_operation
AA    self._combined_file_operation(file_path, new_path, new_base_name, associated_files, action=_int_hard_link, subtitles=subtitles)
AA  File "/home/******/.sickrage/sickbeard/postProcessor.py", line 450, in _hardlink
AA    sickbeard.USE_SUBTITLES and ep_obj.show.subtitles)
AA  File "/home/******/.sickrage/sickbeard/postProcessor.py", line 1135, in process
AA    result.result = processor.process()
AA  File "/home/******/.sickrage/sickbeard/processTV.py", line 575, in process_media
AA    process_media(path, [video], nzbName, process_method, force, is_priority, result)
AA  File "/home/******/.sickrage/sickbeard/processTV.py", line 249, in processDir
AA    ret = func(*args, **kargs)
AA  File "/home/******/.sickrage/sickbeard/processTV.py", line 156, in func_wrapper
AA    processTV.processDir(sickbeard.TV_DOWNLOAD_DIR, force=force)
AA  File "/home/******/.sickrage/sickbeard/auto_postprocessor.py", line 56, in run
AA    self.action.run(self.force)
AA  File "/home/******/.sickrage/sickbeard/scheduler.py", line 106, in run
AATraceback (most recent call last):
2016-02-23 19:29:59 ERROR    POSTPROCESSER :: Exception generated in thread POSTPROCESSER: unsupported operand type(s) for +=: 'Error' and 'unicode' [06cc927]
2016-02-23 19:29:59 WARNING  POSTPROCESSER :: Failed to create hardlink of /Downloads/Torrents/SickRage/[HorribleSubs] Osomatsu-san - 20 [1080p].mkv at /Downloads/TV_Jap/Mr. Osomatsu/Mr. Osomatsu - 020 - Teach Me, Hatabou - School Master - Iyami's School 1080p HDTV HorribleSubs.mkv. Error: u'error 17 : File exists'. Copying instead [06cc927]
2016-02-23 19:29:59 DEBUG    POSTPROCESSER :: Hard linking file from /Downloads/Torrents/SickRage/[HorribleSubs] Osomatsu-san - 20 [1080p].mkv to /Downloads/TV_Jap/Mr. Osomatsu/Mr. Osomatsu - 020 - Teach Me, Hatabou - School Master - Iyami's School 1080p HDTV HorribleSubs.mkv
2016-02-23 19:29:59 DEBUG    POSTPROCESSER :: No associated files for /Downloads/Torrents/SickRage/[HorribleSubs] Osomatsu-san - 20 [1080p].mkv were found during this pass
2016-02-23 19:29:59 DEBUG    POSTPROCESSER :: Checking if the path /Downloads/TV_Jap/Mr. Osomatsu already exists
2016-02-23 19:29:59 DEBUG    POSTPROCESSER :: Destination folder for this episode: /Downloads/TV_Jap/Mr. Osomatsu
2016-02-23 19:29:59 DEBUG    POSTPROCESSER :: formatting pattern: /Downloads/TV_Jap/%SN -> /Downloads/TV_Jap/Mr. Osomatsu
2016-02-23 19:29:59 DEBUG    POSTPROCESSER :: Using cached parse result for: [HorribleSubs] Osomatsu-san - 20 [1080p]
2016-02-23 19:29:59 DEBUG    POSTPROCESSER :: formatting pattern: %SN - S%0SE%0E - %EN %QN %RG -> Mr. Osomatsu - 020 - Teach Me, Hatabou - School Master - Iyami's School 1080p HDTV HorribleSubs
2016-02-23 19:29:59 DEBUG    POSTPROCESSER :: Using cached parse result for: [HorribleSubs] Osomatsu-san - 20 [1080p]
2016-02-23 19:29:59 DEBUG    POSTPROCESSER :: Folder name (SickRage) appears to be a valid release name. Using it.
2016-02-23 19:29:58 DEBUG    POSTPROCESSER :: Found release name [HorribleSubs] Osomatsu-san - 20 [1080p]
2016-02-23 19:29:58 DEBUG    POSTPROCESSER :: Trying to determine free space on destination drive
2016-02-23 19:29:58 DEBUG    POSTPROCESSER :: There is no existing file so there's no worries about replacing it
2016-02-23 19:29:58 DEBUG    POSTPROCESSER :: Is ep a priority download: False
2016-02-23 19:29:58 DEBUG    POSTPROCESSER :: Quality of the episode we're processing: 1080p HDTV
2016-02-23 19:29:58 DEBUG    POSTPROCESSER :: Snatch history had a quality in it, using that: 1080p HDTV
2016-02-23 19:29:58 DEBUG    POSTPROCESSER :: Retrieving episode object for 1x20
2016-02-23 19:29:58 DEBUG    POSTPROCESSER :: Parsed [HorribleSubs] Osomatsu-san - 20 [1080p] into Osomatsu-san - S01E20 [ABS: [20]] [ANIME VER: 1] [GROUP: HorribleSubs] [ABD: False] [ANIME: True] [whichReg: ['anime_horriblesubs']]
2016-02-23 19:29:58 DEBUG    POSTPROCESSER :: Found episode by absolute number 20 which is S01E20
2016-02-23 19:29:58 DEBUG    POSTPROCESSER :: Analyzing name [HorribleSubs] Osomatsu-san - 20 [1080p].mkv
2016-02-23 19:29:58 INFO     POSTPROCESSER :: Processing /Downloads/Torrents/SickRage/[HorribleSubs] Osomatsu-san - 20 [1080p].mkv (None)
2016-02-23 19:29:58 DEBUG    POSTPROCESSER :: Skipping already processed file: [HorribleSubs] Black Bullet - 08 [1080p].mkv
2016-02-23 19:29:58 DEBUG    POSTPROCESSER :: Skipping already processed file: [HorribleSubs] Charlotte - 09 [1080p].mkv
```
