### ISSUE TITLE
[APP SUBMITTED]: near "WHERE": syntax error

### ISSUE THREAD

**Issue by mchrisley** [SickRage/sickrage-issues#1048]
### INFO
Python Version: **2.7.11 (default, Dec 17 2015, 15:58:38) [GCC 4.7.3 20130102 (prerelease)]**
Operating System: **Linux-3.10.35-x86_64-with-glibc2.2.5**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@df65bfb01fd667441592932068a76a6bfb9b954f
Link to Log: https://gist.github.com/696b989c2808fc8d003d
### ERROR
```
Thread-21 :: DB error: near "WHERE": syntax error [df65bfb]
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by SickRage2** [comment]
Thanks for the issue report! Before a real human comes by, please make sure your report has all the below criteria checked

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [x] Post debug logs, either inline (for smaller logs) or using gist

Please make sure you also read [how to create an issue](https://github.com/SickRage/sickrage-issues/blob/master/README.md) and followed all of the steps. 

The title should describe your issue. Having "SR not working" or "I get this bug" for 100 issues, isn't really helpful. We will close issues if there isn't enough information.

Sometimes the devs may seem like grunts and respond with short answers. This isn't (always) because the dev hates you, but because he's on mobile or busy fixing bugs. If something isn't clear, please let us know, and this bot may get updated to automatically answer you.

Thanks!

**Comment by mchrisley** [comment]
### INFO
Python Version: **2.7.11 (default, Dec 17 2015, 15:58:38) [GCC 4.7.3 20130102 (prerelease)]**
Operating System: **Linux-3.10.35-x86_64-with-glibc2.2.5**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@df65bfb01fd667441592932068a76a6bfb9b954f
Link to Log: https://gist.github.com/55a445bb244814e5439a
### ERROR
```
Thread-21 :: Failed doing webui callback: Traceback (most recent call last):
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/webserve.py", line 283, in async_call
    result = function(**kwargs)
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/webserve.py", line 3425, in massEditSubmit
    directCall=True)
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/webserve.py", line 1557, in editShow
    showObj.saveToDB()
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/tv.py", line 1166, in saveToDB
    main_db_con.upsert("imdb_info", newValueDict, controlValueDict)
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/db.py", line 323, in upsert
    self.action(query, valueDict.values() + keyDict.values())
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/db.py", line 254, in action
    sql_results = self._execute(query, args, fetchall=fetchall, fetchone=fetchone)
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/db.py", line 108, in _execute
    sql_results = self.connection.cursor().execute(query, args)
OperationalError: near "WHERE": syntax error
 [df65bfb]
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by mchrisley** [comment]
### INFO
Python Version: **2.7.11 (default, Dec 17 2015, 15:58:38) [GCC 4.7.3 20130102 (prerelease)]**
Operating System: **Linux-3.10.35-x86_64-with-glibc2.2.5**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@df65bfb01fd667441592932068a76a6bfb9b954f
Link to Log: https://gist.github.com/dcc3260260ff46e24b7b
### ERROR
```
Thread-15 :: DB error: near "WHERE": syntax error [df65bfb]
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by mchrisley** [comment]
### INFO
Python Version: **2.7.11 (default, Dec 17 2015, 15:58:38) [GCC 4.7.3 20130102 (prerelease)]**
Operating System: **Linux-3.10.35-x86_64-with-glibc2.2.5**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@df65bfb01fd667441592932068a76a6bfb9b954f
Link to Log: https://gist.github.com/13be880d651a87d058ce
### ERROR
```
Thread-15 :: Failed doing webui callback: Traceback (most recent call last):
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/webserve.py", line 283, in async_call
    result = function(**kwargs)
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/webserve.py", line 3425, in massEditSubmit
    directCall=True)
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/webserve.py", line 1557, in editShow
    showObj.saveToDB()
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/tv.py", line 1166, in saveToDB
    main_db_con.upsert("imdb_info", newValueDict, controlValueDict)
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/db.py", line 323, in upsert
    self.action(query, valueDict.values() + keyDict.values())
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/db.py", line 254, in action
    sql_results = self._execute(query, args, fetchall=fetchall, fetchone=fetchone)
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/db.py", line 108, in _execute
    sql_results = self.connection.cursor().execute(query, args)
OperationalError: near "WHERE": syntax error
 [df65bfb]
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by mchrisley** [comment]
### INFO
Python Version: **2.7.11 (default, Dec 17 2015, 15:58:38) [GCC 4.7.3 20130102 (prerelease)]**
Operating System: **Linux-3.10.35-x86_64-with-glibc2.2.5**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@df65bfb01fd667441592932068a76a6bfb9b954f
Link to Log: https://gist.github.com/f5ad7d3336a2864cd78f
### ERROR
```
Thread-33 :: DB error: near "WHERE": syntax error [df65bfb]
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by mchrisley** [comment]
### INFO
Python Version: **2.7.11 (default, Dec 17 2015, 15:58:38) [GCC 4.7.3 20130102 (prerelease)]**
Operating System: **Linux-3.10.35-x86_64-with-glibc2.2.5**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@df65bfb01fd667441592932068a76a6bfb9b954f
Link to Log: https://gist.github.com/029f05930ce31c376474
### ERROR
```
Thread-33 :: Failed doing webui callback: Traceback (most recent call last):
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/webserve.py", line 283, in async_call
    result = function(**kwargs)
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/webserve.py", line 3425, in massEditSubmit
    directCall=True)
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/webserve.py", line 1557, in editShow
    showObj.saveToDB()
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/tv.py", line 1166, in saveToDB
    main_db_con.upsert("imdb_info", newValueDict, controlValueDict)
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/db.py", line 323, in upsert
    self.action(query, valueDict.values() + keyDict.values())
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/db.py", line 254, in action
    sql_results = self._execute(query, args, fetchall=fetchall, fetchone=fetchone)
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/db.py", line 108, in _execute
    sql_results = self.connection.cursor().execute(query, args)
OperationalError: near "WHERE": syntax error
 [df65bfb]
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by mchrisley** [comment]
### INFO
Python Version: **2.7.11 (default, Dec 17 2015, 15:58:38) [GCC 4.7.3 20130102 (prerelease)]**
Operating System: **Linux-3.10.35-x86_64-with-glibc2.2.5**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@df65bfb01fd667441592932068a76a6bfb9b954f
Link to Log: https://gist.github.com/f727b310a496a57eca66
### ERROR
```
Thread-39 :: DB error: near "WHERE": syntax error [df65bfb]
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by mchrisley** [comment]
### INFO
Python Version: **2.7.11 (default, Dec 17 2015, 15:58:38) [GCC 4.7.3 20130102 (prerelease)]**
Operating System: **Linux-3.10.35-x86_64-with-glibc2.2.5**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@df65bfb01fd667441592932068a76a6bfb9b954f
Link to Log: https://gist.github.com/d6c3c198e61592a5aa20
### ERROR
```
Thread-39 :: Failed doing webui callback: Traceback (most recent call last):
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/webserve.py", line 283, in async_call
    result = function(**kwargs)
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/webserve.py", line 3425, in massEditSubmit
    directCall=True)
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/webserve.py", line 1557, in editShow
    showObj.saveToDB()
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/tv.py", line 1166, in saveToDB
    main_db_con.upsert("imdb_info", newValueDict, controlValueDict)
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/db.py", line 323, in upsert
    self.action(query, valueDict.values() + keyDict.values())
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/db.py", line 254, in action
    sql_results = self._execute(query, args, fetchall=fetchall, fetchone=fetchone)
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/db.py", line 108, in _execute
    sql_results = self.connection.cursor().execute(query, args)
OperationalError: near "WHERE": syntax error
 [df65bfb]
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by MattPark** [comment]
same issue --- looks like it happens on shutdown?

```
2017-03-13 18:32:01 INFO SEARCHQUEUE-BACKLOG-78419 :: [DOGnzb] :: Daily API limit of 50 hits reached
2017-03-13 18:31:59 INFO SEARCHQUEUE-BACKLOG-78419 :: [DOGnzb] :: Daily API limit of 50 hits reached
2017-03-13 18:31:56 INFO SEARCHQUEUE-BACKLOG-78419 :: [DOGnzb] :: Daily API limit of 50 hits reached
2017-03-13 18:31:54 INFO SEARCHQUEUE-BACKLOG-78419 :: [DOGnzb] :: Daily API limit of 50 hits reached
2017-03-13 18:31:52 INFO SEARCHQUEUE-BACKLOG-78419 :: [DOGnzb] :: Daily API limit of 50 hits reached
AA OperationalError: near "WHERE": syntax error
AA sql_results = self.connection.cursor().execute(query, args)
AA File "/app/sickrage/sickbeard/db.py", line 113, in _execute
AA sql_results = self._execute(query, args, fetchall=fetchall, fetchone=fetchone)
AA File "/app/sickrage/sickbeard/db.py", line 262, in action
AA self.action(query, list(valueDict.values()) + keyDict.values())
AA File "/app/sickrage/sickbeard/db.py", line 331, in upsert
AA main_db_con.upsert("imdb_info", newValueDict, controlValueDict)
AA File "/app/sickrage/sickbeard/tv.py", line 1173, in saveToDB
AA show.saveToDB()
AA File "/app/sickrage/sickbeard/__init__.py", line 1735, in saveAll
AA sickbeard.saveAll() # save all shows to DB
AA File "/app/sickrage/SickBeard.py", line 447, in shutdown
AA self.callback(type)
AA File "/app/sickrage/sickbeard/event_queue.py", line 47, in run
AA Traceback (most recent call last):
2017-03-13 18:31:51 ERROR EVENT-QUEUE :: [edc61ac] Exception generated in thread EVENT-QUEUE: near "WHERE": syntax error
AA OperationalError: near "WHERE": syntax error
AA sql_results = self.connection.cursor().execute(query, args)
AA File "/app/sickrage/sickbeard/db.py", line 113, in _execute
AA sql_results = self._execute(query, args, fetchall=fetchall, fetchone=fetchone)
AA File "/app/sickrage/sickbeard/db.py", line 262, in action
AA Traceback (most recent call last):
2017-03-13 18:31:51 ERROR EVENT-QUEUE :: [edc61ac] DB error: near "WHERE": syntax error
2017-03-13 18:31:51 INFO EVENT-QUEUE :: Saving all shows to the database
2017-03-13 18:31:51 INFO EVENT-QUEUE :: Waiting for the EVENT-QUEUE thread to exit
2017-03-13 18:31:51 INFO EVENT-QUEUE :: Waiting for the FINDSUBTITLES thread to exit
2017-03-13 18:31:51 INFO EVENT-QUEUE :: Waiting for the FINDPROPERS thread to exit
2017-03-13 18:31:51 INFO EVENT-QUEUE :: Waiting for the TRAKTCHECKER thread to exit
2017-03-13 18:31:50 INFO EVENT-QUEUE :: Waiting for the POSTPROCESSOR thread to exit
2017-03-13 18:31:50 INFO EVENT-QUEUE :: Waiting for the POSTPROCESSOR thread to exit
2017-03-13 18:31:50 INFO EVENT-QUEUE :: Waiting for the SEARCHQUEUE-BACKLOG-248841 thread to exit
2017-03-13 18:31:50 INFO EVENT-QUEUE :: Waiting for the SHOWQUEUE-REFRESH thread to exit
2017-03-13 18:31:50 INFO EVENT-QUEUE :: Waiting for the CHECKVERSION thread to exit
2017-03-13 18:31:50 INFO EVENT-QUEUE :: Waiting for the SHOWUPDATER thread to exit
2017-03-13 18:31:50 INFO EVENT-QUEUE :: Waiting for the BACKLOG thread to exit
2017-03-13 18:31:50 INFO EVENT-QUEUE :: Waiting for the DAILYSEARCHER thread to exit
2017-03-13 18:31:50 INFO EVENT-QUEUE :: Aborting all threads
```

**Comment by miigotu** [comment]
Whats the info about your OS, kernel, python version, etc?

**Comment by MattPark** [comment]
Latest linuxserver/sickrage:latest docker image (7 days ago)
I did migrate just the the sickbeard.db from a very recent git build maybe 2-3 weeks older.
```
root@linuxserver-sickrage1:/$ cat /etc/alpine-release
3.5.2
root@linuxserver-sickrage1:/$ uname -a
Linux linuxserver-sickrage1 3.10.102 #15047 SMP Sat Feb 18 17:33:56 CST 2017 x86_64 GNU/Linux
root@linuxserver-sickrage1:/$ python --version
Python 2.7.13
```

**Comment by MattPark** [comment]
I think what this breaks is that if I do a sickrage restart, vs full container restart it just sort of sits there in a read only type state.
