### ISSUE TITLE
[APP SUBMITTED]: decoding Unicode is not supported

### ISSUE THREAD

**Issue by Zzaap** [SickRage/sickrage-issues#105]
### INFO
Python Version: **2.7.10 (default, Jun  3 2015, 18:49:44) [GCC 4.6.4]**
Operating System: **Linux-3.2.40-armv7l-with-glibc2.4**
Locale: unknown
Branch: **master**
Commit: SickRage/SickRage@c89376b1847910b128f07b0aa6bf4ca701186e02
Link to Log: https://gist.github.com/074edc0f44398f68ee35
### ERROR
```
Thread-56 :: Failed doing webui callback: Traceback (most recent call last):
  File "/volume1/@appstore/sickrage/var/SickRage/sickbeard/webserve.py", line 265, in async_call
    result = function(**kwargs)
  File "/volume1/@appstore/sickrage/var/SickRage/sickbeard/webserve.py", line 3311, in massEditSubmit
    directCall=True)
  File "/volume1/@appstore/sickrage/var/SickRage/sickbeard/webserve.py", line 1492, in editShow
    location = unicode(location, 'UTF-8')
TypeError: decoding Unicode is not supported

```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by neoatomic** [comment]
@miigotu Strange, the `C` character seems to be replaced by a `*` character in the logs.?

**Comment by ripper1967** [comment]
### INFO
Python Version: **2.7.10 (default, May 23 2015, 09:40:32) [MSC v.1500 32 bit (Intel)]**
Operating System: **Windows-7-6.1.7601-SP1**
Locale: cp1252
Branch: **master**
Commit: SickRage/SickRage@c89376b1847910b128f07b0aa6bf4ca701186e02
Link to Log: https://gist.github.com/8ea33ff7c85c3c596c7f
### ERROR
```
Thread-39 :: Failed doing webui callback: Traceback (most recent call last):
  File "C:\Users\rusty\SickRage\sickbeard\webserve.py", line 265, in async_call
    result = function(**kwargs)
  File "C:\Users\rusty\SickRage\sickbeard\webserve.py", line 3311, in massEditSubmit
    directCall=True)
  File "C:\Users\rusty\SickRage\sickbeard\webserve.py", line 1492, in editShow
    location = unicode(location, 'UTF-8')
TypeError: decoding Unicode is not supported

```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators
