### ISSUE TITLE
[APP SUBMITTED]: Old quality does not match new: 720p HDTV != 1080p HDTV : The Goldbergs Season 2 x264 HDTV 1080p & 720p TitLip

### ISSUE THREAD

**Issue by unbolt** [SickRage/sickrage-issues#1052]
### INFO
Python Version: **2.7.3 (default, Mar 18 2014, 05:13:23) [GCC 4.6.3]**
Operating System: **Linux-4.1.13-v7+-armv7l-with-debian-7.8**
Locale: None
Branch: **master**
Commit: SickRage/SickRage@5195b784b76916a2acfe21c1fffd12f837ce0e93
No Log available with ERRORS:
### ERROR
```
Thread-17 :: Failed doing webui callback: Traceback (most recent call last):
  File "/opt/sickrage/sickbeard/webserve.py", line 285, in async_call
    result = function(**kwargs)
  File "/opt/sickrage/sickbeard/webserve.py", line 2281, in processEpisode
    is_priority=argToBool(is_priority), delete_on=argToBool(delete_on), failed=argToBool(failed), proc_type=type
  File "/opt/sickrage/sickbeard/processTV.py", line 230, in processDir
    for curDir in [x for x in dirs if validateDir(path, x, nzbNameOriginal, failed, result)]:
  File "/opt/sickrage/sickbeard/processTV.py", line 375, in validateDir
    NameParser().parse(proc_dir, cache_result=False)
  File "/opt/sickrage/sickbeard/name_parser/parser.py", line 421, in parse
    file_name_result = self._parse_string(base_file_name)
  File "/opt/sickrage/sickbeard/name_parser/parser.py", line 211, in _parse_string
    bestResult.quality = common.Quality.nameQuality(name, bestResult.show.is_anime)
  File "/opt/sickrage/sickbeard/common.py", line 279, in nameQuality
    quality = Quality.sceneQuality(name, anime)
  File "/opt/sickrage/sickbeard/common.py", line 455, in sceneQuality
    assert old == result, 'Old quality does not match new: %s != %s : %s' % (Quality.qualityStrings[old], Quality.qualityStrings[result], name)
AssertionError: Old quality does not match new: 720p HDTV != 1080p HDTV : The Goldbergs Season 2 x264 HDTV 1080p & 720p TitLip
 [5195b78]
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by SickRage2** [comment]
Thanks for the issue report! Before a real human comes by, please make sure your report has all the below criteria checked

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [ ] Post debug logs, either inline (for smaller logs) or using gist

Please make sure you also read [how to create an issue](https://github.com/SickRage/sickrage-issues/blob/master/README.md) and followed all of the steps. 

The title should describe your issue. Having "SR not working" or "I get this bug" for 100 issues, isn't really helpful. We will close issues if there isn't enough information.

Sometimes the devs may seem like grunts and respond with short answers. This isn't (always) because the dev hates you, but because he's on mobile or busy fixing bugs. If something isn't clear, please let us know, and this bot may get updated to automatically answer you.

Thanks!

**Comment by labrys** [comment]
update, already fixed
