### ISSUE TITLE
[APP SUBMITTED]: [Errno 13] Permission denied: u'/config/config.ini'

### ISSUE THREAD

**Issue by TroisSix** [SickRage/sickrage-issues#1057]
### INFO
Python Version: **2.7.11 (default, Dec 15 2015, 16:46:19) [GCC 4.8.4]**
Operating System: **Linux-3.10.35-x86_64-with-Ubuntu-14.04-trusty**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@06f023f5cdd4449ef2ef7795e3fa55f40882f634
No Log available with ERRORS:
### ERROR
```
Thread-26 :: Failed doing webui callback: Traceback (most recent call last):
  File "/app/sickrage/sickbeard/webserve.py", line 283, in async_call
    result = function(**kwargs)
  File "/app/sickrage/sickbeard/webserve.py", line 3962, in saveGeneral
    sickbeard.save_config()
  File "/app/sickrage/sickbeard/__init__.py", line 2164, in save_config
    new_config.write()
  File "/app/sickrage/lib/configobj.py", line 2066, in write
    h = open(self.filename, 'wb')
IOError: [Errno 13] Permission denied: u'/config/config.ini'
 [06f023f]
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by TroisSix** [comment]
### INFO
Python Version: **2.7.11 (default, Dec 15 2015, 16:46:19) [GCC 4.8.4]**
Operating System: **Linux-3.10.35-x86_64-with-Ubuntu-14.04-trusty**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@06f023f5cdd4449ef2ef7795e3fa55f40882f634
No Log available with ERRORS:
### ERROR
```
Thread-44 :: Failed doing webui callback: Traceback (most recent call last):
  File "/app/sickrage/sickbeard/webserve.py", line 283, in async_call
    result = function(**kwargs)
  File "/app/sickrage/sickbeard/webserve.py", line 3689, in index
    sickbeard.save_config()
  File "/app/sickrage/sickbeard/__init__.py", line 2164, in save_config
    new_config.write()
  File "/app/sickrage/lib/configobj.py", line 2066, in write
    h = open(self.filename, 'wb')
IOError: [Errno 13] Permission denied: u'/config/config.ini'
 [06f023f]
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by SickRage2** [comment]
Thanks for the issue report! Before a real human comes by, please make sure your report has all the below criteria checked

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [ ] Post debug logs, either inline (for smaller logs) or using gist

Please make sure you also read [how to create an issue](https://github.com/SickRage/sickrage-issues/blob/master/README.md) and followed all of the steps. 

The title should describe your issue. Having "SR not working" or "I get this bug" for 100 issues, isn't really helpful. We will close issues if there isn't enough information.

Sometimes the devs may seem like grunts and respond with short answers. This isn't (always) because the dev hates you, but because he's on mobile or busy fixing bugs. If something isn't clear, please let us know, and this bot may get updated to automatically answer you.

Thanks!

**Comment by TroisSix** [comment]
### INFO
Python Version: **2.7.11 (default, Dec 15 2015, 16:46:19) [GCC 4.8.4]**
Operating System: **Linux-3.10.35-x86_64-with-Ubuntu-14.04-trusty**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@06f023f5cdd4449ef2ef7795e3fa55f40882f634
No Log available with ERRORS:
### ERROR
```
Thread-28 :: Failed doing webui callback: Traceback (most recent call last):
  File "/app/sickrage/sickbeard/webserve.py", line 283, in async_call
    result = function(**kwargs)
  File "/app/sickrage/sickbeard/webserve.py", line 3689, in index
    sickbeard.save_config()
  File "/app/sickrage/sickbeard/__init__.py", line 2164, in save_config
    new_config.write()
  File "/app/sickrage/lib/configobj.py", line 2066, in write
    h = open(self.filename, 'wb')
IOError: [Errno 13] Permission denied: u'/config/config.ini'
 [06f023f]
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by TroisSix** [comment]
### INFO
Python Version: **2.7.11 (default, Dec 15 2015, 16:46:19) [GCC 4.8.4]**
Operating System: **Linux-3.10.35-x86_64-with-Ubuntu-14.04-trusty**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@06f023f5cdd4449ef2ef7795e3fa55f40882f634
No Log available with ERRORS:
### ERROR
```
Thread-42 :: Failed doing webui callback: Traceback (most recent call last):
  File "/app/sickrage/sickbeard/webserve.py", line 283, in async_call
    result = function(**kwargs)
  File "/app/sickrage/sickbeard/webserve.py", line 3689, in index
    sickbeard.save_config()
  File "/app/sickrage/sickbeard/__init__.py", line 2164, in save_config
    new_config.write()
  File "/app/sickrage/lib/configobj.py", line 2066, in write
    h = open(self.filename, 'wb')
IOError: [Errno 13] Permission denied: u'/config/config.ini'
 [06f023f]
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by TroisSix** [comment]
### INFO
Python Version: **2.7.11 (default, Dec 15 2015, 16:46:19) [GCC 4.8.4]**
Operating System: **Linux-3.10.35-x86_64-with-Ubuntu-14.04-trusty**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@06f023f5cdd4449ef2ef7795e3fa55f40882f634
No Log available with ERRORS:
### ERROR
```
Thread-17 :: Failed doing webui callback: Traceback (most recent call last):
  File "/app/sickrage/sickbeard/webserve.py", line 283, in async_call
    result = function(**kwargs)
  File "/app/sickrage/sickbeard/webserve.py", line 4131, in saveSearch
    sickbeard.save_config()
  File "/app/sickrage/sickbeard/__init__.py", line 2164, in save_config
    new_config.write()
  File "/app/sickrage/lib/configobj.py", line 2066, in write
    h = open(self.filename, 'wb')
IOError: [Errno 13] Permission denied: u'/config/config.ini'
 [06f023f]
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by TroisSix** [comment]
### INFO
Python Version: **2.7.11 (default, Dec 15 2015, 16:46:19) [GCC 4.8.4]**
Operating System: **Linux-3.10.35-x86_64-with-Ubuntu-14.04-trusty**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@06f023f5cdd4449ef2ef7795e3fa55f40882f634
No Log available with ERRORS:
### ERROR
```
Thread-50 :: Failed doing webui callback: Traceback (most recent call last):
  File "/app/sickrage/sickbeard/webserve.py", line 283, in async_call
    result = function(**kwargs)
  File "/app/sickrage/sickbeard/webserve.py", line 4131, in saveSearch
    sickbeard.save_config()
  File "/app/sickrage/sickbeard/__init__.py", line 2164, in save_config
    new_config.write()
  File "/app/sickrage/lib/configobj.py", line 2066, in write
    h = open(self.filename, 'wb')
IOError: [Errno 13] Permission denied: u'/config/config.ini'
 [06f023f]
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by TroisSix** [comment]
### INFO
Python Version: **2.7.11 (default, Dec 15 2015, 16:46:19) [GCC 4.8.4]**
Operating System: **Linux-3.10.35-x86_64-with-Ubuntu-14.04-trusty**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@06f023f5cdd4449ef2ef7795e3fa55f40882f634
Link to Log: https://gist.github.com/47b3698e19e90f0126f6
### ERROR
```
EVENT-QUEUE :: Exception generated in thread EVENT-QUEUE: error 13 : Permission denied [06f023f]
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by duramato** [comment]
`Permission denied`
