### ISSUE TITLE
[APP SUBMITTED]: 'NoneType' object is not iterable

### ISSUE THREAD

**Issue by Dingmatt** [SickRage/sickrage-issues#1063]
### INFO
Python Version: **2.7.10 (default, May 23 2015, 09:40:32) [MSC v.1500 32 bit (Intel)]**
Operating System: **Windows-2008ServerR2-6.1.7601-SP1**
Locale: cp1252
Branch: **master**
Commit: SickRage/SickRage@1ee61ed7e0a1b31fc5b6d10f3df6d9ff3ade141a
No Log available with ERRORS:
### ERROR
```
Thread-23 :: Failed doing webui callback: Traceback (most recent call last):
  File "C:\Program Files\SickRage_Master\sickbeard\webserve.py", line 287, in async_call
    result = function(**kwargs)
  File "C:\Program Files\SickRage_Master\sickbeard\webserve.py", line 2354, in searchIndexersForShowName
    results.setdefault(indexer, []).extend(indexerResults)
TypeError: 'NoneType' object is not iterable
 [1ee61ed]
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by SickRage2** [comment]
Thanks for the issue report! Before a real human comes by, please make sure your report has all the below criteria checked

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [ ] Post debug logs, either inline (for smaller logs) or using gist

Please make sure you also read [how to create an issue](https://github.com/SickRage/sickrage-issues/blob/master/README.md) and followed all of the steps. 

The title should describe your issue. Having "SR not working" or "I get this bug" for 100 issues, isn't really helpful. We will close issues if there isn't enough information.

Sometimes the devs may seem like grunts and respond with short answers. This isn't (always) because the dev hates you, but because he's on mobile or busy fixing bugs. If something isn't clear, please let us know, and this bot may get updated to automatically answer you.

Thanks!

**Comment by Dingmatt** [comment]
### INFO
Python Version: **2.7.10 (default, May 23 2015, 09:40:32) [MSC v.1500 32 bit (Intel)]**
Operating System: **Windows-2008ServerR2-6.1.7601-SP1**
Locale: cp1252
Branch: **master**
Commit: SickRage/SickRage@1ee61ed7e0a1b31fc5b6d10f3df6d9ff3ade141a
No Log available with ERRORS:
### ERROR
```
Thread-25 :: Failed doing webui callback: Traceback (most recent call last):
  File "C:\Program Files\SickRage_Master\sickbeard\webserve.py", line 287, in async_call
    result = function(**kwargs)
  File "C:\Program Files\SickRage_Master\sickbeard\webserve.py", line 2354, in searchIndexersForShowName
    results.setdefault(indexer, []).extend(indexerResults)
TypeError: 'NoneType' object is not iterable
 [1ee61ed]
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by Dingmatt** [comment]
### INFO
Python Version: **2.7.10 (default, May 23 2015, 09:40:32) [MSC v.1500 32 bit (Intel)]**
Operating System: **Windows-2008ServerR2-6.1.7601-SP1**
Locale: cp1252
Branch: **master**
Commit: SickRage/SickRage@1ee61ed7e0a1b31fc5b6d10f3df6d9ff3ade141a
No Log available with ERRORS:
### ERROR
```
Thread-20 :: Failed doing webui callback: Traceback (most recent call last):
  File "C:\Program Files\SickRage_Master\sickbeard\webserve.py", line 287, in async_call
    result = function(**kwargs)
  File "C:\Program Files\SickRage_Master\sickbeard\webserve.py", line 2354, in searchIndexersForShowName
    results.setdefault(indexer, []).extend(indexerResults)
TypeError: 'NoneType' object is not iterable
 [1ee61ed]
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by neoatomic** [comment]
Could you include the log.? With the current info we cant see where it happens...

**Comment by Dingmatt** [comment]
I think it was a connection issue my end, I'll resubmit if it occurs again.
