### ISSUE TITLE
ImportError: cannot import name TargaFile

### ISSUE THREAD

**Issue by kingmotley** [SickRage/sickrage-issues#1070]
### Before submitting your issue:

Enable debug logging in SickRage settings, reproduce the error (be sure to disable after the bug is fixed)

Branch/Commit: master
OS: Windows 10
What you did: Start SickRage
What happened: It died
What you expected: It to start
Logs:
```
Traceback (most recent call last):
  File "N:\SickRage\SickBeard.py", line 85, in <module>
    import sickbeard
  File "N:\SickRage\sickbeard\__init__.py", line 38, in <module>
    from sickbeard import metadata
  File "N:\SickRage\sickbeard\metadata\__init__.py", line 22, in <module>
    from sickbeard.metadata import kodi, kodi_12plus, mediabrowser, ps3, wdtv, t
ivo, mede8er, generic, helpers
  File "N:\SickRage\sickbeard\metadata\kodi.py", line 23, in <module>
    from sickbeard.metadata import generic
  File "N:\SickRage\sickbeard\metadata\generic.py", line 32, in <module>
    from sickbeard import helpers
  File "N:\SickRage\sickbeard\helpers.py", line 53, in <module>
    from sickbeard import logger, classes
  File "N:\SickRage\sickbeard\logger.py", line 43, in <module>
    from sickbeard import classes
  File "N:\SickRage\sickbeard\classes.py", line 29, in <module>
    from sickbeard.common import USER_AGENT, Quality
  File "N:\SickRage\sickbeard\common.py", line 33, in <module>
    from hachoir_parser import createParser  # pylint: disable=import-error
  File "N:\SickRage\lib\hachoir_parser\__init__.py", line 5, in <module>
    from hachoir_parser import (archive, audio, container,
  File "N:\SickRage\lib\hachoir_parser\audio\__init__.py", line 11, in <module>
    from hachoir_parser.audio.flac import FlacParser
  File "N:\SickRage\lib\hachoir_parser\audio\flac.py", line 16, in <module>
    from hachoir_parser.container.ogg import parseVorbisComment
  File "N:\SickRage\lib\hachoir_parser\container\__init__.py", line 4, in <modul
e>
    from hachoir_parser.container.riff import RiffFile
  File "N:\SickRage\lib\hachoir_parser\container\riff.py", line 42, in <module>
    from hachoir_parser.image.ico import IcoFile
  File "N:\SickRage\lib\hachoir_parser\image\__init__.py", line 8, in <module>
    from hachoir_parser.image.tga import TargaFile
ImportError: cannot import name TargaFile
```

**Comment by SickRage2** [comment]
Thanks for the issue report! Before a real human comes by, please make sure your report has all the below criteria checked

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [ ] Post debug logs, either inline (for smaller logs) or using gist

Please make sure you also read [how to create an issue](https://github.com/SickRage/sickrage-issues/blob/master/README.md) and followed all of the steps. 

The title should describe your issue. Having "SR not working" or "I get this bug" for 100 issues, isn't really helpful. We will close issues if there isn't enough information.

Sometimes the devs may seem like grunts and respond with short answers. This isn't (always) because the dev hates you, but because he's on mobile or busy fixing bugs. If something isn't clear, please let us know, and this bot may get updated to automatically answer you.

Thanks!

**Comment by kingmotley** [comment]
Not sure what I going on, but removing references to TargaFile in lib/hachoir_parser/image/__init__.py (on line 8) then gives a similar issue in /lib/hachoir_metadata/image.py.  So removing the references there (an import a line at the bottom to register an extractor), then allows sickrage to start and function normally.

Looking at lib/hachoir_parser/image/tga.py, it looks fine to me and what is exactly in github, so I'm not sure why it can't import it.

**Comment by kingmotley** [comment]
Deleting tga.pyc seems to have resolve it.  Perhaps that file got corrupt somehow, so I'm guessing it's not a sickrage issue.
