### ISSUE TITLE
UnicodeEncodeError since latest update (Windows 10)

### ISSUE THREAD

**Issue by matsjogback** [SickRage/sickrage-issues#1098]
### Before submitting your issue:

Enable debug logging in SickRage settings, reproduce the error (be sure to disable after the bug is fixed)

Branch/Commit: latest from Master
OS: Windows 10
What you did: Tried updating...
What happened: Updated and now getting UnicodeEncodeError
What you expected: Update to work without problems
Logs: Cant since I cant start SickRage
```
PASTE LOGS HERE
```
From command prompt:
```
"C:\SickRage>python C:\SickRage\SickRage\SickBeard.py
Traceback (most recent call last):
  File "C:\SickRage\SickRage\SickBeard.py", line 95, in <module>
    import sickbeard
  File "C:\SickRage\SickRage\sickbeard\__init__.py", line 39, in <module>
    from sickbeard.config import CheckSection, check_setting_int, check_setting_str, check_setting_float, ConfigMigrator
  File "C:\SickRage\SickRage\sickbeard\config.py", line 29, in <module>
    from sickbeard import naming
  File "C:\SickRage\SickRage\sickbeard\naming.py", line 25, in <module>
    from sickbeard import tv
  File "C:\SickRage\SickRage\sickbeard\tv.py", line 49, in <module>
    from sickbeard import network_timezones
  File "C:\SickRage\SickRage\sickbeard\network_timezones.py", line 34, in <module>
    sb_timezone = tz.tzwinlocal() if tz.tzwinlocal else tz.tzlocal()
  File "C:\SickRage\SickRage\lib\dateutil\tz\win.py", line 239, in __init__
    handle, "%s\%s" % (TZKEYNAME, self._stdname)) as tzkey:
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe4' in position 57: ordinal not in range(128)"
```
Tried doing a fresh install as well, same problem.

**Comment by SickRage2** [comment]
Thanks for the issue report! Before a real human comes by, please make sure your report has all the below criteria checked

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [ ] Post debug logs, either inline (for smaller logs) or using gist

Please make sure you also read [how to create an issue](https://github.com/SickRage/sickrage-issues/blob/master/README.md) and followed all of the steps. 

The title should describe your issue. Having "SR not working" or "I get this bug" for 100 issues, isn't really helpful. We will close issues if there isn't enough information.

Sometimes the devs may seem like grunts and respond with short answers. This isn't (always) because the dev hates you, but because he's on mobile or busy fixing bugs. If something isn't clear, please let us know, and this bot may get updated to automatically answer you.

Thanks!

**Comment by neoatomic** [comment]
Just did a fresh install on win10 with the installer. All running fine. (see screenshot)
Did u use the installer or manual install SR.?

![naamloos](https://cloud.githubusercontent.com/assets/7928052/13553784/6b8d8504-e394-11e5-9808-38c3957ec3a6.png)

**Comment by matsjogback** [comment]
When doing the fresh install I used the installer (deleted entire folder first). Also tried git reset.

Maybe it has something to do with OS locale? I'm using Swedish system language in Windows 10.

Noticed this in the FAQ but it only seems to apply for unix systems (so not Windows).
https://github.com/SickRage/sickrage-issues/wiki/FAQ%27s-and-Fixes#i-have-problems-with-special-characters-%C3%A9-etc-what-can-i-do

**Comment by anarfox** [comment]
Same issue in Windows 7 Ultimate 64bit. Also using Swedish system language.

**Comment by neoatomic** [comment]
No sure whats happening here...
The error seems to be related to the timezone. See if you can change the timezone to something before UTC/UTC+1. And than try to start SR again.

**Comment by anarfox** [comment]
I tried some different time zones and some worked, some didn't. I'm guessing it has something to do with the name of the timezone. My standard timezone name is "Amsterdam, Berlin, Bern, Rom, Stockholm, Wien". Timezone "Windhoek" which is also UTC+1 worked.

**Comment by neoatomic** [comment]
@anarfox Sound like you are correct. We are looking into it right now.
If you have time, you can join IRC for some tests if you like.

**Comment by matsjogback** [comment]
Nice work, thanks!

**Comment by anarfox** [comment]
:+1:
