### ISSUE TITLE
[APP SUBMITTED]: [Errno 28] No space left on device: '/raid/data/MOD_CONFIG/SickRageCE/DATA/cache/mako'

### ISSUE THREAD

**Issue by Kiggerbare** [SickRage/sickrage-issues#1099]
### INFO
Python Version: **2.7.11 (default, Dec 21 2015, 12:20:22) [GCC 4.5.3]**
Operating System: **Linux-2.6.33N7700-i686-with-glibc2.0**
Locale: None
Branch: **master**
Commit: SickRage/SickRage@d775a91c527289afafa04b0e3a9083fa9c89bf3c
No Log available with ERRORS:
### ERROR
```
Thread-18 :: [d775a91] Failed doing webui callback: Traceback (most recent call last):
  File "/raid0/data/module/SickRageCE/sys/SickRage/sickbeard/webserve.py", line 287, in async_call
    result = function(**kwargs)
  File "/raid0/data/module/SickRageCE/sys/SickRage/sickbeard/webserve.py", line 700, in index
    t = PageTemplate(rh=self, filename="home.mako")
  File "/raid0/data/module/SickRageCE/sys/SickRage/sickbeard/webserve.py", line 128, in __init__
    self.template = lookup.get_template(filename)
  File "/raid0/data/module/SickRageCE/sys/SickRage/lib/mako/lookup.py", line 256, in get_template
    return self._load(srcfile, uri)
  File "/raid0/data/module/SickRageCE/sys/SickRage/lib/mako/lookup.py", line 321, in _load
    **self.template_args)
  File "/raid0/data/module/SickRageCE/sys/SickRage/lib/mako/template.py", line 322, in __init__
    module = self._compile_from_file(path, filename)
  File "/raid0/data/module/SickRageCE/sys/SickRage/lib/mako/template.py", line 368, in _compile_from_file
    util.verify_directory(os.path.dirname(path))
  File "/raid0/data/module/SickRageCE/sys/SickRage/lib/mako/util.py", line 60, in verify_directory
    os.makedirs(dir, compat.octal("0775"))
  File "/raid0/data/module/SickRageCE/sys/lib/python2.7/os.py", line 157, in makedirs
    mkdir(name, mode)
OSError: [Errno 28] No space left on device: '/raid/data/MOD_CONFIG/SickRageCE/DATA/cache/mako'

```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by SickRage2** [comment]
Thanks for the issue report! Before a real human comes by, please make sure your report has all the below criteria checked

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [ ] Post debug logs, either inline (for smaller logs) or using gist

Please make sure you also read [how to create an issue](https://github.com/SickRage/sickrage-issues/blob/master/README.md) and followed all of the steps. 

The title should describe your issue. Having "SR not working" or "I get this bug" for 100 issues, isn't really helpful. We will close issues if there isn't enough information.

Sometimes the devs may seem like grunts and respond with short answers. This isn't (always) because the dev hates you, but because he's on mobile or busy fixing bugs. If something isn't clear, please let us know, and this bot may get updated to automatically answer you.

Thanks!

**Comment by Kiggerbare** [comment]
### INFO
Python Version: **2.7.11 (default, Dec 21 2015, 12:20:22) [GCC 4.5.3]**
Operating System: **Linux-2.6.33N7700-i686-with-glibc2.0**
Locale: None
Branch: **master**
Commit: SickRage/SickRage@d775a91c527289afafa04b0e3a9083fa9c89bf3c
No Log available with ERRORS:
### ERROR
```
Thread-17 :: [d775a91] Failed doing webui callback: Traceback (most recent call last):
  File "/raid0/data/module/SickRageCE/sys/SickRage/sickbeard/webserve.py", line 287, in async_call
    result = function(**kwargs)
  File "/raid0/data/module/SickRageCE/sys/SickRage/sickbeard/webserve.py", line 700, in index
    t = PageTemplate(rh=self, filename="home.mako")
  File "/raid0/data/module/SickRageCE/sys/SickRage/sickbeard/webserve.py", line 128, in __init__
    self.template = lookup.get_template(filename)
  File "/raid0/data/module/SickRageCE/sys/SickRage/lib/mako/lookup.py", line 256, in get_template
    return self._load(srcfile, uri)
  File "/raid0/data/module/SickRageCE/sys/SickRage/lib/mako/lookup.py", line 321, in _load
    **self.template_args)
  File "/raid0/data/module/SickRageCE/sys/SickRage/lib/mako/template.py", line 322, in __init__
    module = self._compile_from_file(path, filename)
  File "/raid0/data/module/SickRageCE/sys/SickRage/lib/mako/template.py", line 368, in _compile_from_file
    util.verify_directory(os.path.dirname(path))
  File "/raid0/data/module/SickRageCE/sys/SickRage/lib/mako/util.py", line 60, in verify_directory
    os.makedirs(dir, compat.octal("0775"))
  File "/raid0/data/module/SickRageCE/sys/lib/python2.7/os.py", line 157, in makedirs
    mkdir(name, mode)
OSError: [Errno 28] No space left on device: '/raid/data/MOD_CONFIG/SickRageCE/DATA/cache/mako'

```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by Kiggerbare** [comment]
Ahh, seems like all the errors was lack of storage on the device going on the title of this bug issue. Guess there is no error after all then.
