### ISSUE TITLE
[APP SUBMITTED]: Show search returned zero results (cannot find show on TVDB)

### ISSUE THREAD

**Issue by stanthewizzard** [SickRage/sickrage-issues#1110]
### INFO
Python Version: **2.7.10 (default, Oct 14 2015, 16:09:02) [GCC 5.2.1 20151010]**
Operating System: **Linux-4.2.0-30-generic-x86_64-with-Ubuntu-15.10-wily**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@9149089e176cd9da6b6ac0c023169e0c3102d2d9
No Log available with ERRORS:
### ERROR
```
Thread-26 :: [9149089] Failed doing webui callback: Traceback (most recent call last):
  File "/home/nzb/sickrage/sickbeard/webserve.py", line 287, in async_call
    result = function(**kwargs)
  File "/home/nzb/sickrage/sickbeard/webserve.py", line 2349, in searchIndexersForShowName
    indexerResults = t[searchTerm]
  File "/home/nzb/sickrage/lib/tvdb_api/tvdb_api.py", line 958, in __getitem__
    selected_series = self._getSeries(key)
  File "/home/nzb/sickrage/lib/tvdb_api/tvdb_api.py", line 703, in _getSeries
    raise tvdb_shownotfound("Show search returned zero results (cannot find show on TVDB)")
tvdb_shownotfound: Show search returned zero results (cannot find show on TVDB)

```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by SickRage2** [comment]
Thanks for the issue report! Before a real human comes by, please make sure your report has all the below criteria checked

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [ ] Post debug logs, either inline (for smaller logs) or using gist

Please make sure you also read [how to create an issue](https://github.com/SickRage/sickrage-issues/blob/master/README.md) and followed all of the steps. 

The title should describe your issue. Having "SR not working" or "I get this bug" for 100 issues, isn't really helpful. We will close issues if there isn't enough information.

Sometimes the devs may seem like grunts and respond with short answers. This isn't (always) because the dev hates you, but because he's on mobile or busy fixing bugs. If something isn't clear, please let us know, and this bot may get updated to automatically answer you.

Thanks!

**Comment by konomimaster** [comment]
### INFO
Python Version: **2.7.11 (default, Dec 17 2015, 14:08:17) [GCC 4.6.3]**
Operating System: **Linux-3.2.40-i686-with-glibc2.0**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@9149089e176cd9da6b6ac0c023169e0c3102d2d9
No Log available with ERRORS:
### ERROR
```
Thread-14 :: [9149089] Failed doing webui callback: Traceback (most recent call last):
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/webserve.py", line 287, in async_call
    result = function(**kwargs)
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/webserve.py", line 2349, in searchIndexersForShowName
    indexerResults = t[searchTerm]
  File "/usr/local/sickbeard-custom/var/SickBeard/lib/tvdb_api/tvdb_api.py", line 958, in __getitem__
    selected_series = self._getSeries(key)
  File "/usr/local/sickbeard-custom/var/SickBeard/lib/tvdb_api/tvdb_api.py", line 703, in _getSeries
    raise tvdb_shownotfound("Show search returned zero results (cannot find show on TVDB)")
tvdb_shownotfound: Show search returned zero results (cannot find show on TVDB)

```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by hussamdabit** [comment]
### INFO
Python Version: **2.7.11 (v2.7.11:6d1b6a68f775, Dec  5 2015, 20:40:30) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-10-10.0.10586**
Locale: cp1252
Branch: **master**
Commit: SickRage/SickRage@9149089e176cd9da6b6ac0c023169e0c3102d2d9
No Log available with ERRORS:
### ERROR
```
Thread-33 :: [9149089] Failed doing webui callback: Traceback (most recent call last):
  File "C:\SickRage\sickbeard\webserve.py", line 287, in async_call
    result = function(**kwargs)
  File "C:\SickRage\sickbeard\webserve.py", line 2349, in searchIndexersForShowName
    indexerResults = t[searchTerm]
  File "C:\SickRage\lib\tvdb_api\tvdb_api.py", line 958, in __getitem__
    selected_series = self._getSeries(key)
  File "C:\SickRage\lib\tvdb_api\tvdb_api.py", line 703, in _getSeries
    raise tvdb_shownotfound("Show search returned zero results (cannot find show on TVDB)")
tvdb_shownotfound: Show search returned zero results (cannot find show on TVDB)

```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by habskilla** [comment]
### INFO
Python Version: **2.7.11 (v2.7.11:6d1b6a68f775, Dec  5 2015, 20:40:30) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-8.1-6.3.9600**
Locale: cp1252
Branch: **master**
Commit: SickRage/SickRage@0a1f476a63c552ffd4aae3a9a1e7203ce8707540
No Log available with ERRORS:
### ERROR
```
Thread-22 :: [0a1f476] Failed doing webui callback: Traceback (most recent call last):
  File "C:\SickRage2\sickbeard\webserve.py", line 287, in async_call
    result = function(**kwargs)
  File "C:\SickRage2\sickbeard\webserve.py", line 2349, in searchIndexersForShowName
    indexerResults = t[searchTerm]
  File "C:\SickRage2\lib\tvdb_api\tvdb_api.py", line 958, in __getitem__
    selected_series = self._getSeries(key)
  File "C:\SickRage2\lib\tvdb_api\tvdb_api.py", line 703, in _getSeries
    raise tvdb_shownotfound("Show search returned zero results (cannot find show on TVDB)")
tvdb_shownotfound: Show search returned zero results (cannot find show on TVDB)

```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by habskilla** [comment]
### INFO
Python Version: **2.7.11 (v2.7.11:6d1b6a68f775, Dec  5 2015, 20:40:30) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-8.1-6.3.9600**
Locale: cp1252
Branch: **master**
Commit: SickRage/SickRage@0a1f476a63c552ffd4aae3a9a1e7203ce8707540
No Log available with ERRORS:
### ERROR
```
Thread-23 :: [0a1f476] Failed doing webui callback: Traceback (most recent call last):
  File "C:\SickRage2\sickbeard\webserve.py", line 287, in async_call
    result = function(**kwargs)
  File "C:\SickRage2\sickbeard\webserve.py", line 2349, in searchIndexersForShowName
    indexerResults = t[searchTerm]
  File "C:\SickRage2\lib\tvdb_api\tvdb_api.py", line 958, in __getitem__
    selected_series = self._getSeries(key)
  File "C:\SickRage2\lib\tvdb_api\tvdb_api.py", line 703, in _getSeries
    raise tvdb_shownotfound("Show search returned zero results (cannot find show on TVDB)")
tvdb_shownotfound: Show search returned zero results (cannot find show on TVDB)

```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by ahummaida** [comment]
### INFO
Python Version: **2.7.11 (default, Jan  9 2016, 16:55:40) [GCC 4.8.5]**
Operating System: **Linux-3.12.6-x86_64-with-glibc2.2.5**
Locale: None
Branch: **master**
Commit: SickRage/SickRage@0a1f476a63c552ffd4aae3a9a1e7203ce8707540
No Log available with ERRORS:
### ERROR
```
Thread-13 :: [0a1f476] Failed doing webui callback: Traceback (most recent call last):
  File "/share/CACHEDEV1_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/sickbeard/webserve.py", line 287, in async_call
    result = function(**kwargs)
  File "/share/CACHEDEV1_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/sickbeard/webserve.py", line 2349, in searchIndexersForShowName
    indexerResults = t[searchTerm]
  File "/share/CACHEDEV1_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/lib/tvdb_api/tvdb_api.py", line 958, in __getitem__
    selected_series = self._getSeries(key)
  File "/share/CACHEDEV1_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/lib/tvdb_api/tvdb_api.py", line 703, in _getSeries
    raise tvdb_shownotfound("Show search returned zero results (cannot find show on TVDB)")
tvdb_shownotfound: Show search returned zero results (cannot find show on TVDB)

```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by ahummaida** [comment]
### INFO
Python Version: **2.7.11 (default, Jan  9 2016, 16:55:40) [GCC 4.8.5]**
Operating System: **Linux-3.12.6-x86_64-with-glibc2.2.5**
Locale: None
Branch: **master**
Commit: SickRage/SickRage@0a1f476a63c552ffd4aae3a9a1e7203ce8707540
No Log available with ERRORS:
### ERROR
```
Thread-14 :: [0a1f476] Failed doing webui callback: Traceback (most recent call last):
  File "/share/CACHEDEV1_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/sickbeard/webserve.py", line 287, in async_call
    result = function(**kwargs)
  File "/share/CACHEDEV1_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/sickbeard/webserve.py", line 2349, in searchIndexersForShowName
    indexerResults = t[searchTerm]
  File "/share/CACHEDEV1_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/lib/tvdb_api/tvdb_api.py", line 958, in __getitem__
    selected_series = self._getSeries(key)
  File "/share/CACHEDEV1_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/lib/tvdb_api/tvdb_api.py", line 703, in _getSeries
    raise tvdb_shownotfound("Show search returned zero results (cannot find show on TVDB)")
tvdb_shownotfound: Show search returned zero results (cannot find show on TVDB)

```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by ahummaida** [comment]
### INFO
Python Version: **2.7.11 (default, Jan  9 2016, 16:55:40) [GCC 4.8.5]**
Operating System: **Linux-3.12.6-x86_64-with-glibc2.2.5**
Locale: None
Branch: **master**
Commit: SickRage/SickRage@0a1f476a63c552ffd4aae3a9a1e7203ce8707540
No Log available with ERRORS:
### ERROR
```
Thread-16 :: [0a1f476] Failed doing webui callback: Traceback (most recent call last):
  File "/share/CACHEDEV1_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/sickbeard/webserve.py", line 287, in async_call
    result = function(**kwargs)
  File "/share/CACHEDEV1_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/sickbeard/webserve.py", line 2349, in searchIndexersForShowName
    indexerResults = t[searchTerm]
  File "/share/CACHEDEV1_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/lib/tvdb_api/tvdb_api.py", line 958, in __getitem__
    selected_series = self._getSeries(key)
  File "/share/CACHEDEV1_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/lib/tvdb_api/tvdb_api.py", line 703, in _getSeries
    raise tvdb_shownotfound("Show search returned zero results (cannot find show on TVDB)")
tvdb_shownotfound: Show search returned zero results (cannot find show on TVDB)

```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by ahummaida** [comment]
### INFO
Python Version: **2.7.11 (default, Jan  9 2016, 16:55:40) [GCC 4.8.5]**
Operating System: **Linux-3.12.6-x86_64-with-glibc2.2.5**
Locale: None
Branch: **master**
Commit: SickRage/SickRage@0a1f476a63c552ffd4aae3a9a1e7203ce8707540
No Log available with ERRORS:
### ERROR
```
Thread-15 :: [0a1f476] Failed doing webui callback: Traceback (most recent call last):
  File "/share/CACHEDEV1_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/sickbeard/webserve.py", line 287, in async_call
    result = function(**kwargs)
  File "/share/CACHEDEV1_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/sickbeard/webserve.py", line 2349, in searchIndexersForShowName
    indexerResults = t[searchTerm]
  File "/share/CACHEDEV1_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/lib/tvdb_api/tvdb_api.py", line 958, in __getitem__
    selected_series = self._getSeries(key)
  File "/share/CACHEDEV1_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/lib/tvdb_api/tvdb_api.py", line 703, in _getSeries
    raise tvdb_shownotfound("Show search returned zero results (cannot find show on TVDB)")
tvdb_shownotfound: Show search returned zero results (cannot find show on TVDB)

```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by miigotu** [comment]
Fixed in https://github.com/SickRage/SickRage/pull/1128

**Comment by Vodka2014** [comment]
### INFO
Python Version: **2.7.11 (default, Dec 17 2015, 15:58:38) [GCC 4.7.3 20130102 (prerelease)]**
Operating System: **Linux-3.10.35-x86_64-with-glibc2.2.5**
Locale: None
Branch: **master**
Commit: SickRage/SickRage@0a1f476a63c552ffd4aae3a9a1e7203ce8707540
No Log available with ERRORS:
### ERROR
```
Thread-19 :: [0a1f476] Failed doing webui callback: Traceback (most recent call last):
  File "/volume5/@appstore/sickrage/var/SickRage/sickbeard/webserve.py", line 287, in async_call
    result = function(**kwargs)
  File "/volume5/@appstore/sickrage/var/SickRage/sickbeard/webserve.py", line 2349, in searchIndexersForShowName
    indexerResults = t[searchTerm]
  File "/usr/local/sickrage/var/SickRage/lib/tvdb_api/tvdb_api.py", line 958, in __getitem__
    selected_series = self._getSeries(key)
  File "/usr/local/sickrage/var/SickRage/lib/tvdb_api/tvdb_api.py", line 703, in _getSeries
    raise tvdb_shownotfound("Show search returned zero results (cannot find show on TVDB)")
tvdb_shownotfound: Show search returned zero results (cannot find show on TVDB)

```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by miigotu** [comment]
This is only when you search to add a show and there are no results, it is fixed the n develop

**Comment by cmeriaux** [comment]
### INFO
Python Version: **2.7.9 (default, Mar  1 2015, 12:57:24) [GCC 4.9.2]**
Operating System: **Linux-3.14.32-xxxx-grs-ipv6-64-x86_64-with-Debian-8**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@497ec103a5448e492f7dc2676724b3585d598559
No Log available with ERRORS:
### ERROR
```
Thread-17 :: [497ec10] Failed doing webui callback: Traceback (most recent call last):
  File "/opt/sickrage/sickbeard/webserve.py", line 287, in async_call
    result = function(**kwargs)
  File "/opt/sickrage/sickbeard/webserve.py", line 2349, in searchIndexersForShowName
    indexerResults = t[searchTerm]
  File "/opt/sickrage/lib/tvdb_api/tvdb_api.py", line 958, in __getitem__
    selected_series = self._getSeries(key)
  File "/opt/sickrage/lib/tvdb_api/tvdb_api.py", line 703, in _getSeries
    raise tvdb_shownotfound("Show search returned zero results (cannot find show on TVDB)")
tvdb_shownotfound: Show search returned zero results (cannot find show on TVDB)

```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by cmeriaux** [comment]
### INFO
Python Version: **2.7.9 (default, Mar  1 2015, 12:57:24) [GCC 4.9.2]**
Operating System: **Linux-3.14.32-xxxx-grs-ipv6-64-x86_64-with-Debian-8**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@497ec103a5448e492f7dc2676724b3585d598559
No Log available with ERRORS:
### ERROR
```
Thread-16 :: [497ec10] Failed doing webui callback: Traceback (most recent call last):
  File "/opt/sickrage/sickbeard/webserve.py", line 287, in async_call
    result = function(**kwargs)
  File "/opt/sickrage/sickbeard/webserve.py", line 2349, in searchIndexersForShowName
    indexerResults = t[searchTerm]
  File "/opt/sickrage/lib/tvdb_api/tvdb_api.py", line 958, in __getitem__
    selected_series = self._getSeries(key)
  File "/opt/sickrage/lib/tvdb_api/tvdb_api.py", line 703, in _getSeries
    raise tvdb_shownotfound("Show search returned zero results (cannot find show on TVDB)")
tvdb_shownotfound: Show search returned zero results (cannot find show on TVDB)

```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators
