### ISSUE TITLE
[APP SUBMITTED]: unhashable type: 'dict'

### ISSUE THREAD

**Issue by tgharib** [SickRage/sickrage-issues#1112]
### INFO
Python Version: **2.7.11 (default, Dec  6 2015, 15:43:46) [GCC 5.2.0]**
Operating System: **Linux-4.4.1-2-aufs_friendly-x86_64-with-glibc2.2.5**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@9149089e176cd9da6b6ac0c023169e0c3102d2d9
No Log available with ERRORS:
### ERROR
```
SEARCHQUEUE-DAILY-SEARCH :: [TransmitTheNet] :: [9149089] Failed parsing provider. Traceback: Traceback (most recent call last):
  File "/opt/sickrage/sickbeard/providers/transmitthenet.py", line 141, in search
    download_url = urljoin(self.urls, download_item['href'])
  File "/usr/lib/python2.7/urlparse.py", line 259, in urljoin
    urlparse(base, '', allow_fragments)
  File "/usr/lib/python2.7/urlparse.py", line 143, in urlparse
    tuple = urlsplit(url, scheme, allow_fragments)
  File "/usr/lib/python2.7/urlparse.py", line 176, in urlsplit
    cached = _parse_cache.get(key, None)
TypeError: unhashable type: 'dict'

```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by SickRage2** [comment]
Thanks for the issue report! Before a real human comes by, please make sure your report has all the below criteria checked

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [ ] Post debug logs, either inline (for smaller logs) or using gist

Please make sure you also read [how to create an issue](https://github.com/SickRage/sickrage-issues/blob/master/README.md) and followed all of the steps. 

The title should describe your issue. Having "SR not working" or "I get this bug" for 100 issues, isn't really helpful. We will close issues if there isn't enough information.

Sometimes the devs may seem like grunts and respond with short answers. This isn't (always) because the dev hates you, but because he's on mobile or busy fixing bugs. If something isn't clear, please let us know, and this bot may get updated to automatically answer you.

Thanks!

**Comment by tgharib** [comment]
TTN parsing was working fine 4+ days ago but it seems to be broken now. I'm not sure if this is just a problem on my end or TTN website was updated.

I'm not sure why there are no logs attached since I did enable debug logging.

**Comment by porkchop34** [comment]
### INFO
Python Version: **2.7.11 (v2.7.11:6d1b6a68f775, Dec  5 2015, 20:40:30) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-7-6.1.7601-SP1**
Locale: cp1252
Branch: **master**
Commit: SickRage/SickRage@9149089e176cd9da6b6ac0c023169e0c3102d2d9
No Log available with ERRORS:
### ERROR
```
SEARCHQUEUE-MANUAL-295647 :: [TransmitTheNet] :: [9149089] Failed parsing provider. Traceback: Traceback (most recent call last):
  File "C:\SickRage\sickbeard\providers\transmitthenet.py", line 141, in search
    download_url = urljoin(self.urls, download_item['href'])
  File "C:\Python27\lib\urlparse.py", line 259, in urljoin
    urlparse(base, '', allow_fragments)
  File "C:\Python27\lib\urlparse.py", line 143, in urlparse
    tuple = urlsplit(url, scheme, allow_fragments)
  File "C:\Python27\lib\urlparse.py", line 176, in urlsplit
    cached = _parse_cache.get(key, None)
TypeError: unhashable type: 'dict'

```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by porkchop34** [comment]
### INFO
Python Version: **2.7.11 (v2.7.11:6d1b6a68f775, Dec  5 2015, 20:40:30) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-7-6.1.7601-SP1**
Locale: cp1252
Branch: **master**
Commit: SickRage/SickRage@9149089e176cd9da6b6ac0c023169e0c3102d2d9
No Log available with ERRORS:
### ERROR
```
SEARCHQUEUE-MANUAL-274431 :: [TransmitTheNet] :: [9149089] Failed parsing provider. Traceback: Traceback (most recent call last):
  File "C:\SickRage\sickbeard\providers\transmitthenet.py", line 141, in search
    download_url = urljoin(self.urls, download_item['href'])
  File "C:\Python27\lib\urlparse.py", line 259, in urljoin
    urlparse(base, '', allow_fragments)
  File "C:\Python27\lib\urlparse.py", line 143, in urlparse
    tuple = urlsplit(url, scheme, allow_fragments)
  File "C:\Python27\lib\urlparse.py", line 176, in urlsplit
    cached = _parse_cache.get(key, None)
TypeError: unhashable type: 'dict'

```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by porkchop34** [comment]
### INFO
Python Version: **2.7.11 (v2.7.11:6d1b6a68f775, Dec  5 2015, 20:40:30) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-7-6.1.7601-SP1**
Locale: cp1252
Branch: **master**
Commit: SickRage/SickRage@9149089e176cd9da6b6ac0c023169e0c3102d2d9
No Log available with ERRORS:
### ERROR
```
SEARCHQUEUE-BACKLOG-273181 :: [TransmitTheNet] :: [9149089] Failed parsing provider. Traceback: Traceback (most recent call last):
  File "C:\SickRage\sickbeard\providers\transmitthenet.py", line 141, in search
    download_url = urljoin(self.urls, download_item['href'])
  File "C:\Python27\lib\urlparse.py", line 259, in urljoin
    urlparse(base, '', allow_fragments)
  File "C:\Python27\lib\urlparse.py", line 143, in urlparse
    tuple = urlsplit(url, scheme, allow_fragments)
  File "C:\Python27\lib\urlparse.py", line 176, in urlsplit
    cached = _parse_cache.get(key, None)
TypeError: unhashable type: 'dict'

```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by porkchop34** [comment]
Hey,

I hadn't ran my Sickrage updates for the past few days until last night.

Downloads of episodes for Sunday Evening/Monday Night worked fine.

After the update, this error has cropped up.

**Comment by nitedevil** [comment]
### INFO
Python Version: **2.7.10 (default, May 23 2015, 09:44:00) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-8-6.2.9200**
Locale: cp1252
Branch: **master**
Commit: SickRage/SickRage@9149089e176cd9da6b6ac0c023169e0c3102d2d9
No Log available with ERRORS:
### ERROR
```
SEARCHQUEUE-DAILY-SEARCH :: [TransmitTheNet] :: [9149089] Failed parsing provider. Traceback: Traceback (most recent call last):
  File "C:\SickRage\sickbeard\providers\transmitthenet.py", line 141, in search
    download_url = urljoin(self.urls, download_item['href'])
  File "C:\Python27\lib\urlparse.py", line 259, in urljoin
    urlparse(base, '', allow_fragments)
  File "C:\Python27\lib\urlparse.py", line 143, in urlparse
    tuple = urlsplit(url, scheme, allow_fragments)
  File "C:\Python27\lib\urlparse.py", line 176, in urlsplit
    cached = _parse_cache.get(key, None)
TypeError: unhashable type: 'dict'

```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by nitedevil** [comment]
### INFO
Python Version: **2.7.10 (default, May 23 2015, 09:44:00) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-8-6.2.9200**
Locale: cp1252
Branch: **master**
Commit: SickRage/SickRage@9149089e176cd9da6b6ac0c023169e0c3102d2d9
No Log available with ERRORS:
### ERROR
```
SEARCHQUEUE-MANUAL-295681 :: [TransmitTheNet] :: [9149089] Failed parsing provider. Traceback: Traceback (most recent call last):
  File "C:\SickRage\sickbeard\providers\transmitthenet.py", line 141, in search
    download_url = urljoin(self.urls, download_item['href'])
  File "C:\Python27\lib\urlparse.py", line 259, in urljoin
    urlparse(base, '', allow_fragments)
  File "C:\Python27\lib\urlparse.py", line 143, in urlparse
    tuple = urlsplit(url, scheme, allow_fragments)
  File "C:\Python27\lib\urlparse.py", line 176, in urlsplit
    cached = _parse_cache.get(key, None)
TypeError: unhashable type: 'dict'

```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators
