### ISSUE TITLE
Problem when start/restart Sickrage

### ISSUE THREAD

**Issue by 03397** [SickRage/sickrage-issues#1119]
### Before submitting your issue:

Enable debug logging in SickRage settings, reproduce the error (be sure to disable after the bug is fixed)

Branch/Commit: 9149089e176cd9da6b6ac0c023169e0c3102d2d9
OS: 	Linux-3.4.6-x86_64-with-glibc2.4
What you did: Start/restart sickrage
What happened: If Sickrage starts for first time it starts but it is giving the error message below. If restart Sickrage it does not. The process is going dead. I am using Python Version:	2.7.9 (default, Mar 24 2015, 00:42:24) [GCC 4.1.3 20070929 (prerelease) (Ubuntu 4.1.2-16ubuntu2)] with SSL Version:	OpenSSL 0.9.8e 23 Feb 2007 if this helps.

What you expected:
Logs:
```
PASTE LOGS HERE
```

AAOSError: [Errno 2] No such file or directory
AA    raise child_exception
AA  File "/share/MD0_DATA/.qpkg/Python/lib/python2.7/subprocess.py", line 1335, in _execute_child
AA    errread, errwrite)
AA  File "/share/MD0_DATA/.qpkg/Python/lib/python2.7/subprocess.py", line 710, in __init__
AA    subprocess.Popen(popen_list, cwd=os.getcwd())
AA  File "/share/MD0_DATA/.qpkg/SickRage/SickBeard.py", line 556, in shutdown
AA    self.callback(type)
AA  File "/share/MD0_DATA/.qpkg/SickRage/sickbeard/event_queue.py", line 41, in run
AATraceback (most recent call last):

**Comment by SickRage2** [comment]
Thanks for the issue report! Before a real human comes by, please make sure your report has all the below criteria checked

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [x] Post debug logs, either inline (for smaller logs) or using gist
- [x] Please wrap inline logs inside \`\`\` and \`\`\` for readability

Please make sure you also read [how to create an issue](https://github.com/SickRage/sickrage-issues/blob/master/README.md) and followed all of the steps. 

The title should describe your issue. Having "SR not working" or "I get this bug" for 100 issues, isn't really helpful. We will close issues if there isn't enough information.

Sometimes the devs may seem like grunts and respond with short answers. This isn't (always) because the dev hates you, but because he's on mobile or busy fixing bugs. If something isn't clear, please let us know, and this bot may get updated to automatically answer you.

Thanks!

**Comment by neoatomic** [comment]
@03397 Seems your python package isn't working properly. This is a common issue on QNAP devices because of an outdated package etc...
Here you can find a guide how to setup a proper python package so Sickrage will run fine, and without SSL errors. : 

http://forum.qnap.com/viewtopic.php?f=223&t=118366#p525730
