### ISSUE TITLE
[APP SUBMITTED]: (10053, 'Software caused connection abort')

### ISSUE THREAD

**Issue by gmusgrave** [SickRage/sickrage-issues#1199]
### INFO
Python Version: **2.7.11 (v2.7.11:6d1b6a68f775, Dec  5 2015, 20:40:30) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-7-6.1.7601-SP1**
Locale: cp1252
Branch: **master**
Commit: SickRage/SickRage@0a1f476a63c552ffd4aae3a9a1e7203ce8707540

This problem occurs frequently (a few times most days).

No Log available with ERRORS:
### ERROR
```
SEARCHQUEUE-DAILY-SEARCH :: [ThePirateBay] :: [0a1f476] Unknown exception in getURL https://thepiratebay.se/browse/200 Error: u'error 10053 : Software caused connection abort'
```

DEBUG was on, and here is the relevant (I think!) part of the log:
```
2016-03-13 05:07:40 DEBUG    SEARCHQUEUE-DAILY-SEARCH :: [ThePirateBay] :: [0a1f476] Search Mode: RSS
2016-03-13 05:07:59 ERROR    SEARCHQUEUE-DAILY-SEARCH :: [ThePirateBay] :: [0a1f476] Unknown exception in getURL https://thepiratebay.se/browse/200 Error: u'error 10053 : Software caused connection abort'
Traceback (most recent call last):
  File "C:\SickRage\sickbeard\helpers.py", line 1430, in getURL
    headers=headers, cookies=cookies, proxies=proxies, verify=verify
  File "C:\SickRage\lib\requests\sessions.py", line 468, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\SickRage\lib\requests\sessions.py", line 576, in send
    r = adapter.send(request, **kwargs)
  File "C:\SickRage\lib\cachecontrol\adapter.py", line 46, in send
    resp = super(CacheControlAdapter, self).send(request, **kw)
  File "C:\SickRage\lib\requests\adapters.py", line 376, in send
    timeout=timeout
  File "C:\SickRage\lib\requests\packages\urllib3\connectionpool.py", line 559, in urlopen
    body=body, headers=headers)
  File "C:\SickRage\lib\requests\packages\urllib3\connectionpool.py", line 376, in _make_request
    httplib_response = conn.getresponse(buffering=True)
  File "C:\Python27\lib\httplib.py", line 1136, in getresponse
    response.begin()
  File "C:\Python27\lib\httplib.py", line 453, in begin
    version, status, reason = self._read_status()
  File "C:\Python27\lib\httplib.py", line 409, in _read_status
    line = self.fp.readline(_MAXLINE + 1)
  File "C:\Python27\lib\socket.py", line 480, in readline
    data = self._sock.recv(self._rbufsize)
  File "C:\SickRage\lib\requests\packages\urllib3\contrib\pyopenssl.py", line 196, in recv
    return self.recv(*args, **kwargs)
  File "C:\SickRage\lib\requests\packages\urllib3\contrib\pyopenssl.py", line 179, in recv
    data = self.connection.recv(*args, **kwargs)
SysCallError: (10053, 'Software caused connection abort')
2016-03-13 05:07:59 DEBUG    SEARCHQUEUE-DAILY-SEARCH :: [ThePirateBay] :: [0a1f476] Traceback (most recent call last):
  File "C:\SickRage\sickbeard\helpers.py", line 1430, in getURL
    headers=headers, cookies=cookies, proxies=proxies, verify=verify
  File "C:\SickRage\lib\requests\sessions.py", line 468, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\SickRage\lib\requests\sessions.py", line 576, in send
    r = adapter.send(request, **kwargs)
  File "C:\SickRage\lib\cachecontrol\adapter.py", line 46, in send
    resp = super(CacheControlAdapter, self).send(request, **kw)
  File "C:\SickRage\lib\requests\adapters.py", line 376, in send
    timeout=timeout
  File "C:\SickRage\lib\requests\packages\urllib3\connectionpool.py", line 559, in urlopen
    body=body, headers=headers)
  File "C:\SickRage\lib\requests\packages\urllib3\connectionpool.py", line 376, in _make_request
    httplib_response = conn.getresponse(buffering=True)
  File "C:\Python27\lib\httplib.py", line 1136, in getresponse
    response.begin()
  File "C:\Python27\lib\httplib.py", line 453, in begin
    version, status, reason = self._read_status()
  File "C:\Python27\lib\httplib.py", line 409, in _read_status
    line = self.fp.readline(_MAXLINE + 1)
  File "C:\Python27\lib\socket.py", line 480, in readline
    data = self._sock.recv(self._rbufsize)
  File "C:\SickRage\lib\requests\packages\urllib3\contrib\pyopenssl.py", line 196, in recv
    return self.recv(*args, **kwargs)
  File "C:\SickRage\lib\requests\packages\urllib3\contrib\pyopenssl.py", line 179, in recv
    data = self.connection.recv(*args, **kwargs)
SysCallError: (10053, 'Software caused connection abort')

2016-03-13 05:07:59 DEBUG    SEARCHQUEUE-DAILY-SEARCH :: [ThePirateBay] :: [0a1f476] URL did not return data, maybe try a custom url, or a different one
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by SickRage2** [comment]
Thanks for the issue report! Before a real human comes by, please make sure your report has all the below criteria checked

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [ ] Post debug logs, either inline (for smaller logs) or using gist

Please make sure you also read [how to create an issue](https://github.com/SickRage/sickrage-issues/blob/master/README.md) and followed all of the steps. 

The title should describe your issue. Having "SR not working" or "I get this bug" for 100 issues, isn't really helpful. We will close issues if there isn't enough information.

Sometimes the devs may seem like grunts and respond with short answers. This isn't (always) because the dev hates you, but because he's on mobile or busy fixing bugs. If something isn't clear, please let us know, and this bot may get updated to automatically answer you.

Thanks!

**Comment by gmusgrave** [comment]
### INFO
Python Version: **2.7.11 (v2.7.11:6d1b6a68f775, Dec  5 2015, 20:40:30) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-7-6.1.7601-SP1**
Locale: cp1252
Branch: **master**
Commit: SickRage/SickRage@0a1f476a63c552ffd4aae3a9a1e7203ce8707540
No Log available with ERRORS:
### ERROR
```
SEARCHQUEUE-DAILY-SEARCH :: [NZB.Cat] :: [0a1f476] Unknown exception in getURL https://nzb.cat/api Error: u'error 10053 : Software caused connection abort'
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by miigotu** [comment]
Looks like your connection is unreliable. server connecting over wifi maybe? router on the fritz?

**Comment by gmusgrave** [comment]
Interesting... this has been happening for a couple of weeks, two to five times a day (over several committs).

I'm not using a wireless connection, and there are no issues I'm aware of with anything else. However, if this message represents a local connectivity problem, then I'll do some troubleshooting to try to find a subtle connection issue.

Thanks.

**Comment by miigotu** [comment]
Yeah, its usually when a connection drops out during a read. OFC it could be something else, but I haven't seen anyone else having this issue so far.

**Comment by gmusgrave** [comment]
Thanks. I'll investigate on my end.
