### ISSUE TITLE
SSL to SABNZDB Failed After Upgrade 

### ISSUE THREAD

**Issue by Vodka2014** [SickRage/sickrage-issues#1201]
Hi All

Since the upgrade SSL to SABNZDB has stopped working. If i change it to HTTP then it connects and works

Branch: master
Commit: 0a1f476a63c552ffd4aae3a9a1e7203ce8707540
Version: 2016.03.10-1
OS: Synology
What you did: I upgraded to the last version of SickRage
What happened: SSL to SABNZDB failed
What you expected: SSL to SABNZDB failed When it should work. HTTPS://IP:PORT
Logs:
```
AASSLError: [SSL: TLSV1_ALERT_UNKNOWN_CA] tlsv1 alert unknown ca (_ssl.c:1751)
AA  File "", line 3, in raise_exc_info
AA    raise_exc_info(self._exc_info)
AA  File "/usr/local/sickrage/var/SickRage/lib/tornado/concurrent.py", line 215, in result
AA    value = future.result()
AA  File "/usr/local/sickrage/var/SickRage/lib/tornado/gen.py", line 870, in run
AA    quiet_exceptions=iostream.StreamClosedError)
AA  File "/usr/local/sickrage/var/SickRage/lib/tornado/http1connection.py", line 168, in _read_message
AA    yielded = self.gen.throw(*exc_info)
AA  File "/usr/local/sickrage/var/SickRage/lib/tornado/gen.py", line 876, in run
AA    raise_exc_info(self._exc_info)
AA  File "/usr/local/sickrage/var/SickRage/lib/tornado/concurrent.py", line 215, in result
AA    value = future.result()
AA  File "/usr/local/sickrage/var/SickRage/lib/tornado/gen.py", line 870, in run
AA    ret = yield conn.read_response(request_delegate)
AA  File "/usr/local/sickrage/var/SickRage/lib/tornado/http1connection.py", line 693, in _server_request_loop
AATraceback (most recent call last):
```

**Comment by SickRage2** [comment]
Thanks for the issue report! Before a real human comes by, please make sure your report has all the below criteria checked

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [x] Post debug logs, either inline (for smaller logs) or using gist
- [x] Please wrap inline logs inside \`\`\` and \`\`\` for readability

Please make sure you also read [how to create an issue](https://github.com/SickRage/sickrage-issues/blob/master/README.md) and followed all of the steps. 

The title should describe your issue. Having "SR not working" or "I get this bug" for 100 issues, isn't really helpful. We will close issues if there isn't enough information.

Sometimes the devs may seem like grunts and respond with short answers. This isn't (always) because the dev hates you, but because he's on mobile or busy fixing bugs. If something isn't clear, please let us know, and this bot may get updated to automatically answer you.

Thanks!

**Comment by Vodka2014** [comment]
I just updated again and still SSL is failing.

**Comment by neoatomic** [comment]
SABNZBd had recently an update. And introduced an issue concerning the SSL connection.  (btw. This is not an Sickrage problem.)
Might want to check the SABNZBd forums for more information.

From what i heard http should still work fine, so would advice to switch to http for the time.

**Comment by cpu123** [comment]
I've got the same issue, my SAB synopackage has not had an update lately (I'm on 0.7.20, released October 2015) - issue seems to only have occurred since the recent SickRage update.

**Comment by Vodka2014** [comment]
@neoatomic i am also on 0.7.20 and this issue only started last week when SickRage pushed out a big update.

**Comment by neoatomic** [comment]
Thanks for reporting back, looks to be a separate issue than. The one i heard about SSL on the new  Sabnzbd 1.0 rc5?

Can you provide a little more info.?  Like does the test connection button work.? And does http work etc.? Also both of you are on a Synology.? (dsm 5.2 or 6?)

Also try to shutdown SR and remove the cache.db, then restart.

**Comment by cpu123** [comment]
Test connection button does not work. Error in the log is:

Thread-14 :: [24199e3] Connection error to getURL https://192.168.1.10:9090/api Error: u'error ("bad handshake: Error([(\'SSL routines\', \'ssl3_get_server_certificate\', \'certificate verify failed\')],)",)'

I'm on a synology, DSM 5.2

The issue remains after shutting down, removing cache.db and restarting.

**Comment by neoatomic** [comment]
Strange that only Syno's seem to be effected....

See if you can disable this setting and try again. : 

Settings --> General --> Advanced Settings ---> `Verify SSL Certs`

**Comment by cpu123** [comment]
Yep thats fixed it.

I'm 90% certain that option was unchecked previously, everything was working just fine until recent updates (unclear when the problem first started, last nzb was downloaded on 11th March so sometime after then!)

**Comment by Vodka2014** [comment]
@neoatomic removing this setting worked now :) Thanks for this. So will there be a update to resolve this issue in future at all.

Thanks Again

**Comment by rutgerhendriks** [comment]
@neoatomic Actually, I have the same problem on OpenMediaVault. Also here disabling the 'Verify SSL Certs' options solves it.

**Comment by neoatomic** [comment]
@rutgerhendriks Bedankt. Than its not just the Synology effected.

**Comment by Vodka2014** [comment]
@neoatomic I just saw this - https://github.com/sabnzbd/sabnzbd/releases/tag/1.0.0/

So lets just hope that SickRage will work with the new version.
