### ISSUE TITLE
Schedule Page: A mako error has occured. 

### ISSUE THREAD

**Issue by doublegalz** [SickRage/sickrage-issues#1208]
### Before submitting your issue:

Enable debug logging in SickRage settings, reproduce the error (be sure to disable after the bug is fixed)

Branch/Commit: master/24199e34fe797298f734ef2765a701d9663e5b47
OS: Windows 7 64bit Enterprise
What you did: Click on Schedule
What happened: Getting the error "Mako Error
A mako error has occured.
If this happened during an update a simple page refresh may be the solution.
Mako errors that happen during updates may be a one time error if there were significant ui changes."
What you expected: Expected to see missed and upcoming shows
Logs:
https://gist.github.com/doublegalz/d785a8251fe16f76330c
PASTE LOGS HERE
```
2016-03-14 08:54:49 ERROR    DAILYSEARCHER :: [24199e3] Exception generated in thread DAILYSEARCHER: tzinfo.utcoffset() returned 1440; must be in -1439 .. 1439
Traceback (most recent call last):
  File "D:\SickRage\sickbeard\scheduler.py", line 106, in run
    self.action.run(self.force)
  File "D:\SickRage\sickbeard\dailysearcher.py", line 59, in run
    curTime = datetime.datetime.now(network_timezones.sb_timezone)
ValueError: tzinfo.utcoffset() returned 1440; must be in -1439 .. 1439
2016-03-14 08:54:49 DEBUG    DAILYSEARCHER :: [24199e3] 'Traceback (most recent call last):\n  File "D:\\SickRage\\sickbeard\\scheduler.py", line 106, in run\n    self.action.run(self.force)\n  File "D:\\SickRage\\sickbeard\\dailysearcher.py", line 59, in run\n    curTime = datetime.datetime.now(network_timezones.sb_timezone)\nValueError: tzinfo.utcoffset() returned 1440; must be in -1439 .. 1439\n'
```

**Comment by SickRage2** [comment]
Thanks for the issue report! Before a real human comes by, please make sure your report has all the below criteria checked

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [x] Post debug logs, either inline (for smaller logs) or using gist

Please make sure you also read [how to create an issue](https://github.com/SickRage/sickrage-issues/blob/master/README.md) and followed all of the steps. 

The title should describe your issue. Having "SR not working" or "I get this bug" for 100 issues, isn't really helpful. We will close issues if there isn't enough information.

Sometimes the devs may seem like grunts and respond with short answers. This isn't (always) because the dev hates you, but because he's on mobile or busy fixing bugs. If something isn't clear, please let us know, and this bot may get updated to automatically answer you.

Thanks!

**Comment by miigotu** [comment]
Try installing pywin32 (try both the 32 bit and 64 bit version)

**Comment by miigotu** [comment]
That commit should fix it. If it doesnt, ping me here again. Thanks.

**Comment by doublegalz** [comment]
I tried the latest commit and I already have Python 2.7 pywin32-219 installed on my computer.  I tried the latest, but need to upgrade Python for that.  I have tried that in the past and it broke NZBGet so I haven't upgraded Python since.

**Comment by miigotu** [comment]
you need to stick with a python 2.7.x

**Comment by miigotu** [comment]
I had to revert https://github.com/SickRage/SickRage/commit/6bda6b376c4c79215edf57ee7590478418c7bbc0

because it broke daily search. If the dateutil update alone doesnt fix this error for you then I need to look at patching dateutil.

**Comment by doublegalz** [comment]
I just updated to 00bb35e92a5b2909fafaa5ee6255ce6699ff8ae7.  Still the same issue.  It also appears  to not be downloading any shows automatically, not sure after this last update though.  I will check in the morning, but I did have to download everything from last night manually.

**Comment by miigotu** [comment]
changing the timezone on your machine by 1 hour will fix it temporarily

What timezone do you have set?

**Comment by doublegalz** [comment]
I changed my clock by on my computer back 1 hour.  It is set to CST.  That did not fix even after restarting sickrage.

**Comment by erikhubers** [comment]
I'm also having this issue after updating to the latest version.

Branch:  	 	 	master
Commit:  	 	 	00bb35e92a5b2909fafaa5ee6255ce6699ff8ae7
Version:  	 	 	2016.03.10-1
Python version 	2.7.2 (default, Jun 12 2011, 15:08:59) [MSC v.1500 32 bit (Intel)]
OS: 	 	 	 	Windows Server 2012 R2
Timezone: 	 	(UTC+01:00) Brussels, Copenhagen, Madrid, Paris

**Comment by miigotu** [comment]
Could you try the `tzlocal-test` branch?

**Comment by doublegalz** [comment]
I actually left this morning to go out of town. If I have time this evening, I will remote in and test the branch. Thanks!

**Comment by doublegalz** [comment]
I am still having this issue with the Mako error.  I have not tried updating to the test branch.  Did you still want to to do that?

**Comment by miigotu** [comment]
You can try the tzlocal-test branch

**Comment by doublegalz** [comment]
Ok, I have never switches branches before, what is the process?

**Comment by duramato** [comment]
Add your github credentials on advanced settings and there should appear `tzlocal-test` on checout branch

**Comment by doublegalz** [comment]
Ok, I added my creds and the only other options was Develop in the drop
down.  I switched to it, but am still having the Mako error.

**Comment by erikhubers** [comment]
Sorry for my very late reply on your inquiry, I was really busy @work.

I've switched to tzlocal-test but the issue still occurs.

Branch: tzlocal-test
Commit: 41035bbbb8499707a595d32aca2dc89cd0279c25
Version: 2016.03.20-1
Python version 2.7.2 (default, Jun 12 2011, 15:08:59) [MSC v.1500 32 bit (Intel)]
OS: Windows Server 2012 R2
Timezone: (UTC+01:00) Brussels, Copenhagen, Madrid, Paris

Also this error message caught my attention (occurred while still on master branch)

2016-03-21 20:19:27 DAILYSEARCHER :: [dd619c6] Exception generated in thread DAILYSEARCHER: tzinfo.utcoffset() returned 1440; must be in -1439 .. 1439

**Comment by miigotu** [comment]
Did you restart sickrage after switching branches?

**Comment by erikhubers** [comment]
@miigotu: I'm very sorry, I forgot to do that -_-. It works fine now :)

**Comment by doublegalz** [comment]
Bingo, the python upgrade to 2.7.11 did the trick, I am back on master and it seems to be working fine.  Thanks for all of your help.

**Comment by miigotu** [comment]
@pganssle So that error is only confirmed to be happening for Python 2.7.2.  I will direct people to just update python, but maybe it will help you if someone reports it to you in the future.

**Comment by pganssle** [comment]
@miigotu How very odd, must be a bug in Python or something. Thanks for the info.

**Comment by hoshsadiq** [comment]
I'm using `2.7.9` and this is happening when trying add trakt shows to my library (http://localhost:8081/addShows/getTrendingShows/?traktList=anticipated). Nothing in the logs are being generated when I load that page.

**Comment by miigotu** [comment]
Sure you are using the right repo? Also, this issue tracker is deprecated, we use https://github.com/SickRage/SickRage/issues now

**Comment by hoshsadiq** [comment]
I'm using the right repo. Only realised this was the wrong old place for issues after I'd commented, have already raised the issue in the right place. Thanks!
