### ISSUE TITLE
[APP SUBMITTED]: can't compare offset-naive and offset-aware datetimes

### ISSUE THREAD

**Issue by lmctheboss** [SickRage/sickrage-issues#1209]
### INFO
Python Version: **2.7.10 (default, May 23 2015, 09:44:00) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-8-6.2.9200**
Locale: cp1252
Branch: **master**
Commit: SickRage/SickRage@6bda6b376c4c79215edf57ee7590478418c7bbc0
No Log available with ERRORS:
### ERROR
```
DAILYSEARCHER :: [6bda6b3] Exception generated in thread DAILYSEARCHER: can't compare offset-naive and offset-aware datetimes
```

```
2016-03-14 17:15:40 INFO     DAILYSEARCHER :: [6bda6b3] Searching for new released episodes ...
2016-03-14 17:15:40 ERROR    DAILYSEARCHER :: [6bda6b3] Exception generated in thread DAILYSEARCHER: can't compare offset-naive and offset-aware datetimes
Traceback (most recent call last):
  File "C:\SickRage\SickRage\sickbeard\scheduler.py", line 106, in run
    self.action.run(self.force)
  File "C:\SickRage\SickRage\sickbeard\dailysearcher.py", line 88, in run
    if air_time > curTime:
TypeError: can't compare offset-naive and offset-aware datetimes
2016-03-14 17:15:40 DEBUG    DAILYSEARCHER :: [6bda6b3] 'Traceback (most recent call last):\n  File "C:\\SickRage\\SickRage\\sickbeard\\scheduler.py", line 106, in run\n    self.action.run(self.force)\n  File "C:\\SickRage\\SickRage\\sickbeard\\dailysearcher.py", line 88, in run\n    if air_time > curTime:\nTypeError: can\'t compare offset-naive and offset-aware datetimes\n'
2016-03-14 17:20:40 DEBUG    POSTPROCESSER :: [6bda6b3] Starting new thread: POSTPROCESSER
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by SickRage2** [comment]
Thanks for the issue report! Before a real human comes by, please make sure your report has all the below criteria checked

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [ ] Post debug logs, either inline (for smaller logs) or using gist

Please make sure you also read [how to create an issue](https://github.com/SickRage/sickrage-issues/blob/master/README.md) and followed all of the steps. 

The title should describe your issue. Having "SR not working" or "I get this bug" for 100 issues, isn't really helpful. We will close issues if there isn't enough information.

Sometimes the devs may seem like grunts and respond with short answers. This isn't (always) because the dev hates you, but because he's on mobile or busy fixing bugs. If something isn't clear, please let us know, and this bot may get updated to automatically answer you.

Thanks!

**Comment by lmctheboss** [comment]
[sickrage.txt](https://github.com/SickRage/sickrage-issues/files/172363/sickrage.txt)

**Comment by ejc1967** [comment]
**INFO**

Branch: master
Commit: 6bda6b376c4c79215edf57ee7590478418c7bbc0
Version: 2016.03.10-1
Python Version:	2.7.11 (default, Dec 17 2015, 15:58:38) [GCC 4.7.3 20130102 (prerelease)]
SSL Version:	OpenSSL 1.0.2e 3 Dec 2015
OS:	Linux-3.10.35-x86_64-with-glibc2.2.5
Locale:	None.None


Got the same error.
After a restart, daily search waits 10 minutes before starting, but when it does it fails and stops altogether.
Status is False after this in Status / scheduler view.

**Comment by fpellicciotti** [comment]
### INFO
Python Version: **2.7.10 (default, Oct 23 2015, 18:05:06) [GCC 4.2.1 Compatible Apple LLVM 7.0.0 (clang-700.0.59.5)]**
Operating System: **Darwin-15.3.0-x86_64-i386-64bit**
Locale: None
Branch: **master**
Commit: SickRage/SickRage@6bda6b376c4c79215edf57ee7590478418c7bbc0
No Log available with ERRORS:
### ERROR
```
DAILYSEARCHER :: [6bda6b3] Exception generated in thread DAILYSEARCHER: can't compare offset-naive and offset-aware datetimes
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by fpellicciotti** [comment]
In addition, daily search waits 15 (my interval) minutes before starting, but when it does it fails and stops right away.

Status is set to False in Status / scheduler view.

Therfore, daily search is disabled and not working in this version.

**Comment by Vodka2014** [comment]
### INFO
Python Version: **2.7.11 (default, Dec 17 2015, 15:58:38) [GCC 4.7.3 20130102 (prerelease)]**
Operating System: **Linux-3.10.35-x86_64-with-glibc2.2.5**
Locale: None
Branch: **master**
Commit: SickRage/SickRage@6bda6b376c4c79215edf57ee7590478418c7bbc0
No Log available with ERRORS:
### ERROR
```
DAILYSEARCHER :: [6bda6b3] Exception generated in thread DAILYSEARCHER: can't compare offset-naive and offset-aware datetimes
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by sdgarland35** [comment]
### INFO
Python Version: **2.7.6 (default, Jun 22 2015, 17:58:13) [GCC 4.8.2]**
Operating System: **Linux-3.16.0-57-generic-x86_64-with-Ubuntu-14.04-trusty**
Locale: None
Branch: **master**
Commit: SickRage/SickRage@6bda6b376c4c79215edf57ee7590478418c7bbc0
No Log available with ERRORS:
### ERROR
```
DAILYSEARCHER :: [6bda6b3] Exception generated in thread DAILYSEARCHER: can't compare offset-naive and offset-aware datetimes
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by wijmanb** [comment]
### INFO
Python Version: **2.7.11 (v2.7.11:6d1b6a68f775, Dec  5 2015, 20:40:30) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-10-10.0.10586**
Locale: cp1252
Branch: **master**
Commit: SickRage/SickRage@6bda6b376c4c79215edf57ee7590478418c7bbc0
No Log available with ERRORS:
### ERROR
```
DAILYSEARCHER :: [6bda6b3] Exception generated in thread DAILYSEARCHER: can't compare offset-naive and offset-aware datetimes
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by NicoLeOca** [comment]
### INFO
Python Version: **2.7.11 (default, Dec 17 2015, 14:08:17) [GCC 4.6.3]**
Operating System: **Linux-3.2.40-i686-with-glibc2.0**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@6bda6b376c4c79215edf57ee7590478418c7bbc0
No Log available with ERRORS:
### ERROR
```
DAILYSEARCHER :: [6bda6b3] Exception generated in thread DAILYSEARCHER: can't compare offset-naive and offset-aware datetimes
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by ripper1967** [comment]
### INFO
Python Version: **2.7.11 (v2.7.11:6d1b6a68f775, Dec  5 2015, 20:40:30) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-7-6.1.7601-SP1**
Locale: cp1252
Branch: **master**
Commit: SickRage/SickRage@6bda6b376c4c79215edf57ee7590478418c7bbc0
No Log available with ERRORS:
### ERROR
```
DAILYSEARCHER :: [6bda6b3] Exception generated in thread DAILYSEARCHER: can't compare offset-naive and offset-aware datetimes
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by mrNobody1337** [comment]
### INFO
Python Version: **2.7.6 (default, Jun 22 2015, 17:58:13) [GCC 4.8.2]**
Operating System: **Linux-3.19.0-51-generic-x86_64-with-Ubuntu-14.04-trusty**
Locale: None
Branch: **master**
Commit: SickRage/SickRage@6bda6b376c4c79215edf57ee7590478418c7bbc0
No Log available with ERRORS:
### ERROR
```
DAILYSEARCHER :: [6bda6b3] Exception generated in thread DAILYSEARCHER: can't compare offset-naive and offset-aware datetimes
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by fpellicciotti** [comment]
The latest commits seems to have fixed the problem. I no longer get the exception error and the service runs ever 15 (my schedule) mins.

thanks

**Comment by neoatomic** [comment]
Indeed, the problem has been fixed. Make sure you update to the latest version. :)

**Comment by lmctheboss** [comment]
@neoatomic Thanks a lot. All is working again.

**Comment by gshlomi** [comment]
### INFO
Python Version: **2.7.11 (default, Dec 15 2015, 16:46:19) [GCC 4.8.4]**
Operating System: **Linux-4.1.18-unRAID-x86_64-with-Ubuntu-14.04-trusty**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@dbf446a51f8b6e900aba41e947ef9f925ae12714
No Log available with ERRORS:
### ERROR
```
DAILYSEARCHER :: [dbf446a] Exception generated in thread DAILYSEARCHER: can't compare offset-naive and offset-aware datetimes
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators
