### ISSUE TITLE
Fails to search in Elitetorrent Provider

### ISSUE THREAD

**Issue by curnacat** [SickRage/sickrage-issues#1210]
### Before submitting your issue:

Enable debug logging in SickRage settings, reproduce the error (be sure to disable after the bug is fixed)

Branch: master
Commit: 6bda6b376c4c79215edf57ee7590478418c7bbc0
Version: 2016.03.10-1
 OS:	Linux-3.19.8-x86_64-with-glibc2.2.5 (QNAP)

Every time there is a search using Elitetorrent provider I get an error and doesn't work.

Logs:
```
2016-03-14 17:28:54 SEARCHQUEUE-MANUAL-292262 :: [EliteTorrent] :: [6bda6b3] Failed parsing provider. Traceback: Traceback (most recent call last):
  File "/share/CE_CACHEDEV1_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/sickbeard/providers/elitetorrent.py", line 97, in search
    torrent_rows = torrent_table.find_ll('tr') if torrent_table else []
TypeError: 'NoneType' object is not callable

AA
AATypeError: 'NoneType' object is not callable
AA    torrent_rows = torrent_table.find_ll('tr') if torrent_table else []
AA  File "/share/CE_CACHEDEV1_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/sickbeard/providers/elitetorrent.py", line 97, in search
2016-03-14 17:08:00 WARNING  SEARCHQUEUE-DAILY-SEARCH :: [EliteTorrent] :: [24199e3] Failed parsing provider. Traceback: Traceback (most recent call last):
2016-03-14 17:07:12 INFO     SEARCHQUEUE-DAILY-SEARCH :: [24199e3] Beginning daily search for new episodes
```

**Comment by SickRage2** [comment]
Thanks for the issue report! Before a real human comes by, please make sure your report has all the below criteria checked

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [x] Post debug logs, either inline (for smaller logs) or using gist
- [x] Please wrap inline logs inside \`\`\` and \`\`\` for readability

Please make sure you also read [how to create an issue](https://github.com/SickRage/sickrage-issues/blob/master/README.md) and followed all of the steps. 

The title should describe your issue. Having "SR not working" or "I get this bug" for 100 issues, isn't really helpful. We will close issues if there isn't enough information.

Sometimes the devs may seem like grunts and respond with short answers. This isn't (always) because the dev hates you, but because he's on mobile or busy fixing bugs. If something isn't clear, please let us know, and this bot may get updated to automatically answer you.

Thanks!
