### ISSUE TITLE
[APP SUBMITTED]: 401 {u'documentation_url': u'https://developer.github.com/v3/auth#working-with-two-factor-authentication', u'message': u'Must specify two-factor authentication OTP code.'}

### ISSUE THREAD

**Issue by tuxfre** [SickRage/sickrage-issues#122]
### INFO
Python Version: **2.7.9 (default, Mar  1 2015, 13:48:22) [GCC 4.9.2]**
Operating System: **Linux-3.2.26-armv7l-with-debian-7.1**
Locale: unknown
Branch: **master**
Commit: SickRage/SickRage@1e8a1a0ede9b386f25e243c1c4e3814a520bd325
Link to Log: https://gist.github.com/fc47df010f62278bd256
### ERROR
```
Thread-31 :: Traceback (most recent call last):
  File "/opt/sickrage/SickRage/sickbeard/logger.py", line 249, in submit_errors
    gist = gh.get_user().create_gist(True, {"sickrage.log": InputFileContent(paste_data)})
  File "/opt/sickrage/SickRage/lib/github/AuthenticatedUser.py", line 473, in create_gist
    input=post_parameters
  File "/opt/sickrage/SickRage/lib/github/Requester.py", line 171, in requestJsonAndCheck
    return self.__check(*self.requestJson(verb, url, parameters, headers, input, cnx))
  File "/opt/sickrage/SickRage/lib/github/Requester.py", line 179, in __check
    raise self.__createException(status, responseHeaders, output)
TwoFactorException: 401 {u'documentation_url': u'https://developer.github.com/v3/auth#working-with-two-factor-authentication', u'message': u'Must specify two-factor authentication OTP code.'}

```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by duramato** [comment]
You need to set a token just for SR,when using 2 factor autentication

**Comment by tuxfre** [comment]
Thanks @duramato did just that and now it works ;)

(sorry for the noise)
