### ISSUE TITLE
found this in log about scheduler.py and dailsercher.py and timezones.py

### ISSUE THREAD

**Issue by autobaud** [SickRage/sickrage-issues#1230]
not sure if this is the right place to post, but saw this earlier in my log and it seems the shows that already aired a few hours ago didn't download...

````
AAValueError: need more than 1 value to unpack
AA    (key, val) = line.strip().rsplit(u':', 1)
AA  File "C:\SickRage\SickRage\sickbeard\network_timezones.py", line 57, in update_network_dict
AA    network_timezones.update_network_dict()
AA  File "C:\SickRage\SickRage\sickbeard\dailysearcher.py", line 52, in run
AA    self.action.run(self.force)
AA  File "C:\SickRage\SickRage\sickbeard\scheduler.py", line 106, in run
AATraceback (most recent call last):
2016-03-18 18:49:42 ERROR    DAILYSEARCHER :: [bc5e61a] Exception generated in thread DAILYSEARCHER: need more than 1 value to unpack
2016-03-18 18:49:42 INFO     DAILYSEARCHER :: [bc5e61a] Searching for new released episodes ...
````

**Comment by SickRage2** [comment]
Thanks for the issue report! Before a real human comes by, please make sure your report has all the below criteria checked

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [x] Post debug logs, either inline (for smaller logs) or using gist
- [ ] Please wrap inline logs inside \`\`\` and \`\`\` for readability

Please make sure you also read [how to create an issue](https://github.com/SickRage/sickrage-issues/blob/master/README.md) and followed all of the steps. 

The title should describe your issue. Having "SR not working" or "I get this bug" for 100 issues, isn't really helpful. We will close issues if there isn't enough information.

Sometimes the devs may seem like grunts and respond with short answers. This isn't (always) because the dev hates you, but because he's on mobile or busy fixing bugs. If something isn't clear, please let us know, and this bot may get updated to automatically answer you.

Thanks!

**Comment by miigotu** [comment]
Already fixed, thanks! =P
