### ISSUE TITLE
Cannot process episodes containing "～" in episode name

### ISSUE THREAD

**Issue by autronix** [SickRage/sickrage-issues#1237]
Branch/Commit: master/bc5e61a8f96a8abae80ae78fbf261ff3023a664d
Python Version:	2.7.8 (default, Jun 30 2014, 16:03:49) [MSC v.1500 32 bit (Intel)]
OS:	Windows 10
Locale:	en_CA.cp1252

What you did: Manual post processing/sabnzbd auto processing
What happened: processing does not complete successfully (ERROR) - files are transferred though
What you expected: successful processing

Additional notes: this has happened with every episode for which data was obtained through the processing. The episodes that are causing this issue are all in the following format:
```
Heavy Object - 1x12 - 012 - Three-Legged Mountain Climbing Race is Risking One's Life ～Iguazu Mountains Bombardment Battle III～
```
As can be seen, every file name contains the `\uff5e` character, I've had similar errors with `\u301c`.

Here are my naming patterns:
``` 
Season 02\Show Name - S02E03 - Ep Name.ext #shows
Show Name - 2x03 - 003 - Ep Name.ext #anime
```

Error Log:
```
2016-03-20 04:48:44 Thread-23 :: [bc5e61a] Failed doing webui callback: Traceback (most recent call last):
  File "C:\Program Files (ext)\SickRage-master\sickbeard\webserve.py", line 287, in async_call
    result = function(**kwargs)
  File "C:\Program Files (ext)\SickRage-master\sickbeard\webserve.py", line 2286, in processEpisode
    is_priority=argToBool(is_priority), delete_on=argToBool(delete_on), failed=argToBool(failed), proc_type=type
  File "C:\Program Files (ext)\SickRage-master\sickbeard\processTV.py", line 156, in func_wrapper
    ret = func(*args, **kargs)
  File "C:\Program Files (ext)\SickRage-master\sickbeard\processTV.py", line 297, in processDir
    process_media(processPath, videoFiles, nzbName, process_method, force, is_priority, result)
  File "C:\Program Files (ext)\SickRage-master\sickbeard\processTV.py", line 575, in process_media
    result.result = processor.process()
  File "C:\Program Files (ext)\SickRage-master\sickbeard\postProcessor.py", line 1223, in process
    self._run_extra_scripts(ep_obj)
  File "C:\Program Files (ext)\SickRage-master\sickbeard\postProcessor.py", line 851, in _run_extra_scripts
    ep_location = ep_location.encode(sickbeard.SYS_ENCODING)
  File "C:\Python27\lib\encodings\cp1252.py", line 12, in encode
    return codecs.charmap_encode(input,errors,encoding_table)
UnicodeEncodeError: 'charmap' codec can't encode character u'\uff5e' in position 107: character maps to 
```

**Comment by SickRage2** [comment]
Thanks for the issue report! Before a real human comes by, please make sure your report has all the below criteria checked

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [ ] Post debug logs, either inline (for smaller logs) or using gist

Please make sure you also read [how to create an issue](https://github.com/SickRage/sickrage-issues/blob/master/README.md) and followed all of the steps. 

The title should describe your issue. Having "SR not working" or "I get this bug" for 100 issues, isn't really helpful. We will close issues if there isn't enough information.

Sometimes the devs may seem like grunts and respond with short answers. This isn't (always) because the dev hates you, but because he's on mobile or busy fixing bugs. If something isn't clear, please let us know, and this bot may get updated to automatically answer you.

Thanks!

**Comment by neoatomic** [comment]
Dont think much can be done here than just removing "～"  from the filename.
Windows doesn't play nice when it comes to Unicode.... :(

**Comment by miigotu** [comment]
I'd like to see your external script. Python wont allow me to pass unicode as an argument, but windows uses unicode natively....

So there is a conundrum, I cant leave it unicode or the popen fails, I cant use utf-8 because windows wont know how to decode it, and I cant use the SYS_ENCODING because charmap is latin-1 based...

**Comment by autronix** [comment]
Which external script are you referring to?

This is the first time I've ever had such an issue with episode naming personally, so it is not really common among the episodes I've downloaded.
I'm just reporting this as a bug following the error; I probably won't encounter this issue again, unless another show/scaper decides to use unsupported characters again in the episode titles.

My guess is either ignoring the offending characters (ie. check for encoding issues before encoding and replace or remove the character) would be a simple solution in these cases.
Then again I'm not familiar with the underlying python processes for encoding.

**Comment by miigotu** [comment]
Ignoring the character is not an option.

Say you have a file on disk:
`Heavy Object - 1x12 - 012 - Three-Legged Mountain Climbing Race is Risking One's Life ～Iguazu Mountains Bombardment Battle III～.mkv`

And you need to rename this file or simply check that it exists....

Replacing the character would not allow you to operate on that existing file.
