### ISSUE TITLE
Getting Issue is locked when trying to submit error

### ISSUE THREAD

**Issue by bluezed** [SickRage/sickrage-issues#1339]
Branch/Commit: master / bc5e61a
OS: Ubuntu 15.10
What you did: 
I forced a backlog search for a show and that returned the error below from TorrentProject. I then tried to submit the error from the log.
Please ignore the actual TorrentProject error as I found out in the meantime that they're doing API maintenance... This issue is purely about the submitting of the error from the log.

What happened: 
I got the message "Issue #1188 is locked, check GitHub to find info about the error."

What you expected: 
A new issue should have been submitted as this one seems unrelated to #1188.

Logs:
```
2016-03-21 08:26:07 INFO     Thread-18 :: Issue #1188 is locked, check GitHub to find info about the error.

AAValueError: No JSON object could be decoded
AA    raise ValueError("No JSON object could be decoded")
AA  File "/home/tv/.sickrage/lib/simplejson/decoder.py", line 353, in raw_decode
AA    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
AA  File "/home/tv/.sickrage/lib/simplejson/decoder.py", line 335, in decode
AA    return _default_decoder.decode(s)
AA  File "/home/tv/.sickrage/lib/simplejson/__init__.py", line 307, in loads
AA    return complexjson.loads(self.text, **kwargs)
AA  File "/home/tv/.sickrage/lib/requests/models.py", line 808, in json
AA    return resp if response_type == u'response' or response_type is None else resp.json() if response_type == u'json' else getattr(resp, response_type, resp)
AA  File "/home/tv/.sickrage/sickbeard/helpers.py", line 1443, in getURL
AA    return getURL(url, post_data, params, self.headers, timeout, self.session, **kwargs)
AA  File "/home/tv/.sickrage/sickrage/providers/GenericProvider.py", line 341, in get_url
AA    torrents = self.get_url(search_url, params=search_params, returns='json')
AA  File "/home/tv/.sickrage/sickbeard/providers/torrentproject.py", line 85, in search
AA    items_list += self.search(search_string, ep_obj=episode)
AA  File "/home/tv/.sickrage/sickrage/providers/GenericProvider.py", line 146, in find_search_results
AA    searchResults = curProvider.find_search_results(show, episodes, search_mode, manualSearch, downCurQuality)
AA  File "/home/tv/.sickrage/sickbeard/search.py", line 500, in searchProviders
AATraceback (most recent call last):
2016-03-21 08:25:46 ERROR    SEARCHQUEUE-BACKLOG-301824 :: [TorrentProject] :: [0f2c12e] Unknown exception while searching TorrentProject. Error: 'No JSON object could be decoded'
```

**Comment by SickRage2** [comment]
Thanks for the issue report! Before a real human comes by, please make sure your report has all the below criteria checked

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [x] Post debug logs, either inline (for smaller logs) or using gist
- [x] Please wrap inline logs inside \`\`\` and \`\`\` for readability

Please make sure you also read [how to create an issue](https://github.com/SickRage/sickrage-issues/blob/master/README.md) and followed all of the steps. 

The title should describe your issue. Having "SR not working" or "I get this bug" for 100 issues, isn't really helpful. We will close issues if there isn't enough information.

Sometimes the devs may seem like grunts and respond with short answers. This isn't (always) because the dev hates you, but because he's on mobile or busy fixing bugs. If something isn't clear, please let us know, and this bot may get updated to automatically answer you.

Thanks!

**Comment by miigotu** [comment]
Issue tracker is now on https://github.com/SickRage/SickRage
This repo is only staying open until remaining open issues are resolved. The issue submitter and all links now also point to the new issue tracker, as well as the wiki which has also moved to that repo.

The issue is locked.
https://github.com/SickRage/SickRage/issues/1188
