### ISSUE TITLE
UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 1: character maps to <undefined>

### ISSUE THREAD

**Issue by Stormblade** [SickRage/sickrage-issues#1340]
### Before submitting your issue:

Enable debug logging in SickRage settings, reproduce the error (be sure to disable after the bug is fixed)

Branch/Commit: master
OS: Windows 10
What you did:
Added Yu-Gi-Oh! Arc-V show
What happened:
Cannot view the Yu-Gi-Oh! Arc-V show page in sickrage, and daily search fails.

A mako error has occured.
If this happened during an update a simple page refresh may be the solution.
Mako errors that happen during updates may be a one time error if there were significant ui changes.

"File C:\Python27\lib\encodings\cp1252.py:15, in decode:
return codecs.charmap_decode(input,errors,decoding_table)
UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 38: character maps to "

What you expected:
Logs:
```
2016-03-21 13:16:59 DEBUG    SEARCHQUEUE-DAILY-SEARCH :: [9149089] Seeing if we need anything from Yu-Gi-Oh!
2016-03-21 13:16:59 DEBUG    SEARCHQUEUE-DAILY-SEARCH :: [9149089] Traceback (most recent call last):
  File "C:\NN\SickRage\sickbeard\search_queue.py", line 138, in run
    foundResults = search.searchForNeededEpisodes()
  File "C:\NN\SickRage\sickbeard\search.py", line 386, in searchForNeededEpisodes
    sickbeard.name_cache.buildNameCache(curShow)
  File "C:\NN\SickRage\sickbeard\name_cache.py", line 94, in buildNameCache
    name = sickbeard.helpers.full_sanitizeSceneName(name)
  File "C:\NN\SickRage\sickbeard\helpers.py", line 1042, in full_sanitizeSceneName
    return re.sub('[. -]', ' ', sanitizeSceneName(name)).lower().lstrip()
  File "C:\NN\SickRage\sickbeard\helpers.py", line 764, in sanitizeSceneName
    name = name.replace(x, "")
  File "C:\Python27\lib\encodings\cp1252.py", line 15, in decode
    return codecs.charmap_decode(input,errors,decoding_table)
UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 1: character maps to <undefined>
```

**Comment by SickRage2** [comment]
Thanks for the issue report! Before a real human comes by, please make sure your report has all the below criteria checked

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [x] Post debug logs, either inline (for smaller logs) or using gist
- [x] Please wrap inline logs inside \`\`\` and \`\`\` for readability

Please make sure you also read [how to create an issue](https://github.com/SickRage/sickrage-issues/blob/master/README.md) and followed all of the steps. 

The title should describe your issue. Having "SR not working" or "I get this bug" for 100 issues, isn't really helpful. We will close issues if there isn't enough information.

Sometimes the devs may seem like grunts and respond with short answers. This isn't (always) because the dev hates you, but because he's on mobile or busy fixing bugs. If something isn't clear, please let us know, and this bot may get updated to automatically answer you.

Thanks!

**Comment by miigotu** [comment]
Will be merged into develop after some testing, and to master in the next week or so.

**Comment by bluppfisk** [comment]
Problem seems to be back in the latest version. It won't post-process manually.
