### ISSUE TITLE
global name 'common' is not defined

### ISSUE THREAD

**Issue by stillie** [SickRage/sickrage-issues#1368]
### Before submitting your issue:

Enable debug logging in SickRage settings, reproduce the error (be sure to disable after the bug is fixed)

Branch/Commit: master
OS: ubuntu 14.04 LTS
What you did: Try to connect to Sickrage from external IP
What happened: Cant Log in
What you expected: Didnt Log in and displayed an error as below

BTW i have removed all private info

```
Error:

global name 'common' is not defined

Traceback

Traceback (most recent call last): 
File "/opt/sickrage/lib/tornado/web.py", line 1413, in _execute result = method(*self.path_args, **self.path_kwargs) 
File "/opt/sickrage/sickbeard/webserve.py", line 313, in post notifiers.notify_login(self.request.remote_ip) 
File "/opt/sickrage/sickbeard/notifiers/__init__.py", line 118, in notify_login n.notify_login(ipaddress) 
File "/opt/sickrage/sickbeard/notifiers/boxcar2.py", line 109, in notify_login update_text = common.notifyStrings[common.NOTIFY_LOGIN_TEXT] 
NameError: global name 'common' is not defined 

Request Info

body: username=admin&password={removed_password}&remember_me=1&submit=Login
files: {}
protocol: http
connection: 
body_arguments: {'username': ['admin'], 'remember_me': ['1'], 'password': ['{removed_password}'], 'submit': ['Login']}
uri: /login/?next=%2Ferrorlogs%2F
query_arguments: {'next': ['/errorlogs/']}
_start_time: 1458653942.33
headers: {'Origin': 'http://{removed_remote_url}:8081', 'Content-Length': '64', 'Accept-Language': 'en-US,en;q=0.8,en-ZA;q=0.6', 'Accept-Encoding': 'gzip, deflate', 'Connection': 'keep-alive', 'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8', 'Upgrade-Insecure-Requests': '1', 'Host': '{removed_remote_url}:8081', 'Referer': 'http://{removed_remote_url}:8081/login/?next=%2Ferrorlogs%2F', 'Cache-Control': 'max-age=0', 'Cookie': 'plushQueuePerPage=9999999; advanced_toggle_checked=0; blu_ray_com_new_releases_view=thumb; imdb_movies_in_theaters_view=thumb; imdb_box_office_view=thumb; plushHistPerPage=9999999; manage_view=thumb; __utma=13846133.346203885.1438778968.1455003865.1455015571.15; __utmz=13846133.1438778968.1.1.utmcsr=(direct)|utmccn=(direct)|utmcmd=(none); __utmv=13846133.|3=a-b_group=2=1; snatched_view=list; soon_view=thumb; suggest_view=thumb; late_view=list; wanted_view=thumb; plushContainerWidth=100%25; plushMultiOps=1; plushNoTopMenu=0', 'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.87 Safari/537.36', 'Content-Type': 'application/x-www-form-urlencoded'}
host: {removed_remote_url}:8081
version: HTTP/1.1
arguments: {'username': ['admin'], 'remember_me': ['1'], 'password': ['{removed_password}'], 'submit': ['Login'], 'next': ['/errorlogs/']}
_finish_time: None
query: next=%2Ferrorlogs%2F
path: /login/
method: POST
remote_ip: {removed_remote_ip}

```

**Comment by SickRage2** [comment]
Thanks for the issue report! Before a real human comes by, please make sure your report has all the below criteria checked

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [ ] Post debug logs, either inline (for smaller logs) or using gist

Please make sure you also read [how to create an issue](https://github.com/SickRage/sickrage-issues/blob/master/README.md) and followed all of the steps. 

The title should describe your issue. Having "SR not working" or "I get this bug" for 100 issues, isn't really helpful. We will close issues if there isn't enough information.

Sometimes the devs may seem like grunts and respond with short answers. This isn't (always) because the dev hates you, but because he's on mobile or busy fixing bugs. If something isn't clear, please let us know, and this bot may get updated to automatically answer you.

Thanks!

**Comment by miigotu** [comment]
#1369
