### ISSUE TITLE
Unable to add show codec can't encode character u'\u200b'

### ISSUE THREAD

**Issue by Rouzax** [SickRage/sickrage-issues#1370]
SickRage Info:	Branch: master
Commit: dd619c630445a56dc79ec670faaf45752aae6cf0
Version: 2016.03.20-1
 Python Version:	2.7.11 (v2.7.11:6d1b6a68f775, Dec 5 2015, 20:40:30) [MSC v.1500 64 bit (AMD64)]
 SSL Version:	OpenSSL 1.0.2d 9 Jul 2015
 OS:	Windows-2012ServerR2-6.3.9600
 Locale:	nl_NL.cp1252

What you did: Tried to add "The Story of Cats" 
What happened: It creates the directory in my show folder but after that nothing happens and the show is not in the show list

Logs: The logs do not have the error but the console is spitting out this:
```
16:31:49 DEBUG::Thread-16 :: Searching for Show with searchterm(s): ['The Story
of Cats', 'Story of Cats'] on Indexer: theTVDB
Exception in thread SHOWQUEUE-ADD:
Traceback (most recent call last):
  File "C:\Python27\lib\threading.py", line 801, in __bootstrap_inner
    self.run()
  File "C:\GitHub\SickRage\sickbeard\show_queue.py", line 293, in run
    logger.log(u"Starting to add show {0}".format("by ShowDir: {0}".format(self.
showDir) if self.showDir else "by Indexer Id: {0}".format(self.indexer_id)))
  File "C:\Python27\lib\encodings\cp1252.py", line 12, in encode
    return codecs.charmap_encode(input,errors,encoding_table)
UnicodeEncodeError: 'charmap' codec can't encode character u'\u200b' in position
 18: character maps to <undefined>

```

**Comment by SickRage2** [comment]
Thanks for the issue report! Before a real human comes by, please make sure your report has all the below criteria checked

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [ ] Post debug logs, either inline (for smaller logs) or using gist

Please make sure you also read [how to create an issue](https://github.com/SickRage/sickrage-issues/blob/master/README.md) and followed all of the steps. 

The title should describe your issue. Having "SR not working" or "I get this bug" for 100 issues, isn't really helpful. We will close issues if there isn't enough information.

Sometimes the devs may seem like grunts and respond with short answers. This isn't (always) because the dev hates you, but because he's on mobile or busy fixing bugs. If something isn't clear, please let us know, and this bot may get updated to automatically answer you.

Thanks!

**Comment by Rouzax** [comment]
Just tested with another show and that works without issue so it seems to be linked to the show in question.
http://thetvdb.com/?tab=series&id=308582&lid=7

**Comment by neoatomic** [comment]
Was able to add the show without issues on my Synology.
The error is related to a special character, i removed one from the shows description. Can you try to add it again.?

**Comment by miigotu** [comment]
Still, I am working on making the show queue use unicode_literals now xD

**Comment by miigotu** [comment]
@Rouzax I released to master, can you confirm it is fixed now?

**Comment by Rouzax** [comment]
Upgraded to the latest master and I was able to add the show although I do not know if that is because of the change by @neoatomic of the description.

**Comment by Rouzax** [comment]
@miigotu: Sorry, the issue is not yet resolved.

Now it gives an error if it searches for an episode.
The episodes are available.
![image](https://cloud.githubusercontent.com/assets/4103090/13978277/111d89ae-f0d0-11e5-8178-81100cefd7c3.png)
```
AA
AAUnicodeEncodeError: 'charmap' codec can't encode character u'\u200b' in position 0: character maps to 
AA    return codecs.charmap_encode(input,errors,encoding_table)
AA  File "C:\Python27\lib\encodings\cp1252.py", line 12, in encode
AA    "Couldn't find a download for {0!s}".format(self.segment.prettyName()))
AA  File "C:\GitHub\SickRage\sickbeard\search_queue.py", line 191, in run
2016-03-23 08:18:06 DEBUG    SEARCHQUEUE-MANUAL-308582 :: Traceback (most recent call last):
2016-03-23 08:18:06 DEBUG    SEARCHQUEUE-MANUAL-308582 :: formatting pattern: %SN - S%0SE%0E - %EN -> ​The Story of Cats - S01E01 - Wild at Heart
2016-03-23 08:18:06 INFO     SEARCHQUEUE-MANUAL-308582 :: [TorrentDay] :: Performing season pack search for ​The Story of Cats
2016-03-23 08:18:06 DEBUG    SEARCHQUEUE-MANUAL-308582 :: [TorrentDay] :: Fallback season pack search initiate
2016-03-23 08:18:06 DEBUG    SEARCHQUEUE-MANUAL-308582 :: [TorrentDay] :: Data returned from provider does not contain any torrents
2016-03-23 08:18:06 DEBUG    SEARCHQUEUE-MANUAL-308582 :: [TorrentDay] :: With post data: cata=yes&search=%E2%80%8BThe%2BStory%2Bof%2BCats%2BS01E01&c26=1&jxt=8&jxw=b&c24=1&c2=1&c7=1
2016-03-23 08:18:06 DEBUG    SEARCHQUEUE-MANUAL-308582 :: [TorrentDay] :: POST URL: https://classic.torrentday.com/V3/API/API.php [Status: 200]
2016-03-23 08:18:06 DEBUG    SEARCHQUEUE-MANUAL-308582 :: [TorrentDay] :: Search string: ​The Story of Cats S01E01
2016-03-23 08:18:06 DEBUG    SEARCHQUEUE-MANUAL-308582 :: [TorrentDay] :: Search Mode: Episode
2016-03-23 08:18:06 INFO     SEARCHQUEUE-MANUAL-308582 :: [TorrentDay] :: Performing episode search for ​The Story of Cats
2016-03-23 08:18:06 INFO     SEARCHQUEUE-MANUAL-308582 :: [IPTorrents] :: Performing season pack search for ​The Story of Cats
2016-03-23 08:18:06 DEBUG    SEARCHQUEUE-MANUAL-308582 :: [IPTorrents] :: Fallback season pack search initiate
2016-03-23 08:18:06 DEBUG    SEARCHQUEUE-MANUAL-308582 :: [IPTorrents] :: Data returned from provider does not contain any torrents
2016-03-23 08:18:06 DEBUG    SEARCHQUEUE-MANUAL-308582 :: [IPTorrents] :: GET URL: https://iptorrents.eu/t?73=&60=&q=%E2%80%8BThe%20Story%20of%20Cats%20S01E01&qf=#torrents;o=seeders [Status: 200]
2016-03-23 08:18:06 DEBUG    SEARCHQUEUE-MANUAL-308582 :: [IPTorrents] :: Search string: ​The Story of Cats S01E01
2016-03-23 08:18:06 DEBUG    SEARCHQUEUE-MANUAL-308582 :: [IPTorrents] :: Search Mode: Episode
2016-03-23 08:18:06 INFO     SEARCHQUEUE-MANUAL-308582 :: [IPTorrents] :: Performing episode search for ​The Story of Cats
2016-03-23 08:18:06 DEBUG    SEARCHQUEUE-MANUAL-308582 :: [TorrentDay] :: Last update was too soon, using old cache: 2016-03-23 08:15:28. Updated less then 10 minutes ago
2016-03-23 08:18:06 DEBUG    SEARCHQUEUE-MANUAL-308582 :: [IPTorrents] :: Last update was too soon, using old cache: 2016-03-23 08:15:24. Updated less then 10 minutes ago
2016-03-23 08:18:06 INFO     SEARCHQUEUE-MANUAL-308582 :: Beginning manual search for: [​The Story of Cats - S01E01 - Wild at Heart]
2016-03-23 08:18:06 DEBUG    SEARCHQUEUE-MANUAL-308582 :: formatting pattern: %SN - S%0SE%0E - %EN -> ​The Story of Cats - S01E01 - Wild at Heart
AA
AAUnicodeEncodeError: 'charmap' codec can't encode character u'\u200b' in position 0: character maps to 
AA    return codecs.charmap_encode(input,errors,encoding_table)
AA  File "C:\Python27\lib\encodings\cp1252.py", line 12, in encode
AA    "Couldn't find a download for {0!s}".format(self.segment.prettyName()))
AA  File "C:\GitHub\SickRage\sickbeard\search_queue.py", line 191, in run
```

**Comment by miigotu** [comment]
Thats ok, just another hiccup xD

**Comment by Rouzax** [comment]
Not sure if it should have been resolved with the latest push but I still have the issue.
https://github.com/SickRage/SickRage/commit/6116245c03c8627b33c5cdad7de100e8b0f93529
```
2016-03-23 09:09:54 DEBUG    SEARCHQUEUE-MANUAL-308582 :: Traceback (most recent call last):
2016-03-23 09:09:54 DEBUG    SEARCHQUEUE-MANUAL-308582 :: formatting pattern: %SN - S%0SE%0E - %EN -> ​The Story of Cats - S01E01 - Wild at Heart
2016-03-23 09:09:54 INFO     SEARCHQUEUE-MANUAL-308582 :: [TorrentDay] :: Performing season pack search for ​The Story of Cats
2016-03-23 09:09:54 DEBUG    SEARCHQUEUE-MANUAL-308582 :: [TorrentDay] :: Fallback season pack search initiate
2016-03-23 09:09:54 DEBUG    SEARCHQUEUE-MANUAL-308582 :: [TorrentDay] :: Data returned from provider does not contain any torrents
2016-03-23 09:09:54 DEBUG    SEARCHQUEUE-MANUAL-308582 :: [TorrentDay] :: With post data: cata=yes&search=%E2%80%8BThe%2BStory%2Bof%2BCats%2BS01E01&c26=1&jxt=8&jxw=b&c24=1&c2=1&c7=1
2016-03-23 09:09:54 DEBUG    SEARCHQUEUE-MANUAL-308582 :: [TorrentDay] :: POST URL: https://classic.torrentday.com/V3/API/API.php [Status: 200]
2016-03-23 09:09:54 DEBUG    SEARCHQUEUE-MANUAL-308582 :: [TorrentDay] :: Search string: ​The Story of Cats S01E01
2016-03-23 09:09:54 DEBUG    SEARCHQUEUE-MANUAL-308582 :: [TorrentDay] :: Search Mode: Episode
2016-03-23 09:09:54 INFO     SEARCHQUEUE-MANUAL-308582 :: [TorrentDay] :: Performing episode search for ​The Story of Cats
2016-03-23 09:09:54 INFO     SEARCHQUEUE-MANUAL-308582 :: [IPTorrents] :: Performing season pack search for ​The Story of Cats
2016-03-23 09:09:54 DEBUG    SEARCHQUEUE-MANUAL-308582 :: [IPTorrents] :: Fallback season pack search initiate
2016-03-23 09:09:54 DEBUG    SEARCHQUEUE-MANUAL-308582 :: [IPTorrents] :: Data returned from provider does not contain any torrents
2016-03-23 09:09:54 DEBUG    SEARCHQUEUE-MANUAL-308582 :: [IPTorrents] :: GET URL: https://iptorrents.eu/t?73=&60=&q=%E2%80%8BThe%20Story%20of%20Cats%20S01E01&qf=#torrents;o=seeders [Status: 200]
2016-03-23 09:09:54 DEBUG    SEARCHQUEUE-MANUAL-308582 :: [IPTorrents] :: Search string: ​The Story of Cats S01E01
2016-03-23 09:09:54 DEBUG    SEARCHQUEUE-MANUAL-308582 :: [IPTorrents] :: Search Mode: Episode
2016-03-23 09:09:54 INFO     SEARCHQUEUE-MANUAL-308582 :: [IPTorrents] :: Performing episode search for ​The Story of Cats
2016-03-23 09:09:54 DEBUG    SEARCHQUEUE-MANUAL-308582 :: [TorrentDay] :: Last update was too soon, using old cache: 2016-03-23 09:00:31. Updated less then 10 minutes ago
2016-03-23 09:09:53 DEBUG    SEARCHQUEUE-MANUAL-308582 :: [IPTorrents] :: Last update was too soon, using old cache: 2016-03-23 09:00:35. Updated less then 10 minutes ago
2016-03-23 09:09:53 INFO     SEARCHQUEUE-MANUAL-308582 :: Beginning manual search for: [​The Story of Cats - S01E01 - Wild at Heart]
2016-03-23 09:09:53 DEBUG    SEARCHQUEUE-MANUAL-308582 :: formatting pattern: %SN - S%0SE%0E - %EN -> ​The Story of Cats - S01E01 - Wild at Heart
AA
AAUnicodeEncodeError: 'charmap' codec can't encode character u'\u200b' in position 0: character maps to 
AA    return codecs.charmap_encode(input,errors,encoding_table)
AA  File "C:\Python27\lib\encodings\cp1252.py", line 12, in encode
AA    "Couldn't find a download for {0}".format(self.segment.prettyName()))
AA  File "C:\GitHub\SickRage\sickbeard\search_queue.py", line 191, in run
2016-03-23 09:09:10 DEBUG    SEARCHQUEUE-MANUAL-308582 :: Traceback (most recent call last):
2016-03-23 09:09:10 DEBUG    SEARCHQUEUE-MANUAL-308582 :: formatting pattern: %SN - S%0SE%0E - %EN -> ​The Story of Cats - S01E01 - Wild at Heart
2016-03-23 09:09:10 INFO     SEARCHQUEUE-MANUAL-308582 :: [TorrentDay] :: Performing season pack search for ​The Story of Cats
2016-03-23 09:09:10 DEBUG    SEARCHQUEUE-MANUAL-308582 :: [TorrentDay] :: Fallback season pack search initiate
2016-03-23 09:09:10 DEBUG    SEARCHQUEUE-MANUAL-308582 :: [TorrentDay] :: Data returned from provider does not contain any torrents
2016-03-23 09:09:10 DEBUG    SEARCHQUEUE-MANUAL-308582 :: [TorrentDay] :: With post data: cata=yes&search=%E2%80%8BThe%2BStory%2Bof%2BCats%2BS01E01&c26=1&jxt=8&jxw=b&c24=1&c2=1&c7=1
2016-03-23 09:09:10 DEBUG    SEARCHQUEUE-MANUAL-308582 :: [TorrentDay] :: POST URL: https://classic.torrentday.com/V3/API/API.php [Status: 200]
2016-03-23 09:09:10 DEBUG    SEARCHQUEUE-MANUAL-308582 :: [TorrentDay] :: Search string: ​The Story of Cats S01E01
2016-03-23 09:09:10 DEBUG    SEARCHQUEUE-MANUAL-308582 :: [TorrentDay] :: Search Mode: Episode
2016-03-23 09:09:10 DEBUG    SEARCHQUEUE-MANUAL-308582 :: [TorrentDay] :: GET URL: https://classic.torrentday.com/t [Status: 200]
2016-03-23 09:09:10 DEBUG    SEARCHQUEUE-MANUAL-308582 :: [TorrentDay] :: With post data: username=***********&submit.x=0&password=*********&submit.y=0
2016-03-23 09:09:10 DEBUG    SEARCHQUEUE-MANUAL-308582 :: [TorrentDay] :: POST URL: https://classic.torrentday.com/t [Status: 302]
2016-03-23 09:09:09 INFO     SEARCHQUEUE-MANUAL-308582 :: [TorrentDay] :: Performing episode search for ​The Story of Cats
2016-03-23 09:09:09 INFO     SEARCHQUEUE-MANUAL-308582 :: [IPTorrents] :: Performing season pack search for ​The Story of Cats
2016-03-23 09:09:09 DEBUG    SEARCHQUEUE-MANUAL-308582 :: [IPTorrents] :: Fallback season pack search initiate
2016-03-23 09:09:09 DEBUG    SEARCHQUEUE-MANUAL-308582 :: [IPTorrents] :: Data returned from provider does not contain any torrents
2016-03-23 09:09:09 DEBUG    SEARCHQUEUE-MANUAL-308582 :: [IPTorrents] :: GET URL: https://iptorrents.eu/t?73=&60=&q=%E2%80%8BThe%20Story%20of%20Cats%20S01E01&qf=#torrents;o=seeders [Status: 200]
2016-03-23 09:09:09 DEBUG    SEARCHQUEUE-MANUAL-308582 :: [IPTorrents] :: Search string: ​The Story of Cats S01E01
2016-03-23 09:09:09 DEBUG    SEARCHQUEUE-MANUAL-308582 :: [IPTorrents] :: Search Mode: Episode
2016-03-23 09:09:09 DEBUG    SEARCHQUEUE-MANUAL-308582 :: [IPTorrents] :: GET URL: https://iptorrents.eu/torrents/ [Status: 200]
2016-03-23 09:09:09 DEBUG    SEARCHQUEUE-MANUAL-308582 :: [IPTorrents] :: With post data: username=******&login=submit&password=*********
2016-03-23 09:09:09 DEBUG    SEARCHQUEUE-MANUAL-308582 :: [IPTorrents] :: POST URL: https://iptorrents.eu/torrents/ [Status: 302]
2016-03-23 09:09:09 DEBUG    SEARCHQUEUE-MANUAL-308582 :: [IPTorrents] :: GET URL: https://iptorrents.eu/torrents/ [Status: 200]
2016-03-23 09:09:08 INFO     SEARCHQUEUE-MANUAL-308582 :: [IPTorrents] :: Performing episode search for ​The Story of Cats
2016-03-23 09:09:08 DEBUG    SEARCHQUEUE-MANUAL-308582 :: [TorrentDay] :: Last update was too soon, using old cache: 2016-03-23 09:00:31. Updated less then 10 minutes ago
2016-03-23 09:09:08 DEBUG    SEARCHQUEUE-MANUAL-308582 :: [IPTorrents] :: Last update was too soon, using old cache: 2016-03-23 09:00:35. Updated less then 10 minutes ago
2016-03-23 09:09:08 INFO     SEARCHQUEUE-MANUAL-308582 :: Beginning manual search for: [​The Story of Cats - S01E01 - Wild at Heart]
2016-03-23 09:09:08 DEBUG    SEARCHQUEUE-MANUAL-308582 :: formatting pattern: %SN - S%0SE%0E - %EN -> ​The Story of Cats - S01E01 - Wild at Heart
```

**Comment by Rouzax** [comment]
@miigotu I still can't snatch the episodes.
