### ISSUE TITLE
UnknownTimeZoneError: 'Timezone/Pacific'   error on starting 

### ISSUE THREAD

**Issue by rkelez** [SickRage/sickrage-issues#1399]
Branch/Commit: master
OS: DSM 6.0 (latest official)

What you did:
- Created user "sickbeard-custom" as suggested by @neoatomic here [https://github.com/SickRage/sickrage-issues/issues/587#issuecomment-204302021](url)
- Fresh install of Python, Git, sickbeard-custom
- Repo: git://github.com/SickRage/SickRage.git

What happened:
 - SickRage fails to launch
 - SSH as root, ran start command and receive the errors below about timezones

Logs:
```
root@SynDrive:~# /var/packages/sickbeard-custom/scripts/start-stop-status start
Starting SickBeard Custom ...
Traceback (most recent call last):
  File "/usr/local/sickbeard-custom/var/SickBeard/SickBeard.py", line 94, in <module>
    import sickbeard
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/__init__.py", line 38, in <module>
    from sickbeard.config import CheckSection, check_setting_int, check_setting_str, check_setting_float, ConfigMigrator
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/config.py", line 29, in <module>
    from sickbeard import naming
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/naming.py", line 27, in <module>
    from sickbeard import tv
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/tv.py", line 51, in <module>
    from sickbeard import network_timezones
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/network_timezones.py", line 34, in <module>
    sb_timezone = get_localzone()
  File "/usr/local/sickbeard-custom/var/SickBeard/lib/tzlocal/unix.py", line 122, in get_localzone
    _cache_tz = _get_localzone()
  File "/usr/local/sickbeard-custom/var/SickBeard/lib/tzlocal/unix.py", line 91, in _get_localzone
    return pytz.timezone(etctz.replace(' ', '_'))
  File "/usr/local/sickbeard-custom/var/SickBeard/lib/pytz/__init__.py", line 180, in timezone
    raise UnknownTimeZoneError(zone)
pytz.exceptions.UnknownTimeZoneError: 'Timezone/Pacific'

```

I'm fairly new, if I've missed something I'm happy to provide any further assistance. I don't know how related the issues are but everything worked fine before the DSM 6.0 upgrade.

**Comment by SickRage2** [comment]
This repository is no longer in use for issues or wiki, please use the main repo for [Issues](https://github.com/SickRage/SickRage/issues) and the [Wiki](https://github.com/SickRage/SickRage/wiki)

**Comment by rkelez** [comment]
Sorry about that, I reposted it over there.

Thank you
