### ISSUE TITLE
problem encoding fresh installation

### ISSUE THREAD

**Issue by valantislevas** [SickRage/sickrage-issues#145]
SR Version:    BRANCH: (master) / COMMIT: (c575707408313497ee391e761f0164fe574a3c6f) 
SR User:    valhtpc
SR Locale:    ('el_GR', 'cp1253')
SR Config:    C:\SickRage\config.ini
SR Database:    C:\SickRage\sickbeard.db
SR Cache Dir:    C:\SickRage\cache
SR Log Dir:    C:\SickRage\Logs
SR Arguments:    ['--nolaunch']
Python Version:    2.7.10 (default, May 23 2015, 09:44:00) [MSC v.1500 64 bit (AMD64)]

````
2015-12-04 14:41:16 Thread-36 :: Failed doing webui callback: Traceback (most recent call last):
  File "C:\SickRage\sickbeard\webserve.py", line 267, in async_call
    result = function(**kwargs)
  File "C:\SickRage\sickbeard\webserve.py", line 4336, in canAddTorrentRssProvider
    (succ, errMsg) = tempProvider.validateRSS()
  File "C:\SickRage\sickbeard\providers\rsstorrent.py", line 134, in validateRSS
    return (False, 'Error when trying to load RSS: ' + ex(e))
  File "C:\SickRage\sickrage\helper\exceptions.py", line 47, in ex
    message = '%s : %s' % (message, fixed_arg)
  File "C:\Python27\lib\encodings\cp1253.py", line 15, in decode
    return codecs.charmap_decode(input,errors,decoding_table)
UnicodeDecodeError: 'charmap' codec can't decode byte 0x8e in position 40: character maps to
````

i tried to put the rss syntax like that:
http://magico.info/?p=rss&categories=53&pk=da54sa45as45sa4as54as
and
http://www.greekleech.info/?p=rss&categories=78,76&pk=321312j123213j21

on cmd error:

````
14:40:44 INFO::EVENT-QUEUE :: Restarting SickRage with ['C:\\Python27\\python.ex
e', u'C:\\SickRage\\SickBeard.py', '--nolaunch']
Starting up SickRage master from C:\SickRage\config.ini
4:40:48 INFO::TORNADO :: Starting SickRage on http://0.0.0.0:8855/
14:40:48 INFO::CHECKVERSION :: Checking for updates using GIT
14:40:48 INFO::MAIN :: Building internal name cache for all shows
14:41:16 ERROR::Thread-36 :: Failed doing webui callback: Traceback (most recent
 call last):
  File "C:\SickRage\sickbeard\webserve.py", line 267, in async_call
    result = function(**kwargs)
  File "C:\SickRage\sickbeard\webserve.py", line 4336, in canAddTorrentRssProvid
er
    (succ, errMsg) = tempProvider.***idateRSS()
  File "C:\SickRage\sickbeard\providers\rsstorrent.py", line 134, in ***idateRSS

    return (False, 'Error when trying to load RSS: ' + ex(e))
  File "C:\SickRage\sickrage\helper\exceptions.py", line 47, in ex
    message = '%s : %s' % (message, fixed_arg)
  File "C:\Python27\lib\encodings\cp1253.py", line 15, in decode
    return codecs.charmap_decode(input,errors,decoding_table)
UnicodeDecodeError: 'charmap' codec can't decode byte 0x8e in position 40: chara
cter maps to <undefined>
Traceback (most recent call last):
  File "C:\SickRage\sickbeard\webserve.py", line 267, in async_call
    result = function(**kwargs)
  File "C:\SickRage\sickbeard\webserve.py", line 4336, in canAddTorrentRssProvid
er
    (succ, errMsg) = tempProvider.***idateRSS()
  File "C:\SickRage\sickbeard\providers\rsstorrent.py", line 134, in ***idateRSS

    return (False, 'Error when trying to load RSS: ' + ex(e))
  File "C:\SickRage\sickrage\helper\exceptions.py", line 47, in ex
    message = '%s : %s' % (message, fixed_arg)
  File "C:\Python27\lib\encodings\cp1253.py", line 15, in decode
    return codecs.charmap_decode(input,errors,decoding_table)
UnicodeDecodeError: 'charmap' codec can't decode byte 0x8e in position 40: chara
cter maps to <undefined>
````

**Comment by miigotu** [comment]
Change your startup script to start SR with 
`chcp 65001 && C:\Python27\python.exe C:\SickRage\SickBeard.py --nolaunch`

**Comment by valantislevas** [comment]
i run the SickRage from his folder python SickBeard.py how i can do that?

**Comment by miigotu** [comment]
Then your provider isnt returning valid data?

**Comment by valantislevas** [comment]
no it stucks when it tries to start..

**Comment by miigotu** [comment]
the provider you are trying to add is not in a supported format I think.

**Comment by valantislevas** [comment]
i already have older version of sickrage and it works.. i tried the news for more features.. too strange that..

**Comment by miigotu** [comment]
Stop all SR, then in command line: `chcp 65001 && C:\Python27\python.exe C:\SickRage\SickBeard.py --nolaunch`

**Comment by valantislevas** [comment]
it runs but again can't put the rss feed from provider.. :/
