### ISSUE TITLE
Exception generated in thread POSTPROCESSER: error 2 : No such file or directory

### ISSUE THREAD

**Issue by askinallquestions** [SickRage/sickrage-issues#1456]
Branch: master
Commit: 61b8a1965bcee524b557a667fa11ffdece31ba72
Version: 2016.05.09-2
Database Version: 43.1

OS: Ubuntu 14.04
What you did: Updated to newest version
What happened: SR stopped creating folders at destination when postprocessing shows
What you expected: SR to create folders that did not exist in the destination location (more detail below)

Logs:

2016-05-09 15:53:12 DEBUG    POSTPROCESSER :: 'Traceback (most recent call last):\n  File "/home/user/.sickrage/sickbeard/scheduler.py", line 106, in run\n    self.action.run(self.force)\n  File "/home/user/.sickrage/sickbeard/auto_postprocessor.py", line 56, in run\n    processTV.processDir(sickbeard.TV_DOWNLOAD_DIR, force=force)\n  File "/home/user/.sickrage/sickbeard/processTV.py", line 243, in processDir\n    process_media(path, [video], nzbName, process_method, force, is_priority, result)\n  File "/home/user/.sickrage/sickbeard/processTV.py", line 560, in process_media\n    result.result = processor.process()\n  File "/home/user/.sickrage/sickbeard/postProcessor.py", line 1027, in process\n    if not verify_freespace(self.file_path, ep_obj.show._location, [ep_obj] + ep_obj.relatedEps, method=self.process_method):  # pylint: disable=protected-access\n  File "/home/user/.sickrage/sickbeard/helpers.py", line 1578, in verify_freespace\n    if method == "move" and ek(os.stat, src).st_dev == ek(os.stat, dest).st_dev:  # pylint: disable=no-member\n  File "/home/user/.sickrage/sickrage/helper/encoding.py", line 40, in ek\n    result = function(*[ss(x) if isinstance(x, (str, unicode)) else x for x in args], **kwargs)\nOSError: [Errno 2] No such file or directory: "/mnt/samba/shows/<SHOW>"\n'
AAOSError: [Errno 2] No such file or directory: "/mnt/samba/shows/<SHOW>"
AA    result = function(*[ss(x) if isinstance(x, (str, unicode)) else x for x in args], **kwargs)
AA  File "/home/user/.sickrage/sickrage/helper/encoding.py", line 40, in ek
AA    if method == "move" and ek(os.stat, src).st_dev == ek(os.stat, dest).st_dev:  # pylint: disable=no-member
AA  File "/home/user/.sickrage/sickbeard/helpers.py", line 1578, in verify_freespace
AA    if not verify_freespace(self.file_path, ep_obj.show._location, [ep_obj] + ep_obj.relatedEps, method=self.process_method):  # pylint: disable=protected-access
AA  File "/home/user/.sickrage/sickbeard/postProcessor.py", line 1027, in process
AA    result.result = processor.process()
AA  File "/home/user/.sickrage/sickbeard/processTV.py", line 560, in process_media
AA    process_media(path, [video], nzbName, process_method, force, is_priority, result)
AA  File "/home/user/.sickrage/sickbeard/processTV.py", line 243, in processDir
AA    processTV.processDir(sickbeard.TV_DOWNLOAD_DIR, force=force)
AA  File "/home/user/.sickrage/sickbeard/auto_postprocessor.py", line 56, in run
AA    self.action.run(self.force)
AA  File "/home/user/.sickrage/sickbeard/scheduler.py", line 106, in run
AATraceback (most recent call last):
2016-05-09 15:53:12 ERROR    POSTPROCESSER :: [61b8a19] Exception generated in thread POSTPROCESSER: error 2 : No such file or directory
2016-05-09 15:53:12 DEBUG    POSTPROCESSER :: Trying to determine free space on destination drive
2016-05-09 15:53:12 INFO     POSTPROCESSER :: This download is marked a priority download so I'm going to replace an existing file if I find one
2016-05-09 15:53:12 DEBUG    POSTPROCESSER :: File /mnt/samba/shows/<SHOW>/<SHOW> S06E16.mkv doesn't exist so there's no worries about replacing it
2016-05-09 15:53:12 DEBUG    POSTPROCESSER :: Is ep a priority download: True
2016-05-09 15:53:12 DEBUG    POSTPROCESSER :: SR snatched this episode and it is not processed before
2016-05-09 15:53:12 DEBUG    POSTPROCESSER :: Quality of the episode we're processing: 1080p HDTV
2016-05-09 15:53:12 DEBUG    POSTPROCESSER :: Snatch history had a quality in it, using that: 1080p HDTV
2016-05-09 15:53:12 DEBUG    POSTPROCESSER :: Setter sets location to /mnt/samba/shows/<SHOW>/<SHOW>.mkv
2016-05-09 15:53:12 DEBUG    POSTPROCESSER :: Retrieving episode object for 1x10
2016-05-09 15:53:12 DEBUG    POSTPROCESSER :: Parsed <SHOW> into <SHOW> [GROUP: [Zeus]] [ABD: False] [ANIME: False] [whichReg: ['standard']]
2016-05-09 15:53:12 DEBUG    POSTPROCESSER :: Analyzing name <SHOW>
2016-05-09 15:53:12 INFO     POSTPROCESSER :: Processing /mnt/samba/torrents/shows/<SHOW> (None)
2016-05-09 15:53:12 DEBUG    POSTPROCESSER :: PostProcessing VideoInRar: []
2016-05-09 15:53:12 DEBUG    POSTPROCESSER :: PostProcessing RarContent: []
2016-05-09 15:53:12 DEBUG    POSTPROCESSER :: PostProcessing VideoFiles: ["<SHOW>"]
2016-05-09 15:53:12 DEBUG    POSTPROCESSER :: PostProcessing Files: ["<SHOW>", '.hidden']
2016-05-09 15:53:12 DEBUG    POSTPROCESSER :: PostProcessing Dirs: []
2016-05-09 15:53:12 INFO     POSTPROCESSER :: PostProcessing Path: /mnt/samba/torrents/shows
2016-05-09 15:53:12 DEBUG    POSTPROCESSER :: Processing folder /mnt/samba/torrents/shows
2016-05-09 15:53:12 DEBUG    POSTPROCESSER :: Starting new thread: POSTPROCESSER

Sickrage woked fine up until a few days ago, where it is no longer creating folders in the location where it should move the shows to. I download the shows and place them in /mnt/samba/torrents/shows (which is where SR should find them sitting. Once they are there, SR should then move them to /mnt/samba/shows/<SHOW>/<SHOW S01E01.mkv>. Normally, the <SHOW> folder would not exist, and SR would create it. I noticed about a week ago, that SR does not create those folders and move the file. If the folder exists, then the show gets moved like it should.

Thank you very much for your assistance!

**Comment by SickRage2** [comment]
This repository is no longer in use for issues or wiki, please use the main repo for [Issues](https://github.com/SickRage/SickRage/issues) and the [Wiki](https://github.com/SickRage/SickRage/wiki)
