### ISSUE TITLE
UnicodeEncodeError: 'charmap' codec can't encode character u'\u262e' in position 0: character maps to

### ISSUE THREAD

**Issue by Concept211** [SickRage/sickrage-issues#1481]
Branch/Commit: Latest/Master
OS: Windows 7 SP1
What you did: Ran automated and/or manual post-processing
What happened: Throws the UnicodeEncodeError and won't move any files.
What you expected: To move the files ;)
Logs:
```
2016-09-08 06:05:59 Thread-69 :: [8564c29] Failed doing webui callback: Traceback (most recent call last): File "C:\SickRage\SickRage\sickbeard\webserve.py", line 270, in async_call result = function(**kwargs) File "C:\SickRage\SickRage\sickbeard\webserve.py", line 2298, in processEpisode is_priority=argToBool(is_priority), delete_on=argToBool(delete_on), failed=argToBool(failed), proc_type=proc_type File "C:\SickRage\SickRage\sickbeard\processTV.py", line 251, in processDir for curDir in [x for x in dirs if validateDir(path, x, nzbNameOriginal, failed, result)]: File "C:\SickRage\SickRage\sickbeard\processTV.py", line 400, in validateDir NameParser().parse(proc_dir, cache_result=False) File "C:\SickRage\SickRage\sickbeard\name_parser\parser.py", line 461, in parse name, file_name_result or dir_name_result)) File "C:\SickRage\Python\lib\encodings\cp1252.py", line 12, in encode return codecs.charmap_encode(input,errors,encoding_table) UnicodeEncodeError: 'charmap' codec can't encode character u'\u262e' in position 0: character maps to 
```

It seems this happens when post-processing files that are inside of a sub-directory. If I pull the file out to the root processing directory it works fine. I've tested with multiple subdirectories and they all fail. None of them have any strange characters or anything. This used to work perfectly fine for years and now all of a sudden it's failing. Please help!

**Comment by SickRage2** [comment]
This repository is no longer in use for issues or wiki, please use the main repo for [Issues](https://github.com/SickRage/SickRage/issues) and the [Wiki](https://github.com/SickRage/SickRage/wiki)
