### ISSUE TITLE
[APP SUBMITTED]: HTTP error None while loading URL http://thetvdb.com/api/F9C450E78D99172E/series/315442/en.xml

### ISSUE THREAD

**Issue by nncrypted** [SickRage/sickrage-issues#1483]
### INFO
Python Version: **2.7.3 (default, Jun 21 2016, 18:38:19) [GCC 4.7.2]**
Operating System: **Linux-3.16.0-0.bpo.4-amd64-x86_64-with-debian-7.11**
Locale: None
Branch: **master**
Commit: SickRage/SickRage@5195b784b76916a2acfe21c1fffd12f837ce0e93
No Log available with ERRORS:
### ERROR
```
Thread-180 :: Failed doing webui callback: Traceback (most recent call last):
  File "/opt/sickbeard/sickbeard/webserve.py", line 285, in async_call
    result = function(**kwargs)
  File "/opt/sickbeard/sickbeard/webserve.py", line 2750, in addShowByID
    show_name = get_showname_from_indexer(1, indexer_id)
  File "/opt/sickbeard/sickbeard/helpers.py", line 1787, in get_showname_from_indexer
    s = t[int(indexer_id)]
  File "/opt/sickbeard/lib/tvdb_api/tvdb_api.py", line 953, in __getitem__
    self._getShowData(key, self.config['language'], True)
  File "/opt/sickbeard/lib/tvdb_api/tvdb_api.py", line 848, in _getShowData
    self.config['url_seriesInfo'] % (sid, getShowInLanguage)
  File "/opt/sickbeard/lib/tvdb_api/tvdb_api.py", line 636, in _getetsrc
    raise tvdb_error(e)
tvdb_error: HTTP error None while loading URL http://thetvdb.com/api/F9C450E78D99172E/series/315442/en.xml
 [5195b78]
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by SickRage2** [comment]
This repository is no longer in use for issues or wiki, please use the main repo for [Issues](https://github.com/SickRage/SickRage/issues) and the [Wiki](https://github.com/SickRage/SickRage/wiki)
