### ISSUE TITLE
Search provider error - [HoundDawgs]::Unable to connect to provider

### ISSUE THREAD

**Issue by ramasjang** [SickRage/sickrage-issues#150]
Hi

I am trying to add the HoundDawgs torrent search provider to sickrage on my Sinology NAS.

I am getting this error, I hope someone can help.

Thanks.
````
2015-12-05 20:04:04 ERROR    SEARCHQUEUE-BACKLOG-274897 :: [HoundDawgs]::Unable to connect to provider
AATypeError: __str__ returned non-string (type Error)
AA    if 'timed out' in str(err) or 'did not complete (read)' in str(err):  # Python 2.6
AA  File "/usr/local/sickrage/var/SickRage/lib/requests/packages/urllib3/connectionpool.py", line 314, in _raise_timeout
AA    self._raise_timeout(err=e, url=url, timeout_value=conn.timeout)
AA  File "/usr/local/sickrage/var/SickRage/lib/requests/packages/urllib3/connectionpool.py", line 344, in _make_request
AA    body=body, headers=headers)
AA  File "/usr/local/sickrage/var/SickRage/lib/requests/packages/urllib3/connectionpool.py", line 544, in urlopen
AA    timeout=timeout
AA  File "/usr/local/sickrage/var/SickRage/lib/requests/adapters.py", line 370, in send
AA    resp = super(CacheControlAdapter, self).send(request, **kw)
AA  File "/usr/local/sickrage/var/SickRage/lib/cachecontrol/adapter.py", line 46, in send
AA    r = adapter.send(request, **kwargs)
AA  File "/usr/local/sickrage/var/SickRage/lib/requests/sessions.py", line 576, in send
AA    resp = self.send(prep, **send_kwargs)
AA  File "/usr/local/sickrage/var/SickRage/lib/requests/sessions.py", line 464, in request
AA    return self.request('POST', url, data=data, json=json, **kwargs)
AA  File "/usr/local/sickrage/var/SickRage/lib/requests/sessions.py", line 507, in post
AA    resp = session.post(url, data=post_data, timeout=timeout, allow_redirects=True, verify=session.verify)
AA  File "/volume1/@appstore/sickrage/var/SickRage/sickbeard/helpers.py", line 1605, in getURL
AATraceback (most recent call last):
````

**Comment by neoatomic** [comment]
Sounds like a Cache problem.
Try to remove the cache/mako & sessions folders.

**Comment by miigotu** [comment]
Nope, houndDawgs has updated their SSL encryption method and cypher, you need openssl 1.0.1e+

**Comment by miigotu** [comment]
Almost 100% positive this is fixed in develop with the requests update.
