### ISSUE TITLE
showupdate dies "an integer is required"

### ISSUE THREAD

**Issue by alisonatwork** [SickRage/sickrage-issues#151]
Running on my beautifulsoup PR branch so could theoretically be related.
```
20:00:01 INFO::SHOWUPDATER :: Doing full update on all shows
20:00:01 ERROR::SHOWUPDATER :: Exception generated in thread SHOWUPDATER: an integer is required
Traceback (most recent call last):
  File "C:\SickRage\SickRage\sickbeard\scheduler.py", line 105, in run
    self.action.run(self.force)
  File "C:\SickRage\SickRage\sickbeard\showUpdater.py", line 74, in run
    if curShow.should_update(update_date=update_date) or curShow.indexerid in stale_should_update:
  File "C:\SickRage\SickRage\sickbeard\tv.py", line 319, in should_update
    next_airdate = datetime.date.fromordinal(sql_result[0][0])
TypeError: an integer is required
```
I checked my tv_episodes table and all the airdates are numeric, there are no nulls. I'm not sure what show it was processing when this crashed...

**Comment by medariox** [comment]
Just a heads up: it's not just your branch. The problem seems to be with the recent SQL changes (develop branch), specifically MAX() and MIN() return NULL in some cases and this, as you have noticed, breaks stuff.
