### ISSUE TITLE
[APP SUBMITTED]: local variable 'last_update' referenced before assignment

### ISSUE THREAD

**Issue by neoatomic** [SickRage/sickrage-issues#173]
### INFO
Python Version: **2.7.10 (default, Jun  3 2015, 20:43:13) [GCC 4.7.3 20130102 (prerelease)]**
Operating System: **Linux-3.10.35-x86_64-with-glibc2.2.5**
Locale: unknown
Branch: **develop**
Commit: SickRage/SickRage@44e84a3fe9d34e3b9ce60f7c83d9c0d9033dce2f
Link to Log: https://gist.github.com/e6fa65e2f84476bacfa5
### ERROR
```
SHOWUPDATER :: Exception generated in thread SHOWUPDATER: local variable 'last_update' referenced before assignment
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

I noted that one show did not have the latest episode. So i did a force full update for that show and the  missing episode was added.
This was just before 2am when my auto update for all shows start.

```
2015-12-08 01:57:25 INFO     SHOWQUEUE-REFRESH :: Performing refresh on Cops
2015-12-08 01:57:25 DEBUG    SHOWQUEUE-REFRESH :: 74709: Loading all episodes from the show directory /volume1/video/=_Series_=/=_Nieuw_=/Cops
2015-12-08 01:57:25 DEBUG    SHOWQUEUE-REFRESH :: 74709: Found files: []
2015-12-08 01:57:25 DEBUG    SHOWQUEUE-REFRESH :: 74709: Loading all episodes with a location from the database
2015-12-08 01:57:25 DEBUG    SHOWQUEUE-REFRESH :: 74709: Writing NFOs for show
2015-12-08 01:57:25 DEBUG    SHOWQUEUE-REFRESH :: Checking if /volume1/video/=_Series_=/=_Nieuw_=/Cops/tvshow.nfo exists: True
2015-12-08 01:57:25 DEBUG    SHOWQUEUE-REFRESH :: 74709: Writing NFOs for all episodes
2015-12-08 01:57:25 INFO     SHOWQUEUE-REFRESH :: 74709: Updating NFOs for show with new indexer info
2015-12-08 01:57:25 DEBUG    SHOWQUEUE-REFRESH :: Checking if /volume1/video/=_Series_=/=_Nieuw_=/Cops/tvshow.nfo exists: True
2015-12-08 01:57:25 DEBUG    SHOWQUEUE-REFRESH :: Metadata provider KODI 12+ updating show indexer info metadata file for Cops
2015-12-08 01:57:25 DEBUG    SHOWQUEUE-REFRESH :: Checking & filling cache for show Cops
2015-12-08 01:57:25 DEBUG    SHOWQUEUE-REFRESH :: Checking if we need any cache images for show 74709
2015-12-08 01:57:25 DEBUG    SHOWQUEUE-REFRESH :: Checking if file /usr/local/sickrage/var/cache/images/74709.poster.jpg exists
2015-12-08 01:57:25 DEBUG    SHOWQUEUE-REFRESH :: Checking if file /usr/local/sickrage/var/cache/images/74709.banner.jpg exists
2015-12-08 01:57:25 DEBUG    SHOWQUEUE-REFRESH :: Checking if file /usr/local/sickrage/var/cache/images/thumbnails/74709.poster.jpg exists
2015-12-08 01:57:25 DEBUG    SHOWQUEUE-REFRESH :: Checking if file /usr/local/sickrage/var/cache/images/thumbnails/74709.banner.jpg exists
2015-12-08 01:57:25 DEBUG    SHOWQUEUE-REFRESH :: Checking if file /usr/local/sickrage/var/cache/images/74709.fanart.jpg exists
2015-12-08 01:57:25 DEBUG    SHOWQUEUE-REFRESH :: No new cache images needed, not retrieving new ones
2015-12-08 01:59:00 DEBUG    Thread-60 :: Looking up XEM scene mapping for show 295829 on theTVDB
2015-12-08 01:59:46 DEBUG    Thread-16 :: Looking up XEM scene mapping for show 260449 on theTVDB
2015-12-08 02:00:00 DEBUG    SHOWUPDATER :: Transaction with 2271 queries executed
2015-12-08 02:00:00 ERROR    SHOWUPDATER :: Exception generated in thread SHOWUPDATER: local variable 'last_update' referenced before assignment
Traceback (most recent call last):
  File "/volume1/@appstore/sickrage/var/SickRage/sickbeard/scheduler.py", line 105, in run
    self.action.run(self.force)
  File "/volume1/@appstore/sickrage/var/SickRage/sickbeard/showUpdater.py", line 67, in run
    update_delta = update_timestamp - last_update
UnboundLocalError: local variable 'last_update' referenced before assignment
2015-12-08 02:00:00 DEBUG    SHOWUPDATER :: 'Traceback (most recent call last):\n  File "/volume1/@appstore/sickrage/var/SickRage/sickbeard/scheduler.py", line 105, in run\n    self.action.run(self.force)\n  File "/volume1/@appstore/sickrage/var/SickRage/sickbeard/showUpdater.py", line 67, in run\n    update_delta = update_timestamp - last_update\nUnboundLocalError: local variable \'last_update\' referenced before assignment\n'
```

**Comment by fernandog** [comment]
@Thraxis
