### ISSUE TITLE
[APP SUBMITTED]: must be string or read-only buffer, not None

### ISSUE THREAD

**Issue by NicoLeOca** [SickRage/sickrage-issues#198]
### INFO
Python Version: **2.7.10 (default, Jun  3 2015, 23:30:53) [GCC 4.6.3]**
Operating System: **Linux-3.2.40-i686-with-glibc2.0**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@97cd0fd633581154fb1ef43f3d2c2c0cc4609ebb
Link to Log: https://gist.github.com/2a054876e5450958f840
### ERROR
```
Thread-42 :: Failed doing webui callback: Traceback (most recent call last):
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/webserve.py", line 271, in async_call
    result = function(**kwargs)
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/webserve.py", line 2607, in addShowByID
    tvdb_id = helpers.getTVDBFromID(indexer_id, indexer.upper())
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/helpers.py", line 1736, in getTVDBFromID
    tree = ET.fromstring(data)
  File "/usr/local/python/lib/python2.7/xml/etree/ElementTree.py", line 1300, in XML
    parser.feed(text)
  File "/usr/local/python/lib/python2.7/xml/etree/ElementTree.py", line 1640, in feed
    self._parser.Parse(data, 0)
TypeError: must be string or read-only buffer, not None

```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by NicoLeOca** [comment]
### INFO
Python Version: **2.7.10 (default, Jun  3 2015, 23:30:53) [GCC 4.6.3]**
Operating System: **Linux-3.2.40-i686-with-glibc2.0**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@97cd0fd633581154fb1ef43f3d2c2c0cc4609ebb
Link to Log: https://gist.github.com/a8d93a13af7028d03108
### ERROR
```
Thread-43 :: Failed doing webui callback: Traceback (most recent call last):
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/webserve.py", line 271, in async_call
    result = function(**kwargs)
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/webserve.py", line 2607, in addShowByID
    tvdb_id = helpers.getTVDBFromID(indexer_id, indexer.upper())
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/helpers.py", line 1736, in getTVDBFromID
    tree = ET.fromstring(data)
  File "/usr/local/python/lib/python2.7/xml/etree/ElementTree.py", line 1300, in XML
    parser.feed(text)
  File "/usr/local/python/lib/python2.7/xml/etree/ElementTree.py", line 1640, in feed
    self._parser.Parse(data, 0)
TypeError: must be string or read-only buffer, not None

```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by NicoLeOca** [comment]
### INFO
Python Version: **2.7.10 (default, Jun  3 2015, 23:30:53) [GCC 4.6.3]**
Operating System: **Linux-3.2.40-i686-with-glibc2.0**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@97cd0fd633581154fb1ef43f3d2c2c0cc4609ebb
Link to Log: https://gist.github.com/40b52e605f6fd0f5192e
### ERROR
```
Thread-26 :: Failed doing webui callback: Traceback (most recent call last):
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/webserve.py", line 271, in async_call
    result = function(**kwargs)
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/webserve.py", line 2607, in addShowByID
    tvdb_id = helpers.getTVDBFromID(indexer_id, indexer.upper())
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/helpers.py", line 1736, in getTVDBFromID
    tree = ET.fromstring(data)
  File "/usr/local/python/lib/python2.7/xml/etree/ElementTree.py", line 1300, in XML
    parser.feed(text)
  File "/usr/local/python/lib/python2.7/xml/etree/ElementTree.py", line 1640, in feed
    self._parser.Parse(data, 0)
TypeError: must be string or read-only buffer, not None

```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by NicoLeOca** [comment]
### INFO
Python Version: **2.7.10 (default, Jun  3 2015, 23:30:53) [GCC 4.6.3]**
Operating System: **Linux-3.2.40-i686-with-glibc2.0**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@97cd0fd633581154fb1ef43f3d2c2c0cc4609ebb
Link to Log: https://gist.github.com/0f682c7cf63c257e6792
### ERROR
```
Thread-40 :: Failed doing webui callback: Traceback (most recent call last):
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/webserve.py", line 271, in async_call
    result = function(**kwargs)
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/webserve.py", line 2607, in addShowByID
    tvdb_id = helpers.getTVDBFromID(indexer_id, indexer.upper())
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/helpers.py", line 1736, in getTVDBFromID
    tree = ET.fromstring(data)
  File "/usr/local/python/lib/python2.7/xml/etree/ElementTree.py", line 1300, in XML
    parser.feed(text)
  File "/usr/local/python/lib/python2.7/xml/etree/ElementTree.py", line 1640, in feed
    self._parser.Parse(data, 0)
TypeError: must be string or read-only buffer, not None

```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by NicoLeOca** [comment]
### INFO
Python Version: **2.7.10 (default, Jun  3 2015, 23:30:53) [GCC 4.6.3]**
Operating System: **Linux-3.2.40-i686-with-glibc2.0**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@97cd0fd633581154fb1ef43f3d2c2c0cc4609ebb
Link to Log: https://gist.github.com/bc51749a7189a7024aa6
### ERROR
```
Thread-61 :: Failed doing webui callback: Traceback (most recent call last):
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/webserve.py", line 271, in async_call
    result = function(**kwargs)
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/webserve.py", line 2607, in addShowByID
    tvdb_id = helpers.getTVDBFromID(indexer_id, indexer.upper())
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/helpers.py", line 1736, in getTVDBFromID
    tree = ET.fromstring(data)
  File "/usr/local/python/lib/python2.7/xml/etree/ElementTree.py", line 1300, in XML
    parser.feed(text)
  File "/usr/local/python/lib/python2.7/xml/etree/ElementTree.py", line 1640, in feed
    self._parser.Parse(data, 0)
TypeError: must be string or read-only buffer, not None

```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by NicoLeOca** [comment]
### INFO
Python Version: **2.7.10 (default, Jun  3 2015, 23:30:53) [GCC 4.6.3]**
Operating System: **Linux-3.2.40-i686-with-glibc2.0**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@97cd0fd633581154fb1ef43f3d2c2c0cc4609ebb
Link to Log: https://gist.github.com/5be3c822c801d58f7639
### ERROR
```
Thread-36 :: Failed doing webui callback: Traceback (most recent call last):
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/webserve.py", line 271, in async_call
    result = function(**kwargs)
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/webserve.py", line 2607, in addShowByID
    tvdb_id = helpers.getTVDBFromID(indexer_id, indexer.upper())
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/helpers.py", line 1736, in getTVDBFromID
    tree = ET.fromstring(data)
  File "/usr/local/python/lib/python2.7/xml/etree/ElementTree.py", line 1300, in XML
    parser.feed(text)
  File "/usr/local/python/lib/python2.7/xml/etree/ElementTree.py", line 1640, in feed
    self._parser.Parse(data, 0)
TypeError: must be string or read-only buffer, not None

```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by NicoLeOca** [comment]
### INFO
Python Version: **2.7.10 (default, Jun  3 2015, 23:30:53) [GCC 4.6.3]**
Operating System: **Linux-3.2.40-i686-with-glibc2.0**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@97cd0fd633581154fb1ef43f3d2c2c0cc4609ebb
Link to Log: https://gist.github.com/f769fe590d07f215c3c0
### ERROR
```
Thread-59 :: Failed doing webui callback: Traceback (most recent call last):
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/webserve.py", line 271, in async_call
    result = function(**kwargs)
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/webserve.py", line 2607, in addShowByID
    tvdb_id = helpers.getTVDBFromID(indexer_id, indexer.upper())
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/helpers.py", line 1736, in getTVDBFromID
    tree = ET.fromstring(data)
  File "/usr/local/python/lib/python2.7/xml/etree/ElementTree.py", line 1300, in XML
    parser.feed(text)
  File "/usr/local/python/lib/python2.7/xml/etree/ElementTree.py", line 1640, in feed
    self._parser.Parse(data, 0)
TypeError: must be string or read-only buffer, not None

```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by NicoLeOca** [comment]
### INFO
Python Version: **2.7.10 (default, Jun  3 2015, 23:30:53) [GCC 4.6.3]**
Operating System: **Linux-3.2.40-i686-with-glibc2.0**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@97cd0fd633581154fb1ef43f3d2c2c0cc4609ebb
Link to Log: https://gist.github.com/803272b07b753f3fba3b
### ERROR
```
Thread-56 :: Failed doing webui callback: Traceback (most recent call last):
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/webserve.py", line 271, in async_call
    result = function(**kwargs)
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/webserve.py", line 2607, in addShowByID
    tvdb_id = helpers.getTVDBFromID(indexer_id, indexer.upper())
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/helpers.py", line 1736, in getTVDBFromID
    tree = ET.fromstring(data)
  File "/usr/local/python/lib/python2.7/xml/etree/ElementTree.py", line 1300, in XML
    parser.feed(text)
  File "/usr/local/python/lib/python2.7/xml/etree/ElementTree.py", line 1640, in feed
    self._parser.Parse(data, 0)
TypeError: must be string or read-only buffer, not None

```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by miigotu** [comment]
tvdb was down.

@Thraxis maybe handle when the data is None?

**Comment by snapperhead** [comment]
### INFO
Python Version: **2.7.10 (default, Oct 23 2015, 18:17:08) [GCC 4.2.1 Compatible Apple LLVM 7.0.0 (clang-700.0.59.5)]**
Operating System: **Darwin-15.2.0-x86_64-i386-64bit**
Locale: unknown
Branch: **master**
Commit: SickRage/SickRage@97cd0fd633581154fb1ef43f3d2c2c0cc4609ebb
No Log available with ERRORS: 
### ERROR
```
SHOWUPDATER :: Exception generated in thread SHOWUPDATER: must be string or read-only buffer, not None
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by Thraxis** [comment]
@miigotu Yes I'll add in a check for None on that

**Comment by Thraxis** [comment]
https://github.com/SickRage/SickRage/pull/462

**Comment by frriction** [comment]
### INFO
Python Version: **2.7.11 (default, Dec 11 2015, 05:34:18) [GCC 5.3.0]**
Operating System: **Linux-3.10.92-3-ARCH-armv7l-with-glibc2.4**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@16646d679fbffdf948952722fba32867a596922d
No Log available with ERRORS: 
### ERROR
```
SHOWUPDATER :: Exception generated in thread SHOWUPDATER: must be string or read-only buffer, not None
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by mbnoimi** [comment]
### INFO
Python Version: **2.7.6 (default, Jun 22 2015, 17:58:13) [GCC 4.8.2]**
Operating System: **Linux-3.19.0-18-generic-x86_64-with-LinuxMint-17.2-rafaela**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@f6f2afb5df9ec69b9d6a3a839912bfd761520428
No Log available with ERRORS: 
### ERROR
```
SHOWUPDATER :: Exception generated in thread SHOWUPDATER: must be string or read-only buffer, not None
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by StretchCell** [comment]
### INFO
Python Version: **2.7.10 (default, May 23 2015, 09:44:00) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-8-6.2.9200**
Locale: cp1252
Branch: **master**
Commit: SickRage/SickRage@4eccee2ad1b3e3d144bfd8e315fdf397cfd33361
No Log available with ERRORS: 
### ERROR
```
SHOWUPDATER :: Exception generated in thread SHOWUPDATER: must be string or read-only buffer, not None [4eccee2]
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by Antyrael** [comment]
### INFO
Python Version: **2.7.6 (default, Jun 22 2015, 17:58:13) [GCC 4.8.2]**
Operating System: **Linux-3.13.0-74-generic-x86_64-with-Ubuntu-14.04-trusty**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@4eccee2ad1b3e3d144bfd8e315fdf397cfd33361
No Log available with ERRORS: 
### ERROR
```
SHOWUPDATER :: Exception generated in thread SHOWUPDATER: must be string or read-only buffer, not None [4eccee2]
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by miigotu** [comment]
You guys will need to go through your log files and findm the traceback for me. Without the traceback I can't do anything about it.

**Comment by Antyrael** [comment]
I think it might be due to thetvdb.com being protected by cloudflare and returning something unexpected.

`2016-01-06 03:00:04 DEBUG    SHOWUPDATER :: Requested getURL http://thetvdb.com/api/F5E5E1EEEEFFFFEE/updates/updates_day.xml returned status code is 403: Forbidden
2016-01-06 03:00:04 ERROR    SHOWUPDATER :: Exception generated in thread SHOWUPDATER: must be string or read-only buffer, not None [4eccee2]
Traceback (most recent call last):
  File "/home/sabusr/SickRage/sickbeard/scheduler.py", line 106, in run
    self.action.run(self.force)
  File "/home/sabusr/SickRage/sickbeard/showUpdater.py", line 85, in run
    tree = ET.fromstring(data)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1300, in XML
    parser.feed(text)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1640, in feed
    self._parser.Parse(data, 0)
TypeError: must be string or read-only buffer, not None
2016-01-06 03:00:04 DEBUG    SHOWUPDATER :: 'Traceback (most recent call last):\n  File "/home/sabusr/SickRage/sickbeard/scheduler.py", line 106, in run\n    self.action.run(self.force)\n  File "/home/sabusr/SickRage/sickbeard/showUpdater.py", line 85, in run\n    tree = ET.fromstring(data)\n  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1300, in XML\n    parser.feed(text)\n  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1640, in feed\n    self._parser.Parse(data, 0)\nTypeError: must be string or read-only buffer, not None\n'
`

**Comment by fernandog** [comment]
@Antyrael can you access `http://thetvdb.com/api/F5E5E1EEEEFFFFEE/updates/updates_day.xml` in your browser?

**Comment by Antyrael** [comment]
@fernandog Yes, I can. But I remember having problems getting thetvdb.com updates when using a tor/proxy combination. URL's that used to work, were now getting blocked by a cloudflare captcha page (only when I connected through this tor/proxy though).
I was also getting 403: Forbidden when this occurred.

**Comment by duramato** [comment]
@Antyrael the captcha happens if they see that you are making too much requests or if they are on "under atack mode"

**Comment by Antyrael** [comment]
@duramato I know, it's not something you or I can really anticipate. So my guess is that it just happens sometimes ;)

**Comment by miigotu** [comment]
I can add code to handle when it is none. will look later when I'm at the pc

**Comment by miigotu** [comment]
Fixed in develop.

**Comment by raygunxd** [comment]
### INFO
Python Version: **2.7.10 (default, May 23 2015, 09:44:00) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-2012Server-6.2.9200**
Locale: cp1252
Branch: **master**
Commit: SickRage/SickRage@7fd6c98aafe1f543bf8f96b2e370666be5412288
No Log available with ERRORS: 
### ERROR
```
SHOWUPDATER :: Exception generated in thread SHOWUPDATER: must be string or read-only buffer, not None [7fd6c98]
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators
