### ISSUE TITLE
[APP SUBMITTED]: [Errno 2] No such file or directory: '/mnt/media/downloads/sabnzbd/complete/tv/Hawaii.Five-0.2010.S05E22.Ho\xc3\x95amoano.(chasing.Yesterday).1080p.WEB-DL.DD5.1.H.264-KINGS'

### ISSUE THREAD

**Issue by joakim93** [SickRage/sickrage-issues#205]
### INFO
Python Version: **2.7.9 (default, Sep  9 2015, 14:50:03) [GCC 4.2.1 20070831 patched [FreeBSD]]**
Operating System: **FreeBSD-9.1-RELEASE-amd64-64bit-ELF**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@b5b45cb6e8fb8a6ca77860516187368cdeea3ce6
No Log available with ERRORS: 
### ERROR
```
Thread-14 :: Failed doing webui callback: Traceback (most recent call last):
  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/sickbeard/webserve.py", line 271, in async_call
    result = function(**kwargs)
  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/sickbeard/webserve.py", line 2247, in processEpisode
    is_priority=argToBool(is_priority), delete_on=argToBool(delete_on), failed=argToBool(failed), proc_type=type
  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/sickbeard/processTV.py", line 232, in processDir
    for curDir in [x for x in dirs if validateDir(path, x, nzbNameOriginal, failed, result)]:
  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/sickbeard/processTV.py", line 336, in validateDir
    process_failed(ek(os.path.join, path, dirName), nzbNameOriginal, result)
  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/sickbeard/processTV.py", line 608, in process_failed
    result.result = processor.process()
  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/sickbeard/failedProcessor.py", line 49, in process
    releaseName = show_name_helpers.determineReleaseName(self.dir_name, self.nzb_name)
  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/sickbeard/show_name_helpers.py", line 354, in determineReleaseName
    files = [file_name for file_name in ek(os.listdir, dir_name) if
  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/sickrage/helper/encoding.py", line 39, in ek
    result = function(*[ss(x) if isinstance(x, (str, unicode)) else x for x in args], **kwargs)
OSError: [Errno 2] No such file or directory: '/mnt/media/downloads/sabnzbd/complete/tv/Hawaii.Five-0.2010.S05E22.Ho\xc3\x95amoano.(chasing.Yesterday).1080p.WEB-DL.DD5.1.H.264-KINGS'

```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by neoatomic** [comment]
Looks to be a bad nzb/download. : 

`Hawaii.Five-0.2010.S05E22.Ho\xc3\x95amoano.(chasing.Yesterday).1080p.WEB-DL.DD5.1.H.264-KINGS`

Should be a one time error. :)

**Comment by labrys** [comment]
@neoatomic It looks to me like an issue with unicode as `\xc3\x95` should be `Õ`.

**Comment by joakim93** [comment]
I was just about to comment that issue :)

**Comment by fernandog** [comment]
@joakim93 can you confirm that sabnzbd that created the file with the \xc3\x95 ? or the original filename  in nzb has this \xc3\x95 ?

**Comment by joakim93** [comment]
I think my locales are fucked up.. Because it says it can't encode it but it shows Õ in the log.. So I'll do a clean install whenever i got som spare time.. I'll submit a issue if the clean install dosen't solve it
