### ISSUE TITLE
[APP SUBMITTED]: No module named providers.GenericProvider

### ISSUE THREAD

**Issue by dwightturner36** [SickRage/sickrage-issues#213]
### INFO
Python Version: **2.7.9 (default, Sep  9 2015, 14:50:03) [GCC 4.2.1 20070831 patched [FreeBSD]]**
Operating System: **FreeBSD-9.3-RELEASE-p28-amd64-64bit-ELF**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@0142cd326ca59d88885d1ff23063a6522cad9399
Link to Log: https://gist.github.com/11b03587cfa161aa0a42
### ERROR
```
Thread-31 :: Failed doing webui callback: Traceback (most recent call last):
  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/sickbeard/webserve.py", line 265, in async_call
    result = function(**kwargs)
  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/sickbeard/webserve.py", line 4199, in index
    t = PageTemplate(rh=self, filename="config_providers.mako")
  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/sickbeard/webserve.py", line 114, in __init__
    self.template = lookup.get_template(filename)
  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/lib/mako/lookup.py", line 256, in get_template
    return self._load(srcfile, uri)
  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/lib/mako/lookup.py", line 321, in _load
    **self.template_args)
  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/lib/mako/template.py", line 322, in __init__
    module = self._compile_from_file(path, filename)
  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/lib/mako/template.py", line 379, in _compile_from_file
    module = compat.load_module(self.module_id, path)
  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/lib/mako/compat.py", line 89, in load_module
    return imp.load_source(module_id, path, fp)
  File "/var/db/sickrage/cache/mako/config_providers.mako.py", line 19, in <module>
    from sickrage.providers.GenericProvider import GenericProvider
ImportError: No module named providers.GenericProvider

```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by SickRage2** [comment]
Thanks for the issue report! Before a real human comes by, please make sure your report has all the below criteria checked

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [x] Post debug logs, either inline (for smaller logs) or using gist)

Please make sure you also read [how to create an issue](https://github.com/SickRage/sickrage-issues/blob/master/README.md) and followed all of the steps. 

The title should describe your issue. Having "SR not working" or "I get this bug" for 100 issues, isn't really helpful. We will close issues if there isn't enough information.

Sometimes the devs may seem like grunts and respond with short answers. This isn't (always) because the dev hates you, but because he's on mobile or busy fixing bugs. If something isn't clear, please let us know, and this bot may get updated to automatically answer you.

Thanks!

**Comment by miigotu** [comment]
Idk how you are getting this error, but you could try stopping SR and deleting cache/mako
