### ISSUE TITLE
Error on Search provider page, and backlog acting strange.

### ISSUE THREAD

**Issue by neoatomic** [SickRage/sickrage-issues#216]
`SR Version: 	BRANCH: (develop) / COMMIT: (d55e2a0553ef6ac2921609724618187b38001072) `

When i open the Search provider page i get the below error.
Thinking it might be related to the usenet-crawler Cert problems.?

Also Backlog seems to be not working for me. I did a force backlog search, but the log tells me that nothing is needed. However as you can see in the screen shot 2 episodes are wanted.
(Backlog search is 21 days.)

And lastly SR didn't want to submit the error from the GUI. :(

```
2015-12-13 21:03:06 DEBUG    BACKLOG :: Seeing if we need anything from Pawn Stars
2015-12-13 21:03:06 DEBUG    BACKLOG :: 111051: Loading episode details for Pawn Stars S2015E42 from DB
2015-12-13 21:03:06 DEBUG    BACKLOG :: 111051: Loading episode details for Pawn Stars S2015E43 from DB
2015-12-13 21:03:06 DEBUG    BACKLOG :: Nothing needs to be downloaded for Pawn Stars, skipping 
```
![1](https://cloud.githubusercontent.com/assets/7928052/11769146/adbb6374-a1e0-11e5-9b1c-5e6b73408bae.png)

```
2015-12-13 21:23:05 ERROR    Thread-25 :: Failed doing webui callback: Traceback (most recent call last):
  File "/volume1/@appstore/sickrage/var/SickRage/sickbeard/webserve.py", line 271, in async_call
    result = function(**kwargs)
  File "/volume1/@appstore/sickrage/var/SickRage/sickbeard/webserve.py", line 4319, in getNewznabCategories
    success, tv_categories, error = tempProvider.get_newznab_categories()
  File "/volume1/@appstore/sickrage/var/SickRage/sickbeard/providers/newznab.py", line 128, in get_newznab_categories
    for category in data.caps.categories.findAll('category'):
AttributeError: 'NoneType' object has no attribute 'categories'
Traceback (most recent call last):
  File "/volume1/@appstore/sickrage/var/SickRage/sickbeard/webserve.py", line 271, in async_call
    result = function(**kwargs)
  File "/volume1/@appstore/sickrage/var/SickRage/sickbeard/webserve.py", line 4319, in getNewznabCategories
    success, tv_categories, error = tempProvider.get_newznab_categories()
  File "/volume1/@appstore/sickrage/var/SickRage/sickbeard/providers/newznab.py", line 128, in get_newznab_categories
    for category in data.caps.categories.findAll('category'):
AttributeError: 'NoneType' object has no attribute 'categories'
2015-12-13 21:23:05 DEBUG    TORNADO :: Failed doing webui request "getNewznabCategories": Traceback (most recent call last):
  File "/volume1/@appstore/sickrage/var/SickRage/sickbeard/webserve.py", line 256, in get
    results = yield self.async_call(method)
  File "/usr/local/sickrage/var/SickRage/lib/tornado/gen.py", line 870, in run
    value = future.result()
  File "/usr/local/sickrage/var/SickRage/lib/concurrent/futures/_base.py", line 400, in result
    return self.__get_result()
  File "/usr/local/sickrage/var/SickRage/lib/concurrent/futures/_base.py", line 359, in __get_result
    reraise(self._exception, self._traceback)
  File "/usr/local/sickrage/var/SickRage/lib/concurrent/futures/_compat.py", line 107, in reraise
    exec('raise exc_type, exc_value, traceback', {}, locals_)
  File "/usr/local/sickrage/var/SickRage/lib/concurrent/futures/thread.py", line 61, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/volume1/@appstore/sickrage/var/SickRage/sickbeard/webserve.py", line 271, in async_call
    result = function(**kwargs)
  File "/volume1/@appstore/sickrage/var/SickRage/sickbeard/webserve.py", line 4319, in getNewznabCategories
    success, tv_categories, error = tempProvider.get_newznab_categories()
  File "/volume1/@appstore/sickrage/var/SickRage/sickbeard/providers/newznab.py", line 128, in get_newznab_categories
    for category in data.caps.categories.findAll('category'):
AttributeError: 'NoneType' object has no attribute 'categories'
```

**Comment by SickRage2** [comment]
Thanks for the issue report! Before a real human comes by, please make sure your report has all the below criteria checked

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [x] Post debug logs, either inline (for smaller logs) or using gist)
- [x] Please wrap inline logs inside \`\`\` and \`\`\` for readability

Please make sure you also read [how to create an issue](https://github.com/SickRage/sickrage-issues/blob/master/README.md) and followed all of the steps. 

The title should describe your issue. Having "SR not working" or "I get this bug" for 100 issues, isn't really helpful. We will close issues if there isn't enough information.

Sometimes the devs may seem like grunts and respond with short answers. This isn't (always) because the dev hates you, but because he's on mobile or busy fixing bugs. If something isn't clear, please let us know, and this bot may get updated to automatically answer you.

Thanks!

**Comment by miigotu** [comment]
`(Backlog search is 21 days.)`
The shows aired longer than 21 days ago, so a forced backlog search will not search for them.
A manual search will.

Added a check on the soup to prevent that exception, even though it doesnt make much sense =P
