### ISSUE TITLE
[APP SUBMITTED]: int() argument must be a string or a number, not 'NoneType'

### ISSUE THREAD

**Issue by Trapizomba** [SickRage/sickrage-issues#230]
### INFO
Python Version: **2.7.9 (default, Sep  9 2015, 14:50:03) [GCC 4.2.1 20070831 patched [FreeBSD]]**
Operating System: **FreeBSD-9.1-RELEASE-amd64-64bit-ELF**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@2eaf3fb24a465765d22d8ad8f0780d06a2b7ff89
No Log available with ERRORS: 
### ERROR
```
POSTPROCESSER :: Exception generated in thread POSTPROCESSER: int() argument must be a string or a number, not 'NoneType'
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by SickRage2** [comment]
Thanks for the issue report! Before a real human comes by, please make sure your report has all the below criteria checked

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [ ] Post debug logs, either inline (for smaller logs) or using gist)

Please make sure you also read [how to create an issue](https://github.com/SickRage/sickrage-issues/blob/master/README.md) and followed all of the steps. 

The title should describe your issue. Having "SR not working" or "I get this bug" for 100 issues, isn't really helpful. We will close issues if there isn't enough information.

Sometimes the devs may seem like grunts and respond with short answers. This isn't (always) because the dev hates you, but because he's on mobile or busy fixing bugs. If something isn't clear, please let us know, and this bot may get updated to automatically answer you.

Thanks!

**Comment by rrd911** [comment]
### INFO
Python Version: **2.7.10 (default, Oct 14 2015, 16:09:02) [GCC 5.2.1 20151010]**
Operating System: **Linux-4.2.0-22-generic-x86_64-with-Ubuntu-15.10-wily**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@4eccee2ad1b3e3d144bfd8e315fdf397cfd33361
Link to Log: https://gist.github.com/5bd8c1bb4419ac3e5922
### ERROR
```
SHOWQUEUE-ADD :: Error searching dir for episodes: int() argument must be a string or a number, not 'NoneType' [4eccee2]
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by tchobbs** [comment]
### INFO
Python Version: **2.7.9 (default, Mar  1 2015, 12:57:24) [GCC 4.9.2]**
Operating System: **Linux-3.16.0-4-amd64-x86_64-with-debian-8.2**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@820b900a6dc72ed4958a90ac027d8f92d785810b
Link to Log: https://gist.github.com/08cf8903f0bb019c108d
### ERROR
```
POSTPROCESSER :: Exception generated in thread POSTPROCESSER: int() argument must be a string or a number, not 'NoneType' [820b900]
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by tchobbs** [comment]
### INFO
Python Version: **2.7.9 (default, Mar  1 2015, 12:57:24) [GCC 4.9.2]**
Operating System: **Linux-3.16.0-4-amd64-x86_64-with-debian-8.3**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@26ddbf4b882c293c187fe3ec88dd6e826eeed7a7
No Log available with ERRORS:
### ERROR
```
Thread-55 :: Failed doing webui callback: Traceback (most recent call last):
  File "/media/sdb1/home/dowd/.sickrage/sickbeard/webserve.py", line 283, in async_call
    result = function(**kwargs)
  File "/media/sdb1/home/dowd/.sickrage/sickbeard/webserve.py", line 2282, in processEpisode
    is_priority=argToBool(is_priority), delete_on=argToBool(delete_on), failed=argToBool(failed), proc_type=type
  File "/media/sdb1/home/dowd/.sickrage/sickbeard/processTV.py", line 230, in processDir
    process_media(path, [video], nzbName, process_method, force, is_priority, result)
  File "/media/sdb1/home/dowd/.sickrage/sickbeard/processTV.py", line 556, in process_media
    result.result = processor.process()
  File "/media/sdb1/home/dowd/.sickrage/sickbeard/postProcessor.py", line 1001, in process
    if int(ep_obj.season) > int(max_season[0][0]):
TypeError: int() argument must be a string or a number, not 'NoneType'
 [26ddbf4]
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by tchobbs** [comment]
### INFO
Python Version: **2.7.9 (default, Mar  1 2015, 12:57:24) [GCC 4.9.2]**
Operating System: **Linux-3.16.0-4-amd64-x86_64-with-debian-8.3**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@26ddbf4b882c293c187fe3ec88dd6e826eeed7a7
No Log available with ERRORS:
### ERROR
```
Thread-41 :: Failed doing webui callback: Traceback (most recent call last):
  File "/media/sdb1/home/dowd/.sickrage/sickbeard/webserve.py", line 283, in async_call
    result = function(**kwargs)
  File "/media/sdb1/home/dowd/.sickrage/sickbeard/webserve.py", line 2282, in processEpisode
    is_priority=argToBool(is_priority), delete_on=argToBool(delete_on), failed=argToBool(failed), proc_type=type
  File "/media/sdb1/home/dowd/.sickrage/sickbeard/processTV.py", line 230, in processDir
    process_media(path, [video], nzbName, process_method, force, is_priority, result)
  File "/media/sdb1/home/dowd/.sickrage/sickbeard/processTV.py", line 556, in process_media
    result.result = processor.process()
  File "/media/sdb1/home/dowd/.sickrage/sickbeard/postProcessor.py", line 1001, in process
    if int(ep_obj.season) > int(max_season[0][0]):
TypeError: int() argument must be a string or a number, not 'NoneType'
 [26ddbf4]
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by tchobbs** [comment]
Sorry for the report spam.  Here are more details on the files being processed.
```
2016-02-19 16:39:54 INFO     Thread-34 :: Commented on existing issue #230 successfully!
2016-02-19 16:39:26 ERROR    Thread-55 :: Failed doing webui callback: Traceback (most recent call last):
2016-02-19 16:39:26 INFO     Thread-55 :: Processing /media/sdb1/home/****/private/media/complete/tv/Star.Wars.The.Clone.Wars.S01-S06.Complete.480p.BluRay.WEB-DL.WEBRip.x264-Sticky83/Star.Wars.The.Clone.Wars.S05E18.480p.WEB-DL.x264-Sticky83.mkv (None)
2016-02-19 16:39:26 INFO     Thread-55 :: PostProcessing Path: /media/sdb1/home/****/private/media/complete/tv/Star.Wars.The.Clone.Wars.S01-S06.Complete.480p.BluRay.WEB-DL.WEBRip.x264-Sticky83
2016-02-19 16:39:13 ERROR    Thread-48 :: Failed doing webui callback: Traceback (most recent call last):
2016-02-19 16:39:13 INFO     Thread-48 :: Processing /media/sdb1/home/****/private/media/complete/tv/Star.Wars.The.Clone.Wars.S01-S06.Complete.480p.BluRay.WEB-DL.WEBRip.x264-Sticky83/Star.Wars.The.Clone.Wars.S05E18.480p.WEB-DL.x264-Sticky83.mkv (None)
2016-02-19 16:39:13 INFO     Thread-48 :: PostProcessing Path: /media/sdb1/home/****/private/media/complete/tv/Star.Wars.The.Clone.Wars.S01-S06.Complete.480p.BluRay.WEB-DL.WEBRip.x264-Sticky83
2016-02-19 16:36:07 INFO     Thread-58 :: No update needed
2016-02-19 16:34:34 ERROR    Thread-62 :: Failed doing webui callback: Traceback (most recent call last):
2016-02-19 16:34:34 INFO     Thread-62 :: Processing /media/sdb1/home/****/private/media/complete/tv/Star.Wars.The.Clone.Wars.S01-S06.Complete.480p.BluRay.WEB-DL.WEBRip.x264-Sticky83/Star.Wars.The.Clone.Wars.S05E18.480p.WEB-DL.x264-Sticky83.mkv (None)
2016-02-19 16:34:34 INFO     Thread-62 :: PostProcessing Path: /media/sdb1/home/****/private/media/complete/tv/Star.Wars.The.Clone.Wars.S01-S06.Complete.480p.BluRay.WEB-DL.WEBRip.x264-Sticky83
2016-02-19 16:33:22 ERROR    Thread-48 :: Failed doing webui callback: Traceback (most recent call last):
2016-02-19 16:33:22 INFO     Thread-48 :: Processing /media/sdb1/home/****/private/media/complete/tv/Star.Wars.The.Clone.Wars.S01-S06.Complete.480p.BluRay.WEB-DL.WEBRip.x264-Sticky83/Star.Wars.The.Clone.Wars.S05E18.480p.WEB-DL.x264-Sticky83.mkv (None)
2016-02-19 16:33:22 INFO     Thread-48 :: PostProcessing Path: /media/sdb1/home/****/private/media/complete/tv/Star.Wars.The.Clone.Wars.S01-S06.Complete.480p.BluRay.WEB-DL.WEBRip.x264-Sticky83
2016-02-19 16:31:15 INFO     POSTPROCESSER :: Processing /media/sdb1/home/****/private/media/complete/tv/Star.Wars.The.Clone.Wars.S01-S06.Complete.480p.BluRay.WEB-DL.WEBRip.x264-Sticky83/Star.Wars.The.Clone.Wars.S05E18.480p.WEB-DL.x264-Sticky83.mkv (None)
```

**Comment by fernandog** [comment]
Enable debug in SR. Restart SR. Reproduce error and past new logs.

**Comment by tchobbs** [comment]
### INFO
Python Version: **2.7.9 (default, Mar  1 2015, 12:57:24) [GCC 4.9.2]**
Operating System: **Linux-3.16.0-4-amd64-x86_64-with-debian-8.3**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@26ddbf4b882c293c187fe3ec88dd6e826eeed7a7
No Log available with ERRORS:
### ERROR
```
Thread-28 :: Failed doing webui callback: Traceback (most recent call last):
  File "/media/sdb1/home/dowd/.sickrage/sickbeard/webserve.py", line 283, in async_call
    result = function(**kwargs)
  File "/media/sdb1/home/dowd/.sickrage/sickbeard/webserve.py", line 2282, in processEpisode
    is_priority=argToBool(is_priority), delete_on=argToBool(delete_on), failed=argToBool(failed), proc_type=type
  File "/media/sdb1/home/dowd/.sickrage/sickbeard/processTV.py", line 230, in processDir
    process_media(path, [video], nzbName, process_method, force, is_priority, result)
  File "/media/sdb1/home/dowd/.sickrage/sickbeard/processTV.py", line 556, in process_media
    result.result = processor.process()
  File "/media/sdb1/home/dowd/.sickrage/sickbeard/postProcessor.py", line 1001, in process
    if int(ep_obj.season) > int(max_season[0][0]):
TypeError: int() argument must be a string or a number, not 'NoneType'
 [26ddbf4]
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by tchobbs** [comment]
Debug is enabled in config.ini and the UI.  I have restarted.
The auto-reporting is not picking up additional logs.  I'm trying again with the UI filter set to DEBUG.

**Comment by tchobbs** [comment]
### INFO
Python Version: **2.7.9 (default, Mar  1 2015, 12:57:24) [GCC 4.9.2]**
Operating System: **Linux-3.16.0-4-amd64-x86_64-with-debian-8.3**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@26ddbf4b882c293c187fe3ec88dd6e826eeed7a7
No Log available with ERRORS:
### ERROR
```
Thread-41 :: Failed doing webui callback: Traceback (most recent call last):
  File "/media/sdb1/home/dowd/.sickrage/sickbeard/webserve.py", line 283, in async_call
    result = function(**kwargs)
  File "/media/sdb1/home/dowd/.sickrage/sickbeard/webserve.py", line 2282, in processEpisode
    is_priority=argToBool(is_priority), delete_on=argToBool(delete_on), failed=argToBool(failed), proc_type=type
  File "/media/sdb1/home/dowd/.sickrage/sickbeard/processTV.py", line 230, in processDir
    process_media(path, [video], nzbName, process_method, force, is_priority, result)
  File "/media/sdb1/home/dowd/.sickrage/sickbeard/processTV.py", line 556, in process_media
    result.result = processor.process()
  File "/media/sdb1/home/dowd/.sickrage/sickbeard/postProcessor.py", line 1001, in process
    if int(ep_obj.season) > int(max_season[0][0]):
TypeError: int() argument must be a string or a number, not 'NoneType'
 [26ddbf4]
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by tchobbs** [comment]
I'm not sure why the logs are not being picked up.
Here is the gist: https://gist.github.com/e58ec1b8e2d31c0537b4

**Comment by fernandog** [comment]
the new submit is fine. thanks

**Comment by fernandog** [comment]
@tchobbs can you send a full print of the show page that is failing to process?

**Comment by tchobbs** [comment]
![show](https://cloud.githubusercontent.com/assets/1881208/13194984/310ddb72-d7a5-11e5-843c-b6325541550c.png)

Please let me know if you need more information

**Comment by fernandog** [comment]
There is no season and episode info?!

**Comment by tchobbs** [comment]
The entire page is in the screenshot.  I have attempted a manual scan on the folder where the files are downloaded and that is the log I have attached.

Based on your surprise that the shows were not even located, I have removed and re-added the show and now it has the seasons AND processes the files correctly.

Thank you for your assistance in leading to a solution.

**Comment by fernandog** [comment]
@labrys may check if ep object has at least one season and one episode for that season?

**Comment by labrys** [comment]
@tchobbs You are on the old repository.  Please update to this repository and let us know if this still occurs.

**Comment by tchobbs** [comment]
Thank you for letting me know, I've changed to the correct repo.  Thanks for all the assistance on this issue and the great work on the project!

**Comment by mchrisley** [comment]
### INFO
Python Version: **2.7.11 (default, Dec 17 2015, 15:58:38) [GCC 4.7.3 20130102 (prerelease)]**
Operating System: **Linux-3.10.35-x86_64-with-glibc2.2.5**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@06f023f5cdd4449ef2ef7795e3fa55f40882f634
No Log available with ERRORS:
### ERROR
```
Thread-14 :: Failed doing webui callback: Traceback (most recent call last):
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/webserve.py", line 283, in async_call
    result = function(**kwargs)
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/webserve.py", line 2282, in processEpisode
    is_priority=argToBool(is_priority), delete_on=argToBool(delete_on), failed=argToBool(failed), proc_type=type
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/processTV.py", line 156, in func_wrapper
    ret = func(*args, **kargs)
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/processTV.py", line 297, in processDir
    process_media(processPath, videoFiles, nzbName, process_method, force, is_priority, result)
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/processTV.py", line 575, in process_media
    result.result = processor.process()
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/postProcessor.py", line 1001, in process
    if int(ep_obj.season) > int(max_season[0][0]):
TypeError: int() argument must be a string or a number, not 'NoneType'
 [06f023f]
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by veribaka** [comment]
### INFO
Python Version: **2.7.9 (default, Mar  1 2015, 13:48:22) [GCC 4.9.2]**
Operating System: **Linux-4.2.3-sunxi-armv7l-with-debian-8.3**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@ace5e56d632654b03f00d533c2489440e792cba9
No Log available with ERRORS:
### ERROR
```
POSTPROCESSER :: Exception generated in thread POSTPROCESSER: int() argument must be a string or a number, not 'NoneType' [ace5e56]
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by jonnyboy** [comment]
### INFO
Python Version: **2.7.6 (default, Jun 22 2015, 17:58:13) [GCC 4.8.2]**
Operating System: **Linux-4.2.0-30-generic-x86_64-with-Ubuntu-14.04-trusty**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@cc2812af9bd824653fbaf9b0fb49c48ce097a766
No Log available with ERRORS:
### ERROR
```
Thread-15 :: [cc2812a] Failed doing webui callback: Traceback (most recent call last):
  File "/opt/sickrage/sickbeard/webserve.py", line 287, in async_call
    result = function(**kwargs)
  File "/opt/sickrage/sickbeard/webserve.py", line 2286, in processEpisode
    is_priority=argToBool(is_priority), delete_on=argToBool(delete_on), failed=argToBool(failed), proc_type=type
  File "/opt/sickrage/sickbeard/processTV.py", line 156, in func_wrapper
    ret = func(*args, **kargs)
  File "/opt/sickrage/sickbeard/processTV.py", line 297, in processDir
    process_media(processPath, videoFiles, nzbName, process_method, force, is_priority, result)
  File "/opt/sickrage/sickbeard/processTV.py", line 575, in process_media
    result.result = processor.process()
  File "/opt/sickrage/sickbeard/postProcessor.py", line 1014, in process
    if int(ep_obj.season) > int(max_season[0][0]):
TypeError: int() argument must be a string or a number, not 'NoneType'

```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators
