### ISSUE TITLE
[BitCannon] Unknown exception in getURL

### ISSUE THREAD

**Issue by Trapizomba** [SickRage/sickrage-issues#231]
>**SR Version:** BRANCH: (master) / COMMIT: (2eaf3fb24a465765d22d8ad8f0780d06a2b7ff89) 
>**SR Arguments:** ['--datadir', '/var/db/sickrage', '-d', '--pidfile', '/var/run/sickrage/sickrage.pid', '-q', '--nolaunch']
>**Python Version:** 2.7.9 (default, Sep 9 2015, 14:50:03) [GCC 4.2.1 20070831 patched [FreeBSD]]

**Log:**
```
2015-12-15 09:32:16 SEARCHQUEUE-BACKLOG-281662 :: [BitCannon] :: Unknown exception in getURL /api/search?q=Marvel%27s+Daredevil+S01E01&category=tv&apiKey= Error: "Invalid URL '/api/search?q=Marvel%27s+Daredevil+S01E01&category=tv&apiKey=': No schema supplied. Perhaps you meant http:///api/search?q=Marvel%27s+Daredevil+S01E01&category=tv&apiKey=?"
2015-12-15 09:32:16 SEARCHQUEUE-BACKLOG-281662 :: [BitCannon] :: Traceback (most recent call last):
  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/sickbeard/helpers.py", line 1440, in getURL
    resp = session.get(url, timeout=timeout, allow_redirects=True, verify=session.verify)
  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/lib/requests/sessions.py", line 480, in get
    return self.request('GET', url, **kwargs)
  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/lib/requests/sessions.py", line 454, in request
    prep = self.prepare_request(req)
  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/lib/requests/sessions.py", line 388, in prepare_request
    hooks=merge_hooks(request.hooks, self.hooks),
  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/lib/requests/models.py", line 293, in prepare
    self.prepare_url(url, params)
  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/lib/requests/models.py", line 353, in prepare_url
    raise MissingSchema(error)
MissingSchema: Invalid URL '/api/search?q=Marvel%27s+Daredevil+S01E01&category=tv&apiKey=': No schema supplied. Perhaps you meant http:///api/search?q=Marvel%27s+Daredevil+S01E01&category=tv&apiKey=?
```

**Comment by SickRage2** [comment]
Thanks for the issue report! Before a real human comes by, please make sure your report has all the below criteria checked

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [ ] Post debug logs, either inline (for smaller logs) or using gist)

Please make sure you also read [how to create an issue](https://github.com/SickRage/sickrage-issues/blob/master/README.md) and followed all of the steps. 

The title should describe your issue. Having "SR not working" or "I get this bug" for 100 issues, isn't really helpful. We will close issues if there isn't enough information.

Sometimes the devs may seem like grunts and respond with short answers. This isn't (always) because the dev hates you, but because he's on mobile or busy fixing bugs. If something isn't clear, please let us know, and this bot may get updated to automatically answer you.

Thanks!

**Comment by labrys** [comment]
@Trapizomba please wrap your logs in \`\`\` so it's easier to read them.  I have done it for you this time.

**Comment by labrys** [comment]
@Trapizomba It looks like you don't have a URL configured for BitCannon, can you please check your settings?

**Comment by OmgImAlexis** [comment]
@labrys this could also happen if they're using the old version of it before it was converted to node.
[This](https://github.com/bitcannon-org/bitcannon-web) is the node version and it's the only one that works with SickRage.

**Comment by duramato** [comment]
cant both be supported?

**Comment by OmgImAlexis** [comment]
@duramato no, the api changed drastically between the two versions. We choose to only support this version since the old one probably isn't ever being updated again.

**Comment by Trapizomba** [comment]
Looking my BitCannon's Provider Options, the "Custom URL" have a "/" in it...

I did not set this value after the clean install...

Do I need to remove the "/"?

Thank you!

**Comment by miigotu** [comment]
You need to set the url to the url of your bitcannon install.
