### ISSUE TITLE
Shows with a "!" in the episode title.

### ISSUE THREAD

**Issue by Trotter73** [SickRage/sickrage-issues#233]
Hi Guys,

 I think I have found an issue with how SR handles shows with a ! in the title, an example would be 3rd Rock from the Sun, Season 3, Episodes 14 & 15

The episode listings seem to get messed, 36 episodes are listed up and files do not process properly, I’ve checked on thetvdb and the show listings there seem as I would expect, 27 episodes....

SR Version: 	BRANCH: (master) / COMMIT: (2eaf3fb24a465765d22d8ad8f0780d06a2b7ff89)
SR Locale:	('en_GB', 'cp1252')
SR Config:	C:\Utils\Sickrage\config.ini
SR Database:	C:\Utils\Sickrage\sickbeard.db
SR Cache Dir:	C:\Utils\Sickrage\cache
SR Log Dir:	C:\Utils\Sickrage\Logs
SR Arguments:	['--nolaunch', '--quiet']
Python Version:	2.7.10 (default, May 23 2015, 09:40:32) [MSC v.1500 32 bit (Intel)]

Any ideas ?

Trotter.

**Comment by SickRage2** [comment]
Thanks for the issue report! Before a real human comes by, please make sure your report has all the below criteria checked

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [ ] Post debug logs, either inline (for smaller logs) or using gist)

Please make sure you also read [how to create an issue](https://github.com/SickRage/sickrage-issues/blob/master/README.md) and followed all of the steps. 

The title should describe your issue. Having "SR not working" or "I get this bug" for 100 issues, isn't really helpful. We will close issues if there isn't enough information.

Sometimes the devs may seem like grunts and respond with short answers. This isn't (always) because the dev hates you, but because he's on mobile or busy fixing bugs. If something isn't clear, please let us know, and this bot may get updated to automatically answer you.

Thanks!

**Comment by fernandog** [comment]
@Trotter73 can you send some screen shots?

Just drag&drop image in the input field

**Comment by Trotter73** [comment]
Hi,
Thanks for taking the time to look !

There is some strange voodoo in the logs as well, when I get 5 I'll run a manual process and post back here...

![capture1](https://cloud.githubusercontent.com/assets/16307645/11873098/c0807d1c-a4d0-11e5-92ae-e849c8926dc9.JPG)

![capture2](https://cloud.githubusercontent.com/assets/16307645/11873157/06aa4e3a-a4d1-11e5-8d2d-60b49fa0e54c.JPG)

**Comment by Trotter73** [comment]
2015-12-17 15:27:08 INFO     Thread-19 :: Processing C:\Users\trotter\Documents\Downloads\complete\TV\3rd Rock From The Sun S03 DVDRip x264-hqe\3rd Rock from the Sun - S03E14-36! 24! 36! Dick! (1).mkv (None)
2015-12-17 15:27:08 INFO     Thread-19 :: This download is marked a priority download so I'm going to replace an existing file if I find one
2015-12-17 15:27:09 ERROR    Thread-19 :: Unable to copy file C:\Users\trotter\Documents\Downloads\complete\TV\3rd Rock From The Sun S03 DVDRip x264-hqe\3rd Rock from the Sun - S03E14-36! 24! 36! Dick! (1).mkv to E:\My Documents\My Videos\TV\Shows\3rd Rock from the Sun\Season-3\3rd Rock from the Sun - S03E14E15E16E17E18E19E20E21E22E23E24E25E26E27E28E29E30E31E32E33E34E35E36 - 36! 24! 36! Dick! (1) & 36! 24! 36! Dick! (2) & Pickles and Ice Cream & Auto EuroDicka & Portrait of Tommy as an Old Man & Stuck with Dick & My Daddy's Little Girl & The Physics of Being Dick & Just Your Average Dick & Dick and the Other Guy & Sally and Don's First Kiss & When Aliens Camp & The Tooth Harry & Eat, Drink, Dick, Mary &  &  &  &  &  &  &  &  &.mkv: error 2 : No such file or directory
Traceback (most recent call last):
  File "C:\Utils\Sickrage\sickbeard\postProcessor.py", line 414, in _int_copy
    helpers.copyFile(cur_file_path, new_file_path)
  File "C:\Utils\Sickrage\sickbeard\helpers.py", line 347, in copyFile
    ek(shutil.copyfile, srcFile, destFile)
  File "C:\Utils\Sickrage\sickrage\helper\encoding.py", line 37, in ek
    result = function(*args, **kwargs)
  File "C:\Utils\Sickrage\lib\shutil_custom\__init__.py", line 42, in copyfile_custom
    fout = os.open(dst, WRITE_FLAGS)
OSError: [Errno 2] No such file or directory
2015-12-17 15:27:09 WARNING  Thread-19 :: Processing failed for C:\Users\trotter\Documents\Downloads\complete\TV\3rd Rock From The Sun S03 DVDRip x264-hqe\3rd Rock from the Sun - S03E14-36! 24! 36! Dick! (1).mkv: Unable to move the files to their new home
2015-12-17 15:27:09 INFO     Thread-19 :: Processing C:\Users\trotter\Documents\Downloads\complete\TV\3rd Rock From The Sun S03 DVDRip x264-hqe\3rd Rock from the Sun - S03E15-36! 24! 36! Dick! (2).mkv (None)
2015-12-17 15:27:09 ERROR    Thread-19 :: Unable to copy file C:\Users\trotter\Documents\Downloads\complete\TV\3rd Rock From The Sun S03 DVDRip x264-hqe\3rd Rock from the Sun - S03E15-36! 24! 36! Dick! (2).mkv to E:\My Documents\My Videos\TV\Shows\3rd Rock from the Sun\Season-3\3rd Rock from the Sun - S03E15E16E17E18E19E20E21E22E23E24E25E26E27E28E29E30E31E32E33E34E35E36 - 36! 24! 36! Dick! (2) & Pickles and Ice Cream & Auto EuroDicka & Portrait of Tommy as an Old Man & Stuck with Dick & My Daddy's Little Girl & The Physics of Being Dick & Just Your Average Dick & Dick and the Other Guy & Sally and Don's First Kiss & When Aliens Camp & The Tooth Harry & Eat, Drink, Dick, Mary &  &  &  &  &  &  &  &  &.mkv: error 2 : No such file or directory
Traceback (most recent call last):
  File "C:\Utils\Sickrage\sickbeard\postProcessor.py", line 414, in _int_copy
    helpers.copyFile(cur_file_path, new_file_path)
  File "C:\Utils\Sickrage\sickbeard\helpers.py", line 347, in copyFile
    ek(shutil.copyfile, srcFile, destFile)
  File "C:\Utils\Sickrage\sickrage\helper\encoding.py", line 37, in ek
    result = function(*args, **kwargs)
  File "C:\Utils\Sickrage\lib\shutil_custom\__init__.py", line 42, in copyfile_custom
    fout = os.open(dst, WRITE_FLAGS)
OSError: [Errno 2] No such file or directory

**Comment by miigotu** [comment]
This has nothing to do with the !, its the `S03E15-36`

A small adjustment in the regex should fix this

**Comment by miigotu** [comment]
Fixed in develop

**Comment by Trotter73** [comment]
Nice one, thanks Gents, appreciated !
