### ISSUE TITLE
[APP SUBMITTED]: list index out of range

### ISSUE THREAD

**Issue by duramato** [SickRage/sickrage-issues#235]
### INFO
Python Version: **2.7.6 (default, Jun 22 2015, 18:00:18) [GCC 4.8.2]**
Operating System: **Linux-3.19.0-39-generic-i686-with-Ubuntu-14.04-trusty**
Locale: unknown
Branch: **develop**
Commit: SickRage/SickRage@5732e314ad14130bae8981660bce039d10155530
No Log available with ERRORS: 
### ERROR
```
FINDSUBTITLES :: Traceback (most recent call last):
  File "/home/home/SickRage/sickbeard/subtitles.py", line 200, in download_subtitles
    matches = sub.get_matches(video, hearing_impaired=False)
  File "/home/home/SickRage/lib/subliminal/providers/opensubtitles.py", line 69, in get_matches
    matches |= guess_matches(video, guess_episode_info(self.movie_release_name + '.mkv'))
  File "/home/home/SickRage/lib/guessit/__init__.py", line 370, in guess_episode_info
    return guess_file_info(filename, info=info, options=options, type='episode', **kwargs)
  File "/home/home/SickRage/lib/guessit/__init__.py", line 302, in guess_file_info
    result.append(_guess_filename(filename, options, **kwargs))
  File "/home/home/SickRage/lib/guessit/__init__.py", line 114, in _guess_filename
    mtree = _build_filename_mtree(filename, options=options, **kwargs)
  File "/home/home/SickRage/lib/guessit/__init__.py", line 121, in _build_filename_mtree
    mtree = IterativeMatcher(filename, options=options, **kwargs)
  File "/home/home/SickRage/lib/guessit/matcher.py", line 120, in __init__
    self._process(transformer, False)
  File "/home/home/SickRage/lib/guessit/matcher.py", line 138, in _process
    transformer.process(self.match_tree, self.options)
  File "/home/home/SickRage/lib/guessit/transfo/guess_filetype.py", line 214, in process
    filetype, other = self.guess_filetype(mtree, options)
  File "/home/home/SickRage/lib/guessit/transfo/guess_filetype.py", line 141, in guess_filetype
    guess = episode_transformer.guess_episodes_rexps(filename_part)
  File "/home/home/SickRage/lib/guessit/transfo/guess_episodes_rexps.py", line 124, in guess_episodes_rexps
    guess = self.container.as_guess(found, string)
  File "/home/home/SickRage/lib/guessit/containers.py", line 630, in as_guess
    value = self._effective_prop_value(prop, group_name, input, match.span(group_name) if group_name else match.span(), sep_replacement)
  File "/home/home/SickRage/lib/guessit/containers.py", line 669, in _effective_prop_value
    value = prop.format(value, group_name)
  File "/home/home/SickRage/lib/guessit/containers.py", line 377, in format
    return formatter(value)
  File "/home/home/SickRage/lib/guessit/transfo/guess_episodes_rexps.py", line 56, in episode_parser_x
    return list_parser(value, 'episodeList', discrete_separators_re=re.compile('x', re.IGNORECASE))
  File "/home/home/SickRage/lib/guessit/patterns/list.py", line 36, in list_parser
    proper_discrete_elements[i - 1] += discrete_elements[i]
IndexError: list index out of range

```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by SickRage2** [comment]
Thanks for the issue report! Before a real human comes by, please make sure your report has all the below criteria checked

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [ ] Post debug logs, either inline (for smaller logs) or using gist)

Please make sure you also read [how to create an issue](https://github.com/SickRage/sickrage-issues/blob/master/README.md) and followed all of the steps. 

The title should describe your issue. Having "SR not working" or "I get this bug" for 100 issues, isn't really helpful. We will close issues if there isn't enough information.

Sometimes the devs may seem like grunts and respond with short answers. This isn't (always) because the dev hates you, but because he's on mobile or busy fixing bugs. If something isn't clear, please let us know, and this bot may get updated to automatically answer you.

Thanks!

**Comment by miigotu** [comment]
updated guessit fixes this afaik.

**Comment by tuxfre** [comment]
### INFO
Python Version: **2.7.9 (default, Mar  1 2015, 13:48:22) [GCC 4.9.2]**
Operating System: **Linux-3.2.26-armv7l-with-debian-7.1**
Locale: unknown
Branch: **master**
Commit: SickRage/SickRage@ed25b12a4e71535607a72d8036e43a830e435595
No Log available with ERRORS: 
### ERROR
```
SEARCHQUEUE-BACKLOG-259702 :: [Cpasbien] :: Failed parsing provider. Traceback: Traceback (most recent call last):
  File "/opt/sickrage/SickRage/sickbeard/providers/cpasbien.py", line 94, in search
    seeders = torrent.findAll(attrs={'class': ["seed_ok"]})[0].text
IndexError: list index out of range
 [ed25b12]
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by miigotu** [comment]
@tuxfre working on the cpasbian provider now, will let you know.

**Comment by joakim93** [comment]
### INFO
Python Version: **2.7.9 (default, Sep  9 2015, 14:50:03) [GCC 4.2.1 20070831 patched [FreeBSD]]**
Operating System: **FreeBSD-9.1-RELEASE-amd64-64bit-ELF**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@1b0a6a5a6cc665fcdc4cf69f5b67d4a07add1522
Link to Log: https://gist.github.com/2b596d95870fc5d7616f
### ERROR
```
SEARCHQUEUE-MANUAL-278125 :: [TorrentBytes] :: Unknown exception while searching TorrentBytes. Error: 'list index out of range' [1b0a6a5]
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by HitmanThe47** [comment]
### INFO
Python Version: **2.7.6 (default, Mar 22 2014, 22:59:56) [GCC 4.8.2]**
Operating System: **Linux-3.14.51-grsec-x86_64-with-Ubuntu-14.04-trusty**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@8695768ddc77b28c451bcd7b6f2f0fbbc299bd46
Link to Log: https://gist.github.com/6e57cd479fac7a612766
### ERROR
```
SEARCHQUEUE-BACKLOG-299139 :: [TorrentBytes] :: Unknown exception while searching TorrentBytes. Error: 'list index out of range' [8695768]
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by HitmanThe47** [comment]
### INFO
Python Version: **2.7.6 (default, Mar 22 2014, 22:59:56) [GCC 4.8.2]**
Operating System: **Linux-3.14.51-grsec-x86_64-with-Ubuntu-14.04-trusty**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@8695768ddc77b28c451bcd7b6f2f0fbbc299bd46
No Log available with ERRORS:
### ERROR
```
SEARCHQUEUE-BACKLOG-295686 :: [TorrentBytes] :: Unknown exception while searching TorrentBytes. Error: 'list index out of range' [8695768]
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by HitmanThe47** [comment]
### INFO
Python Version: **2.7.6 (default, Mar 22 2014, 22:59:56) [GCC 4.8.2]**
Operating System: **Linux-3.14.51-grsec-x86_64-with-Ubuntu-14.04-trusty**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@8695768ddc77b28c451bcd7b6f2f0fbbc299bd46
No Log available with ERRORS:
### ERROR
```
SEARCHQUEUE-BACKLOG-295684 :: [TorrentBytes] :: Unknown exception while searching TorrentBytes. Error: 'list index out of range' [8695768]
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by HitmanThe47** [comment]
### INFO
Python Version: **2.7.6 (default, Mar 22 2014, 22:59:56) [GCC 4.8.2]**
Operating System: **Linux-3.14.51-grsec-x86_64-with-Ubuntu-14.04-trusty**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@8695768ddc77b28c451bcd7b6f2f0fbbc299bd46
No Log available with ERRORS:
### ERROR
```
SEARCHQUEUE-BACKLOG-301347 :: [TorrentBytes] :: Unknown exception while searching TorrentBytes. Error: 'list index out of range' [8695768]
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by HitmanThe47** [comment]
### INFO
Python Version: **2.7.6 (default, Mar 22 2014, 22:59:56) [GCC 4.8.2]**
Operating System: **Linux-3.14.51-grsec-x86_64-with-Ubuntu-14.04-trusty**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@8695768ddc77b28c451bcd7b6f2f0fbbc299bd46
No Log available with ERRORS:
### ERROR
```
SEARCHQUEUE-BACKLOG-293614 :: [TorrentBytes] :: Unknown exception while searching TorrentBytes. Error: 'list index out of range' [8695768]
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by HitmanThe47** [comment]
### INFO
Python Version: **2.7.6 (default, Mar 22 2014, 22:59:56) [GCC 4.8.2]**
Operating System: **Linux-3.14.51-grsec-x86_64-with-Ubuntu-14.04-trusty**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@8695768ddc77b28c451bcd7b6f2f0fbbc299bd46
No Log available with ERRORS:
### ERROR
```
SEARCHQUEUE-BACKLOG-295760 :: [TorrentBytes] :: Unknown exception while searching TorrentBytes. Error: 'list index out of range' [8695768]
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by HitmanThe47** [comment]
### INFO
Python Version: **2.7.6 (default, Mar 22 2014, 22:59:56) [GCC 4.8.2]**
Operating System: **Linux-3.14.51-grsec-x86_64-with-Ubuntu-14.04-trusty**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@8695768ddc77b28c451bcd7b6f2f0fbbc299bd46
No Log available with ERRORS:
### ERROR
```
SEARCHQUEUE-BACKLOG-281485 :: [TorrentBytes] :: Unknown exception while searching TorrentBytes. Error: 'list index out of range' [8695768]
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by HitmanThe47** [comment]
### INFO
Python Version: **2.7.6 (default, Mar 22 2014, 22:59:56) [GCC 4.8.2]**
Operating System: **Linux-3.14.51-grsec-x86_64-with-Ubuntu-14.04-trusty**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@8695768ddc77b28c451bcd7b6f2f0fbbc299bd46
No Log available with ERRORS:
### ERROR
```
SEARCHQUEUE-BACKLOG-284190 :: [TorrentBytes] :: Unknown exception while searching TorrentBytes. Error: 'list index out of range' [8695768]
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by HitmanThe47** [comment]
### INFO
Python Version: **2.7.6 (default, Mar 22 2014, 22:59:56) [GCC 4.8.2]**
Operating System: **Linux-3.14.51-grsec-x86_64-with-Ubuntu-14.04-trusty**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@8695768ddc77b28c451bcd7b6f2f0fbbc299bd46
No Log available with ERRORS:
### ERROR
```
SEARCHQUEUE-BACKLOG-265074 :: [TorrentBytes] :: Unknown exception while searching TorrentBytes. Error: 'list index out of range' [8695768]
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by HitmanThe47** [comment]
### INFO
Python Version: **2.7.6 (default, Mar 22 2014, 22:59:56) [GCC 4.8.2]**
Operating System: **Linux-3.14.51-grsec-x86_64-with-Ubuntu-14.04-trusty**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@8695768ddc77b28c451bcd7b6f2f0fbbc299bd46
No Log available with ERRORS:
### ERROR
```
SEARCHQUEUE-BACKLOG-75805 :: [TorrentBytes] :: Unknown exception while searching TorrentBytes. Error: 'list index out of range' [8695768]
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by HitmanThe47** [comment]
### INFO
Python Version: **2.7.6 (default, Mar 22 2014, 22:59:56) [GCC 4.8.2]**
Operating System: **Linux-3.14.51-grsec-x86_64-with-Ubuntu-14.04-trusty**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@8695768ddc77b28c451bcd7b6f2f0fbbc299bd46
No Log available with ERRORS:
### ERROR
```
SEARCHQUEUE-BACKLOG-80379 :: [TorrentBytes] :: Unknown exception while searching TorrentBytes. Error: 'list index out of range' [8695768]
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by HitmanThe47** [comment]
### INFO
Python Version: **2.7.6 (default, Mar 22 2014, 22:59:56) [GCC 4.8.2]**
Operating System: **Linux-3.14.51-grsec-x86_64-with-Ubuntu-14.04-trusty**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@8695768ddc77b28c451bcd7b6f2f0fbbc299bd46
No Log available with ERRORS:
### ERROR
```
SEARCHQUEUE-BACKLOG-261451 :: [TorrentBytes] :: Unknown exception while searching TorrentBytes. Error: 'list index out of range' [8695768]
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by HitmanThe47** [comment]
### INFO
Python Version: **2.7.6 (default, Mar 22 2014, 22:59:56) [GCC 4.8.2]**
Operating System: **Linux-3.14.51-grsec-x86_64-with-Ubuntu-14.04-trusty**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@8695768ddc77b28c451bcd7b6f2f0fbbc299bd46
No Log available with ERRORS:
### ERROR
```
SEARCHQUEUE-BACKLOG-281776 :: [TorrentBytes] :: Unknown exception while searching TorrentBytes. Error: 'list index out of range' [8695768]
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by HitmanThe47** [comment]
### INFO
Python Version: **2.7.6 (default, Mar 22 2014, 22:59:56) [GCC 4.8.2]**
Operating System: **Linux-3.14.51-grsec-x86_64-with-Ubuntu-14.04-trusty**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@8695768ddc77b28c451bcd7b6f2f0fbbc299bd46
No Log available with ERRORS:
### ERROR
```
SEARCHQUEUE-BACKLOG-277021 :: [TorrentBytes] :: Unknown exception while searching TorrentBytes. Error: 'list index out of range' [8695768]
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by HitmanThe47** [comment]
### INFO
Python Version: **2.7.6 (default, Mar 22 2014, 22:59:56) [GCC 4.8.2]**
Operating System: **Linux-3.14.51-grsec-x86_64-with-Ubuntu-14.04-trusty**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@8695768ddc77b28c451bcd7b6f2f0fbbc299bd46
No Log available with ERRORS:
### ERROR
```
SEARCHQUEUE-BACKLOG-279121 :: [TorrentBytes] :: Unknown exception while searching TorrentBytes. Error: 'list index out of range' [8695768]
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by HitmanThe47** [comment]
### INFO
Python Version: **2.7.6 (default, Mar 22 2014, 22:59:56) [GCC 4.8.2]**
Operating System: **Linux-3.14.51-grsec-x86_64-with-Ubuntu-14.04-trusty**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@8695768ddc77b28c451bcd7b6f2f0fbbc299bd46
No Log available with ERRORS:
### ERROR
```
SEARCHQUEUE-BACKLOG-263365 :: [TorrentBytes] :: Unknown exception while searching TorrentBytes. Error: 'list index out of range' [8695768]
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by jaypjay** [comment]
### INFO
Python Version: **2.7.11 (v2.7.11:6d1b6a68f775, Dec  5 2015, 20:40:30) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-2008ServerR2-6.1.7601-SP1**
Locale: cp1252
Branch: **master**
Commit: SickRage/SickRage@26ddbf4b882c293c187fe3ec88dd6e826eeed7a7
Link to Log: https://gist.github.com/4d119e9d705cce3adef0
### ERROR
```
SEARCHQUEUE-BACKLOG-74475 :: [TorrentBytes] :: Unknown exception while searching TorrentBytes. Error: 'list index out of range' [26ddbf4]
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by jaypjay** [comment]
### INFO
Python Version: **2.7.11 (v2.7.11:6d1b6a68f775, Dec  5 2015, 20:40:30) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-2008ServerR2-6.1.7601-SP1**
Locale: cp1252
Branch: **master**
Commit: SickRage/SickRage@26ddbf4b882c293c187fe3ec88dd6e826eeed7a7
Link to Log: https://gist.github.com/bdaa29c8c83afaa9ecdc
### ERROR
```
SEARCHQUEUE-BACKLOG-250498 :: [TorrentBytes] :: Unknown exception while searching TorrentBytes. Error: 'list index out of range' [26ddbf4]
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by jaypjay** [comment]
### INFO
Python Version: **2.7.11 (v2.7.11:6d1b6a68f775, Dec  5 2015, 20:40:30) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-2008ServerR2-6.1.7601-SP1**
Locale: cp1252
Branch: **master**
Commit: SickRage/SickRage@26ddbf4b882c293c187fe3ec88dd6e826eeed7a7
Link to Log: https://gist.github.com/30b085f251ac145894d2
### ERROR
```
SEARCHQUEUE-BACKLOG-253323 :: [TorrentBytes] :: Unknown exception while searching TorrentBytes. Error: 'list index out of range' [26ddbf4]
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by jaypjay** [comment]
### INFO
Python Version: **2.7.11 (v2.7.11:6d1b6a68f775, Dec  5 2015, 20:40:30) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-2008ServerR2-6.1.7601-SP1**
Locale: cp1252
Branch: **master**
Commit: SickRage/SickRage@26ddbf4b882c293c187fe3ec88dd6e826eeed7a7
Link to Log: https://gist.github.com/32aeff46d22d8e4b3838
### ERROR
```
SEARCHQUEUE-BACKLOG-281537 :: [TorrentBytes] :: Unknown exception while searching TorrentBytes. Error: 'list index out of range' [26ddbf4]
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by jaypjay** [comment]
### INFO
Python Version: **2.7.11 (v2.7.11:6d1b6a68f775, Dec  5 2015, 20:40:30) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-2008ServerR2-6.1.7601-SP1**
Locale: cp1252
Branch: **master**
Commit: SickRage/SickRage@26ddbf4b882c293c187fe3ec88dd6e826eeed7a7
Link to Log: https://gist.github.com/94e53b341fda94e73ed1
### ERROR
```
SEARCHQUEUE-BACKLOG-281472 :: [TorrentBytes] :: Unknown exception while searching TorrentBytes. Error: 'list index out of range' [26ddbf4]
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by CrazySwed** [comment]
### INFO
Python Version: **2.7.10 (default, May 23 2015, 09:44:00) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-7-6.1.7601-SP1**
Locale: cp1252
Branch: **master**
Commit: SickRage/SickRage@ace5e56d632654b03f00d533c2489440e792cba9
No Log available with ERRORS:
### ERROR
```
SEARCHQUEUE-BACKLOG-79485 :: [TorrentBytes] :: Unknown exception while searching TorrentBytes. Error: 'list index out of range' [ace5e56]
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by rbode1904** [comment]
### INFO
Python Version: **2.7.11 (default, Dec 17 2015, 15:58:38) [GCC 4.7.3 20130102 (prerelease)]**
Operating System: **Linux-3.2.40-x86_64-with-glibc2.2.5**
Locale: None
Branch: **master**
Commit: SickRage/SickRage@ace5e56d632654b03f00d533c2489440e792cba9
Link to Log: https://gist.github.com/6fc533737e6d429d1904
### ERROR
```
SEARCHQUEUE-BACKLOG-146711 :: [TorrentBytes] :: Unknown exception while searching TorrentBytes. Error: 'list index out of range' [ace5e56]
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by rbode1904** [comment]
### INFO
Python Version: **2.7.11 (default, Dec 17 2015, 15:58:38) [GCC 4.7.3 20130102 (prerelease)]**
Operating System: **Linux-3.2.40-x86_64-with-glibc2.2.5**
Locale: None
Branch: **master**
Commit: SickRage/SickRage@ace5e56d632654b03f00d533c2489440e792cba9
Link to Log: https://gist.github.com/9f9b6e6de6af9eded7aa
### ERROR
```
SEARCHQUEUE-BACKLOG-75760 :: [TorrentBytes] :: Unknown exception while searching TorrentBytes. Error: 'list index out of range' [ace5e56]
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by rbode1904** [comment]
### INFO
Python Version: **2.7.11 (default, Dec 17 2015, 15:58:38) [GCC 4.7.3 20130102 (prerelease)]**
Operating System: **Linux-3.2.40-x86_64-with-glibc2.2.5**
Locale: None
Branch: **master**
Commit: SickRage/SickRage@ace5e56d632654b03f00d533c2489440e792cba9
No Log available with ERRORS:
### ERROR
```
SEARCHQUEUE-BACKLOG-80379 :: [TorrentBytes] :: Unknown exception while searching TorrentBytes. Error: 'list index out of range' [ace5e56]
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by rbode1904** [comment]
### INFO
Python Version: **2.7.11 (default, Dec 17 2015, 15:58:38) [GCC 4.7.3 20130102 (prerelease)]**
Operating System: **Linux-3.2.40-x86_64-with-glibc2.2.5**
Locale: None
Branch: **master**
Commit: SickRage/SickRage@ace5e56d632654b03f00d533c2489440e792cba9
No Log available with ERRORS:
### ERROR
```
SEARCHQUEUE-BACKLOG-164541 :: [TorrentBytes] :: Unknown exception while searching TorrentBytes. Error: 'list index out of range' [ace5e56]
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by rbode1904** [comment]
### INFO
Python Version: **2.7.11 (default, Dec 17 2015, 15:58:38) [GCC 4.7.3 20130102 (prerelease)]**
Operating System: **Linux-3.2.40-x86_64-with-glibc2.2.5**
Locale: None
Branch: **master**
Commit: SickRage/SickRage@ace5e56d632654b03f00d533c2489440e792cba9
No Log available with ERRORS:
### ERROR
```
SEARCHQUEUE-BACKLOG-108611 :: [TorrentBytes] :: Unknown exception while searching TorrentBytes. Error: 'list index out of range' [ace5e56]
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by rbode1904** [comment]
### INFO
Python Version: **2.7.11 (default, Dec 17 2015, 15:58:38) [GCC 4.7.3 20130102 (prerelease)]**
Operating System: **Linux-3.2.40-x86_64-with-glibc2.2.5**
Locale: None
Branch: **master**
Commit: SickRage/SickRage@ace5e56d632654b03f00d533c2489440e792cba9
No Log available with ERRORS:
### ERROR
```
SEARCHQUEUE-BACKLOG-73762 :: [TorrentBytes] :: Unknown exception while searching TorrentBytes. Error: 'list index out of range' [ace5e56]
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators
