### ISSUE TITLE
[APP SUBMITTED]: Exception generated in thread POSTPROCESSER: 

### ISSUE THREAD

**Issue by didyouexpectthat** [SickRage/sickrage-issues#240]
### INFO
Python Version: **2.7.9 (default, Mar  1 2015, 12:57:24) [GCC 4.9.2]**
Operating System: **Linux-4.2.3-2-pve-x86_64-with-debian-8.2**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@2eaf3fb24a465765d22d8ad8f0780d06a2b7ff89
Link to Log: https://gist.github.com/ced4cf2c44a44a6e7dc0
### ERROR
```
POSTPROCESSER :: Exception generated in thread POSTPROCESSER: 
```

POSTPROCESS crashed on me while it was working on some file.

```
2015-12-16 05:06:36 DEBUG    POSTPROCESSER :: Parsed Agatha.Christies.Poirot.S02E10.The.Mysterious.Affair.at.Styles.avi into Agatha Christies Poirot - S02E10 [ABD: False] [ANIME: False] [whichReg: ['standard']]
2015-12-16 05:06:36 DEBUG    POSTPROCESSER :: Parsed /completed/sickrage/Agatha.Christies.Poirot.S02E10.The.Mysterious.Affair.at.Styles into Agatha Christies Poirot - S02E10 [ABD: False] [ANIME: False] [whichReg: ['standard']]
2015-12-16 05:06:36 INFO     POSTPROCESSER :: Processing /completed/sickrage/Agatha.Christies.Poirot.S02E10.The.Mysterious.Affair.at.Styles/Agatha.Christies.Poirot.S02E10.The.Mysterious.Affair.at.Styles.avi (None)
2015-12-16 05:06:36 ERROR    POSTPROCESSER :: Exception generated in thread POSTPROCESSER:
Traceback (most recent call last):
  File "/usr/share/sickrage/sickbeard/scheduler.py", line 105, in run
    self.action.run(self.force)
  File "/usr/share/sickrage/sickbeard/autoPostProcesser.py", line 55, in run
    processTV.processDir(sickbeard.TV_DOWNLOAD_DIR)
  File "/usr/share/sickrage/sickbeard/processTV.py", line 271, in processDir
    process_media(processPath, videoFiles, nzbName, process_method, force, is_priority, result)
  File "/usr/share/sickrage/sickbeard/processTV.py", line 554, in process_media
    result.result = processor.process()
  File "/usr/share/sickrage/sickbeard/postProcessor.py", line 922, in process
    (show, season, episodes, quality, version) = self._find_info()
  File "/usr/share/sickrage/sickbeard/postProcessor.py", line 652, in _find_info
    (cur_show, cur_season, cur_episodes, cur_quality, cur_version) = cur_attempt()
  File "/usr/share/sickrage/sickbeard/postProcessor.py", line 514, in _history_lookup
    self._log("Found result in history for %s - Season: %s - Quality: %s - Version: %s" % (show.name, season, common.Quality.qualityStrings[quality], version), logger.DEBUG)
  File "/usr/share/sickrage/sickbeard/numdict.py", line 45, in __getitem__
    raise KeyError(key)
KeyError: None
2015-12-16 05:06:36 DEBUG    POSTPROCESSER :: 'Traceback (most recent call last):\n  File "/usr/share/sickrage/sickbeard/scheduler.py", line 105, in run\n    self.action.run(self.force)\n  File "/usr/share/sickrage/sickbeard/autoPostProcesser.py", line 55, in run\n    processTV.processDir(sickbeard.TV_DOWNLOAD_DIR)\n  File "/usr/share/sickrage/sickbeard/processTV.py", line 271, in processDir\n    process_media(processPath, videoFiles, nzbName, process_method, force, is_priority, result)\n  File "/usr/share/sickrage/sickbeard/processTV.py", line 554, in process_media\n    result.result = processor.process()\n  File "/usr/share/sickrage/sickbeard/postProcessor.py", line 922, in process\n    (show, season, episodes, quality, version) = self._find_info()\n  File "/usr/share/sickrage/sickbeard/postProcessor.py", line 652, in _find_info\n    (cur_show, cur_season, cur_episodes, cur_quality, cur_version) = cur_attempt()\n  File "/usr/share/sickrage/sickbeard/postProcessor.py", line 514, in _history_lookup\n    self._log("Found result in history for %s - Season: %s - Quality: %s - Version: %s" % (show.name, season, common.Quality.qualityStrings[quality], version), logger.DEBUG)\n  File "/usr/share/sickrage/sickbeard/numdict.py", line 45, in __getitem__\n    raise KeyError(key)\nKeyError: None\n'

```

---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by SickRage2** [comment]
Thanks for the issue report! Before a real human comes by, please make sure your report has all the below criteria checked

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [x] Post debug logs, either inline (for smaller logs) or using gist)

Please make sure you also read [how to create an issue](https://github.com/SickRage/sickrage-issues/blob/master/README.md) and followed all of the steps. 

The title should describe your issue. Having "SR not working" or "I get this bug" for 100 issues, isn't really helpful. We will close issues if there isn't enough information.

Sometimes the devs may seem like grunts and respond with short answers. This isn't (always) because the dev hates you, but because he's on mobile or busy fixing bugs. If something isn't clear, please let us know, and this bot may get updated to automatically answer you.

Thanks!

**Comment by josephasmith1** [comment]
### INFO
Python Version: **2.7.6 (default, Jun 22 2015, 17:58:13) [GCC 4.8.2]**
Operating System: **Linux-4.3.0-040300-generic-x86_64-with-LinuxMint-17.3-rosa**
Locale: UTF-8
Branch: **develop**
Commit: SickRage/SickRage@dfa6e2765b19052a9a3c6d9704dd9e85e5527702
Link to Log: https://gist.github.com/2c85270b085233685e1f
### ERROR
```
POSTPROCESSER :: Exception generated in thread POSTPROCESSER: 
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by josephasmith1** [comment]
### INFO
Python Version: **2.7.6 (default, Jun 22 2015, 17:58:13) [GCC 4.8.2]**
Operating System: **Linux-4.3.0-040300-generic-x86_64-with-LinuxMint-17.3-rosa**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@2eaf3fb24a465765d22d8ad8f0780d06a2b7ff89
Link to Log: https://gist.github.com/3aa01f1fd7807b35b1cc
### ERROR
```
POSTPROCESSER :: Exception generated in thread POSTPROCESSER: 
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by josephasmith1** [comment]
### INFO
Python Version: **2.7.6 (default, Jun 22 2015, 17:58:13) [GCC 4.8.2]**
Operating System: **Linux-4.3.0-040300-generic-x86_64-with-LinuxMint-17.3-rosa**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@2eaf3fb24a465765d22d8ad8f0780d06a2b7ff89
Link to Log: https://gist.github.com/f08ae52527b3aea6270e
### ERROR
```
POSTPROCESSER :: Exception generated in thread POSTPROCESSER: 
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by technazz** [comment]
### INFO
Python Version: **2.7.9 (default, Dec 10 2014, 12:24:55) [MSC v.1500 32 bit (Intel)]**
Operating System: **Windows-7-6.1.7601-SP1**
Locale: cp1252
Branch: **master**
Commit: SickRage/SickRage@2eaf3fb24a465765d22d8ad8f0780d06a2b7ff89
No Log available with ERRORS: 
### ERROR
```
POSTPROCESSER :: Exception generated in thread POSTPROCESSER: 
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by duramato** [comment]
### INFO
Python Version: **2.7.6 (default, Jun 22 2015, 18:00:18) [GCC 4.8.2]**
Operating System: **Linux-3.19.0-39-generic-i686-with-Ubuntu-14.04-trusty**
Locale: UTF-8
Branch: **develop**
Commit: SickRage/SickRage@93d5df13da4983aa9573d0552c147468cb6b75dd
No Log available with ERRORS: 
### ERROR
```
POSTPROCESSER :: Exception generated in thread POSTPROCESSER:  [93d5df1]
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by duramato** [comment]
```

2015-12-18 12:58:23 DEBUG    POSTPROCESSER :: 'Traceback (most recent call last):\n  File "/home/home/SickRage/sickbeard/scheduler.py", line 105, in run\n    self.action.run(self.force)\n  File "/home/home/SickRage/sickbeard/autoPostProcesser.py", line 55, in run\n    processTV.processDir(sickbeard.TV_DOWNLOAD_DIR)\n  File "/home/home/SickRage/sickbeard/processTV.py", line 271, in processDir\n    process_media(processPath, videoFiles, nzbName, process_method, force, is_priority, result)\n  File "/home/home/SickRage/sickbeard/processTV.py", line 554, in process_media\n    result.result = processor.process()\n  File "/home/home/SickRage/sickbeard/postProcessor.py", line 922, in process\n    (show, season, episodes, quality, version) = self._find_info()\n  File "/home/home/SickRage/sickbeard/postProcessor.py", line 652, in _find_info\n    (cur_show, cur_season, cur_episodes, cur_quality, cur_version) = cur_attempt()\n  File "/home/home/SickRage/sickbeard/postProcessor.py", line 514, in _history_lookup\n    self._log("Found result in history for %s - Season: %s - Quality: %s - Version: %s" % (show.name, season, common.Quality.qualityStrings[quality], version), logger.DEBUG)\n  File "/home/home/SickRage/sickbeard/numdict.py", line 45, in __getitem__\n    raise KeyError(key)\nKeyError: None\n'
AAKeyError: None
AA    raise KeyError(key)
AA  File "/home/home/SickRage/sickbeard/numdict.py", line 45, in __getitem__
AA    self._log("Found result in history for %s - Season: %s - Quality: %s - Version: %s" % (show.name, season, common.Quality.qualityStrings[quality], version), logger.DEBUG)
AA  File "/home/home/SickRage/sickbeard/postProcessor.py", line 514, in _history_lookup
AA    (cur_show, cur_season, cur_episodes, cur_quality, cur_version) = cur_attempt()
AA  File "/home/home/SickRage/sickbeard/postProcessor.py", line 652, in _find_info
AA    (show, season, episodes, quality, version) = self._find_info()
AA  File "/home/home/SickRage/sickbeard/postProcessor.py", line 922, in process
AA    result.result = processor.process()
AA  File "/home/home/SickRage/sickbeard/processTV.py", line 554, in process_media
AA    process_media(processPath, videoFiles, nzbName, process_method, force, is_priority, result)
AA  File "/home/home/SickRage/sickbeard/processTV.py", line 271, in processDir
AA    processTV.processDir(sickbeard.TV_DOWNLOAD_DIR)
AA  File "/home/home/SickRage/sickbeard/autoPostProcesser.py", line 55, in run
AA    self.action.run(self.force)
AA  File "/home/home/SickRage/sickbeard/scheduler.py", line 105, in run
AATraceback (most recent call last):
2015-12-18 12:58:23 ERROR    POSTPROCESSER :: Exception generated in thread POSTPROCESSER:  [93d5df1]
2015-12-18 12:58:23 INFO     POSTPROCESSER :: Processing /media/extssd/download/sickrage/Der Tatortreiniger S01E02 Spuren/Der Tatortreiniger S01E02 Spuren.avi (None)
2015-12-18 12:58:23 DEBUG    POSTPROCESSER :: Parsed /media/extssd/download/sickrage/Der Tatortreiniger S01E02 Spuren into Der Tatortreiniger - S01E02 [ABD: False] [ANIME: False] [whichReg: ['standard']]
```

**Comment by josephasmith1** [comment]
### INFO
Python Version: **2.7.6 (default, Jun 22 2015, 17:58:13) [GCC 4.8.2]**
Operating System: **Linux-4.3.0-040300-generic-x86_64-with-LinuxMint-17.3-rosa**
Locale: UTF-8
Branch: **develop**
Commit: SickRage/SickRage@93d5df13da4983aa9573d0552c147468cb6b75dd
Link to Log: https://gist.github.com/162496d0f0de59925673
### ERROR
```
POSTPROCESSER :: Exception generated in thread POSTPROCESSER:  [93d5df1]
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by josephasmith1** [comment]
### INFO
Python Version: **2.7.6 (default, Jun 22 2015, 17:58:13) [GCC 4.8.2]**
Operating System: **Linux-4.3.0-040300-generic-x86_64-with-LinuxMint-17.3-rosa**
Locale: UTF-8
Branch: **develop**
Commit: SickRage/SickRage@93d5df13da4983aa9573d0552c147468cb6b75dd
Link to Log: https://gist.github.com/b7413585e9ee4f695aa3
### ERROR
```
POSTPROCESSER :: Exception generated in thread POSTPROCESSER:  [93d5df1]
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by miigotu** [comment]
Should be fixed in develop

**Comment by didyouexpectthat** [comment]
### INFO
Python Version: **2.7.9 (default, Mar  1 2015, 12:57:24) [GCC 4.9.2]**
Operating System: **Linux-4.2.3-2-pve-x86_64-with-debian-8.2**
Locale: UTF-8
Branch: **develop**
Commit: SickRage/SickRage@16646d679fbffdf948952722fba32867a596922d
Link to Log: https://gist.github.com/b997dfbba054f38353fa
### ERROR
```
POSTPROCESSER :: Exception generated in thread POSTPROCESSER: 
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by didyouexpectthat** [comment]
Still broken in develop.

**Comment by labrys** [comment]
@didyouexpectthat Which dev commit did you try on? Also please wrap your logs in \`\`\` and don't use \\n escape codes in your logs.  I've cleaned it up for you this time.

**Comment by labrys** [comment]
@didyouexpectthat Try the latest dev and let me know if its fixed.

**Comment by didyouexpectthat** [comment]
That was a direct copy/paste from sickrage logs; the \n came from that log. 

I am now on commit 16646d679fbffdf948952722fba32867a596922d now and I will see if reproducible.

**Comment by didyouexpectthat** [comment]
``2015-12-22 13:16:00 ERROR    POSTPROCESSER :: Exception generated in thread POSTPROCESSER:
Traceback (most recent call last):
  File "/usr/share/sickrage/sickbeard/scheduler.py", line 105, in run
    self.action.run(self.force)
  File "/usr/share/sickrage/sickbeard/autoPostProcesser.py", line 55, in run
    processTV.processDir(sickbeard.TV_DOWNLOAD_DIR)
  File "/usr/share/sickrage/sickbeard/processTV.py", line 271, in processDir
    process_media(processPath, videoFiles, nzbName, process_method, force, is_priority, result)
  File "/usr/share/sickrage/sickbeard/processTV.py", line 555, in process_media
    result.result = processor.process()
  File "/usr/share/sickrage/sickbeard/postProcessor.py", line 922, in process
    (show, season, episodes, quality, version) = self._find_info()
  File "/usr/share/sickrage/sickbeard/postProcessor.py", line 652, in _find_info
    (cur_show, cur_season, cur_episodes, cur_quality, cur_version) = cur_attempt()
  File "/usr/share/sickrage/sickbeard/postProcessor.py", line 514, in _history_lookup
    self._log("Found result in history for %s - Season: %s - Quality: %s - Version: %s" % (show.name, season, common.Quality.qualityStrings[quality], version), logger.DEBUG)
  File "/usr/share/sickrage/sickbeard/numdict.py", line 45, in __getitem__
    raise KeyError(key)
KeyError: None
``
On commit: https://github.com/SickRage/SickRage/commit/16646d679fbffdf948952722fba32867a596922d

**Comment by labrys** [comment]
@didyouexpectthat that commit is master

**Comment by didyouexpectthat** [comment]
I fixed the git pulling develop and it has not had an issue in 2 hours with postprocess. It is fixed, thanks.
