### ISSUE TITLE
[APP SUBMITTED]: [Errno 28] No space left on device

### ISSUE THREAD

**Issue by duramato** [SickRage/sickrage-issues#246]
### INFO
Python Version: **2.7.6 (default, Jun 22 2015, 18:00:18) [GCC 4.8.2]**
Operating System: **Linux-3.19.0-39-generic-i686-with-Ubuntu-14.04-trusty**
Locale: unknown
Branch: **develop**
Commit: SickRage/SickRage@dfa6e2765b19052a9a3c6d9704dd9e85e5527702
No Log available with ERRORS: 
### ERROR
```
FINDSUBTITLES :: Traceback (most recent call last):
  File "/home/home/SickRage/sickbeard/subtitles.py", line 210, in download_subtitles
    single=not sickbeard.SUBTITLES_MULTI)
  File "/home/home/SickRage/lib/subliminal/api.py", line 429, in save_subtitles
    f.write(subtitle.content)
IOError: [Errno 28] No space left on device

```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by SickRage2** [comment]
Thanks for the issue report! Before a real human comes by, please make sure your report has all the below criteria checked

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [ ] Post debug logs, either inline (for smaller logs) or using gist)

Please make sure you also read [how to create an issue](https://github.com/SickRage/sickrage-issues/blob/master/README.md) and followed all of the steps. 

The title should describe your issue. Having "SR not working" or "I get this bug" for 100 issues, isn't really helpful. We will close issues if there isn't enough information.

Sometimes the devs may seem like grunts and respond with short answers. This isn't (always) because the dev hates you, but because he's on mobile or busy fixing bugs. If something isn't clear, please let us know, and this bot may get updated to automatically answer you.

Thanks!

**Comment by duramato** [comment]
shouldnt this not be an error?

**Comment by Arcanemagus** [comment]
Why wouldn't running out of disk space be an error?

**Comment by duramato** [comment]
It should be a warning at most not an error

**Comment by miigotu** [comment]
we normally catch this in SR, this came from subliminal. Will PR a fix for it in a sec.
