### ISSUE TITLE
Title TBD

### ISSUE THREAD

**Issue by OmgImAlexis** [SickRage/sickrage-issues#254]
I've done nothing to my sickrage install at all for the last 2 months apart from update.

This is from trying to open a show.
````
2015-12-18 05:08:19 Thread-34 :: Failed doing webui callback: Traceback (most recent call last):
  File "/home/media/sickrage/sickbeard/webserve.py", line 271, in async_call
    result = function(**kwargs)
  File "/home/media/sickrage/sickbeard/webserve.py", line 1217, in displayShow
    t = PageTemplate(rh=self, filename="displayShow.mako")
  File "/home/media/sickrage/sickbeard/webserve.py", line 118, in __init__
    self.template = lookup.get_template(filename)
  File "/home/media/sickrage/lib/mako/lookup.py", line 256, in get_template
  File "/home/media/sickrage/lib/mako/lookup.py", line 321, in _load
  File "/home/media/sickrage/lib/mako/template.py", line 322, in __init__
  File "/home/media/sickrage/lib/mako/template.py", line 381, in _compile_from_file
AttributeError: 'module' object has no attribute '_magic_number'
````

This is from restarting/shutting down.
````
2015-12-18 05:06:28 EVENT-QUEUE :: Fatal error executing query: UNIQUE constraint failed: tv_shows.indexer_id
2015-12-18 05:06:28 EVENT-QUEUE :: Exception generated in thread EVENT-QUEUE: UNIQUE constraint failed: tv_shows.indexer_id
2015-12-18 05:06:22 Thread-48 :: Failed doing webui callback: Traceback (most recent call last):
  File "/home/media/sickrage/sickbeard/webserve.py", line 271, in async_call
    result = function(**kwargs)
  File "/home/media/sickrage/sickbeard/webserve.py", line 1130, in restart
    t = PageTemplate(rh=self, filename="restart.mako")
  File "/home/media/sickrage/sickbeard/webserve.py", line 118, in __init__
    self.template = lookup.get_template(filename)
  File "/home/media/sickrage/lib/mako/lookup.py", line 256, in get_template
  File "/home/media/sickrage/lib/mako/lookup.py", line 321, in _load
  File "/home/media/sickrage/lib/mako/template.py", line 322, in __init__
  File "/home/media/sickrage/lib/mako/template.py", line 372, in _compile_from_file
  File "/home/media/sickrage/lib/mako/util.py", line 367, in read_file
IOError: [Errno 5] Input/output error
````

This is from the history page.
````
2015-12-18 05:08:50 Thread-33 :: Failed doing webui callback: Traceback (most recent call last):
  File "/home/media/sickrage/sickbeard/webserve.py", line 271, in async_call
    result = function(**kwargs)
  File "/home/media/sickrage/sickbeard/webserve.py", line 3614, in index
    sickbeard.save_config()
  File "/home/media/sickrage/sickbeard/__init__.py", line 2121, in save_config
  File "/home/media/sickrage/lib/configobj.py", line 2066, in write
IOError: [Errno 30] Read-only file system: u'/home/media/sickrage/config.ini'
````

**Comment by SickRage2** [comment]
Thanks for the issue report! Before a real human comes by, please make sure your report has all the below criteria checked

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [ ] Post debug logs, either inline (for smaller logs) or using gist)

Please make sure you also read [how to create an issue](https://github.com/SickRage/sickrage-issues/blob/master/README.md) and followed all of the steps. 

The title should describe your issue. Having "SR not working" or "I get this bug" for 100 issues, isn't really helpful. We will close issues if there isn't enough information.

Sometimes the devs may seem like grunts and respond with short answers. This isn't (always) because the dev hates you, but because he's on mobile or busy fixing bugs. If something isn't clear, please let us know, and this bot may get updated to automatically answer you.

Thanks!

**Comment by OmgImAlexis** [comment]
@SickRage/collaborators @SickRage/moderators

**Comment by duramato** [comment]
```IOError: [Errno 30] Read-only file system: u'/home/media/sickrage/config.ini'```

**Comment by miigotu** [comment]
Your SR is running as another user or had ran/updated as root.
