### ISSUE TITLE
[APP SUBMITTED]: None

### ISSUE THREAD

**Issue by technazz** [SickRage/sickrage-issues#259]
### INFO
Python Version: **2.7.9 (default, Dec 10 2014, 12:24:55) [MSC v.1500 32 bit (Intel)]**
Operating System: **Windows-7-6.1.7601-SP1**
Locale: cp1252
Branch: **master**
Commit: SickRage/SickRage@2eaf3fb24a465765d22d8ad8f0780d06a2b7ff89
Link to Log: https://gist.github.com/feeb957a997c488e07b0
### ERROR
```
Thread-36 :: Failed doing webui callback: Traceback (most recent call last):
  File "C:\SickRage\SickRage\sickbeard\webserve.py", line 271, in async_call
    result = function(**kwargs)
  File "C:\SickRage\SickRage\sickbeard\webserve.py", line 2247, in processEpisode
    is_priority=argToBool(is_priority), delete_on=argToBool(delete_on), failed=argToBool(failed), proc_type=type
  File "C:\SickRage\SickRage\sickbeard\processTV.py", line 271, in processDir
    process_media(processPath, videoFiles, nzbName, process_method, force, is_priority, result)
  File "C:\SickRage\SickRage\sickbeard\processTV.py", line 554, in process_media
    result.result = processor.process()
  File "C:\SickRage\SickRage\sickbeard\postProcessor.py", line 922, in process
    (show, season, episodes, quality, version) = self._find_info()
  File "C:\SickRage\SickRage\sickbeard\postProcessor.py", line 652, in _find_info
    (cur_show, cur_season, cur_episodes, cur_quality, cur_version) = cur_attempt()
  File "C:\SickRage\SickRage\sickbeard\postProcessor.py", line 514, in _history_lookup
    self._log("Found result in history for %s - Season: %s - Quality: %s - Version: %s" % (show.name, season, common.Quality.qualityStrings[quality], version), logger.DEBUG)
  File "C:\SickRage\SickRage\sickbeard\numdict.py", line 45, in __getitem__
    raise KeyError(key)
KeyError: None

```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by SickRage2** [comment]
Thanks for the issue report! Before a real human comes by, please make sure your report has all the below criteria checked

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [x] Post debug logs, either inline (for smaller logs) or using gist)

Please make sure you also read [how to create an issue](https://github.com/SickRage/sickrage-issues/blob/master/README.md) and followed all of the steps. 

The title should describe your issue. Having "SR not working" or "I get this bug" for 100 issues, isn't really helpful. We will close issues if there isn't enough information.

Sometimes the devs may seem like grunts and respond with short answers. This isn't (always) because the dev hates you, but because he's on mobile or busy fixing bugs. If something isn't clear, please let us know, and this bot may get updated to automatically answer you.

Thanks!

**Comment by technazz** [comment]
### INFO
Python Version: **2.7.9 (default, Dec 10 2014, 12:24:55) [MSC v.1500 32 bit (Intel)]**
Operating System: **Windows-7-6.1.7601-SP1**
Locale: cp1252
Branch: **master**
Commit: SickRage/SickRage@2eaf3fb24a465765d22d8ad8f0780d06a2b7ff89
No Log available with ERRORS: 
### ERROR
```
Thread-29 :: Failed doing webui callback: Traceback (most recent call last):
  File "C:\SickRage\SickRage\sickbeard\webserve.py", line 271, in async_call
    result = function(**kwargs)
  File "C:\SickRage\SickRage\sickbeard\webserve.py", line 2247, in processEpisode
    is_priority=argToBool(is_priority), delete_on=argToBool(delete_on), failed=argToBool(failed), proc_type=type
  File "C:\SickRage\SickRage\sickbeard\processTV.py", line 271, in processDir
    process_media(processPath, videoFiles, nzbName, process_method, force, is_priority, result)
  File "C:\SickRage\SickRage\sickbeard\processTV.py", line 554, in process_media
    result.result = processor.process()
  File "C:\SickRage\SickRage\sickbeard\postProcessor.py", line 922, in process
    (show, season, episodes, quality, version) = self._find_info()
  File "C:\SickRage\SickRage\sickbeard\postProcessor.py", line 652, in _find_info
    (cur_show, cur_season, cur_episodes, cur_quality, cur_version) = cur_attempt()
  File "C:\SickRage\SickRage\sickbeard\postProcessor.py", line 514, in _history_lookup
    self._log("Found result in history for %s - Season: %s - Quality: %s - Version: %s" % (show.name, season, common.Quality.qualityStrings[quality], version), logger.DEBUG)
  File "C:\SickRage\SickRage\sickbeard\numdict.py", line 45, in __getitem__
    raise KeyError(key)
KeyError: None

```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by labrys** [comment]
#240

**Comment by didyouexpectthat** [comment]
### INFO
Python Version: **2.7.9 (default, Mar  1 2015, 12:57:24) [GCC 4.9.2]**
Operating System: **Linux-4.2.3-2-pve-x86_64-with-debian-8.2**
Locale: UTF-8
Branch: **develop**
Commit: SickRage/SickRage@16646d679fbffdf948952722fba32867a596922d
Link to Log: https://gist.github.com/db7b9940afcc69ead1eb
### ERROR
```
Thread-19 :: Failed doing webui callback: Traceback (most recent call last):
  File "/usr/share/sickrage/sickbeard/webserve.py", line 271, in async_call
    result = function(**kwargs)
  File "/usr/share/sickrage/sickbeard/webserve.py", line 2247, in processEpisode
    is_priority=argToBool(is_priority), delete_on=argToBool(delete_on), failed=argToBool(failed), proc_type=type
  File "/usr/share/sickrage/sickbeard/processTV.py", line 271, in processDir
    process_media(processPath, videoFiles, nzbName, process_method, force, is_priority, result)
  File "/usr/share/sickrage/sickbeard/processTV.py", line 555, in process_media
    result.result = processor.process()
  File "/usr/share/sickrage/sickbeard/postProcessor.py", line 922, in process
    (show, season, episodes, quality, version) = self._find_info()
  File "/usr/share/sickrage/sickbeard/postProcessor.py", line 652, in _find_info
    (cur_show, cur_season, cur_episodes, cur_quality, cur_version) = cur_attempt()
  File "/usr/share/sickrage/sickbeard/postProcessor.py", line 514, in _history_lookup
    self._log("Found result in history for %s - Season: %s - Quality: %s - Version: %s" % (show.name, season, common.Quality.qualityStrings[quality], version), logger.DEBUG)
  File "/usr/share/sickrage/sickbeard/numdict.py", line 45, in __getitem__
    raise KeyError(key)
KeyError: None

```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators
