### ISSUE TITLE
ConnectionError: ('Connection aborted.', BadStatusLine("''",))

### ISSUE THREAD

**Issue by fernandog** [SickRage/sickrage-issues#267]
Any clue about this error?

```
A2015-12-19 10:34:35 INFO     Listing subtitles with provider 'opensubtitles' and languages set([])
AAConnectionError: ('Connection aborted.', BadStatusLine("''",))
AA    raise ConnectionError(err, request=request)
AA  File "/home/osmc/SickRage/lib/requests/adapters.py", line 426, in send
AA    r = adapter.send(request, **kwargs)
AA  File "/home/osmc/SickRage/lib/requests/sessions.py", line 576, in send
AA    resp = self.send(prep, **send_kwargs)
AA  File "/home/osmc/SickRage/lib/requests/sessions.py", line 468, in request
AA    return self.request('GET', url, **kwargs)
AA  File "/home/osmc/SickRage/lib/requests/sessions.py", line 480, in get
AA    r = self.session.get('%s/legenda/sugestao/%s' % (self.server_url, keyword), timeout=TIMEOUT)
AA  File "/home/osmc/SickRage/lib/subliminal/providers/legendastv.py", line 181, in search_titles
AA    return fn(*arg, **kw)
AA  File "/home/osmc/SickRage/lib/dogpile/cache/region.py", line 1036, in creator
AA    created_value = creator()
AA  File "/home/osmc/SickRage/lib/dogpile/cache/region.py", line 619, in gen_value
AA    created = self.creator()
AA  File "/home/osmc/SickRage/lib/dogpile/core/dogpile.py", line 149, in _enter_create
AA    generated = self._enter_create(createdtime)
AA  File "/home/osmc/SickRage/lib/dogpile/core/dogpile.py", line 98, in _enter
AA    return self._enter()
AA  File "/home/osmc/SickRage/lib/dogpile/core/dogpile.py", line 158, in __enter__
AA    async_creator) as value:
AA  File "/home/osmc/SickRage/lib/dogpile/cache/region.py", line 651, in get_or_create
AA    should_cache_fn)
AA  File "/home/osmc/SickRage/lib/dogpile/cache/region.py", line 1040, in decorate
AA    titles = self.search_titles(params)
AA  File "/home/osmc/SickRage/lib/subliminal/providers/legendastv.py", line 297, in query
AA    return [s for l in languages for s in self.query(l, video, params) if params]
AA  File "/home/osmc/SickRage/lib/subliminal/providers/legendastv.py", line 402, in list_subtitles
AA    provider_subtitles = self[name].list_subtitles(video, provider_languages)
AA  File "/home/osmc/SickRage/lib/subliminal/api.py", line 141, in list_subtitles
AATraceback (most recent call last):
AA2015-12-19 10:34:35 ERROR    Unexpected error in provider 'legendastv', discarding it
AAConnectionError: ('Connection aborted.', BadStatusLine("''",))
AA    raise ConnectionError(err, request=request)
AA  File "/home/osmc/SickRage/lib/requests/adapters.py", line 426, in send
AA    r = adapter.send(request, **kwargs)
AA  File "/home/osmc/SickRage/lib/requests/sessions.py", line 576, in send
AA    resp = self.send(prep, **send_kwargs)
AA  File "/home/osmc/SickRage/lib/requests/sessions.py", line 468, in request
AA    return self.request('GET', url, **kwargs)
AA  File "/home/osmc/SickRage/lib/requests/sessions.py", line 480, in get
AA    r = self.session.get('%s/legenda/sugestao/%s' % (self.server_url, keyword), timeout=TIMEOUT)
AA  File "/home/osmc/SickRage/lib/subliminal/providers/legendastv.py", line 181, in search_titles
AA    return fn(*arg, **kw)
AA  File "/home/osmc/SickRage/lib/dogpile/cache/region.py", line 1036, in creator
AA    created_value = creator()
AA  File "/home/osmc/SickRage/lib/dogpile/cache/region.py", line 619, in gen_value
AA    created = self.creator()
AA  File "/home/osmc/SickRage/lib/dogpile/core/dogpile.py", line 149, in _enter_create
AA    generated = self._enter_create(createdtime)
AA  File "/home/osmc/SickRage/lib/dogpile/core/dogpile.py", line 98, in _enter
AA    return self._enter()
AA  File "/home/osmc/SickRage/lib/dogpile/core/dogpile.py", line 158, in __enter__
AA    async_creator) as value:
AA  File "/home/osmc/SickRage/lib/dogpile/cache/region.py", line 651, in get_or_create
AA    should_cache_fn)
AA  File "/home/osmc/SickRage/lib/dogpile/cache/region.py", line 1040, in decorate
AA    titles = self.search_titles(params)
AA  File "/home/osmc/SickRage/lib/subliminal/providers/legendastv.py", line 297, in query
AA    return [s for l in languages for s in self.query(l, video, params) if params]
AA  File "/home/osmc/SickRage/lib/subliminal/providers/legendastv.py", line 402, in list_subtitles
AA    provider_subtitles = self[name].list_subtitles(video, provider_languages)
AA  File "/home/osmc/SickRage/lib/subliminal/api.py", line 141, in list_subtitles
AATraceback (most recent call last):
AA2015-12-19 10:34:35 ERROR    Unexpected error in provider 'legendastv', discarding it
```

**Comment by SickRage2** [comment]
Thanks for the issue report! Before a real human comes by, please make sure your report has all the below criteria checked

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [x] Post debug logs, either inline (for smaller logs) or using gist)
- [x] Please wrap inline logs inside \`\`\` and \`\`\` for readability

Please make sure you also read [how to create an issue](https://github.com/SickRage/sickrage-issues/blob/master/README.md) and followed all of the steps. 

The title should describe your issue. Having "SR not working" or "I get this bug" for 100 issues, isn't really helpful. We will close issues if there isn't enough information.

Sometimes the devs may seem like grunts and respond with short answers. This isn't (always) because the dev hates you, but because he's on mobile or busy fixing bugs. If something isn't clear, please let us know, and this bot may get updated to automatically answer you.

Thanks!
