### ISSUE TITLE
Issue with log page

### ISSUE THREAD

**Issue by brse** [SickRage/sickrage-issues#268]
```
2015-12-19 15:16:19 Thread-31 :: Failed doing webui callback: Traceback (most recent call last):
  File "/mnt/HD/HD_a2/Nas_Prog/SickRage/sickbeard/webserve.py", line 271, in async_call
    result = function(**kwargs)
  File "/mnt/HD/HD_a2/Nas_Prog/SickRage/sickbeard/webserve.py", line 5147, in viewlog
    t = PageTemplate(rh=self, filename="viewlogs.mako")
  File "/mnt/HD/HD_a2/Nas_Prog/SickRage/sickbeard/webserve.py", line 118, in __init__
    self.template = lookup.get_template(filename)
  File "/mnt/HD/HD_a2/Nas_Prog/SickRage/lib/mako/lookup.py", line 256, in get_template
    return self._load(srcfile, uri)
  File "/mnt/HD/HD_a2/Nas_Prog/SickRage/lib/mako/lookup.py", line 321, in _load
    **self.template_args)
  File "/mnt/HD/HD_a2/Nas_Prog/SickRage/lib/mako/template.py", line 322, in __init__
    module = self._compile_from_file(path, filename)
  File "/mnt/HD/HD_a2/Nas_Prog/SickRage/lib/mako/template.py", line 379, in _compile_from_file
    module = compat.load_module(self.module_id, path)
  File "/mnt/HD/HD_a2/Nas_Prog/SickRage/lib/mako/compat.py", line 89, in load_module
    return imp.load_source(module_id, path, fp)
  File "/mnt/HD/HD_a2/Nas_Prog/SickRage/cache/mako/viewlogs.mako.py", line 19, in 
    from sickbeard.logger import SRLogger
ImportError: cannot import name SRLogger
```

**Comment by SickRage2** [comment]
Thanks for the issue report! Before a real human comes by, please make sure your report has all the below criteria checked

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [ ] Post debug logs, either inline (for smaller logs) or using gist)

Please make sure you also read [how to create an issue](https://github.com/SickRage/sickrage-issues/blob/master/README.md) and followed all of the steps. 

The title should describe your issue. Having "SR not working" or "I get this bug" for 100 issues, isn't really helpful. We will close issues if there isn't enough information.

Sometimes the devs may seem like grunts and respond with short answers. This isn't (always) because the dev hates you, but because he's on mobile or busy fixing bugs. If something isn't clear, please let us know, and this bot may get updated to automatically answer you.

Thanks!

**Comment by miigotu** [comment]
Did you just switch from SiCKRAGETV repo to here?

**Comment by labrys** [comment]
@brse Sorry to hear you had problems after the switch.  Have you tried shutting down SR, deleting the mako and sessions folders from the cache directory and restarting?  The location of the cache directory is listed on the Help & Info page.  By default its in the SR directory, but that may differ depending on type of install (Windows installer, FreeNAS, etc).  Also please wrap logs in \`\`\` for future posts as it makes them much more clear.  In addition please provide all information requested for by the bot.

**Comment by brse** [comment]
This ticket can be closed now. 

The problem occurred due to me copying my entire old cache folder to the new location and copying the old config.ini to the new location.

I redownloaded a clean version and only copied the relevant files and folders to the new location (like sickbeard.db and the images folder in the cache folder),
