### ISSUE TITLE
[APP SUBMITTED]: timestamp out of range for platform time_t

### ISSUE THREAD

**Issue by duramato** [SickRage/sickrage-issues#269]
### INFO
Python Version: **2.7.6 (default, Jun 22 2015, 18:00:18) [GCC 4.8.2]**
Operating System: **Linux-3.19.0-39-generic-i686-with-Ubuntu-14.04-trusty**
Locale: UTF-8
Branch: **develop**
Commit: SickRage/SickRage@b372067e9e6d6750da42fe3935744ea869dee7b4
Link to Log: https://gist.github.com/4fe826c96bd94961a973
### ERROR
```
POSTPROCESSER :: Exception generated in thread POSTPROCESSER: timestamp out of range for platform time_t [b372067]
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by SickRage2** [comment]
Thanks for the issue report! Before a real human comes by, please make sure your report has all the below criteria checked

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [x] Post debug logs, either inline (for smaller logs) or using gist)

Please make sure you also read [how to create an issue](https://github.com/SickRage/sickrage-issues/blob/master/README.md) and followed all of the steps. 

The title should describe your issue. Having "SR not working" or "I get this bug" for 100 issues, isn't really helpful. We will close issues if there isn't enough information.

Sometimes the devs may seem like grunts and respond with short answers. This isn't (always) because the dev hates you, but because he's on mobile or busy fixing bugs. If something isn't clear, please let us know, and this bot may get updated to automatically answer you.

Thanks!

**Comment by duramato** [comment]
```
2015-12-19 14:23:43 DEBUG    POSTPROCESSER :: 'Traceback (most recent call last):\n  File "/home/home/SickRage/sickbeard/scheduler.py", line 105, in run\n    self.action.run(self.force)\n  File "/home/home/SickRage/sickbeard/autoPostProcesser.py", line 55, in run\n    processTV.processDir(sickbeard.TV_DOWNLOAD_DIR)\n  File "/home/home/SickRage/sickbeard/processTV.py", line 271, in processDir\n    process_media(processPath, videoFiles, nzbName, process_method, force, is_priority, result)\n  File "/home/home/SickRage/sickbeard/processTV.py", line 555, in process_media\n    result.result = processor.process()\n  File "/home/home/SickRage/sickbeard/postProcessor.py", line 1154, in process\n    cur_ep.airdateModifyStamp()\n  File "/home/home/SickRage/sickbeard/tv.py", line 2531, in airdateModifyStamp\n    airdatetime = airdatetime.astimezone(network_timezones.sb_timezone)\n  File "/home/home/SickRage/lib/dateutil/tz.py", line 115, in utcoffset\n    if self._isdst(dt):\n  File "/home/home/SickRage/lib/dateutil/tz.py", line 159, in _isdst\n    return time.localtime(timestamp+time.timezone).tm_isdst\nValueError: timestamp out of range for platform time_t\n'
AAValueError: timestamp out of range for platform time_t
AA    return time.localtime(timestamp+time.timezone).tm_isdst
AA  File "/home/home/SickRage/lib/dateutil/tz.py", line 159, in _isdst
AA    if self._isdst(dt):
AA  File "/home/home/SickRage/lib/dateutil/tz.py", line 115, in utcoffset
AA    airdatetime = airdatetime.astimezone(network_timezones.sb_timezone)
AA  File "/home/home/SickRage/sickbeard/tv.py", line 2531, in airdateModifyStamp
AA    cur_ep.airdateModifyStamp()
AA  File "/home/home/SickRage/sickbeard/postProcessor.py", line 1154, in process
AA    result.result = processor.process()
AA  File "/home/home/SickRage/sickbeard/processTV.py", line 555, in process_media
AA    process_media(processPath, videoFiles, nzbName, process_method, force, is_priority, result)
AA  File "/home/home/SickRage/sickbeard/processTV.py", line 271, in processDir
AA    processTV.processDir(sickbeard.TV_DOWNLOAD_DIR)
AA  File "/home/home/SickRage/sickbeard/autoPostProcesser.py", line 55, in run
AA    self.action.run(self.force)
AA  File "/home/home/SickRage/sickbeard/scheduler.py", line 105, in run
AATraceback (most recent call last):
2015-12-19 14:23:43 ERROR    POSTPROCESSER :: Exception generated in thread POSTPROCESSER: timestamp out of range for platform time_t [b372067]
2015-12-19 14:23:43 DEBUG    POSTPROCESSER :: Transaction with 1 queries executed
```

**Comment by labrys** [comment]
@duramato It fails because the show's named wrong.  No episode Season 3 doesn't have an Episode 307

**Comment by fernandog** [comment]
related to season regex ?
@medariox

**Comment by miigotu** [comment]
@medariox this was the issue I was fixing I think when I made that commit. We really need to overhaul the whole regex system @labrys, try and move to guessit. New branch yay.

**Comment by neoatomic** [comment]
Can be closed.?

**Comment by duramato** [comment]
### INFO
Python Version: **2.7.6 (default, Jun 22 2015, 18:00:18) [GCC 4.8.2]**
Operating System: **Linux-3.19.0-49-generic-i686-with-Ubuntu-14.04-trusty**
Locale: UTF-8
Branch: **develop**
Commit: SickRage/SickRage@d419d63d7c9ddcf64217b59e2dedcfdc6b19ac89
No Log available with ERRORS:
### ERROR
```
Thread-33 :: Failed doing webui callback: Traceback (most recent call last):
  File "/home/home/SickRage/sickbeard/webserve.py", line 283, in async_call
    result = function(**kwargs)
  File "/home/home/SickRage/sickbeard/webserve.py", line 2279, in processEpisode
    is_priority=argToBool(is_priority), delete_on=argToBool(delete_on), failed=argToBool(failed), proc_type=type
  File "/home/home/SickRage/sickbeard/processTV.py", line 278, in processDir
    process_media(processPath, videoFiles, nzbName, process_method, force, is_priority, result)
  File "/home/home/SickRage/sickbeard/processTV.py", line 556, in process_media
    result.result = processor.process()
  File "/home/home/SickRage/sickbeard/postProcessor.py", line 1175, in process
    cur_ep.airdateModifyStamp()
  File "/home/home/SickRage/sickbeard/tv.py", line 2541, in airdateModifyStamp
    airdatetime = airdatetime.astimezone(network_timezones.sb_timezone)
  File "/home/home/SickRage/lib/dateutil/tz.py", line 115, in utcoffset
    if self._isdst(dt):
  File "/home/home/SickRage/lib/dateutil/tz.py", line 159, in _isdst
    return time.localtime(timestamp+time.timezone).tm_isdst
ValueError: timestamp out of range for platform time_t
 [d419d63]
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by duramato** [comment]
### INFO
Python Version: **2.7.6 (default, Jun 22 2015, 18:00:18) [GCC 4.8.2]**
Operating System: **Linux-3.19.0-49-generic-i686-with-Ubuntu-14.04-trusty**
Locale: UTF-8
Branch: **develop**
Commit: SickRage/SickRage@d419d63d7c9ddcf64217b59e2dedcfdc6b19ac89
No Log available with ERRORS:
### ERROR
```
Thread-13 :: Failed doing webui callback: Traceback (most recent call last):
  File "/home/home/SickRage/sickbeard/webserve.py", line 283, in async_call
    result = function(**kwargs)
  File "/home/home/SickRage/sickbeard/webserve.py", line 2279, in processEpisode
    is_priority=argToBool(is_priority), delete_on=argToBool(delete_on), failed=argToBool(failed), proc_type=type
  File "/home/home/SickRage/sickbeard/processTV.py", line 278, in processDir
    process_media(processPath, videoFiles, nzbName, process_method, force, is_priority, result)
  File "/home/home/SickRage/sickbeard/processTV.py", line 556, in process_media
    result.result = processor.process()
  File "/home/home/SickRage/sickbeard/postProcessor.py", line 1175, in process
    cur_ep.airdateModifyStamp()
  File "/home/home/SickRage/sickbeard/tv.py", line 2541, in airdateModifyStamp
    airdatetime = airdatetime.astimezone(network_timezones.sb_timezone)
  File "/home/home/SickRage/lib/dateutil/tz.py", line 115, in utcoffset
    if self._isdst(dt):
  File "/home/home/SickRage/lib/dateutil/tz.py", line 159, in _isdst
    return time.localtime(timestamp+time.timezone).tm_isdst
ValueError: timestamp out of range for platform time_t
 [d419d63]
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by duramato** [comment]
```
AA
AAValueError: timestamp out of range for platform time_t
AA    return time.localtime(timestamp+time.timezone).tm_isdst
AA  File "/home/home/SickRage/lib/dateutil/tz.py", line 159, in _isdst
AA    if self._isdst(dt):
AA  File "/home/home/SickRage/lib/dateutil/tz.py", line 115, in utcoffset
AA    airdatetime = airdatetime.astimezone(network_timezones.sb_timezone)
AA  File "/home/home/SickRage/sickbeard/tv.py", line 2541, in airdateModifyStamp
AA    cur_ep.airdateModifyStamp()
AA  File "/home/home/SickRage/sickbeard/postProcessor.py", line 1175, in process
AA    result.result = processor.process()
AA  File "/home/home/SickRage/sickbeard/processTV.py", line 556, in process_media
AA    process_media(processPath, videoFiles, nzbName, process_method, force, is_priority, result)
AA  File "/home/home/SickRage/sickbeard/processTV.py", line 278, in processDir
AA    is_priority=argToBool(is_priority), delete_on=argToBool(delete_on), failed=argToBool(failed), proc_type=type
AA  File "/home/home/SickRage/sickbeard/webserve.py", line 2279, in processEpisode
AA    result = function(**kwargs)
AA  File "/home/home/SickRage/sickbeard/webserve.py", line 283, in async_call
AA    result = self.fn(*self.args, **self.kwargs)
AA  File "/home/home/SickRage/lib/concurrent/futures/thread.py", line 61, in run
AA    exec('raise exc_type, exc_value, traceback', {}, locals_)
AA  File "/home/home/SickRage/lib/concurrent/futures/_compat.py", line 107, in reraise
AA    reraise(self._exception, self._traceback)
AA  File "/home/home/SickRage/lib/concurrent/futures/_base.py", line 359, in __get_result
AA    return self.__get_result()
AA  File "/home/home/SickRage/lib/concurrent/futures/_base.py", line 400, in result
AA    value = future.result()
AA  File "/home/home/SickRage/lib/tornado/gen.py", line 870, in run
AA    results = yield self.async_call(method)
AA  File "/home/home/SickRage/sickbeard/webserve.py", line 268, in get
2016-02-12 17:10:01 DEBUG    TORNADO :: Failed doing webui request "processEpisode": Traceback (most recent call last):
AAValueError: timestamp out of range for platform time_t
AA    return time.localtime(timestamp+time.timezone).tm_isdst
AA  File "/home/home/SickRage/lib/dateutil/tz.py", line 159, in _isdst
AA    if self._isdst(dt):
AA  File "/home/home/SickRage/lib/dateutil/tz.py", line 115, in utcoffset
AA    airdatetime = airdatetime.astimezone(network_timezones.sb_timezone)
AA  File "/home/home/SickRage/sickbeard/tv.py", line 2541, in airdateModifyStamp
AA    cur_ep.airdateModifyStamp()
AA  File "/home/home/SickRage/sickbeard/postProcessor.py", line 1175, in process
AA    result.result = processor.process()
AA  File "/home/home/SickRage/sickbeard/processTV.py", line 556, in process_media
AA    process_media(processPath, videoFiles, nzbName, process_method, force, is_priority, result)
AA  File "/home/home/SickRage/sickbeard/processTV.py", line 278, in processDir
AA    is_priority=argToBool(is_priority), delete_on=argToBool(delete_on), failed=argToBool(failed), proc_type=type
AA  File "/home/home/SickRage/sickbeard/webserve.py", line 2279, in processEpisode
AA    result = function(**kwargs)
AA  File "/home/home/SickRage/sickbeard/webserve.py", line 283, in async_call
AATraceback (most recent call last):
AA [d419d63]
AAValueError: timestamp out of range for platform time_t
AA    return time.localtime(timestamp+time.timezone).tm_isdst
AA  File "/home/home/SickRage/lib/dateutil/tz.py", line 159, in _isdst
AA    if self._isdst(dt):
AA  File "/home/home/SickRage/lib/dateutil/tz.py", line 115, in utcoffset
AA    airdatetime = airdatetime.astimezone(network_timezones.sb_timezone)
AA  File "/home/home/SickRage/sickbeard/tv.py", line 2541, in airdateModifyStamp
AA    cur_ep.airdateModifyStamp()
AA  File "/home/home/SickRage/sickbeard/postProcessor.py", line 1175, in process
AA    result.result = processor.process()
AA  File "/home/home/SickRage/sickbeard/processTV.py", line 556, in process_media
AA    process_media(processPath, videoFiles, nzbName, process_method, force, is_priority, result)
AA  File "/home/home/SickRage/sickbeard/processTV.py", line 278, in processDir
AA    is_priority=argToBool(is_priority), delete_on=argToBool(delete_on), failed=argToBool(failed), proc_type=type
AA  File "/home/home/SickRage/sickbeard/webserve.py", line 2279, in processEpisode
AA    result = function(**kwargs)
AA  File "/home/home/SickRage/sickbeard/webserve.py", line 283, in async_call
2016-02-12 17:10:01 ERROR    Thread-33 :: Failed doing webui callback: Traceback (most recent call last):
 ```
