### ISSUE TITLE
Issues switching from sickragetv

### ISSUE THREAD

**Issue by brse** [SickRage/sickrage-issues#270]
I switched from sickragetv which was running fine. Now I have 3 issues I cannot resolve. 
1. Logging errors, error message
```
2015-12-19 20:29:57 Thread-28 :: Failed doing webui callback: Traceback (most recent call last):
  File "/mnt/HD/HD_a2/Nas_Prog/SickRage/sickbeard/webserve.py", line 271, in async_call
    result = function(kwargs)
  File "/mnt/HD/HD_a2/Nas_Prog/SickRage/sickbeard/webserve.py", line 5147, in viewlog
    t = PageTemplate(rh=self, filename="viewlogs.mako")
  File "/mnt/HD/HD_a2/Nas_Prog/SickRage/sickbeard/webserve.py", line 118, in \_\_init\_\_
    self.template = lookup.get_template(filename)
  File "/mnt/HD/HD_a2/Nas_Prog/SickRage/lib/mako/lookup.py", line 256, in get\_template
    return self.\_load(srcfile, uri)
  File "/mnt/HD/HD_a2/Nas_Prog/SickRage/lib/mako/lookup.py", line 321, in \_load
    self.template\_args)
  File "/mnt/HD/HD_a2/Nas_Prog/SickRage/lib/mako/template.py", line 322, in \_\_init\_\_
    module = self.\_compile\_from\_file(path, filename)
  File "/mnt/HD/HD_a2/Nas_Prog/SickRage/lib/mako/template.py", line 379, in \_compile\_from\_file
    module = compat.load_module(self.module_id, path)
  File "/mnt/HD/HD_a2/Nas_Prog/SickRage/lib/mako/compat.py", line 89, in load_module
    return imp.load_source(module_id, path, fp)
  File "/mnt/HD/HD_a2/Nas\_Prog/SickRage/cache/mako/viewlogs.mako.py", line 19, in 
    from sickbeard.logger import SRLogger
ImportError: cannot import name SRLogger
```

2. Cannot update due to some vague arithmetic calculations error message

3. General Settings page error:
```
AttributeError: 'module' object has no attribute 'FILTER_ROW'
<input type="number" step="1" min="7" name="coming_eps_missed_range" id="coming_eps_missed_range" value="${sickbeard.COMING_EPS_MISSED_RANGE}" class="form-control input-sm input75" /> <p>Set the range in days of the missed episodes in the Schedule page</p> </span> </label> </div> <div class="field-pair"> <label for="fuzzy_dating"> <span class="component-title">Display fuzzy dates</span> <span class="component-desc"> 
/mnt/HD/HD_a2/Nas_Prog/SickRage/gui/slick/views/config_general.mako, line 281:
</label>
/mnt/HD/HD_a2/Nas_Prog/SickRage/gui/slick/views/layouts/main.mako, line 252:
<% inner_first = False %>
/mnt/HD/HD_a2/Nas_Prog/SickRage/lib/mako/runtime.py, line 883:
callable_(context, args, kwargs)
```

I am guessing it has to do with some config.ini settings. Any ideas I can try?

**Comment by SickRage2** [comment]
Thanks for the issue report! Before a real human comes by, please make sure your report has all the below criteria checked

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [ ] Post debug logs, either inline (for smaller logs) or using gist)

Please make sure you also read [how to create an issue](https://github.com/SickRage/sickrage-issues/blob/master/README.md) and followed all of the steps. 

The title should describe your issue. Having "SR not working" or "I get this bug" for 100 issues, isn't really helpful. We will close issues if there isn't enough information.

Sometimes the devs may seem like grunts and respond with short answers. This isn't (always) because the dev hates you, but because he's on mobile or busy fixing bugs. If something isn't clear, please let us know, and this bot may get updated to automatically answer you.

Thanks!

**Comment by labrys** [comment]
@brse have you tried shutting down SR, deleting the mako and sessions folders from the cache directory and restarting?  The location of the cache directory is listed on the Help & Info page.  By default its in the SR directory, but that may differ depending on type of install (Windows installer, FreeNAS, etc).  Also please wrap logs in \`\`\` for future posts as it makes them much more clear.  In addition please provide all information requested for by the bot.

**Comment by labrys** [comment]
Also closing this as a duplicate. #268
