### ISSUE TITLE
[APP SUBMITTED]: index() got an unexpected keyword argument 'cmd'

### ISSUE THREAD

**Issue by J4ce** [SickRage/sickrage-issues#278]
### INFO
Python Version: **2.7.10 (default, Jun  3 2015, 20:43:13) [GCC 4.7.3 20130102 (prerelease)]**
Operating System: **Linux-3.10.35-x86_64-with-glibc2.2.5**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@16646d679fbffdf948952722fba32867a596922d
Link to Log: https://gist.github.com/73dfbc3db7ad8b5d6fec
### ERROR
```
Thread-39 :: Failed doing webui callback: Traceback (most recent call last):
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/webserve.py", line 271, in async_call
    result = function(**kwargs)
TypeError: index() got an unexpected keyword argument 'cmd'

```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by SickRage2** [comment]
Thanks for the issue report! Before a real human comes by, please make sure your report has all the below criteria checked

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [x] Post debug logs, either inline (for smaller logs) or using gist)

Please make sure you also read [how to create an issue](https://github.com/SickRage/sickrage-issues/blob/master/README.md) and followed all of the steps. 

The title should describe your issue. Having "SR not working" or "I get this bug" for 100 issues, isn't really helpful. We will close issues if there isn't enough information.

Sometimes the devs may seem like grunts and respond with short answers. This isn't (always) because the dev hates you, but because he's on mobile or busy fixing bugs. If something isn't clear, please let us know, and this bot may get updated to automatically answer you.

Thanks!

**Comment by fernandog** [comment]
Are you using third party apps ? Did you set the API correctlty?

**Comment by fernandog** [comment]
@MGaetan89 do you know why this happens?

I found this:
https://github.com/MGaetan89/ShowsRage/issues/17

**Comment by fernandog** [comment]
@MGaetan89 please?!

**Comment by MGaetan89** [comment]
@fernandog I have no idea why this is happening. I didn't do anything about the issue you linked.

**Comment by andevellicus** [comment]
### INFO
Python Version: **2.7.9 (default, Mar  1 2015, 12:57:24) [GCC 4.9.2]**
Operating System: **Linux-3.16.0-4-amd64-x86_64-with-debian-8.3**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@3f0efd1338faf8796fd355bada4f546ec1cb5ed6
No Log available with ERRORS:
### ERROR
```
Thread-15 :: Failed doing webui callback: Traceback (most recent call last):
  File "/opt/sickrage/sickbeard/webserve.py", line 282, in async_call
    result = function(**kwargs)
TypeError: index() got an unexpected keyword argument 'cmd'
 [3f0efd1]
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by andevellicus** [comment]
### INFO
Python Version: **2.7.9 (default, Mar  1 2015, 12:57:24) [GCC 4.9.2]**
Operating System: **Linux-3.16.0-4-amd64-x86_64-with-debian-8.3**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@3f0efd1338faf8796fd355bada4f546ec1cb5ed6
No Log available with ERRORS:
### ERROR
```
Thread-44 :: Failed doing webui callback: Traceback (most recent call last):
  File "/opt/sickrage/sickbeard/webserve.py", line 282, in async_call
    result = function(**kwargs)
TypeError: index() got an unexpected keyword argument 'cmd'
 [3f0efd1]
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by OmgImAlexis** [comment]
@andevellicus any idea what you did when this error popped up?

**Comment by andevellicus** [comment]
I think I was just trying to sort by title name on the main page.

That error popped up and I closed and re opened the window....

**Comment by OmgImAlexis** [comment]
@fernandog did you want to look into this again?
