### ISSUE TITLE
blank Newznab search categories

### ISSUE THREAD

**Issue by benpeart** [SickRage/sickrage-issues#284]
Clean install today, new DB.  Added my custom Newsnab provider information and it fails trying to get the search categories.  Error is in the log file copy/pasted below.

![nzbis](https://cloud.githubusercontent.com/assets/15252029/11919433/d94c71e6-a720-11e5-88e6-17606d672fe9.jpg)

```
2015-12-20 13:01:41 Thread-36 :: Failed doing webui callback: Traceback (most recent call last):
  File "/volume1/@appstore/sickrage/var/SickRage/sickbeard/webserve.py", line 271, in async_call
    result = function(**kwargs)
  File "/volume1/@appstore/sickrage/var/SickRage/sickbeard/webserve.py", line 4319, in getNewznabCategories
    success, tv_categories, error = tempProvider.get_newznab_categories()
  File "/volume1/@appstore/sickrage/var/SickRage/sickbeard/providers/newznab.py", line 128, in get_newznab_categories
    for category in data.caps.categories.findAll('category'):
AttributeError: 'NoneType' object has no attribute 'categories'
```

**Comment by SickRage2** [comment]
Thanks for the issue report! Before a real human comes by, please make sure your report has all the below criteria checked

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [ ] Post debug logs, either inline (for smaller logs) or using gist)

Please make sure you also read [how to create an issue](https://github.com/SickRage/sickrage-issues/blob/master/README.md) and followed all of the steps. 

The title should describe your issue. Having "SR not working" or "I get this bug" for 100 issues, isn't really helpful. We will close issues if there isn't enough information.

Sometimes the devs may seem like grunts and respond with short answers. This isn't (always) because the dev hates you, but because he's on mobile or busy fixing bugs. If something isn't clear, please let us know, and this bot may get updated to automatically answer you.

Thanks!

**Comment by duramato** [comment]
Clear your mako cache

**Comment by neoatomic** [comment]
Seems to be working fine here.
When you add a provider you need to save first and then refresh the page to set the category's.
Also you can try to Shutdown SR and remove the Cache/sessions & mako folders, and than restart.

![1](https://cloud.githubusercontent.com/assets/7928052/11919488/b12cc088-a754-11e5-9c77-a2c9a211f234.png)

**Comment by benpeart** [comment]
I shutdown SR and rm -rf on both mako and sessions then restarted.  When I first went to the page, it said "Updating categories" then looked like this:

![newznab](https://cloud.githubusercontent.com/assets/15252029/11920357/bf8e4b20-a73a-11e5-9e6c-03962ed30c16.jpg)

**Comment by neoatomic** [comment]
@benpeart Only difference i see is `https://www.nzb.is/`
You sure that you are on the new Repo.? As this was a bug on the old Repository.

**Comment by benpeart** [comment]
I tried using https://www.nzb.is/ and get the same behavior.  I tried with IE and Edge just in case it was browser related - same behavior.  Any other things I can try?  Any debug/log settings you need?

![config](https://cloud.githubusercontent.com/assets/15252029/11920770/8d45d614-a745-11e5-8e3f-9f19de74a317.jpg)

**Comment by duramato** [comment]
Try removing the provider del mako cache and readding it

**Comment by benpeart** [comment]
I tried that before (see my 2nd post) but just to be sure I'm getting the right on, here are the exact commands I ran as root:

cd /usr/local/sickrage/var/cache
rm -rf mako
rm -rf sessions

Then restarted SR.  Tried it again right now just in case but still just shows 5030 and 5040.  I don't know if this is supposed to hit nzb.is but when I check my profile, it says "API requests today: 0"

**Comment by duramato** [comment]
the commands are right but did you  try removing the provider first?

**Comment by benpeart** [comment]
The first time was a new install so I was starting from scratch.  I also just 1) removed the provider and saved changes, shut down SR, removed the mako and sessions directories, started up SR, added the provider anew, watched "updating categories" come and then go.  Still have the same result. :(

**Comment by neoatomic** [comment]
@benpeart The category's  5030 (SD) and 5040 (HD) are auto added. Just in case users forget to add any at all. Thats a separate process from detecting the category's.

I saw you where using the new python 2.7.11 so i installed that on my Synology and tested again by adding another custom provider. Still all working fine... 
You sure you dont have any permission issues.? or are you using a proxy.?

**Comment by benpeart** [comment]
I'm not sure how to check for permission issues - I don't see anything in the errors or log file about that.  No fancy networking settings, no proxy or VPN.  This worked a few months ago when I first set it up (on the old git repo) but then all my news group downloads stopped working.  The old repo is on the floor (completely hosed on my Synology) so today I switched hoping this one would work.  So far everything is working well for me except this one piece.

**Comment by labrys** [comment]
If you haven't, try deleting the config and starting with a fresh config file as I have seen it affect some users.

**Comment by neoatomic** [comment]
I'm also out of ideas. Would advice to remove the sickrage package from the package center.
Then reinstall it again (with the new repo off course) and start completely fresh. So not restoring any old files. And then try to add the custom nzb.is provider to see if it than works.

**Comment by benpeart** [comment]
That is where I started out earlier today as it was the only way I could figure out how to change the SickRage Synology package to point to the new repo.  Is there anything I can edit/create manually so that my news group downloader will work?  Any debug flags I can turn on? Any log files to send?

**Comment by neoatomic** [comment]
@benpeart You are able to add/save the provider right.? 
So than the provider should be in your provider list. Enable it there, and select daily & backlog search. And as 5030&5040 are auto added, the providers should work fine.:)

**Comment by miigotu** [comment]
Double check your apikey with an api call in the browser... maybe wrong key or you are past the api limit?

**Comment by fernandog** [comment]
that error was fixed with miigotu PR
