### ISSUE TITLE
Error : AttributeError: 'NoneType' object has no attribute 'categories'

### ISSUE THREAD

**Issue by albatorsssx** [SickRage/sickrage-issues#289]
Hi,

I just switch on your fork. I have this error loop:

2015-12-21 14:24:15 Thread-21 :: Failed doing webui callback: Traceback (most recent call last):
  File "/opt/sickrage/sickbeard/webserve.py", line 271, in async_call
    result = function(**kwargs)
  File "/opt/sickrage/sickbeard/webserve.py", line 4319, in getNewznabCategories
    success, tv_categories, error = tempProvider.get_newznab_categories()
  File "/opt/sickrage/sickbeard/providers/newznab.py", line 128, in get_newznab_categories
    for category in data.caps.categories.findAll('category'):
AttributeError: 'NoneType' object has no attribute 'categories'

What can I do ?

Thank you.

Best regards

**Comment by SickRage2** [comment]
Thanks for the issue report! Before a real human comes by, please make sure your report has all the below criteria checked

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [ ] Post debug logs, either inline (for smaller logs) or using gist)

Please make sure you also read [how to create an issue](https://github.com/SickRage/sickrage-issues/blob/master/README.md) and followed all of the steps. 

The title should describe your issue. Having "SR not working" or "I get this bug" for 100 issues, isn't really helpful. We will close issues if there isn't enough information.

Sometimes the devs may seem like grunts and respond with short answers. This isn't (always) because the dev hates you, but because he's on mobile or busy fixing bugs. If something isn't clear, please let us know, and this bot may get updated to automatically answer you.

Thanks!

**Comment by neoatomic** [comment]
See if you can shutdown SR and remove the cache/sessions & mako folders. Then restart.

**Comment by miigotu** [comment]
That error is fixed in develop. Anyways, it is cosmetic anyways, and wont hurt anything until develop can be merged to master.
