### ISSUE TITLE
[APP SUBMITTED]: Index must be int or string

### ISSUE THREAD

**Issue by duramato** [SickRage/sickrage-issues#292]
### INFO
Python Version: **2.7.6 (default, Jun 22 2015, 18:00:18) [GCC 4.8.2]**
Operating System: **Linux-3.19.0-42-generic-i686-with-Ubuntu-14.04-trusty**
Locale: unknown
Branch: **develop**
Commit: SickRage/SickRage@db1edfbb2db5ce47a65c9f3ddb95bd435cf367de
Link to Log: https://gist.github.com/0bbfc418a76cbeb250c9
### ERROR
```
POSTPROCESSER :: Exception generated in thread POSTPROCESSER: Index must be int or string [db1edfb]
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by SickRage2** [comment]
Thanks for the issue report! Before a real human comes by, please make sure your report has all the below criteria checked

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [x] Post debug logs, either inline (for smaller logs) or using gist)

Please make sure you also read [how to create an issue](https://github.com/SickRage/sickrage-issues/blob/master/README.md) and followed all of the steps. 

The title should describe your issue. Having "SR not working" or "I get this bug" for 100 issues, isn't really helpful. We will close issues if there isn't enough information.

Sometimes the devs may seem like grunts and respond with short answers. This isn't (always) because the dev hates you, but because he's on mobile or busy fixing bugs. If something isn't clear, please let us know, and this bot may get updated to automatically answer you.

Thanks!

**Comment by duramato** [comment]
```
2015-12-22 01:28:57 DEBUG    POSTPROCESSER :: 'Traceback (most recent call last):\n  File "/home/home/SickRage/sickbeard/scheduler.py", line 106, in run\n    self.action.run(self.force)\n  File "/home/home/SickRage/sickbeard/auto_postprocessor.py", line 56, in run\n    processTV.processDir(sickbeard.TV_DOWNLOAD_DIR, force=force)\n  File "/home/home/SickRage/sickbeard/processTV.py", line 229, in processDir\n    for curDir in [x for x in dirs if validateDir(path, x, nzbNameOriginal, failed, result)]:\n  File "/home/home/SickRage/sickbeard/processTV.py", line 344, in validateDir\n    if dirName.lower().startswith(ek(os.path.realpath, sqlShow[u"location"]).lower() + os.sep) or \\\nIndexError: Index must be int or string\n'
AAIndexError: Index must be int or string
AA    if dirName.lower().startswith(ek(os.path.realpath, sqlShow[u"location"]).lower() + os.sep) or \
AA  File "/home/home/SickRage/sickbeard/processTV.py", line 344, in validateDir
AA    for curDir in [x for x in dirs if validateDir(path, x, nzbNameOriginal, failed, result)]:
AA  File "/home/home/SickRage/sickbeard/processTV.py", line 229, in processDir
AA    processTV.processDir(sickbeard.TV_DOWNLOAD_DIR, force=force)
AA  File "/home/home/SickRage/sickbeard/auto_postprocessor.py", line 56, in run
AA    self.action.run(self.force)
AA  File "/home/home/SickRage/sickbeard/scheduler.py", line 106, in run
AATraceback (most recent call last):
2015-12-22 01:28:57 ERROR    POSTPROCESSER :: Exception generated in thread POSTPROCESSER: Index must be int or string [db1edfb]
```

**Comment by fernandog** [comment]
@Labrys

**Comment by miigotu** [comment]
boom! lol

**Comment by labrys** [comment]
Yeah that's what I was hoping to find, or rather not find, with that change.  Would like to switch to unicode_literals but things like that might hamper that kind of mass change.
