### ISSUE TITLE
UnicodeEncodeError

### ISSUE THREAD

**Issue by danyboy666** [SickRage/sickrage-issues#313]
Again with some ascii troubles. Sickrage won't process anything wich have (éÉàÀÊê) accents.

SR Version:	BRANCH: (master) / COMMIT: (f6f2afb5df9ec69b9d6a3a839912bfd761520428) 
SR User:	
SR Locale:	(None, None)
SR Config:	/opt/SickRage/config.ini
SR Database:	/opt/SickRage/sickbeard.db
SR Cache Dir:	/opt/SickRage/cache
SR Log Dir:	/opt/SickRage/Logs
SR Arguments:	['-q', '--daemon', '--nolaunch', '--pidfile=/var/run/sickrage/sickrage.pid', '--datadir=/opt/SickRage/']
Python Version:	2.7.6 (default, Jun 22 2015, 17:58:13) [GCC 4.8.2]

**Comment by SickRage2** [comment]
Thanks for the issue report! Before a real human comes by, please make sure your report has all the below criteria checked

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [ ] Post debug logs, either inline (for smaller logs) or using gist)

Please make sure you also read [how to create an issue](https://github.com/SickRage/sickrage-issues/blob/master/README.md) and followed all of the steps. 

The title should describe your issue. Having "SR not working" or "I get this bug" for 100 issues, isn't really helpful. We will close issues if there isn't enough information.

Sometimes the devs may seem like grunts and respond with short answers. This isn't (always) because the dev hates you, but because he's on mobile or busy fixing bugs. If something isn't clear, please let us know, and this bot may get updated to automatically answer you.

Thanks!

**Comment by danyboy666** [comment]
Another one here 

2015-12-23 21:28:29 POSTPROCESSER :: Exception generated in thread POSTPROCESSER: ascii : /samba/anonymous/library/Videos/TV Shows fr/Infoman/Season 16/Infoman - S16E15 - Épisode 15.nfo : error 81 : error 82 : ordinal not in range(128)

**Comment by danyboy666** [comment]
Oops forgot to post complete log

2015-12-23 21:41:12 Thread-43 :: Failed doing webui callback: Traceback (most recent call last):
  File "/opt/SickRage/sickbeard/webserve.py", line 271, in async_call
    result = function(**kwargs)
  File "/opt/SickRage/sickbeard/webserve.py", line 2247, in processEpisode
    is_priority=argToBool(is_priority), delete_on=argToBool(delete_on), failed=argToBool(failed), proc_type=type
  File "/opt/SickRage/sickbeard/processTV.py", line 224, in processDir
    process_media(path, [video], nzbName, process_method, force, is_priority, result)
  File "/opt/SickRage/sickbeard/processTV.py", line 555, in process_media
    result.result = processor.process()
  File "/opt/SickRage/sickbeard/postProcessor.py", line 1159, in process
    ep_obj.createMetaFiles()
  File "/opt/SickRage/sickbeard/tv.py", line 1838, in createMetaFiles
    self.createNFO()
  File "/opt/SickRage/sickbeard/tv.py", line 1849, in createNFO
    result = cur_provider.create_episode_metadata(self) or result
  File "/opt/SickRage/sickbeard/metadata/generic.py", line 260, in create_episode_metadata
    return self.write_ep_file(ep_obj)
  File "/opt/SickRage/sickbeard/metadata/generic.py", line 458, in write_ep_file
    nfo_file = io.open(nfo_file_path, 'wb')
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe9' in position 50: ordinal not in range(128)

2015-12-23 21:35:49 Thread-37 :: Failed doing webui callback: Traceback (most recent call last):
  File "/opt/SickRage/sickbeard/webserve.py", line 271, in async_call
    result = function(**kwargs)
  File "/opt/SickRage/sickbeard/webserve.py", line 2247, in processEpisode
    is_priority=argToBool(is_priority), delete_on=argToBool(delete_on), failed=argToBool(failed), proc_type=type
  File "/opt/SickRage/sickbeard/processTV.py", line 224, in processDir
    process_media(path, [video], nzbName, process_method, force, is_priority, result)
  File "/opt/SickRage/sickbeard/processTV.py", line 555, in process_media
    result.result = processor.process()
  File "/opt/SickRage/sickbeard/postProcessor.py", line 1159, in process
    ep_obj.createMetaFiles()
  File "/opt/SickRage/sickbeard/tv.py", line 1838, in createMetaFiles
    self.createNFO()
  File "/opt/SickRage/sickbeard/tv.py", line 1849, in createNFO
    result = cur_provider.create_episode_metadata(self) or result
  File "/opt/SickRage/sickbeard/metadata/generic.py", line 260, in create_episode_metadata
    return self.write_ep_file(ep_obj)
  File "/opt/SickRage/sickbeard/metadata/generic.py", line 458, in write_ep_file
    nfo_file = io.open(nfo_file_path, 'wb')
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe9' in position 189: ordinal not in range(128)

2015-12-23 21:28:29 POSTPROCESSER :: Exception generated in thread POSTPROCESSER: ascii : /samba/anonymous/library/Videos/TV Shows fr/Infoman/Season 16/Infoman - S16E15 - Épisode 15.nfo : error 81 : error 82 : ordinal not in range(128)

**Comment by divx-guy** [comment]
### INFO
Python Version: **2.7.10 (default, May 23 2015, 09:44:00) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-8-6.2.9200**
Locale: cp1252
Branch: **master**
Commit: SickRage/SickRage@f6f2afb5df9ec69b9d6a3a839912bfd761520428
No Log available with ERRORS: 
### ERROR
```
SHOWQUEUE-REFRESH :: 164541: Could not refresh subtitles
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by medariox** [comment]
[Set your locale](https://github.com/SickRage/sickrage-issues/wiki/FAQ%27s-and-Fixes#i-have-problems-with-special-characters-%C3%A9-etc-what-can-i-do).

**Comment by danyboy666** [comment]
My locale are set correctly wolfboy.

LANG=en_CA.UTF-8
LANGUAGE=en_CA:en
LC_CTYPE="en_CA.UTF-8"
LC_NUMERIC="en_CA.UTF-8"
LC_TIME="en_CA.UTF-8"
LC_COLLATE="en_CA.UTF-8"
LC_MONETARY="en_CA.UTF-8"
LC_MESSAGES="en_CA.UTF-8"
LC_PAPER="en_CA.UTF-8"
LC_NAME="en_CA.UTF-8"
LC_ADDRESS="en_CA.UTF-8"
LC_TELEPHONE="en_CA.UTF-8"
LC_MEASUREMENT="en_CA.UTF-8"
LC_IDENTIFICATION="en_CA.UTF-8"
LC_ALL=en_CA.UTF-8

I even used the old solution proposed by echel0n the last time https://sickrage.tv/forums/forum/help-support/general-support/12825-ensuring-your-locale-s-are-set-properly-to-avoid-unicode-issues

which only worsten the problem.

I've reported this issue in the past so did many other users. https://github.com/SickRage/sickrage-issues/issues/12

This is a recurring issue which i'm getting pretty tired of dealing with and only occuring with release which have accentuated chars.  By all mean i do not want to sound like an asshole here but this issue isn't specific to ubuntu and my setup in particular. Several users under BSD, Windows and other OSes are facing this issue too.

I'm not saying it's entirely SR side (most likely this is a python issue which it seem they are not in a rush to fix) but i'm only getting this problem when SR post-processing.

I fixed within python temporaly the last time it occured but the issue came back when i rebooted. I don't want to mess too much with python since it can easily break other stuff i'm running on the same box (i.e. Couchpotato, Headphones, Deluge, SabNZB).

I had a similar issue which Deluge would not add accentuated release which the Deluge team helped me hotfix. Since then though SR is not longer able to send accentuated release to Deluge since Deluge sanitize the name of the torrent before adding it so when SR come and try to retreive the release it is no longer reconized and thus can no longer be post-processed. To avoid this i have to rename the downloaded release once it is transfered back to my watch folder so SR can process it.

Anywais this is only an example which is a separate issue but it is nonetheless kind of related to SR since both soft are using the same python version.

The fact is right now post-processing is failing due to this error. Although after forcing post-processing folder seemed to have bypassed this for now. I'll gladely give more infos as soon i get this error back. These days are pretty quiet anywais not many releases since this is the holidays.

So yeah. Setting my locale isn't the solution here. 

Happy Holidays.

**Comment by duramato** [comment]
Whats your OS?

**Comment by danyboy666** [comment]
3.13.0-67-generic #110-Ubuntu SMP Fri Oct 23 13:24:41 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

**Comment by duramato** [comment]
What ubuntu version?

**Comment by danyboy666** [comment]
hum sorry : 

DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=14.04
DISTRIB_CODENAME=trusty
DISTRIB_DESCRIPTION="Ubuntu 14.04.3 LTS"

**Comment by medariox** [comment]
Your locale is obviously not set, as you can see yourself from what you have posted:
```
SR Locale: (None, None)
```
And uh, surprise! It's the Ubuntu version with the bugged locale.
Since you seem to know everything already, I wish you good luck finding the solution for that, as "wolfboy" is really tired helping rude people. 

Happy Holidays to you too!

**Comment by danyboy666** [comment]
Well i no i did not notice SR Locale: (None, None) weirdly they are not set anymore.

I'll deal with this trust me Uninstalling SR completely. 

Close this ticket.

btw: Do you have that tail too? https://pbs.twimg.com/media/B0u_XUUIUAAyOWb.jpg

**Comment by duramato** [comment]
Other user are facing the same issue becouse they need to set their locale you on the other side either upgrade to ubuntu 15 or there is nothing that you can as ubuntu 14.04 has a bug with locale..
