### ISSUE TITLE
Last update stops sickrage from starting

### ISSUE THREAD

**Issue by nucshuco** [SickRage/sickrage-issues#316]
freenas 9.3

BRANCH: (master) / COMMIT: (16646d679fbffdf948952722fba32867a596922d) 
SR User:	media
SR Locale:	(None, None)
SR Config:	/var/db/sickrage/config.ini
SR Database:	/var/db/sickrage/sickbeard.db
SR Cache Dir:	/var/db/sickrage/cache
SR Log Dir:	/var/db/sickrage/Logs
SR Arguments:	['--datadir', '/var/db/sickrage', '-d', '--pidfile', '/var/run/sickrage/sickrage.pid', '-q', '--nolaunch']
Python Version:	2.7.10 (default, Nov 6 2015, 04:06:37) [GCC 4.2.1 20070831 patched [FreeBSD]]

I had to roll back to get it to start. now im 202 commits behind.  I was just 2 commits behind when i updated this morning. 
I got this error.
```
Traceback (most recent call last):
  File "/usr/local/share/sickrage/SickRage/SickBeard.py", line 66, in <module>
    import sickbeard
  File "/usr/local/share/sickrage/SickRage/sickbeard/__init__.py", line 36, in <module>
    from sickbeard import metadata
  File "/usr/local/share/sickrage/SickRage/sickbeard/metadata/__init__.py", line 22, in <module>
    from sickbeard.metadata import kodi, kodi_12plus, mediabrowser, ps3, wdtv, tivo, mede8er, generic, helpers
  File "/usr/local/share/sickrage/SickRage/sickbeard/metadata/kodi.py", line 23, in <module>
    from sickbeard.metadata import generic
  File "/usr/local/share/sickrage/SickRage/sickbeard/metadata/generic.py", line 32, in <module>
    from sickbeard import helpers
  File "/usr/local/share/sickrage/SickRage/sickbeard/helpers.py", line 51, in <module>
    from sickbeard import logger, classes
  File "/usr/local/share/sickrage/SickRage/sickbeard/logger.py", line 36, in <module>
    from sickbeard import classes
  File "/usr/local/share/sickrage/SickRage/sickbeard/classes.py", line 29, in <module>
    from sickbeard.common import USER_AGENT, Quality
  File "/usr/local/share/sickrage/SickRage/sickbeard/common.py", line 49, in <module>
    UA_POOL = UserAgent()
  File "/usr/local/share/sickrage/SickRage/lib/fake_useragent/fake.py", line 10, in __init__
    self.data = load_cached()
  File "/usr/local/share/sickrage/SickRage/lib/fake_useragent/utils.py", line 140, in load_cached
    update()
  File "/usr/local/share/sickrage/SickRage/lib/fake_useragent/utils.py", line 135, in update
    write(load())
  File "/usr/local/share/sickrage/SickRage/lib/fake_useragent/utils.py", line 82, in load
    for item in get_browsers():
  File "/usr/local/share/sickrage/SickRage/lib/fake_useragent/utils.py", line 27, in get_browsers
    html = get(settings.BROWSERS_STATS_PAGE)
  File "/usr/local/share/sickrage/SickRage/lib/fake_useragent/utils.py", line 20, in get
    return urlopen(url).read()
  File "/usr/local/lib/python2.7/urllib.py", line 87, in urlopen
    return opener.open(url)
  File "/usr/local/lib/python2.7/urllib.py", line 213, in open
    return getattr(self, name)(url)
  File "/usr/local/lib/python2.7/urllib.py", line 350, in open_http
    h.endheaders(data)
  File "/usr/local/lib/python2.7/httplib.py", line 1049, in endheaders
    self._send_output(message_body)
  File "/usr/local/lib/python2.7/httplib.py", line 893, in _send_output
    self.send(msg)
  File "/usr/local/lib/python2.7/httplib.py", line 855, in send
    self.connect()
  File "/usr/local/lib/python2.7/httplib.py", line 832, in connect
    self.timeout, self.source_address)
  File "/usr/local/lib/python2.7/socket.py", line 575, in create_connection
    raise err
IOError: [Errno socket error] [Errno 61] Connection refused
/usr/local/etc/rc.d/sickrage: WARNING: failed to start sickrage
```

**Comment by SickRage2** [comment]
Thanks for the issue report! Before a real human comes by, please make sure your report has all the below criteria checked

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [ ] Post debug logs, either inline (for smaller logs) or using gist)

Please make sure you also read [how to create an issue](https://github.com/SickRage/sickrage-issues/blob/master/README.md) and followed all of the steps. 

The title should describe your issue. Having "SR not working" or "I get this bug" for 100 issues, isn't really helpful. We will close issues if there isn't enough information.

Sometimes the devs may seem like grunts and respond with short answers. This isn't (always) because the dev hates you, but because he's on mobile or busy fixing bugs. If something isn't clear, please let us know, and this bot may get updated to automatically answer you.

Thanks!

**Comment by duramato** [comment]
Maybe sr is already running or something is already running on the same port?
```IOError: [Errno socket error] [Errno 61] Connection refused```

**Comment by andyblac** [comment]
not where you got commit '16646d679fbffdf948952722fba32867a596922d' from but thats not the latest master commit. try doing a manual pull.

**Comment by nucshuco** [comment]
I tried manual pull of  latest master with the same error.  i had to roll back my jail to get sickrage to start. that why im on 16646d679fbffdf948952722fba32867a596922d

**Comment by andyblac** [comment]
starting fine here. hmm strange.

**Comment by nucshuco** [comment]
Im trying a fresh install now to see what happens

**Comment by nucshuco** [comment]
fresh install on different freenas same issue

Traceback (most recent call last):
  File "/usr/local/share/sickrage/SickRage/SickBeard.py", line 66, in <module>
    import sickbeard
  File "/usr/local/share/sickrage/SickRage/sickbeard/__init__.py", line 36, in <module>
    from sickbeard import metadata
  File "/usr/local/share/sickrage/SickRage/sickbeard/metadata/__init__.py", line 22, in <module>
    from sickbeard.metadata import kodi, kodi_12plus, mediabrowser, ps3, wdtv, tivo, mede8er, generic, helpers
  File "/usr/local/share/sickrage/SickRage/sickbeard/metadata/kodi.py", line 23, in <module>
    from sickbeard.metadata import generic
  File "/usr/local/share/sickrage/SickRage/sickbeard/metadata/generic.py", line 32, in <module>
    from sickbeard import helpers
  File "/usr/local/share/sickrage/SickRage/sickbeard/helpers.py", line 51, in <module>
    from sickbeard import logger, classes
  File "/usr/local/share/sickrage/SickRage/sickbeard/logger.py", line 36, in <module>
    from sickbeard import classes
  File "/usr/local/share/sickrage/SickRage/sickbeard/classes.py", line 29, in <module>
    from sickbeard.common import USER_AGENT, Quality
  File "/usr/local/share/sickrage/SickRage/sickbeard/common.py", line 49, in <module>
    UA_POOL = UserAgent()
  File "/usr/local/share/sickrage/SickRage/lib/fake_useragent/fake.py", line 10, in __init__
    self.data = load_cached()
  File "/usr/local/share/sickrage/SickRage/lib/fake_useragent/utils.py", line 140, in load_cached
    update()
  File "/usr/local/share/sickrage/SickRage/lib/fake_useragent/utils.py", line 135, in update
    write(load())
  File "/usr/local/share/sickrage/SickRage/lib/fake_useragent/utils.py", line 82, in load
    for item in get_browsers():
  File "/usr/local/share/sickrage/SickRage/lib/fake_useragent/utils.py", line 27, in get_browsers
    html = get(settings.BROWSERS_STATS_PAGE)
  File "/usr/local/share/sickrage/SickRage/lib/fake_useragent/utils.py", line 20, in get
    return urlopen(url).read()
  File "/usr/local/lib/python2.7/urllib.py", line 87, in urlopen
    return opener.open(url)
  File "/usr/local/lib/python2.7/urllib.py", line 213, in open
    return getattr(self, name)(url)
  File "/usr/local/lib/python2.7/urllib.py", line 350, in open_http
    h.endheaders(data)
  File "/usr/local/lib/python2.7/httplib.py", line 1053, in endheaders
    self._send_output(message_body)
  File "/usr/local/lib/python2.7/httplib.py", line 897, in _send_output
    self.send(msg)
  File "/usr/local/lib/python2.7/httplib.py", line 859, in send
    self.connect()
  File "/usr/local/lib/python2.7/httplib.py", line 836, in connect
    self.timeout, self.source_address)
  File "/usr/local/lib/python2.7/socket.py", line 575, in create_connection
    raise err
IOError: [Errno socket error] [Errno 61] Connection refused
/usr/local/etc/rc.d/sickrage: WARNING: failed to start sickrage

**Comment by nucshuco** [comment]
Restarted my pfsense firewall/router seems to be ok now.
thank you guys I love sickrage
Merry Christmas :)

**Comment by andyblac** [comment]
glad you tracked it down.
