### ISSUE TITLE
Sickrage won't start after latest pull with pfsense (Fix inside)

### ISSUE THREAD

**Issue by zflash** [SickRage/sickrage-issues#321]
Git hash: 8579dfb47f5b12698cc44e0b18f9602fa0cc4421 / Master
Latest pull: 25-10-2015 6:31 GMT+1
OS: Windows
Python ver: 2.7
Debuglog: Log is not being written unfortunately.

Error: 

Traceback (most recent call last):
  File "c:\sickrage\SickBeard.py", line 66, in <module>
    import sickbeard
  File "c:\sickrage\sickbeard\__init__.py", line 36, in <module>
    from sickbeard import metadata
  File "c:\sickrage\sickbeard\metadata\__init__.py", line 22, in <module>
    from sickbeard.metadata import kodi, kodi_12plus, mediabrowser, ps3, wdtv, tivo, mede8er, generic, helpers
  File "c:\sickrage\sickbeard\metadata\kodi.py", line 23, in <module>
    from sickbeard.metadata import generic
  File "c:\sickrage\sickbeard\metadata\generic.py", line 32, in <module>
    from sickbeard import helpers
  File "c:\sickrage\sickbeard\helpers.py", line 51, in <module>
    from sickbeard import logger, classes
  File "c:\sickrage\sickbeard\logger.py", line 36, in <module>
    from sickbeard import classes
  File "c:\sickrage\sickbeard\classes.py", line 29, in <module>
    from sickbeard.common import USER_AGENT, Quality
  File "c:\sickrage\sickbeard\common.py", line 49, in <module>
    UA_POOL = UserAgent()
  File "c:\sickrage\lib\fake_useragent\fake.py", line 10, in __init__
    self.data = load_cached()
  File "c:\sickrage\lib\fake_useragent\utils.py", line 140, in load_cached
    update()
  File "c:\sickrage\lib\fake_useragent\utils.py", line 135, in update
    write(load())
  File "c:\sickrage\lib\fake_useragent\utils.py", line 92, in load
    browsers_dict[browser_key] = get_browser_versions(browser)
  File "c:\sickrage\lib\fake_useragent\utils.py", line 53, in get_browser_versions
    html = get(settings.BROWSER_BASE_PAGE, browser)
  File "c:\sickrage\lib\fake_useragent\utils.py", line 20, in get
    return urlopen(url).read()
  File "C:\Python27\lib\urllib.py", line 87, in urlopen
    return opener.open(url)
  File "C:\Python27\lib\urllib.py", line 213, in open
    return getattr(self, name)(url)
  File "C:\Python27\lib\urllib.py", line 350, in open_http
    h.endheaders(data)
  File "C:\Python27\lib\httplib.py", line 1049, in endheaders
    self._send_output(message_body)
  File "C:\Python27\lib\httplib.py", line 893, in _send_output
    self.send(msg)
  File "C:\Python27\lib\httplib.py", line 855, in send
    self.connect()
  File "C:\Python27\lib\httplib.py", line 832, in connect
    self.timeout, self.source_address)
  File "C:\Python27\lib\socket.py", line 575, in create_connection
    raise err
IOError: [Errno socket error] [Errno 10060]

Allready tried:
- Git reset hard
- Changed the portnumer
- Removed cache
- Removed all compiled versions

[EDIT]
Did a complete new clone, copied my DB into the folder incl. the config. Same error.

**Comment by SickRage2** [comment]
Thanks for the issue report! Before a real human comes by, please make sure your report has all the below criteria checked

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [ ] Post debug logs, either inline (for smaller logs) or using gist)

Please make sure you also read [how to create an issue](https://github.com/SickRage/sickrage-issues/blob/master/README.md) and followed all of the steps. 

The title should describe your issue. Having "SR not working" or "I get this bug" for 100 issues, isn't really helpful. We will close issues if there isn't enough information.

Sometimes the devs may seem like grunts and respond with short answers. This isn't (always) because the dev hates you, but because he's on mobile or busy fixing bugs. If something isn't clear, please let us know, and this bot may get updated to automatically answer you.

Thanks!

**Comment by zflash** [comment]
After a restore from a backup of the 24th, the installation runs. As soon as a do a 'git pull' the installation breaks again. Even with a new installation, and a copy from my DB, it can't be started again.

**Comment by nucshuco** [comment]
I was having the same problem. My firewall was blocking 72.21.91.8 
https://github.com/SickRage/sickrage-issues/issues/321

**Comment by zflash** [comment]
What's that IP used for?

**Comment by miigotu** [comment]
IP is either http://www.w3schools.com or http://useragentstring.com

**Comment by miigotu** [comment]
Maybe you could ask the lib dev why here: https://github.com/hellysmile/fake-useragent

**Comment by AnatomicFlack** [comment]
Also running PFSense with the pfBlockerNG plugin.  I had to disable it in order to get past the broken version and update.  My install was trying to talk to 91.250.101.245:80.  Can I ask what you were trying to talk to on start up?  pfBlockerNG only blocks overseas addresses from known bad countries, so doesn't make me too comfortable knowing that's where the traffic was attempting to go.  

After I disabled and updated this morning, it's working normally once again with pfBlockerNG enabled.  

Starting SickBeard
Traceback (most recent call last):
  File "SickBeard.py", line 66, in <module>
    import sickbeard
  File "/home/mediaserver/.sickrage/sickbeard/__init__.py", line 36, in <module>
    from sickbeard import metadata
  File "/home/mediaserver/.sickrage/sickbeard/metadata/__init__.py", line 22, in <module>
    from sickbeard.metadata import kodi, kodi_12plus, mediabrowser, ps3, wdtv, tivo, mede8er, generic, helpers
  File "/home/mediaserver/.sickrage/sickbeard/metadata/kodi.py", line 23, in <module>
    from sickbeard.metadata import generic
  File "/home/mediaserver/.sickrage/sickbeard/metadata/generic.py", line 32, in <module>
    from sickbeard import helpers
  File "/home/mediaserver/.sickrage/sickbeard/helpers.py", line 51, in <module>
    from sickbeard import logger, classes
  File "/home/mediaserver/.sickrage/sickbeard/logger.py", line 36, in <module>
    from sickbeard import classes
  File "/home/mediaserver/.sickrage/sickbeard/classes.py", line 29, in <module>
    from sickbeard.common import USER_AGENT, Quality
  File "/home/mediaserver/.sickrage/sickbeard/common.py", line 49, in <module>
    UA_POOL = UserAgent()
  File "/home/mediaserver/.sickrage/lib/fake_useragent/fake.py", line 10, in __init__
    self.data = load_cached()
  File "/home/mediaserver/.sickrage/lib/fake_useragent/utils.py", line 140, in load_cached
    update()
  File "/home/mediaserver/.sickrage/lib/fake_useragent/utils.py", line 135, in update
    write(load())
  File "/home/mediaserver/.sickrage/lib/fake_useragent/utils.py", line 92, in load
    browsers_dict[browser_key] = get_browser_versions(browser)
  File "/home/mediaserver/.sickrage/lib/fake_useragent/utils.py", line 53, in get_browser_versions
    html = get(settings.BROWSER_BASE_PAGE, browser)
  File "/home/mediaserver/.sickrage/lib/fake_useragent/utils.py", line 20, in get
    return urlopen(url).read()
  File "/usr/lib/python2.7/urllib.py", line 87, in urlopen
    return opener.open(url)
  File "/usr/lib/python2.7/urllib.py", line 208, in open
    return getattr(self, name)(url)
  File "/usr/lib/python2.7/urllib.py", line 345, in open_http
    h.endheaders(data)
  File "/usr/lib/python2.7/httplib.py", line 975, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python2.7/httplib.py", line 835, in _send_output
    self.send(msg)
  File "/usr/lib/python2.7/httplib.py", line 797, in send
    self.connect()
  File "/usr/lib/python2.7/httplib.py", line 778, in connect
    self.timeout, self.source_address)
  File "/usr/lib/python2.7/socket.py", line 571, in create_connection
    raise err
IOError: [Errno socket error] [Errno 111] Connection refused

**Comment by zflash** [comment]
I'm not running pfblockerng, but it still blocks the address. Probably a rule from snort that's in the firewall. But really to anxious to disable that either.

**Comment by miigotu** [comment]
there is no reason not to trust w3schools. it updates the UA's generated one time after the update, so that everyone has a unique pool of UA.

**Comment by zflash** [comment]
I know, that's why I will try to get it working with allowing that ip. So far I'm having no luck with that. Will keep you updated.

**Comment by miigotu** [comment]
Was letting @AnatomicFlack know, that it isnt anything fishy going on.

It tries to scrape the 2 urls in https://github.com/hellysmile/fake-useragent/blob/master/fake_useragent/settings.py

to create the file lib/fake_useragent/ua.json

Once the file is created, it doesn't update it again.

So @zflash you could disable the firewall and start SR one time, or start SR on another machine and copy the lib/fake_useragent/ua.json to your machine, and it will run with the firewall enabled.

Will be looking for a better solution to this soon, it's really a strange problem.

**Comment by zflash** [comment]
Fund the solution for my usecase. People using PFsense and are having this issue are probably using PFBLockerNG or SNORT. We know from AnatomicFlack that simply disabling pfblocker works, but not with Snort. you have to clear the snort2c table. in my case, that table contained the blocked IP adresses of www.useragenstring.com. There was no need to make any rules or disabling snort.

Fact is, that this ip was used by someone with malicious intentions and snort's ruleset prevented this ip from being connected.
