### ISSUE TITLE
[APP SUBMITTED]: 'NoneType' object has no attribute 'name'

### ISSUE THREAD

**Issue by tiki1980** [SickRage/sickrage-issues#324]
### INFO
Python Version: **2.7.9 (default, Mar  1 2015, 12:57:24) [GCC 4.9.2]**
Operating System: **Linux-3.16.0-4-amd64-x86_64-with-debian-8.2**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@8579dfb47f5b12698cc44e0b18f9602fa0cc4421
Link to Log: https://gist.github.com/90998623a3852bfdcd97
### ERROR
```
POSTPROCESSER :: Exception generated in thread POSTPROCESSER: 'NoneType' object has no attribute 'name' [8579dfb]
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by SickRage2** [comment]
Thanks for the issue report! Before a real human comes by, please make sure your report has all the below criteria checked

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [x] Post debug logs, either inline (for smaller logs) or using gist)

Please make sure you also read [how to create an issue](https://github.com/SickRage/sickrage-issues/blob/master/README.md) and followed all of the steps. 

The title should describe your issue. Having "SR not working" or "I get this bug" for 100 issues, isn't really helpful. We will close issues if there isn't enough information.

Sometimes the devs may seem like grunts and respond with short answers. This isn't (always) because the dev hates you, but because he's on mobile or busy fixing bugs. If something isn't clear, please let us know, and this bot may get updated to automatically answer you.

Thanks!

**Comment by ValiantThor** [comment]
### INFO
Python Version: **2.7.3 (default, Apr 12 2012, 20:25:04) [GCC 4.2.1]**
Operating System: **Linux-3.12.6-x86_64-with-glibc2.0**
Locale: unknown
Branch: **master**
Commit: SickRage/SickRage@7fd6c98aafe1f543bf8f96b2e370666be5412288
No Log available with ERRORS: 
### ERROR
```
Thread-31 :: Failed doing webui callback: Traceback (most recent call last):
  File "/share/CACHEDEV1_DATA/.qpkg/SickBeard-TVRage/sickbeard/webserve.py", line 271, in async_call
    result = function(**kwargs)
  File "/share/CACHEDEV1_DATA/.qpkg/SickBeard-TVRage/sickbeard/webserve.py", line 1582, in deleteShow
    show.name,
AttributeError: 'NoneType' object has no attribute 'name'
 [7fd6c98]
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by nncrypted** [comment]
### INFO
Python Version: **2.7.3 (default, Mar 13 2014, 11:03:55) [GCC 4.7.2]**
Operating System: **Linux-3.16.0-0.bpo.4-amd64-x86_64-with-debian-7.9**
Locale: None
Branch: **master**
Commit: SickRage/SickRage@5195b784b76916a2acfe21c1fffd12f837ce0e93
No Log available with ERRORS:
### ERROR
```
Thread-155 :: Failed doing webui callback: Traceback (most recent call last):
  File "/opt/sickbeard/sickbeard/webserve.py", line 285, in async_call
    result = function(**kwargs)
  File "/opt/sickbeard/sickbeard/webserve.py", line 1609, in deleteShow
    show.name,
AttributeError: 'NoneType' object has no attribute 'name'
 [5195b78]
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators
