### ISSUE TITLE
[APP SUBMITTED]: can only concatenate list (not "unicode") to list

### ISSUE THREAD

**Issue by Natrixz** [SickRage/sickrage-issues#340]
### INFO
Python Version: **2.7.10 (default, May 23 2015, 09:40:32) [MSC v.1500 32 bit (Intel)]**
Operating System: **Windows-8-6.2.9200**
Locale: cp1252
Branch: **master**
Commit: SickRage/SickRage@dbf446a51f8b6e900aba41e947ef9f925ae12714
No Log available with ERRORS: 
### ERROR
```
Thread-55 :: Failed doing webui callback: Traceback (most recent call last):
  File "C:\SickRage\sickbeard\webserve.py", line 271, in async_call
    result = function(**kwargs)
  File "C:\SickRage\sickbeard\webserve.py", line 3076, in downloadSubtitleMissed
    show.getEpisode(int(season), int(episode)).download_subtitles()
  File "C:\SickRage\sickbeard\tv.py", line 1432, in download_subtitles
    self.subtitles, new_subtitles = subtitles.download_subtitles(subtitles_info)
  File "C:\SickRage\sickbeard\subtitles.py", line 241, in download_subtitles
    current_subtitles = sorted({subtitle for subtitle in new_subtitles + existing_subtitles})
TypeError: can only concatenate list (not "unicode") to list
 [dbf446a]
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by SickRage2** [comment]
Thanks for the issue report! Before a real human comes by, please make sure your report has all the below criteria checked

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [ ] Post debug logs, either inline (for smaller logs) or using gist)

Please make sure you also read [how to create an issue](https://github.com/SickRage/sickrage-issues/blob/master/README.md) and followed all of the steps. 

The title should describe your issue. Having "SR not working" or "I get this bug" for 100 issues, isn't really helpful. We will close issues if there isn't enough information.

Sometimes the devs may seem like grunts and respond with short answers. This isn't (always) because the dev hates you, but because he's on mobile or busy fixing bugs. If something isn't clear, please let us know, and this bot may get updated to automatically answer you.

Thanks!

**Comment by medariox** [comment]
Should be fixed in develop with https://github.com/SickRage/SickRage/pull/588

Please let us know if yous till face this issue.
