### ISSUE TITLE
OSError: [Errno 2] No such file or directory: ~/SickRage/cache/mako

### ISSUE THREAD

**Issue by fernandog** [SickRage/sickrage-issues#341]
SR not starting 

```
Starting up SickRage develop from /home/osmc/SickRage/config.ini
Traceback (most recent call last):
  File "SickBeard.py", line 538, in <module>
    SickRage().start()
  File "SickBeard.py", line 309, in start
    shutil.rmtree(ek(os.path.join, sickbeard.CACHE_DIR, 'mako'))
  File "/usr/lib/python2.7/shutil.py", line 239, in rmtree
    onerror(os.listdir, path, sys.exc_info())
  File "/usr/lib/python2.7/shutil.py", line 237, in rmtree
    names = os.listdir(path)
OSError: [Errno 2] Arquivo ou diretório não encontrado: '/home/osmc/SickRage/cache/mako'
```

**Comment by SickRage2** [comment]
Thanks for the issue report! Before a real human comes by, please make sure your report has all the below criteria checked

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [ ] Post debug logs, either inline (for smaller logs) or using gist)

Please make sure you also read [how to create an issue](https://github.com/SickRage/sickrage-issues/blob/master/README.md) and followed all of the steps. 

The title should describe your issue. Having "SR not working" or "I get this bug" for 100 issues, isn't really helpful. We will close issues if there isn't enough information.

Sometimes the devs may seem like grunts and respond with short answers. This isn't (always) because the dev hates you, but because he's on mobile or busy fixing bugs. If something isn't clear, please let us know, and this bot may get updated to automatically answer you.

Thanks!

**Comment by fernandog** [comment]
@miigotu
