### ISSUE TITLE
[APP SUBMITTED]: failedDownloads() got an unexpected keyword argument '_Ned_the_Quadruped_1080i_HDTV_DD5_1_MPEG2_TrollHD|Dinosaur_Train_S01E04_One_Smart_Dinosaur'

### ISSUE THREAD

**Issue by Wackywoods** [SickRage/sickrage-issues#352]
### INFO
Python Version: **2.7.10 (default, May 23 2015, 09:44:00) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-8-6.2.9200**
Locale: cp1252
Branch: **master**
Commit: SickRage/SickRage@475db54a21ea3352b206c35dada38d61b9be45ad
No Log available with ERRORS: 
### ERROR
```
Thread-25 :: Failed doing webui callback: Traceback (most recent call last):
  File "C:\Sickrage\SickRage\sickbeard\webserve.py", line 271, in async_call
    result = function(**kwargs)
TypeError: failedDownloads() got an unexpected keyword argument '_Ned_the_Quadruped_1080i_HDTV_DD5_1_MPEG2_TrollHD|Dinosaur_Train_S01E04_One_Smart_Dinosaur'
 [475db54]
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by SickRage2** [comment]
Thanks for the issue report! Before a real human comes by, please make sure your report has all the below criteria checked

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [ ] Post debug logs, either inline (for smaller logs) or using gist)

Please make sure you also read [how to create an issue](https://github.com/SickRage/sickrage-issues/blob/master/README.md) and followed all of the steps. 

The title should describe your issue. Having "SR not working" or "I get this bug" for 100 issues, isn't really helpful. We will close issues if there isn't enough information.

Sometimes the devs may seem like grunts and respond with short answers. This isn't (always) because the dev hates you, but because he's on mobile or busy fixing bugs. If something isn't clear, please let us know, and this bot may get updated to automatically answer you.

Thanks!

**Comment by Wackywoods** [comment]
Python Version: 2.7.3 (default, Apr 12 2012, 20:25:04) [GCC 4.2.1]
Operating System: Windows 10 (64Bit)
Locale: unknown
Branch: master
Commit: SickRage/SickRage@dbf446a

Errors from logs : 

2015-12-28 19:38:23 ERROR    Thread-65 :: Failed doing webui callback: Traceback (most recent call last):
2015-12-28 19:37:48 INFO     CHECKVERSION :: Checking for updates using GIT
2015-12-28 19:37:48 INFO     TORNADO :: Starting SickRage on http://0.0.0.0:8081/
2015-12-28 19:37:48 INFO     MAIN :: Starting up SickRage [master] from 'C:\Sickrage\SickRage\config.ini'
2015-12-28 19:37:48 INFO     MAIN :: 275120: Unable to find IMDb show info in the database
2015-12-28 19:37:48 INFO     MAIN :: 292982: Unable to find IMDb show info in the database
2015-12-28 19:37:47 INFO     MAIN :: 259462: Unable to find IMDb show info in the database
2015-12-28 19:37:46 INFO     MAIN :: 79649: Unable to find IMDb show info in the database

I am trying to clean up the failed downloads list and i get this : 

2015-12-28 19:42:19 ERROR    Thread-54 :: Failed doing webui callback: Traceback (most recent call last):
AA
AATypeError: failedDownloads() got an unexpected keyword argument '_Ned_the_Quadruped_1080i_HDTV_DD5_1_MPEG2_TrollHD|Dinosaur_Train_S01E04_One_Smart_Dinosaur'
AA    result = function(**kwargs)
AA  File "C:\Sickrage\SickRage\sickbeard\webserve.py", line 271, in async_call
AA    result = self.fn(*self.args, **self.kwargs)
AA  File "C:\Sickrage\SickRage\lib\concurrent\futures\thread.py", line 61, in run
AA    exec('raise exc_type, exc_value, traceback', {}, locals_)
AA  File "C:\Sickrage\SickRage\lib\concurrent\futures\_compat.py", line 107, in reraise
AA    reraise(self._exception, self._traceback)
AA  File "C:\Sickrage\SickRage\lib\concurrent\futures\_base.py", line 359, in __get_result
AA    return self.__get_result()
AA  File "C:\Sickrage\SickRage\lib\concurrent\futures\_base.py", line 400, in result
AA    value = future.result()
AA  File "C:\Sickrage\SickRage\lib\tornado\gen.py", line 870, in run
AA    results = yield self.async_call(method)
AA  File "C:\Sickrage\SickRage\sickbeard\webserve.py", line 256, in get
2015-12-28 19:42:01 ERROR    Thread-61 :: Failed doing webui callback: Traceback (most recent call last):

**Comment by Wackywoods** [comment]
Ok, so i was going through the failed downloads and removing some and they seemed stuck so i just deleted the failed DB files and that is now clear, guess my file must have been corrupt some how.

Closing this ticket off thanks.
