### ISSUE TITLE
[APP SUBMITTED]: [Errno 22] invalid mode ('wb') or filename: u'C:\\SickRage\\SickRage\\config.ini'

### ISSUE THREAD

**Issue by m184711** [SickRage/sickrage-issues#361]
### INFO
Python Version: **2.7.10 (default, May 23 2015, 09:44:00) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-7-6.1.7601-SP1**
Locale: cp1252
Branch: **master**
Commit: SickRage/SickRage@475db54a21ea3352b206c35dada38d61b9be45ad
No Log available with ERRORS: 
### ERROR
```
Thread-20 :: Failed doing webui callback: Traceback (most recent call last):
  File "C:\SickRage\SickRage\sickbeard\webserve.py", line 271, in async_call
    result = function(**kwargs)
  File "C:\SickRage\SickRage\sickbeard\webserve.py", line 2189, in index
    sickbeard.save_config()
  File "C:\SickRage\SickRage\sickbeard\__init__.py", line 2124, in save_config
    new_config.write()
  File "C:\SickRage\SickRage\lib\configobj.py", line 2066, in write
    h = open(self.filename, 'wb')
IOError: [Errno 22] invalid mode ('wb') or filename: u'C:\\SickRage\\SickRage\\config.ini'
 [475db54]
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by SickRage2** [comment]
Thanks for the issue report! Before a real human comes by, please make sure your report has all the below criteria checked

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [ ] Post debug logs, either inline (for smaller logs) or using gist)

Please make sure you also read [how to create an issue](https://github.com/SickRage/sickrage-issues/blob/master/README.md) and followed all of the steps. 

The title should describe your issue. Having "SR not working" or "I get this bug" for 100 issues, isn't really helpful. We will close issues if there isn't enough information.

Sometimes the devs may seem like grunts and respond with short answers. This isn't (always) because the dev hates you, but because he's on mobile or busy fixing bugs. If something isn't clear, please let us know, and this bot may get updated to automatically answer you.

Thanks!
