### ISSUE TITLE
Adding New show Creates Folders With Read Only Permissions [BUG]

### ISSUE THREAD

**Issue by XxUnkn0wnxX** [SickRage/sickrage-issues#364]
Branch: Master
Commit: ed25b12a4e71535607a72d8036e43a830e435595
OS: Mac OS El Capitan 10.11.2
Python: Python 2.7.11

```
2015-12-30 15:35:58 DEBUG    SHOWQUEUE-ADD :: 284210: Loading all episodes from the show directory /Volumes/Media/TV Shows/Colony
2015-12-30 15:35:58 ERROR    SHOWQUEUE-ADD :: Error searching dir for episodes: error 13 : Permission denied [ed25b12]
Traceback (most recent call last):
  File "/Users/XxUnkn0wnxX/Apps/SickRage/sickbeard/show_queue.py", line 438, in run
    self.show.loadEpisodesFromDir()
  File "/Users/XxUnkn0wnxX/Apps/SickRage/sickbeard/tv.py", line 410, in loadEpisodesFromDir
    mediaFiles = helpers.listMediaFiles(self._location)
  File "/Users/XxUnkn0wnxX/Apps/SickRage/sickbeard/helpers.py", line 327, in listMediaFiles
    for curFile in ek(os.listdir, path):
  File "/Users/XxUnkn0wnxX/Apps/SickRage/sickrage/helper/encoding.py", line 40, in ek
    result = function(*[ss(x) if isinstance(x, (str, unicode)) else x for x in args], **kwargs)
OSError: [Errno 13] Permission denied: '/Volumes/Media/TV Shows/Colony'
2015-12-30 15:35:58 DEBUG    SHOWQUEUE-ADD :: Traceback (most recent call last):
  File "/Users/XxUnkn0wnxX/Apps/SickRage/sickbeard/show_queue.py", line 438, in run
    self.show.loadEpisodesFromDir()
  File "/Users/XxUnkn0wnxX/Apps/SickRage/sickbeard/tv.py", line 410, in loadEpisodesFromDir
    mediaFiles = helpers.listMediaFiles(self._location)
  File "/Users/XxUnkn0wnxX/Apps/SickRage/sickbeard/helpers.py", line 327, in listMediaFiles
    for curFile in ek(os.listdir, path):
  File "/Users/XxUnkn0wnxX/Apps/SickRage/sickrage/helper/encoding.py", line 40, in ek
    result = function(*[ss(x) if isinstance(x, (str, unicode)) else x for x in args], **kwargs)
OSError: [Errno 13] Permission denied: '/Volumes/Media/TV Shows/Colony'
```

when ever i add a new show from now it creates a folder with read only permissions, i would say this is a serious issue

![image](http://i.imgur.com/bVOHKAv.png)

Full Log: https://gist.github.com/XxUnkn0wnxX/3d2101ad472f9316ec21

**Comment by SickRage2** [comment]
Thanks for the issue report! Before a real human comes by, please make sure your report has all the below criteria checked

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [x] Post debug logs, either inline (for smaller logs) or using gist)
- [x] Please wrap inline logs inside \`\`\` and \`\`\` for readability

Please make sure you also read [how to create an issue](https://github.com/SickRage/sickrage-issues/blob/master/README.md) and followed all of the steps. 

The title should describe your issue. Having "SR not working" or "I get this bug" for 100 issues, isn't really helpful. We will close issues if there isn't enough information.

Sometimes the devs may seem like grunts and respond with short answers. This isn't (always) because the dev hates you, but because he's on mobile or busy fixing bugs. If something isn't clear, please let us know, and this bot may get updated to automatically answer you.

Thanks!

**Comment by labrys** [comment]
Sounds like SickRage may have been run with wrong user such as root.  Check permissions and try again to see if you can reproduce.

**Comment by XxUnkn0wnxX** [comment]
i have always ran SR via this:

#!/usr/local/bin/bash
source ~/.bash_profile
python ~/"Apps/SickRage/SickBeard.py" -d &

i have also manually re-launched SR VIA Terminal under my username and i still got the same issue

**Comment by XxUnkn0wnxX** [comment]
I believe this issue is closed:

i noticed this when it was creating the folder: 

```
2015-12-30 15:25:53 DEBUG    Thread-26 :: Setting permissions for /Volumes/Media/TV Shows/Colony to 55 as parent directory has 55
```

i think my TV Shows Folder initial perms where thrown off..

so i did chown -R myusername:admin */* to all file on my media drive & chmod -R 755 */* to all files and folders on my media drive as well as the SR direcotry
