### ISSUE TITLE
[APP SUBMITTED]: This show is already queued to be removed

### ISSUE THREAD

**Issue by gijosh28** [SickRage/sickrage-issues#375]
### INFO
Python Version: **2.7.3 (default, Dec  8 2014, 06:18:26) [GCC 4.8.2 20131014 (prerelease)]**
Operating System: **Linux-3.10.20-al-2.5.3_sa-armv7l-with-glibc2.4**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@4423fe95002315b812b4ef9867ea6df7d94c2083
No Log available with ERRORS: 
### ERROR
```
Thread-41 :: Failed doing webui callback: Traceback (most recent call last):
  File "/share/CACHEDEV1_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/sickbeard/webserve.py", line 271, in async_call
    result = function(**kwargs)
  File "/share/CACHEDEV1_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/sickbeard/webserve.py", line 3419, in massUpdate
    sickbeard.showQueueScheduler.action.removeShow(showObj)
  File "/share/CACHEDEV1_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/sickbeard/show_queue.py", line 159, in removeShow
    raise CantRemoveShowException("This show is already queued to be removed")
CantRemoveShowException: This show is already queued to be removed
 [4423fe9]
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by SickRage2** [comment]
Thanks for the issue report! Before a real human comes by, please make sure your report has all the below criteria checked

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [ ] Post debug logs, either inline (for smaller logs) or using gist)

Please make sure you also read [how to create an issue](https://github.com/SickRage/sickrage-issues/blob/master/README.md) and followed all of the steps. 

The title should describe your issue. Having "SR not working" or "I get this bug" for 100 issues, isn't really helpful. We will close issues if there isn't enough information.

Sometimes the devs may seem like grunts and respond with short answers. This isn't (always) because the dev hates you, but because he's on mobile or busy fixing bugs. If something isn't clear, please let us know, and this bot may get updated to automatically answer you.

Thanks!
