### ISSUE TITLE
[APP SUBMITTED]: setHomeLayout() takes exactly 2 arguments (1 given)

### ISSUE THREAD

**Issue by neoatomic** [SickRage/sickrage-issues#379]
### INFO
Python Version: **2.7.11 (default, Dec 17 2015, 15:58:38) [GCC 4.7.3 20130102 (prerelease)]**
Operating System: **Linux-3.10.35-x86_64-with-glibc2.2.5**
Locale: unknown
Branch: **develop**
Commit: SickRage/SickRage@716e564c1909eb91a5e1bbbe82ca90a8b2c3d748
No Log available with ERRORS: 
### ERROR
```
Thread-23 :: Failed doing webui callback: Traceback (most recent call last):
  File "/volume1/@appstore/sickrage/var/SickRage/sickbeard/webserve.py", line 271, in async_call
    result = function(**kwargs)
TypeError: setHomeLayout() takes exactly 2 arguments (1 given)
 [716e564]
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators 

```
2016-01-01 18:32:50 ERROR    Thread-27 :: Failed doing webui callback: Traceback (most recent call last):
  File "/volume1/@appstore/sickrage/var/SickRage/sickbeard/webserve.py", line 271, in async_call
    result = function(**kwargs)
TypeError: setHomeLayout() takes exactly 2 arguments (1 given)
 [716e564]
Traceback (most recent call last):
  File "/volume1/@appstore/sickrage/var/SickRage/sickbeard/webserve.py", line 271, in async_call
    result = function(**kwargs)
TypeError: setHomeLayout() takes exactly 2 arguments (1 given)
2016-01-01 18:32:50 DEBUG    TORNADO :: Failed doing webui request "setHomeLayout": Traceback (most recent call last):
  File "/volume1/@appstore/sickrage/var/SickRage/sickbeard/webserve.py", line 256, in get
    results = yield self.async_call(method)
  File "/usr/local/sickrage/var/SickRage/lib/tornado/gen.py", line 870, in run
    value = future.result()
  File "/usr/local/sickrage/var/SickRage/lib/concurrent/futures/_base.py", line 400, in result
    return self.__get_result()
  File "/usr/local/sickrage/var/SickRage/lib/concurrent/futures/_base.py", line 359, in __get_result
    reraise(self._exception, self._traceback)
  File "/usr/local/sickrage/var/SickRage/lib/concurrent/futures/_compat.py", line 107, in reraise
    exec('raise exc_type, exc_value, traceback', {}, locals_)
  File "/usr/local/sickrage/var/SickRage/lib/concurrent/futures/thread.py", line 61, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/volume1/@appstore/sickrage/var/SickRage/sickbeard/webserve.py", line 271, in async_call
    result = function(**kwargs)
TypeError: setHomeLayout() takes exactly 2 arguments (1 given)
```

**Comment by SickRage2** [comment]
Thanks for the issue report! Before a real human comes by, please make sure your report has all the below criteria checked

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [ ] Post debug logs, either inline (for smaller logs) or using gist)

Please make sure you also read [how to create an issue](https://github.com/SickRage/sickrage-issues/blob/master/README.md) and followed all of the steps. 

The title should describe your issue. Having "SR not working" or "I get this bug" for 100 issues, isn't really helpful. We will close issues if there isn't enough information.

Sometimes the devs may seem like grunts and respond with short answers. This isn't (always) because the dev hates you, but because he's on mobile or busy fixing bugs. If something isn't clear, please let us know, and this bot may get updated to automatically answer you.

Thanks!

**Comment by neoatomic** [comment]
### INFO
Python Version: **2.7.11 (default, Dec 17 2015, 15:58:38) [GCC 4.7.3 20130102 (prerelease)]**
Operating System: **Linux-3.10.35-x86_64-with-glibc2.2.5**
Locale: unknown
Branch: **develop**
Commit: SickRage/SickRage@716e564c1909eb91a5e1bbbe82ca90a8b2c3d748
No Log available with ERRORS: 
### ERROR
```
Thread-17 :: Failed doing webui callback: Traceback (most recent call last):
  File "/volume1/@appstore/sickrage/var/SickRage/sickbeard/webserve.py", line 271, in async_call
    result = function(**kwargs)
TypeError: setHomeLayout() takes exactly 2 arguments (1 given)
 [716e564]
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by neoatomic** [comment]
### INFO
Python Version: **2.7.11 (default, Dec 17 2015, 15:58:38) [GCC 4.7.3 20130102 (prerelease)]**
Operating System: **Linux-3.10.35-x86_64-with-glibc2.2.5**
Locale: unknown
Branch: **develop**
Commit: SickRage/SickRage@716e564c1909eb91a5e1bbbe82ca90a8b2c3d748
No Log available with ERRORS: 
### ERROR
```
Thread-19 :: Failed doing webui callback: Traceback (most recent call last):
  File "/volume1/@appstore/sickrage/var/SickRage/sickbeard/webserve.py", line 271, in async_call
    result = function(**kwargs)
TypeError: setHomeLayout() takes exactly 2 arguments (1 given)
 [716e564]
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by neoatomic** [comment]
### INFO
Python Version: **2.7.11 (default, Dec 17 2015, 15:58:38) [GCC 4.7.3 20130102 (prerelease)]**
Operating System: **Linux-3.10.35-x86_64-with-glibc2.2.5**
Locale: unknown
Branch: **develop**
Commit: SickRage/SickRage@716e564c1909eb91a5e1bbbe82ca90a8b2c3d748
No Log available with ERRORS: 
### ERROR
```
Thread-57 :: Failed doing webui callback: Traceback (most recent call last):
  File "/volume1/@appstore/sickrage/var/SickRage/sickbeard/webserve.py", line 271, in async_call
    result = function(**kwargs)
TypeError: setHomeLayout() takes exactly 2 arguments (1 given)
 [716e564]
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by neoatomic** [comment]
### INFO
Python Version: **2.7.11 (default, Dec 17 2015, 15:58:38) [GCC 4.7.3 20130102 (prerelease)]**
Operating System: **Linux-3.10.35-x86_64-with-glibc2.2.5**
Locale: unknown
Branch: **develop**
Commit: SickRage/SickRage@716e564c1909eb91a5e1bbbe82ca90a8b2c3d748
No Log available with ERRORS: 
### ERROR
```
Thread-35 :: Failed doing webui callback: Traceback (most recent call last):
  File "/volume1/@appstore/sickrage/var/SickRage/sickbeard/webserve.py", line 271, in async_call
    result = function(**kwargs)
TypeError: setHomeLayout() takes exactly 2 arguments (1 given)
 [716e564]
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by neoatomic** [comment]
### INFO
Python Version: **2.7.11 (default, Dec 17 2015, 15:58:38) [GCC 4.7.3 20130102 (prerelease)]**
Operating System: **Linux-3.10.35-x86_64-with-glibc2.2.5**
Locale: unknown
Branch: **develop**
Commit: SickRage/SickRage@716e564c1909eb91a5e1bbbe82ca90a8b2c3d748
No Log available with ERRORS: 
### ERROR
```
Thread-29 :: Failed doing webui callback: Traceback (most recent call last):
  File "/volume1/@appstore/sickrage/var/SickRage/sickbeard/webserve.py", line 271, in async_call
    result = function(**kwargs)
TypeError: setHomeLayout() takes exactly 2 arguments (1 given)
 [716e564]
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by neoatomic** [comment]
### INFO
Python Version: **2.7.11 (default, Dec 17 2015, 15:58:38) [GCC 4.7.3 20130102 (prerelease)]**
Operating System: **Linux-3.10.35-x86_64-with-glibc2.2.5**
Locale: unknown
Branch: **develop**
Commit: SickRage/SickRage@716e564c1909eb91a5e1bbbe82ca90a8b2c3d748
No Log available with ERRORS: 
### ERROR
```
Thread-40 :: Failed doing webui callback: Traceback (most recent call last):
  File "/volume1/@appstore/sickrage/var/SickRage/sickbeard/webserve.py", line 271, in async_call
    result = function(**kwargs)
TypeError: setHomeLayout() takes exactly 2 arguments (1 given)
 [716e564]
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by neoatomic** [comment]
### INFO
Python Version: **2.7.11 (default, Dec 17 2015, 15:58:38) [GCC 4.7.3 20130102 (prerelease)]**
Operating System: **Linux-3.10.35-x86_64-with-glibc2.2.5**
Locale: unknown
Branch: **develop**
Commit: SickRage/SickRage@716e564c1909eb91a5e1bbbe82ca90a8b2c3d748
No Log available with ERRORS: 
### ERROR
```
Thread-27 :: Failed doing webui callback: Traceback (most recent call last):
  File "/volume1/@appstore/sickrage/var/SickRage/sickbeard/webserve.py", line 271, in async_call
    result = function(**kwargs)
TypeError: setHomeLayout() takes exactly 2 arguments (1 given)
 [716e564]
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by neoatomic** [comment]
Happens when switching between the Banner and simple view. (dark theme)

**Comment by miigotu** [comment]
idk what could cause that for you. The code is ok and it works here.
