### ISSUE TITLE
[APP SUBMITTED]: addShowByID() got an unexpected keyword argument ' Hyde'

### ISSUE THREAD

**Issue by rmilyard** [SickRage/sickrage-issues#380]
### INFO
Python Version: **2.7.9 (default, Sep  9 2015, 14:50:03) [GCC 4.2.1 20070831 patched [FreeBSD]]**
Operating System: **FreeBSD-9.1-RELEASE-amd64-64bit-ELF**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@4423fe95002315b812b4ef9867ea6df7d94c2083
No Log available with ERRORS: 
### ERROR
```
Thread-41 :: Failed doing webui callback: Traceback (most recent call last):
  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/sickbeard/webserve.py", line 271, in async_call
    result = function(**kwargs)
TypeError: addShowByID() got an unexpected keyword argument ' Hyde'
 [4423fe9]
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by SickRage2** [comment]
Thanks for the issue report! Before a real human comes by, please make sure your report has all the below criteria checked

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [ ] Post debug logs, either inline (for smaller logs) or using gist)

Please make sure you also read [how to create an issue](https://github.com/SickRage/sickrage-issues/blob/master/README.md) and followed all of the steps. 

The title should describe your issue. Having "SR not working" or "I get this bug" for 100 issues, isn't really helpful. We will close issues if there isn't enough information.

Sometimes the devs may seem like grunts and respond with short answers. This isn't (always) because the dev hates you, but because he's on mobile or busy fixing bugs. If something isn't clear, please let us know, and this bot may get updated to automatically answer you.

Thanks!

**Comment by crow50** [comment]
### INFO
Python Version: **2.7.9 (default, Sep  9 2015, 14:50:03) [GCC 4.2.1 20070831 patched [FreeBSD]]**
Operating System: **FreeBSD-9.1-RELEASE-amd64-64bit-ELF**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@4eccee2ad1b3e3d144bfd8e315fdf397cfd33361
No Log available with ERRORS: 
### ERROR
```
Thread-99 :: Failed doing webui callback: Traceback (most recent call last):
  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/sickbeard/webserve.py", line 271, in async_call
    result = function(**kwargs)
TypeError: addShowByID() got an unexpected keyword argument ' Hyde'
 [4eccee2]
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by miigotu** [comment]
Fixed in develop.

**Comment by snapperhead** [comment]
### INFO
Python Version: **2.7.10 (default, Oct 23 2015, 18:05:06) [GCC 4.2.1 Compatible Apple LLVM 7.0.0 (clang-700.0.59.5)]**
Operating System: **Darwin-15.3.0-x86_64-i386-64bit**
Locale: unknown
Branch: **master**
Commit: SickRage/SickRage@7fd6c98aafe1f543bf8f96b2e370666be5412288
No Log available with ERRORS: 
### ERROR
```
Thread-59 :: Failed doing webui callback: Traceback (most recent call last):
  File "/Applications/SickRage/sickbeard/webserve.py", line 271, in async_call
    result = function(**kwargs)
TypeError: addShowByID() got an unexpected keyword argument ' Hyde'
 [7fd6c98]
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators
