### ISSUE TITLE
Sickrage won't start

### ISSUE THREAD

**Issue by Karajorma** [SickRage/sickrage-issues#384]
After an update Sickrage refuses to start. After trying various things, I simply deleted and did a fresh checkout only to have the same issue. 

Checked out Sickrage with the following command 
git clone https://github.com/SickRage/SickRage.git /opt/sickrage

Then ran it using 
python /opt/sickrage/SickBeard.py -d

And I got this error. 

```
Traceback (most recent call last):
  File "/opt/sickrage/SickBeard.py", line 66, in <module>
    import sickbeard
  File "/opt/sickrage/sickbeard/__init__.py", line 36, in <module>
    from sickbeard import metadata
  File "/opt/sickrage/sickbeard/metadata/__init__.py", line 22, in <module>
    from sickbeard.metadata import kodi, kodi_12plus, mediabrowser, ps3, wdtv, tivo, mede8er, generic, helpers
  File "/opt/sickrage/sickbeard/metadata/kodi.py", line 23, in <module>
    from sickbeard.metadata import generic
  File "/opt/sickrage/sickbeard/metadata/generic.py", line 32, in <module>
    from sickbeard import helpers
  File "/opt/sickrage/sickbeard/helpers.py", line 51, in <module>
    from sickbeard import logger, classes
  File "/opt/sickrage/sickbeard/logger.py", line 36, in <module>
    from sickbeard import classes
  File "/opt/sickrage/sickbeard/classes.py", line 29, in <module>
    from sickbeard.common import USER_AGENT, Quality
  File "/opt/sickrage/sickbeard/common.py", line 49, in <module>
    UA_POOL = UserAgent()
  File "/opt/sickrage/lib/fake_useragent/fake.py", line 10, in __init__
    self.data = load_cached()
  File "/opt/sickrage/lib/fake_useragent/utils.py", line 140, in load_cached
    update()
  File "/opt/sickrage/lib/fake_useragent/utils.py", line 135, in update
    write(load())
  File "/opt/sickrage/lib/fake_useragent/utils.py", line 82, in load
    for item in get_browsers():
  File "/opt/sickrage/lib/fake_useragent/utils.py", line 27, in get_browsers
    html = get(settings.BROWSERS_STATS_PAGE)
  File "/opt/sickrage/lib/fake_useragent/utils.py", line 20, in get
    return urlopen(url).read()
  File "/usr/lib/python2.7/urllib.py", line 87, in urlopen
    return opener.open(url)
  File "/usr/lib/python2.7/urllib.py", line 213, in open
    return getattr(self, name)(url)
  File "/usr/lib/python2.7/urllib.py", line 350, in open_http
    h.endheaders(data)
  File "/usr/lib/python2.7/httplib.py", line 997, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python2.7/httplib.py", line 850, in _send_output
    self.send(msg)
  File "/usr/lib/python2.7/httplib.py", line 812, in send
    self.connect()
  File "/usr/lib/python2.7/httplib.py", line 793, in connect
    self.timeout, self.source_address)
  File "/usr/lib/python2.7/socket.py", line 571, in create_connection
    raise err
```

I'm using bananian 15.08 last commit is 574b10cabac92e5524ed3f35abd4e621542838e7 
Since SickRage won't actually run, I have no log to attach.

**Comment by SickRage2** [comment]
Thanks for the issue report! Before a real human comes by, please make sure your report has all the below criteria checked

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [ ] Post debug logs, either inline (for smaller logs) or using gist)

Please make sure you also read [how to create an issue](https://github.com/SickRage/sickrage-issues/blob/master/README.md) and followed all of the steps. 

The title should describe your issue. Having "SR not working" or "I get this bug" for 100 issues, isn't really helpful. We will close issues if there isn't enough information.

Sometimes the devs may seem like grunts and respond with short answers. This isn't (always) because the dev hates you, but because he's on mobile or busy fixing bugs. If something isn't clear, please let us know, and this bot may get updated to automatically answer you.

Thanks!

**Comment by labrys** [comment]
@Karajorma what commit and what OS?

**Comment by labrys** [comment]
nvm see it now.. please wrap your logs in \`\`\` so its easier too read.

**Comment by neoatomic** [comment]
All seems to be working fine here.

You removed the previous install completely.? 
And did you restore the backup on the new install, or started completely fresh install with new config.ini & sickbeard.db.? 
I'm thinking you might have run sickrage/git with different/wrong users.? (permission probs.?)

**Comment by miigotu** [comment]
Problem is your firewall (likely pfsense?) blocking the connection to www.w3schools.com or http://useragentstring.com/

Disabling the firewall or blocklist for the first startup and it will start, and then the firewall/blocklist can be re-enabled and stay that way. #316

**Comment by tmm0f5** [comment]
Hello all, i'm on a Win7 machine with python 2.7.  The last SickRage update has caused this exact problem.  I don't run pfsense as a firewall.  Any thoughts on how I can get back up and running?  I tried the fixes above (turning off firewall, etc.) with no success.  Thanks.

**Comment by Karajorma** [comment]
https://github.com/SickRage/sickrage-issues/issues/394

Use the ua.json from that page to get things working.

**Comment by tmm0f5** [comment]
I had tried placing that file in folder described above with no 
success.  Unfortunately I had then tried a Git-Reset and it wiped my 
SickRage settings.   I have to play around with it some more.  It's 
really unfortunate as everything was working so smoothly.   Thanks for 
your help.

**Comment by fernandog** [comment]
@tmm0f5 
after place that file in the folder, check if permissions are ok so SR can see it

**Comment by miigotu** [comment]
@tmm0f5 I dont think you are running the SR from this repo. Can you check `git remote show origin | grep URL`  and verify it shows 'https://github.com/SickRage/SickRage.git` and not SiCKRAGETV ?

**Comment by tmm0f5** [comment]
You were right.  I was on SickRageTV.  Ita all fixed and running.  Thanks
for your help.

Tim
