### ISSUE TITLE
Cannot Start my SickRage after last release

### ISSUE THREAD

**Issue by carlosgblos** [SickRage/sickrage-issues#394]
I have an Arm7 computer (odroid) running the Sickrage. It was working until the last changes (the ones where was released the Archive First Match was disabled. I don't know if this information is relevant, but I live in china, and maybe it is not possible to connect due to the great wall (firewall).

follow the message showing when I try to start. I have no idea how to get more information to help you find the problem. I hope it is enough.

```
Starting SickRage
Traceback (most recent call last):
  File "SickBeard.py", line 66, in <module>
    import sickbeard
  File "/opt/sickrage/sickbeard/__init__.py", line 36, in <module>
    from sickbeard import metadata
  File "/opt/sickrage/sickbeard/metadata/__init__.py", line 22, in <module>
    from sickbeard.metadata import kodi, kodi_12plus, mediabrowser, ps3, wdtv, tivo, mede8er, generic, helpers
  File "/opt/sickrage/sickbeard/metadata/kodi.py", line 23, in <module>
    from sickbeard.metadata import generic
  File "/opt/sickrage/sickbeard/metadata/generic.py", line 32, in <module>
    from sickbeard import helpers
  File "/opt/sickrage/sickbeard/helpers.py", line 51, in <module>
    from sickbeard import logger, classes
  File "/opt/sickrage/sickbeard/logger.py", line 36, in <module>
    from sickbeard import classes
  File "/opt/sickrage/sickbeard/classes.py", line 29, in <module>
    from sickbeard.common import USER_AGENT, Quality
  File "/opt/sickrage/sickbeard/common.py", line 49, in <module>
    UA_POOL = UserAgent()
  File "/opt/sickrage/lib/fake_useragent/fake.py", line 10, in __init__
    self.data = load_cached()
  File "/opt/sickrage/lib/fake_useragent/utils.py", line 140, in load_cached
    update()
  File "/opt/sickrage/lib/fake_useragent/utils.py", line 135, in update
    write(load())
  File "/opt/sickrage/lib/fake_useragent/utils.py", line 82, in load
    for item in get_browsers():
  File "/opt/sickrage/lib/fake_useragent/utils.py", line 27, in get_browsers
    html = get(settings.BROWSERS_STATS_PAGE)
  File "/opt/sickrage/lib/fake_useragent/utils.py", line 20, in get
    return urlopen(url).read()
  File "/usr/lib/python2.7/urllib.py", line 87, in urlopen
    return opener.open(url)
  File "/usr/lib/python2.7/urllib.py", line 208, in open
    return getattr(self, name)(url)
  File "/usr/lib/python2.7/urllib.py", line 345, in open_http
    h.endheaders(data)
  File "/usr/lib/python2.7/httplib.py", line 975, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python2.7/httplib.py", line 835, in _send_output
    self.send(msg)
  File "/usr/lib/python2.7/httplib.py", line 797, in send
    self.connect()
  File "/usr/lib/python2.7/httplib.py", line 778, in connect
    self.timeout, self.source_address)
  File "/usr/lib/python2.7/socket.py", line 571, in create_connection
    raise err
IOError: [Errno socket error] [Errno 110] Connection timed out
```

Thanks

**Comment by SickRage2** [comment]
Thanks for the issue report! Before a real human comes by, please make sure your report has all the below criteria checked

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [ ] Post debug logs, either inline (for smaller logs) or using gist)

Please make sure you also read [how to create an issue](https://github.com/SickRage/sickrage-issues/blob/master/README.md) and followed all of the steps. 

The title should describe your issue. Having "SR not working" or "I get this bug" for 100 issues, isn't really helpful. We will close issues if there isn't enough information.

Sometimes the devs may seem like grunts and respond with short answers. This isn't (always) because the dev hates you, but because he's on mobile or busy fixing bugs. If something isn't clear, please let us know, and this bot may get updated to automatically answer you.

Thanks!

**Comment by miigotu** [comment]
Problem is your firewall (likely pfsense?) blocking the connection to www.w3schools.com or http://useragentstring.com/

Disabling the firewall or blocklist for the first startup and it will start, and then the firewall/blocklist can be re-enabled and stay that way. #316

**Comment by carlosgblos** [comment]
I'm not at china right now. But I just ran a traceroute on www.w3schools.com, and it seems to be blocked. Not by my firewall, but china's firewall.
As soon as I arrive home, I will restart my modem (because I was able to restart my pfsense remotely).

Thanks for your prompt response.

**Comment by Karajorma** [comment]
I'm also in China and having the exact same problem. I'm pretty sure it's blocked.

**Comment by Karajorma** [comment]
Actually, while we're trying to solve this, can you just post a ua.json file we can use in the meanwhile? Right now I can't use SickRage at all.

**Comment by labrys** [comment]
@carlosgblos Please post all required information in the future, such as commit hash.

**Comment by miigotu** [comment]
https://gist.githubusercontent.com/miigotu/99384743b07adf1e4651/raw/656a4de21d4ebe560dd531a54b001584817622a9/ua.json

Save that as SickRage/lib/fake_useragent/ua.json
I did pretty-format that so I hope it works, if not I can paste one that doesnt have line breaks.

**Comment by carlosgblos** [comment]
Now it started. Seems to be working. Thanks so much

**Comment by Karajorma** [comment]
I posted my details on Issue #384. But the bug seems to be that if a certain website is unreachable then Sickrage fails to start. The fake-useragent lib should exit gracefully in those cases, perhaps falling back to a .json file in the repo.

**Comment by miigotu** [comment]
@Karajorma no shit, the lib just got added, and there were other issues that effected more users than a few pfsense users. This problem is a one time thing.

By the next release it should catch and default back to a pregenerated version.

**Comment by Karajorma** [comment]
Yeah, I was just kinda surprised that the library had such a big flaw in it given that according to the python package index it has been around for over 3 months. Maybe Sickrage is the first major project to use it.
