### ISSUE TITLE
Unicode Decode Error

### ISSUE THREAD

**Issue by jaxxstorm** [SickRage/sickrage-issues#400]
Error is `UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 30: ordinal not in range(128)`

```
                </tr>
205
                % endif
206
207
                <tr><td class="showLegend">Size:</td><td>${sickbeard.helpers.pretty_filesize(sickbeard.helpers.get_size(showLoc[0]))}</td></tr>
208
209
                </table>
210
211
                <table style="width:180px; float: right; vertical-align: middle; height: 100%;">
212
                    <% info_flag = subtitles.fromietf(show.lang).opensubtitles if show.lang else '' %>
```

Log entry:

```
2016-01-03 11:47:13 DEBUG::TORNADO::Failed doing webui callback [/home/displayShow?show=121361]: Traceback (most recent call last):
  File "/opt/sickrage/sickbeard/webserve.py", line 221, in async_call
    return function(**kwargs)
  File "/opt/sickrage/sickbeard/webserve.py", line 1268, in displayShow
    title=showObj.name
  File "/opt/sickrage/sickbeard/webserve.py", line 194, in render
    return self.render_string(template_name, **kwargs)
  File "/opt/sickrage/sickbeard/webserve.py", line 191, in render_string
    return self.mako_lookup.get_template(template_name).render_unicode(**template_kwargs)
  File "/opt/sickrage/lib/mako/template.py", line 454, in render_unicode
    as_unicode=True)
  File "/opt/sickrage/lib/mako/runtime.py", line 829, in _render
    **_kwargs_for_callable(callable_, data))
  File "/opt/sickrage/lib/mako/runtime.py", line 864, in _render_context
    _exec_template(inherit, lclcontext, args=args, kwargs=kwargs)
  File "/opt/sickrage/lib/mako/runtime.py", line 890, in _exec_template
    callable_(context, *args, **kwargs)
  File "/opt/sickrage/data/cache/mako/layouts/main.mako.py", line 480, in render_body
    context['self'].content(**pageargs)
  File "/opt/sickrage/data/cache/mako/displayShow.mako.py", line 607, in render_content
    __M_writer(unicode(sickbeard.helpers.pretty_filesize(sickbeard.helpers.get_size(showLoc[0]))))
  File "/opt/sickrage/sickbeard/helpers.py", line 1764, in get_size
    for dirpath, _, filenames in ek(os.walk, start_path):
  File "/usr/lib64/python2.7/os.py", line 294, in walk
    for x in walk(new_path, topdown, onerror, followlinks):
  File "/usr/lib64/python2.7/os.py", line 284, in walk
    if isdir(join(top, name)):
  File "/usr/lib64/python2.7/posixpath.py", line 80, in join
    path += '/' + b
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 30: ordinal not in range(128)
```

This happens when clicking on a show, in particular game of thrones.

**Comment by SickRage2** [comment]
Thanks for the issue report! Before a real human comes by, please make sure your report has all the below criteria checked

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [ ] Post debug logs, either inline (for smaller logs) or using gist)

Please make sure you also read [how to create an issue](https://github.com/SickRage/sickrage-issues/blob/master/README.md) and followed all of the steps. 

The title should describe your issue. Having "SR not working" or "I get this bug" for 100 issues, isn't really helpful. We will close issues if there isn't enough information.

Sometimes the devs may seem like grunts and respond with short answers. This isn't (always) because the dev hates you, but because he's on mobile or busy fixing bugs. If something isn't clear, please let us know, and this bot may get updated to automatically answer you.

Thanks!

**Comment by medariox** [comment]
```
Please include the following when opening a ticket :

Branch
Commit hash
Your operating system and python version
What you did
What happened
What you expected
How can we reproduce your issue
Include a link with your FULL(Not just a few lines!) log file that has the error. Please use GIST or Pastebin
```

Also please make sure that your [locale is set correctly](https://github.com/SiCKRAGE/sickrage-issues/wiki/FAQ%27s-and-Fixes#i-have-problems-with-special-characters-%C3%A9-etc-what-can-i-do).
```
If you have a 'ascii' codec can't encode character error, than set your Locale to UTF-8
```

**Comment by miigotu** [comment]
@jaxxstorm you are using the old SiCKRAGTV fork, so ofc you would get the errors.

You would need to switch to this for to get any support here (aka you need to be using our code for your reports to be valid here).
