### ISSUE TITLE
[APP SUBMITTED]: 403 {u'documentation_url': u'https://help.github.com/articles/adding-an-email-address-to-your-github-account', u'message': u'At least one email address must be verified to do that.'}

### ISSUE THREAD

**Issue by rpillala** [SickRage/sickrage-issues#401]
### INFO
Python Version: **2.7.9 (default, Sep  9 2015, 14:50:03) [GCC 4.2.1 20070831 patched [FreeBSD]]**
Operating System: **FreeBSD-9.1-RELEASE-amd64-64bit-ELF**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@
Link to Log: https://gist.github.com/eb3281762e7ba7e7f615
### ERROR
```
Thread-55 :: Traceback (most recent call last):
  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/sickbeard/logger.py", line 297, in submit_errors
    if report.create_comment(message):
  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/lib/github/Issue.py", line 247, in create_comment
    input=post_parameters
  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/lib/github/Requester.py", line 171, in requestJsonAndCheck
    return self.__check(*self.requestJson(verb, url, parameters, headers, input, cnx))
  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/lib/github/Requester.py", line 179, in __check
    raise self.__createException(status, responseHeaders, output)
GithubException: 403 {u'documentation_url': u'https://help.github.com/articles/adding-an-email-address-to-your-github-account', u'message': u'At least one email address must be verified to do that.'}

```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by SickRage2** [comment]
Thanks for the issue report! Before a real human comes by, please make sure your report has all the below criteria checked

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [x] Post debug logs, either inline (for smaller logs) or using gist)

Please make sure you also read [how to create an issue](https://github.com/SickRage/sickrage-issues/blob/master/README.md) and followed all of the steps. 

The title should describe your issue. Having "SR not working" or "I get this bug" for 100 issues, isn't really helpful. We will close issues if there isn't enough information.

Sometimes the devs may seem like grunts and respond with short answers. This isn't (always) because the dev hates you, but because he's on mobile or busy fixing bugs. If something isn't clear, please let us know, and this bot may get updated to automatically answer you.

Thanks!

**Comment by labrys** [comment]
@rpillala You are on the old repository.  If you need assistance switching please let us know.

**Comment by Classified711** [comment]
### INFO
Python Version: **2.7.10 (default, May 23 2015, 09:44:00) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-8-6.2.9200**
Locale: cp1252
Branch: **master**
Commit: SickRage/SickRage@7fd6c98aafe1f543bf8f96b2e370666be5412288
No Log available with ERRORS: 
### ERROR
```
Thread-25 :: Traceback (most recent call last):
  File "C:\SickRage\SickRage\sickbeard\logger.py", line 304, in submit_errors
    if report.create_comment(message):
  File "C:\SickRage\SickRage\lib\github\Issue.py", line 247, in create_comment
    input=post_parameters
  File "C:\SickRage\SickRage\lib\github\Requester.py", line 171, in requestJsonAndCheck
    return self.__check(*self.requestJson(verb, url, parameters, headers, input, cnx))
  File "C:\SickRage\SickRage\lib\github\Requester.py", line 179, in __check
    raise self.__createException(status, responseHeaders, output)
GithubException: 403 {u'documentation_url': u'https://help.github.com/articles/adding-an-email-address-to-your-github-account', u'message': u'At least one email address must be verified to do that.'}
 [7fd6c98]
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by luigose** [comment]
### INFO
Python Version: **2.7.11 (default, Jan  9 2016, 16:55:40) [GCC 4.8.5]**
Operating System: **Linux-3.12.6-x86_64-with-glibc2.2.5**
Locale: None
Branch: **master**
Commit: SickRage/SickRage@5d51b1687edf252958317c8cbb110069d7b207b3
No Log available with ERRORS:
### ERROR
```
Thread-56 :: Traceback (most recent call last):
  File "/share/CACHEDEV1_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/sickbeard/logger.py", line 348, in submit_errors
    if report.create_comment(message):
  File "/share/CACHEDEV1_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/lib/github/Issue.py", line 247, in create_comment
    input=post_parameters
  File "/share/CACHEDEV1_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/lib/github/Requester.py", line 171, in requestJsonAndCheck
    return self.__check(*self.requestJson(verb, url, parameters, headers, input, cnx))
  File "/share/CACHEDEV1_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/lib/github/Requester.py", line 179, in __check
    raise self.__createException(status, responseHeaders, output)
GithubException: 403 {u'documentation_url': u'https://help.github.com/articles/adding-an-email-address-to-your-github-account', u'message': u'At least one email address must be verified to do that.'}
 [5d51b16]
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by porkchop34** [comment]
### INFO
Python Version: **2.7.11 (v2.7.11:6d1b6a68f775, Dec  5 2015, 20:40:30) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-7-6.1.7601-SP1**
Locale: cp1252
Branch: **master**
Commit: SickRage/SickRage@7a94dd094c2861d54f500c39af5fb2cdb856dfdc
No Log available with ERRORS:
### ERROR
```
Thread-29 :: Traceback (most recent call last):
  File "C:\SickRage\sickbeard\logger.py", line 359, in submit_errors
    issue = git.get_organization(gh_org).get_repo(gh_repo).create_issue(title_error, message)
  File "C:\SickRage\lib\github\Repository.py", line 885, in create_issue
    input=post_parameters
  File "C:\SickRage\lib\github\Requester.py", line 171, in requestJsonAndCheck
    return self.__check(*self.requestJson(verb, url, parameters, headers, input, cnx))
  File "C:\SickRage\lib\github\Requester.py", line 179, in __check
    raise self.__createException(status, responseHeaders, output)
GithubException: 403 {u'documentation_url': u'https://help.github.com/articles/adding-an-email-address-to-your-github-account', u'message': u'At least one email address must be verified to do that.'}
 [7a94dd0]
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by ozmutley** [comment]
### INFO
Python Version: **2.7.9 (default, Dec 10 2014, 12:28:03) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-2008ServerR2-6.1.7601-SP1**
Locale: cp1252
Branch: **master**
Commit: SickRage/SickRage@cd3834f8c2674006701e9d5c7e376f66a3d15a2a
No Log available with ERRORS:
### ERROR
```
Thread-36 :: Traceback (most recent call last):
  File "C:\SickRage\sickbeard\logger.py", line 359, in submit_errors
    issue = git.get_organization(gh_org).get_repo(gh_repo).create_issue(title_error, message)
  File "C:\SickRage\lib\github\Repository.py", line 885, in create_issue
    input=post_parameters
  File "C:\SickRage\lib\github\Requester.py", line 171, in requestJsonAndCheck
    return self.__check(*self.requestJson(verb, url, parameters, headers, input, cnx))
  File "C:\SickRage\lib\github\Requester.py", line 179, in __check
    raise self.__createException(status, responseHeaders, output)
GithubException: 403 {u'documentation_url': u'https://help.github.com/articles/adding-an-email-address-to-your-github-account', u'message': u'At least one email address must be verified to do that.'}
 [cd3834f]
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by ncfitzge** [comment]
### INFO
Python Version: **2.7.11 (default, Jan  9 2016, 16:55:40) [GCC 4.8.5]**
Operating System: **Linux-3.12.6-x86_64-with-glibc2.2.5**
Locale: None
Branch: **master**
Commit: SickRage/SickRage@820b900a6dc72ed4958a90ac027d8f92d785810b
No Log available with ERRORS:
### ERROR
```
Thread-20 :: Traceback (most recent call last):
  File "/share/CACHEDEV1_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/sickbeard/logger.py", line 359, in submit_errors
    issue = git.get_organization(gh_org).get_repo(gh_repo).create_issue(title_error, message)
  File "/share/CACHEDEV1_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/lib/github/Repository.py", line 885, in create_issue
    input=post_parameters
  File "/share/CACHEDEV1_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/lib/github/Requester.py", line 171, in requestJsonAndCheck
    return self.__check(*self.requestJson(verb, url, parameters, headers, input, cnx))
  File "/share/CACHEDEV1_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/lib/github/Requester.py", line 179, in __check
    raise self.__createException(status, responseHeaders, output)
GithubException: 403 {u'documentation_url': u'https://help.github.com/articles/adding-an-email-address-to-your-github-account', u'message': u'At least one email address must be verified to do that.'}
 [820b900]
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by darkh89** [comment]
### INFO
Python Version: **2.7.5 (default, Nov 20 2015, 02:00:19) [GCC 4.8.5 20150623 (Red Hat 4.8.5-4)]**
Operating System: **Linux-3.10.0-327.4.5.el7.x86_64-x86_64-with-centos-7.2.1511-Core**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@820b900a6dc72ed4958a90ac027d8f92d785810b
No Log available with ERRORS:
### ERROR
```
Thread-19 :: Traceback (most recent call last):
  File "/apps/sickrage/sickbeard/logger.py", line 359, in submit_errors
    issue = git.get_organization(gh_org).get_repo(gh_repo).create_issue(title_error, message)
  File "/apps/sickrage/lib/github/Repository.py", line 885, in create_issue
    input=post_parameters
  File "/apps/sickrage/lib/github/Requester.py", line 171, in requestJsonAndCheck
    return self.__check(*self.requestJson(verb, url, parameters, headers, input, cnx))
  File "/apps/sickrage/lib/github/Requester.py", line 179, in __check
    raise self.__createException(status, responseHeaders, output)
GithubException: 403 {u'documentation_url': u'https://help.github.com/articles/adding-an-email-address-to-your-github-account', u'message': u'At least one email address must be verified to do that.'}
 [820b900]
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators
