### ISSUE TITLE
[APP SUBMITTED]: ('The read operation timed out',)

### ISSUE THREAD

**Issue by StretchCell** [SickRage/sickrage-issues#422]
### INFO
Python Version: **2.7.10 (default, May 23 2015, 09:44:00) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-8-6.2.9200**
Locale: cp1252
Branch: **master**
Commit: SickRage/SickRage@4eccee2ad1b3e3d144bfd8e315fdf397cfd33361
No Log available with ERRORS: 
### ERROR
```
Thread-59 :: Traceback (most recent call last):
  File "C:\SickRage\SickRage\sickbeard\logger.py", line 282, in submit_errors
    reports = gh.get_organization(gh_org).get_repo(gh_repo).get_issues(state="all")
  File "C:\SickRage\SickRage\lib\github\Organization.py", line 518, in get_repo
    "/repos/" + self.login + "/" + name
  File "C:\SickRage\SickRage\lib\github\Requester.py", line 171, in requestJsonAndCheck
    return self.__check(*self.requestJson(verb, url, parameters, headers, input, cnx))
  File "C:\SickRage\SickRage\lib\github\Requester.py", line 212, in requestJson
    return self.__requestEncode(cnx, verb, url, parameters, headers, input, encode)
  File "C:\SickRage\SickRage\lib\github\Requester.py", line 251, in __requestEncode
    status, responseHeaders, output = self.__requestRaw(cnx, verb, url, requestHeaders, encoded_input)
  File "C:\SickRage\SickRage\lib\github\Requester.py", line 281, in __requestRaw
    output = response.read()
  File "C:\SickRage\Python\lib\httplib.py", line 596, in read
    s = self._safe_read(self.length)
  File "C:\SickRage\Python\lib\httplib.py", line 703, in _safe_read
    chunk = self.fp.read(min(amt, MAXAMOUNT))
  File "C:\SickRage\Python\lib\socket.py", line 384, in read
    data = self._sock.recv(left)
  File "C:\SickRage\Python\lib\ssl.py", line 734, in recv
    return self.read(buflen)
  File "C:\SickRage\Python\lib\ssl.py", line 621, in read
    v = self._sslobj.read(len or 1024)
SSLError: ('The read operation timed out',)
 [4eccee2]
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by SickRage2** [comment]
Thanks for the issue report! Before a real human comes by, please make sure your report has all the below criteria checked

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [ ] Post debug logs, either inline (for smaller logs) or using gist)

Please make sure you also read [how to create an issue](https://github.com/SickRage/sickrage-issues/blob/master/README.md) and followed all of the steps. 

The title should describe your issue. Having "SR not working" or "I get this bug" for 100 issues, isn't really helpful. We will close issues if there isn't enough information.

Sometimes the devs may seem like grunts and respond with short answers. This isn't (always) because the dev hates you, but because he's on mobile or busy fixing bugs. If something isn't clear, please let us know, and this bot may get updated to automatically answer you.

Thanks!
