### ISSUE TITLE
[APP SUBMITTED]: `/i-data/3b7d53b0/torrents/shows/[V-A]_Now_and_Then,_Here_and_There/[V-A]_Now_and_Then,_Here_and_There_02_[F3B0D83F].avi` and `/i-data/md0/shows/Now and Then, Here and There/Now.and.Then.Here.and.There.S01E02.A.Boy.and.A.Mad.King.SDTV.avi` are the same file

### ISSUE THREAD

**Issue by blakadder** [SickRage/sickrage-issues#424]
### INFO
Python Version: **2.7.9 (default, Jan 16 2015, 11:00:00) [GCC 4.9.2]**
Operating System: **Linux-2.6.31.8-armv5tel-with-libc0**
Locale: ISO8859-1
Branch: **master**
Commit: SickRage/SickRage@4eccee2ad1b3e3d144bfd8e315fdf397cfd33361
No Log available with ERRORS: 
### ERROR
```
Thread-30 :: Failed doing webui callback: Traceback (most recent call last):
  File "/usr/local/zy-pkgs/ffproot/ffp/share/sickrage/sickbeard/webserve.py", line 271, in async_call
    result = function(**kwargs)
  File "/usr/local/zy-pkgs/ffproot/ffp/share/sickrage/sickbeard/webserve.py", line 2251, in processEpisode
    is_priority=argToBool(is_priority), delete_on=argToBool(delete_on), failed=argToBool(failed), proc_type=type
  File "/usr/local/zy-pkgs/ffproot/ffp/share/sickrage/sickbeard/processTV.py", line 264, in processDir
    process_media(processPath, videoFiles, nzbName, process_method, force, is_priority, result)
  File "/usr/local/zy-pkgs/ffproot/ffp/share/sickrage/sickbeard/processTV.py", line 539, in process_media
    result.result = processor.process()
  File "/usr/local/zy-pkgs/ffproot/ffp/share/sickrage/sickbeard/postProcessor.py", line 1128, in process
    sickbeard.USE_SUBTITLES and ep_obj.show.subtitles)
  File "/usr/local/zy-pkgs/ffproot/ffp/share/sickrage/sickbeard/postProcessor.py", line 447, in _hardlink
    self._combined_file_operation(file_path, new_path, new_base_name, associated_files, action=_int_hard_link, subtitles=subtitles)
  File "/usr/local/zy-pkgs/ffproot/ffp/share/sickrage/sickbeard/postProcessor.py", line 379, in _combined_file_operation
    action(cur_file_path, new_file_path)
  File "/usr/local/zy-pkgs/ffproot/ffp/share/sickrage/sickbeard/postProcessor.py", line 441, in _int_hard_link
    helpers.hardlinkFile(cur_file_path, new_file_path)
  File "/usr/local/zy-pkgs/ffproot/ffp/share/sickrage/sickbeard/helpers.py", line 401, in hardlinkFile
    copyFile(srcFile, destFile)
  File "/usr/local/zy-pkgs/ffproot/ffp/share/sickrage/sickbeard/helpers.py", line 348, in copyFile
    ek(shutil.copyfile, srcFile, destFile)
  File "/usr/local/zy-pkgs/ffproot/ffp/share/sickrage/sickrage/helper/encoding.py", line 40, in ek
    result = function(*[ss(x) if isinstance(x, (str, unicode)) else x for x in args], **kwargs)
  File "/ffp/share/sickrage/lib/shutil_custom/__init__.py", line 14, in copyfile_custom
    raise Error("`%s` and `%s` are the same file" % (src, dst))
Error: `/i-data/3b7d53b0/torrents/shows/[V-A]_Now_and_Then,_Here_and_There/[V-A]_Now_and_Then,_Here_and_There_02_[F3B0D83F].avi` and `/i-data/md0/shows/Now and Then, Here and There/Now.and.Then.Here.and.There.S01E02.A.Boy.and.A.Mad.King.SDTV.avi` are the same file
 [4eccee2]
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by SickRage2** [comment]
Thanks for the issue report! Before a real human comes by, please make sure your report has all the below criteria checked

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [ ] Post debug logs, either inline (for smaller logs) or using gist)

Please make sure you also read [how to create an issue](https://github.com/SickRage/sickrage-issues/blob/master/README.md) and followed all of the steps. 

The title should describe your issue. Having "SR not working" or "I get this bug" for 100 issues, isn't really helpful. We will close issues if there isn't enough information.

Sometimes the devs may seem like grunts and respond with short answers. This isn't (always) because the dev hates you, but because he's on mobile or busy fixing bugs. If something isn't clear, please let us know, and this bot may get updated to automatically answer you.

Thanks!

**Comment by fernandog** [comment]
@SickRage/moderators we shouldn't raise this to error isn't?

**Comment by blakadder** [comment]
Indeed, it was a misclick in the UI and it autosent the error log to github

**Comment by fernandog** [comment]
@blakadder we should change code to not raise that
