### ISSUE TITLE
Can't launch sickrage : A provider with the same name already exist

### ISSUE THREAD

**Issue by Patafix** [SickRage/sickrage-issues#436]
After a git reset on branch develop, sickrage is not working now, when i do sudo service sickbeard start

```Traceback (most recent call last):
  File "SickBeard.py", line 88, in <module>
    import sickbeard
  File "*****/sickbeard/__init__.py", line 38, in <module>
    from sickbeard.config import CheckSection, check_setting_int, check_setting_str, check_setting_float, ConfigMigrator, \
  File "*****/sickbeard/config.py", line 29, in <module>
    from sickbeard import naming
  File "*****/sickbeard/naming.py", line 25, in <module>
    from sickbeard import tv
  File "*****/sickbeard/tv.py", line 47, in <module>
    from sickbeard import subtitles
  File "*****/sickbeard/subtitles.py", line 43, in <module>
    provider_manager.register('napiprojekt = subliminal.providers.napiprojekt:NapiProjektProvider')
  File "*****/lib/subliminal/api.py", line 76, in register
    raise ValueError('A provider with the same name already exist')
ValueError: A provider with the same name already exist'```

Debian

Version: Branch: develop
Commit: 84ef6bcf2c8623bb64afa7b6664568e1c11bd64a

**Comment by SickRage2** [comment]
Thanks for the issue report! Before a real human comes by, please make sure your report has all the below criteria checked

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [ ] Post debug logs, either inline (for smaller logs) or using gist)

Please make sure you also read [how to create an issue](https://github.com/SickRage/sickrage-issues/blob/master/README.md) and followed all of the steps. 

The title should describe your issue. Having "SR not working" or "I get this bug" for 100 issues, isn't really helpful. We will close issues if there isn't enough information.

Sometimes the devs may seem like grunts and respond with short answers. This isn't (always) because the dev hates you, but because he's on mobile or busy fixing bugs. If something isn't clear, please let us know, and this bot may get updated to automatically answer you.

Thanks!

**Comment by medariox** [comment]
You seem to have some old files in ../lib/subliminal.
Shut down SR (make sure it is really stopped), delete the content of ../lib/subliminal and do a 'git pull --force'.
Now you should have the new files and be able to start SR again.

**Comment by miigotu** [comment]
@Patafix looks like when you did `git reset` you forgot the `--hard`

**Comment by Patafix** [comment]
Thank you for your quick help.

Yet I do a 'git reset --hard'.

I deleted the lib/sublimal and it has not worked.
I even try to recloned all the project, even result.

I deleted cache and cache.db without success.

For now I commented line 43 of subtilite.py file and I managed to run sickbeard.

**Comment by medariox** [comment]
Is it possible that you have subliminal installed with pip on your machine?

**Comment by Patafix** [comment]
Yes i have subliminal install.

**Comment by medariox** [comment]
@Patafix 
Then you probably have an old version installed (< 1.1). Please update subliminal to a version >= 1.1 with pip and see if that solves the problem, it should.

**Comment by Patafix** [comment]
Thx @medariox it work now, I upgrade subliminal.

For others I run 

```pip install --upgrade subliminal```
