### ISSUE TITLE
 DB error: table history has no column named showid

### ISSUE THREAD

**Issue by giggsey** [SickRage/sickrage-issues#438]
>  DB error: table history has no column named showid [4423fe9]

It seems to do this when going a backlog search.

Running: SickRage/SickRage@4423fe95002315b812b4ef9867ea6df7d94c2083
Python Version:	2.7.10

I came from the other Sickrage, restoring a backup of it into this version, so that's likely where the issue came from.

**Comment by SickRage2** [comment]
Thanks for the issue report! Before a real human comes by, please make sure your report has all the below criteria checked

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [ ] Post debug logs, either inline (for smaller logs) or using gist)

Please make sure you also read [how to create an issue](https://github.com/SickRage/sickrage-issues/blob/master/README.md) and followed all of the steps. 

The title should describe your issue. Having "SR not working" or "I get this bug" for 100 issues, isn't really helpful. We will close issues if there isn't enough information.

Sometimes the devs may seem like grunts and respond with short answers. This isn't (always) because the dev hates you, but because he's on mobile or busy fixing bugs. If something isn't clear, please let us know, and this bot may get updated to automatically answer you.

Thanks!

**Comment by giggsey** [comment]
Just tried on latest master (SickRage/SickRage@4eccee2ad1b3e3d144bfd8e315fdf397cfd33361):

```
2016-01-07 15:14:57 INFO     SEARCHQUEUE-BACKLOG-284190 :: Beginning backlog search for: [Marvel's Jessica Jones]
2016-01-07 15:14:57 INFO     SEARCHQUEUE-BACKLOG-284190 :: [BTN] :: Performing season pack search for Marvel's Jessica Jones
2016-01-07 15:15:01 INFO     SEARCHQUEUE-BACKLOG-284190 :: [BTN] :: Quality of Marvels.Jessica.Jones.S01.1080p.WEBRip.DD5.1.x264-BTN is 1080p WEB-DL
2016-01-07 15:15:01 INFO     SEARCHQUEUE-BACKLOG-284190 :: [BTN] :: Quality of Marvels.Jessica.Jones.S01.1080p.NF.WEBRip.DD5.1.x264-NTb is 1080p WEB-DL
2016-01-07 15:15:01 INFO     SEARCHQUEUE-BACKLOG-284190 :: [BTN] :: Quality of Marvels.Jessica.Jones.S01.1080p.NF.WEBRip.DD5.1.x264-iON is 1080p WEB-DL
2016-01-07 15:15:01 INFO     SEARCHQUEUE-BACKLOG-284190 :: [BTN] :: Quality of Marvels.Jessica.Jones.S01.720p.WEBRip.DD5.1.x264-BTN is 720p WEB-DL
2016-01-07 15:15:01 INFO     SEARCHQUEUE-BACKLOG-284190 :: [BTN] :: Quality of Marvels.Jessica.Jones.S01.720p.NF.WEBRip.DD5.1.x264-iON is 720p WEB-DL
2016-01-07 15:15:01 INFO     SEARCHQUEUE-BACKLOG-284190 :: [BTN] :: Quality of Marvels.Jessica.Jones.S01.720p.NF.WEBRip.DD5.1.x264-NTb is 720p WEB-DL
2016-01-07 15:15:01 INFO     SEARCHQUEUE-BACKLOG-284190 :: [BTN] :: Quality of Marvels.Jessica.Jones.S01.2160p.NF.WEBRip.DD5.1.x264-TrollUHD is SDTV
2016-01-07 15:15:01 INFO     SEARCHQUEUE-BACKLOG-284190 :: [BTN] :: Quality of Marvels.Jessica.Jones.S01.2160p.NF.WEBRip.DD5.1.x264-iON is SDTV
2016-01-07 15:15:01 INFO     SEARCHQUEUE-BACKLOG-284190 :: [BTN] :: Quality of Marvels.Jessica.Jones.S01.WEBRip.AAC2.0.x264-LoV is SDTV
2016-01-07 15:15:01 INFO     SEARCHQUEUE-BACKLOG-284190 :: [BTN] :: Quality of Marvels.Jessica.Jones.S01.WEBRip.AAC2.0.x264-BTN is SDTV
2016-01-07 15:15:01 INFO     SEARCHQUEUE-BACKLOG-284190 :: [BTN] :: Executed query: [SELECT episode FROM tv_episodes WHERE showid = 284190 AND season in  1,1,1,1,1,1,1,1,1,1,1,1,1]
2016-01-07 15:15:01 INFO     SEARCHQUEUE-BACKLOG-284190 :: [BTN] :: Adding multi-ep result for full-season torrent. Set the episodes you don't want to 'don't download' in your torrent client if desired!
2016-01-07 15:15:01 INFO     SEARCHQUEUE-BACKLOG-284190 :: [BTN] :: Quality of Marvels.Jessica.Jones.S01.2160p.NF.WEBRip.DD5.1.x264-TrollUHD is SDTV
2016-01-07 15:15:01 INFO     SEARCHQUEUE-BACKLOG-284190 :: [BTN] :: Downloading Marvels.Jessica.Jones.S01.2160p.NF.WEBRip.DD5.1.x264-TrollUHD from BTN
2016-01-07 15:15:06 ERROR    SEARCHQUEUE-BACKLOG-284190 :: [BTN] :: DB error: table history has no column named showid [4eccee2]
Traceback (most recent call last):
  File "/opt/sickrage/sickbeard/db.py", line 214, in action
    sqlResult = self._execute(query, args, fetchall=fetchall, fetchone=fetchone)
  File "/opt/sickrage/sickbeard/db.py", line 105, in _execute
    sqlResult = self.connection.cursor().execute(query, args)
OperationalError: table history has no column named showid
```

**Comment by miigotu** [comment]
Hard to tell which db that is coming from.

Can you shut down SR, and rename failed.db to something else and start SR up and see if it still occurs?

**Comment by giggsey** [comment]
Looks like that fixed it, thanks

**Comment by miigotu** [comment]
Still, I'll look at fixing that up so people dont have to delete their failed.db =P
