### ISSUE TITLE
Error: 'Error -5 while decompressing data: incomplete or truncated stream'

### ISSUE THREAD

**Issue by ikriz** [SickRage/sickrage-issues#44]
Any ideas as to why this is happening on my raspberry pi2?

Currently on BRANCH: (master) / COMMIT: (c19526435dc15ba1bcd5827dd24d6a8e69c83e2b)
haven't taken the time to switch yet.. this has been happening for a while now and never took the time to report it.

```
2015-11-21 22:21:30 CHECKVERSION :: Unknown exception in getURL http://sickragetv.github.io/sickrage-news/news.md Error: 'Error -5 while decompressing data: incomplete or truncated stream'
2015-11-21 22:21:30 CHECKVERSION :: Traceback (most recent call last):
  File "/opt/sickrage/sickbeard/helpers.py", line 1608, in getURL
    resp = session.get(url, timeout=timeout, allow_redirects=True, verify=session.verify)
  File "/opt/sickrage/lib/requests/sessions.py", line 476, in get
    return self.request('GET', url, **kwargs)
  File "/opt/sickrage/lib/requests/sessions.py", line 464, in request
    resp = self.send(prep, **send_kwargs)
  File "/opt/sickrage/lib/requests/sessions.py", line 576, in send
    r = adapter.send(request, **kwargs)
  File "/opt/sickrage/lib/cachecontrol/adapter.py", line 36, in send
    cached_response = self.controller.cached_request(request)
  File "/opt/sickrage/lib/cachecontrol/controller.py", line 102, in cached_request
    resp = self.serializer.loads(request, self.cache.get(cache_url))
  File "/opt/sickrage/lib/cachecontrol/serialize.py", line 108, in loads
    return getattr(self, "_loads_v{0}".format(ver))(request, data)
  File "/opt/sickrage/lib/cachecontrol/serialize.py", line 164, in _loads_v2
    cached = json.loads(zlib.decompress(data).decode("utf8"))
error: Error -5 while decompressing data: incomplete or truncated stream
```

**Comment by miigotu** [comment]
maybe stop SR and delete cache/sessions?

**Comment by labrys** [comment]
yeah clearing cache fixed it for a couple other users
