### ISSUE TITLE
ExtraTorrent Connection error

### ISSUE THREAD

**Issue by ward0** [SickRage/sickrage-issues#451]
Hello,

I'm getting following error when looking for a episode? :
```
2016-01-09 10:47:33 SEARCHQUEUE-MANUAL-295640 :: [ExtraTorrent] :: Failed parsing provider. Traceback: 'Traceback (most recent call last):\n  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/providers/extratorrent.py", line 87, in search\n    info_hash = item.find(\'info_hash\').get_text(strip=True)\nAttributeError: \'NoneType\' object has no attribute \'get_text\'\n' [7fd6c98]
```

**Comment by SickRage2** [comment]
Thanks for the issue report! Before a real human comes by, please make sure your report has all the below criteria checked

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [ ] Post debug logs, either inline (for smaller logs) or using gist)

Please make sure you also read [how to create an issue](https://github.com/SickRage/sickrage-issues/blob/master/README.md) and followed all of the steps. 

The title should describe your issue. Having "SR not working" or "I get this bug" for 100 issues, isn't really helpful. We will close issues if there isn't enough information.

Sometimes the devs may seem like grunts and respond with short answers. This isn't (always) because the dev hates you, but because he's on mobile or busy fixing bugs. If something isn't clear, please let us know, and this bot may get updated to automatically answer you.

Thanks!

**Comment by ward0** [comment]
This is extra info 

Branch : Master
Commit : latest
OS : Synology 

Debug log =
2016-01-09 10:47:33 WARNING  SEARCHQUEUE-MANUAL-295640 :: [ExtraTorrent] :: Failed parsing provider. Traceback: 'Traceback (most recent call last):\n  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/providers/extratorrent.py", line 87, in search\n    info_hash = item.find(\'info_hash\').get_text(strip=True)\nAttributeError: \'NoneType\' object has no attribute \'get_text\'\n' [7fd6c98]
2016-01-09 10:47:33 WARNING  SEARCHQUEUE-MANUAL-295640 :: [ExtraTorrent] :: Failed parsing provider. Traceback: 'Traceback (most recent call last):\n  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/providers/extratorrent.py", line 87, in search\n    info_hash = item.find(\'info_hash\').get_text(strip=True)\nAttributeError: \'NoneType\' object has no attribute \'get_text\'\n' [7fd6c98]
2016-01-09 10:47:30 INFO     SEARCHQUEUE-MANUAL-295640 :: [ExtraTorrent] :: Performing episode search for Chicago MED
2016-01-09 10:47:30 INFO     SEARCHQUEUE-MANUAL-295640 :: Beginning manual search for: [Chicago MED - S01E04 - Mistaken]
2016-01-09 10:47:24 INFO     SEARCHQUEUE-BACKLOG-295640 :: [ExtraTorrent] :: Executing command ['/usr/syno/bin/synodsmnotify', '@*****istrators', 'Started Download', u'Chicago MED - 1x04 - Mistaken - 720p HDTV from ExtraTorrent']
2016-01-09 10:47:20 INFO     SEARCHQUEUE-BACKLOG-295640 :: [ExtraTorrent] :: Downloading Chicago.Med.S01E04.720p.HDTV.x264-KILLERS[ettv] from ExtraTorrent
2016-01-09 10:47:20 INFO     SEARCHQUEUE-BACKLOG-295640 :: [ExtraTorrent] :: Ignoring Chicago.Med.S01E04.720p.HDTV.x264.AAC-SS.-={SPARROW}=- based on required words filter: KILLERS
2016-01-09 10:47:20 INFO     SEARCHQUEUE-BACKLOG-295640 :: [ExtraTorrent] :: Quality of Chicago.Med.S01E04.720p.HDTV.x264.AAC-SS.-={SPARROW}=- is 720p HDTV
2016-01-09 10:47:20 INFO     SEARCHQUEUE-BACKLOG-295640 :: [ExtraTorrent] :: Quality of Chicago.Med.S01E04.720p.HDTV.x264-KILLERS[ettv] is 720p HDTV
2016-01-09 10:47:16 WARNING  SEARCHQUEUE-BACKLOG-295640 :: [ExtraTorrent] :: Failed parsing provider. Traceback: 'Traceback (most recent call last):\n  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/providers/extratorrent.py", line 87, in search\n    info_hash = item.find(\'info_hash\').get_text(strip=True)\nAttributeError: \'NoneType\' object has no attribute \'get_text\'\n' [7fd6c98]
2016-01-09 10:47:16 WARNING  SEARCHQUEUE-BACKLOG-295640 :: [ExtraTorrent] :: Failed parsing provider. Traceback: 'Traceback (most recent call last):\n  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/providers/extratorrent.py", line 87, in search\n    info_hash = item.find(\'info_hash\').get_text(strip=True)\nAttributeError: \'NoneType\' object has no attribute \'get_text\'\n' [7fd6c98]
2016-01-09 10:47:14 INFO     SEARCHQUEUE-BACKLOG-295640 :: [ExtraTorrent] :: Performing episode search for Chicago MED

**Comment by rmbleeker** [comment]
I'm experiencing the same.

Branch: **master**
Commit: **7fd6c98aafe1f543bf8f96b2e370666be5412288**
Version: **v5.1**
OS: **Ubuntu 14.04 LTS** with kernel **4.2.0-22-generic**

`2016-01-09 02:29:24 SEARCHQUEUE-BACKLOG-121361 :: [ExtraTorrent] :: Failed parsing provider. Traceback: 'Traceback (most recent call last):\n  File "/opt/sickrage/sickbeard/providers/extratorrent.py", line 87, in search\n    info_hash = item.find(\'info_hash\').get_text(strip=True)\nAttributeError: \'NoneType\' object has no attribute \'get_text\'\n' [7fd6c98]'
`2016-01-09 12:19:24 SEARCHQUEUE-DAILY-SEARCH :: [ExtraTorrent] :: Failed parsing provider. Traceback: 'Traceback (most recent call last):\n  File "/opt/sickrage/sickbeard/providers/extratorrent.py", line 87, in search\n    info_hash = item.find(\'info_hash\').get_text(strip=True)\nAttributeError: \'NoneType\' object has no attribute \'get_text\'\n' [7fd6c98]`

**Comment by fernandog** [comment]
fixed in develop

**Comment by ward0** [comment]
Thanks!
