### ISSUE TITLE
[APP SUBMITTED]: 'NoneType' object has no attribute 'guesses'

### ISSUE THREAD

**Issue by devenashani** [SickRage/sickrage-issues#452]
### INFO
Python Version: **2.7.10 (default, Aug 23 2015, 01:50:01) [GCC 4.4.5]**
Operating System: **Linux-2.6.31.8.nv+v2-armv5tel-with-debian-6.0.3**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@7fd6c98aafe1f543bf8f96b2e370666be5412288
No Log available with ERRORS: 
### ERROR
```
POSTPROCESSER :: Traceback (most recent call last):
  File "/usr/share/sickrage/sickbeard/subtitles.py", line 201, in download_subtitles
    matches = subtitle.get_matches(video, hearing_impaired=sickbeard.SUBTITLES_HEARING_IMPAIRED)
  File "/usr/share/sickrage/lib/subliminal/providers/addic7ed.py", line 68, in get_matches
    matches |= guess_matches(video, guess_properties(self.version), partial=True)
  File "/usr/share/sickrage/lib/subliminal/subtitle.py", line 328, in guess_properties
    get_transformer('guess_properties').process(mtree)
  File "/usr/share/sickrage/lib/guessit/transfo/guess_properties.py", line 281, in process
    GuessFinder(self.guess_properties, 1.0, self.log, options).process_nodes(mtree.unidentified_leaves())
  File "/usr/share/sickrage/lib/guessit/matcher.py", line 227, in process_nodes
    self.process_node(node)
  File "/usr/share/sickrage/lib/guessit/matcher.py", line 241, in process_node
    matcher_result = self.guess_func(string, node, self.options)
  File "/usr/share/sickrage/lib/guessit/transfo/guess_properties.py", line 261, in guess_properties
    for existing_guess in node.group_node().guesses:
AttributeError: 'NoneType' object has no attribute 'guesses'
 [7fd6c98]
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by SickRage2** [comment]
Thanks for the issue report! Before a real human comes by, please make sure your report has all the below criteria checked

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [ ] Post debug logs, either inline (for smaller logs) or using gist)

Please make sure you also read [how to create an issue](https://github.com/SickRage/sickrage-issues/blob/master/README.md) and followed all of the steps. 

The title should describe your issue. Having "SR not working" or "I get this bug" for 100 issues, isn't really helpful. We will close issues if there isn't enough information.

Sometimes the devs may seem like grunts and respond with short answers. This isn't (always) because the dev hates you, but because he's on mobile or busy fixing bugs. If something isn't clear, please let us know, and this bot may get updated to automatically answer you.

Thanks!

**Comment by labrys** [comment]
I guess we should do something about that. > rimshot <

**Comment by Henk2484** [comment]
### INFO
Python Version: **2.7.11 (default, Dec 17 2015, 12:58:48) [GCC 4.6.4]**
Operating System: **Linux-3.2.40-armv7l-with-glibc2.4**
Locale: None
Branch: **master**
Commit: SickRage/SickRage@b6c8acedafc0057f6da5e2f7ca91213c83fe2e42
No Log available with ERRORS:
### ERROR
```
FINDSUBTITLES :: Traceback (most recent call last):
  File "/volume1/@appstore/sickrage/var/SickRage/sickbeard/subtitles.py", line 176, in download_subtitles
    matches = subtitle.get_matches(video, hearing_impaired=sickbeard.SUBTITLES_HEARING_IMPAIRED)
  File "/usr/local/sickrage/var/SickRage/lib/subliminal/providers/addic7ed.py", line 69, in get_matches
    matches |= guess_matches(video, guess_properties(self.version), partial=True)
  File "/usr/local/sickrage/var/SickRage/lib/subliminal/subtitle.py", line 328, in guess_properties
    get_transformer('guess_properties').process(mtree)
  File "/usr/local/sickrage/var/SickRage/lib/guessit/transfo/guess_properties.py", line 281, in process
    GuessFinder(self.guess_properties, 1.0, self.log, options).process_nodes(mtree.unidentified_leaves())
  File "/usr/local/sickrage/var/SickRage/lib/guessit/matcher.py", line 227, in process_nodes
    self.process_node(node)
  File "/usr/local/sickrage/var/SickRage/lib/guessit/matcher.py", line 241, in process_node
    matcher_result = self.guess_func(string, node, self.options)
  File "/usr/local/sickrage/var/SickRage/lib/guessit/transfo/guess_properties.py", line 261, in guess_properties
    for existing_guess in node.group_node().guesses:
AttributeError: 'NoneType' object has no attribute 'guesses'
 [b6c8ace]
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by neoatomic** [comment]
@medariox Could you see if you can suppress this error and change to a warning.? Think its for files that already haven been moved.?

**Comment by medariox** [comment]
@neoatomic 
I can do that. I suspect the issue is caused by the file being moved while the "matching" is in progress.

**Comment by fernandog** [comment]
@medariox racing condition? but that needs two thread running together isn't?

**Comment by medariox** [comment]
@fernandog 
Maybe. Anyway, the problem is that this error happens in the guessit lib so it should be taken care of there. I don't see anything wrong with catching the exception and showing it as a warning tho.

**Comment by fernandog** [comment]
anyone reported that to guessit ?

**Comment by medariox** [comment]
Hmm, I don't think so. Subliminal uses an outdated version of guessit, I'm not even sure the dev is interested in fixing something that old.

**Comment by fernandog** [comment]
should we patch our guessit ?

**Comment by medariox** [comment]
It would be probably the best solution for now, maybe we should try asking the guessit dev. I can vaguely remember that @labrys wanted to fix it. :P
