### ISSUE TITLE
Error when removing show

### ISSUE THREAD

**Issue by jangrewe** [SickRage/sickrage-issues#455]
I'm currently migrating from SB to SR, using the master branch with the latest commit.
SR somehow decided to add "Two and a Half Men" to my shows, which i didn't add myself and also don't have in my existing shows.
Anyways, as i was trying to use the "remove" button, i got this error in the log (and nothing was removed):

```
2016-01-09 23:23:07 Thread-30 :: Failed doing webui callback: Traceback (most recent call last):
  File "/opt/sickrage/sickbeard/webserve.py", line 271, in async_call
    result = function(**kwargs)
  File "/opt/sickrage/sickbeard/webserve.py", line 1574, in deleteShow
    error, show = Show.delete(show, full)
  File "/opt/sickrage/sickrage/show/Show.py", line 51, in delete
    sickbeard.showQueueScheduler.action.removeShow(show, bool(remove_files))
  File "/opt/sickrage/sickbeard/show_queue.py", line 163, in removeShow
    if x and x != self.currentItem and show.indexerid == x.show.indexerid:
AttributeError: 'NoneType' object has no attribute 'indexerid'
 [7fd6c98]
```
This happens on Debian "jessie" 8 with Python 2.7.9 and every time i try to remove the show.

**Comment by SickRage2** [comment]
Thanks for the issue report! Before a real human comes by, please make sure your report has all the below criteria checked

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [ ] Post debug logs, either inline (for smaller logs) or using gist)

Please make sure you also read [how to create an issue](https://github.com/SickRage/sickrage-issues/blob/master/README.md) and followed all of the steps. 

The title should describe your issue. Having "SR not working" or "I get this bug" for 100 issues, isn't really helpful. We will close issues if there isn't enough information.

Sometimes the devs may seem like grunts and respond with short answers. This isn't (always) because the dev hates you, but because he's on mobile or busy fixing bugs. If something isn't clear, please let us know, and this bot may get updated to automatically answer you.

Thanks!

**Comment by jangrewe** [comment]
fyi, today i was able to delete the show just fine, so i'm not sure if this issue can be closed or if you may want to check if there's anything that may cause this to happen again? thanks!

**Comment by miigotu** [comment]
Will just chanlk it up as an anomaly for now.
