### ISSUE TITLE
[APP SUBMITTED]: need more than 1 value to unpack

### ISSUE THREAD

**Issue by dirkr07** [SickRage/sickrage-issues#469]
### INFO
Python Version: **2.7.11 (default, Dec 17 2015, 15:07:57) [GCC 4.3.2]**
Operating System: **Linux-2.6.32.12-ppc-with-glibc2.0**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@7fd6c98aafe1f543bf8f96b2e370666be5412288
Link to Log: https://gist.github.com/e4e0cb1cca0eb872cbdd
### ERROR
```
SHOWUPDATER :: Exception generated in thread SHOWUPDATER: need more than 1 value to unpack [7fd6c98]
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by SickRage2** [comment]
Thanks for the issue report! Before a real human comes by, please make sure your report has all the below criteria checked

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [x] Post debug logs, either inline (for smaller logs) or using gist)

Please make sure you also read [how to create an issue](https://github.com/SickRage/sickrage-issues/blob/master/README.md) and followed all of the steps. 

The title should describe your issue. Having "SR not working" or "I get this bug" for 100 issues, isn't really helpful. We will close issues if there isn't enough information.

Sometimes the devs may seem like grunts and respond with short answers. This isn't (always) because the dev hates you, but because he's on mobile or busy fixing bugs. If something isn't clear, please let us know, and this bot may get updated to automatically answer you.

Thanks!

**Comment by neoatomic** [comment]
@dirkr07 Not sure what is coursing this...
Could you ssh/winscp into your Syno and find the sickrage log file.?
There should be a traceback included with that error, that gives some more info where we need to look.

`2016-01-12 01:01:11 ERROR SHOWUPDATER :: Exception generated in thread SHOWUPDATER: need more than 1 value to unpack [7fd6c98] `

**Comment by dirkr07** [comment]
Can't get to the box right now so got this from the log through SR.

```
2016-01-12 01:01:11 DEBUG    SHOWUPDATER :: 'Traceback (most recent call last):\n  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/scheduler.py", line 106, in run\n    self.action.run(self.force)\n  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/showUpdater.py", line 64, in run\n    network_timezones.update_network_dict()\n  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/network_timezones.py", line 52, in update_network_dict\n    (key, val) = line.strip().rsplit(u\':\', 1)\nValueError: need more than 1 value to unpack\n'
AAValueError: need more than 1 value to unpack
AA    (key, val) = line.strip().rsplit(u':', 1)
AA  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/network_timezones.py", line 52, in update_network_dict
AA    network_timezones.update_network_dict()
AA  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/showUpdater.py", line 64, in run
AA    self.action.run(self.force)
AA  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/scheduler.py", line 106, in run
AATraceback (most recent call last):
2016-01-12 01:01:11 ERROR    SHOWUPDATER :: Exception generated in thread SHOWUPDATER: need more than 1 value to unpack [7fd6c98]
```

Seems like the traceback you would be looking for? 
If not, I'll get you the file asap.

**Comment by fernandog** [comment]
@Labrys ^^

**Comment by fernandog** [comment]
@dirkr07 do you still have this error? Can't reproduce

**Comment by dirkr07** [comment]
@fernandog haven't seen it again so far.
I'll open a new issue (or have you re-open this one) should it ever re-occur..

**Comment by snapperhead** [comment]
### INFO
Python Version: **2.7.10 (default, Oct 23 2015, 19:19:21) [GCC 4.2.1 Compatible Apple LLVM 7.0.0 (clang-700.0.59.5)]**
Operating System: **Darwin-15.4.0-x86_64-i386-64bit**
Locale: None
Branch: **master**
Commit: SickRage/SickRage@bc5e61a8f96a8abae80ae78fbf261ff3023a664d
No Log available with ERRORS:
### ERROR
```
DAILYSEARCHER :: [bc5e61a] Exception generated in thread DAILYSEARCHER: need more than 1 value to unpack
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by backslash05** [comment]
### INFO
Python Version: **2.7.9 (default, Mar  1 2015, 12:57:24) [GCC 4.9.2]**
Operating System: **Linux-3.16.7-ckt20-feral-x86_64-with-debian-8.3**
Locale: None
Branch: **master**
Commit: SickRage/SickRage@bc5e61a8f96a8abae80ae78fbf261ff3023a664d
No Log available with ERRORS:
### ERROR
```
DAILYSEARCHER :: [bc5e61a] Exception generated in thread DAILYSEARCHER: need more than 1 value to unpack
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by Merrick28** [comment]
### INFO
Python Version: **2.7.9 (default, Mar  1 2015, 12:57:24) [GCC 4.9.2]**
Operating System: **Linux-3.16.0-4-amd64-x86_64-with-debian-8.3**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@bc5e61a8f96a8abae80ae78fbf261ff3023a664d
No Log available with ERRORS:
### ERROR
```
DAILYSEARCHER :: [bc5e61a] Exception generated in thread DAILYSEARCHER: need more than 1 value to unpack
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by stanthewizzard** [comment]
### INFO
Python Version: **2.7.10 (default, Oct 14 2015, 16:09:02) [GCC 5.2.1 20151010]**
Operating System: **Linux-4.2.0-34-generic-x86_64-with-Ubuntu-15.10-wily**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@bc5e61a8f96a8abae80ae78fbf261ff3023a664d
No Log available with ERRORS:
### ERROR
```
SHOWUPDATER :: [bc5e61a] Exception generated in thread SHOWUPDATER: need more than 1 value to unpack
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by stanthewizzard** [comment]
### INFO
Python Version: **2.7.10 (default, Oct 14 2015, 16:09:02) [GCC 5.2.1 20151010]**
Operating System: **Linux-4.2.0-34-generic-x86_64-with-Ubuntu-15.10-wily**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@bc5e61a8f96a8abae80ae78fbf261ff3023a664d
No Log available with ERRORS:
### ERROR
```
DAILYSEARCHER :: [bc5e61a] Exception generated in thread DAILYSEARCHER: need more than 1 value to unpack
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by stephan-schwarz** [comment]
### INFO
Python Version: **2.7.10 (default, May 23 2015, 09:44:00) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-2012Server-6.2.9200**
Locale: cp1252
Branch: **master**
Commit: SickRage/SickRage@bc5e61a8f96a8abae80ae78fbf261ff3023a664d
No Log available with ERRORS:
### ERROR
```
DAILYSEARCHER :: [bc5e61a] Exception generated in thread DAILYSEARCHER: need more than 1 value to unpack
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by stephan-schwarz** [comment]
### INFO
Python Version: **2.7.10 (default, May 23 2015, 09:44:00) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-2012Server-6.2.9200**
Locale: cp1252
Branch: **master**
Commit: SickRage/SickRage@bc5e61a8f96a8abae80ae78fbf261ff3023a664d
No Log available with ERRORS:
### ERROR
```
SHOWUPDATER :: [bc5e61a] Exception generated in thread SHOWUPDATER: need more than 1 value to unpack
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by CodaAmok** [comment]
### INFO
Python Version: **2.7.10 (default, May 23 2015, 09:44:00) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-8-6.2.9200**
Locale: cp1252
Branch: **master**
Commit: SickRage/SickRage@bc5e61a8f96a8abae80ae78fbf261ff3023a664d
No Log available with ERRORS:
### ERROR
```
DAILYSEARCHER :: [bc5e61a] Exception generated in thread DAILYSEARCHER: need more than 1 value to unpack
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by rmbleeker** [comment]
### INFO
Python Version: **2.7.6 (default, Jun 22 2015, 17:58:13) [GCC 4.8.2]**
Operating System: **Linux-4.2.0-30-generic-x86_64-with-Ubuntu-14.04-trusty**
Locale: None
Branch: **master**
Commit: SickRage/SickRage@bc5e61a8f96a8abae80ae78fbf261ff3023a664d
No Log available with ERRORS:
### ERROR
```
DAILYSEARCHER :: [bc5e61a] Exception generated in thread DAILYSEARCHER: need more than 1 value to unpack
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by Trapizomba** [comment]
### INFO
Python Version: **2.7.9 (default, Sep  9 2015, 14:50:03) [GCC 4.2.1 20070831 patched [FreeBSD]]**
Operating System: **FreeBSD-9.1-RELEASE-amd64-64bit-ELF**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@bc5e61a8f96a8abae80ae78fbf261ff3023a664d
No Log available with ERRORS:
### ERROR
```
DAILYSEARCHER :: [bc5e61a] Exception generated in thread DAILYSEARCHER: need more than 1 value to unpack
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by NeoMod** [comment]
### INFO
Python Version: **2.7.9 (default, Mar  1 2015, 13:48:22) [GCC 4.9.2]**
Operating System: **Linux-3.4.110-sun7i-armv7l-with-debian-8.3**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@bc5e61a8f96a8abae80ae78fbf261ff3023a664d
No Log available with ERRORS:
### ERROR
```
SHOWUPDATER :: [bc5e61a] Exception generated in thread SHOWUPDATER: need more than 1 value to unpack
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by NeoMod** [comment]
### INFO
Python Version: **2.7.9 (default, Mar  1 2015, 13:48:22) [GCC 4.9.2]**
Operating System: **Linux-3.4.110-sun7i-armv7l-with-debian-8.3**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@bc5e61a8f96a8abae80ae78fbf261ff3023a664d
No Log available with ERRORS:
### ERROR
```
DAILYSEARCHER :: [bc5e61a] Exception generated in thread DAILYSEARCHER: need more than 1 value to unpack
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by PapaFatHead** [comment]
### INFO
Python Version: **2.7.3 (default, Jun 22 2015, 19:33:41) [GCC 4.6.3]**
Operating System: **Linux-3.14.32-xxxx-grs-ipv6-64-x86_64-with-Ubuntu-12.04-precise**
Locale: None
Branch: **master**
Commit: SickRage/SickRage@5195b784b76916a2acfe21c1fffd12f837ce0e93
No Log available with ERRORS:
### ERROR
```
SHOWUPDATER :: Exception generated in thread SHOWUPDATER: need more than 1 value to unpack [5195b78]
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators
