### ISSUE TITLE
[APP SUBMITTED]: cannot import name LOGGING_LEVELS

### ISSUE THREAD

**Issue by MrCee** [SickRage/sickrage-issues#476]
### INFO
Python Version: **2.7.11 (default, Dec 17 2015, 14:08:17) [GCC 4.6.3]**
Operating System: **Linux-3.2.40-i686-with-glibc2.0**
Locale: unknown
Branch: **master**
Commit: SickRage/SickRage@e31a2e250047c554851fe21d2465e54415345ded
No Log available with ERRORS: 
### ERROR
```
Thread-40 :: Failed doing webui callback: Traceback (most recent call last):
  File "/volume1/@appstore/sickrage/var/SickRage/sickbeard/webserve.py", line 271, in async_call
    raise HTTPError(404)
  File "/volume1/@appstore/sickrage/var/SickRage/sickbeard/webserve.py", line 5143, in viewlog
    if match:
  File "/volume1/@appstore/sickrage/var/SickRage/sickbeard/webserve.py", line 118, in __init__
    class PageTemplate(MakoTemplate):
  File "/usr/local/sickrage/var/SickRage/lib/mako/lookup.py", line 245, in get_template
    return self._check(uri, self._collection[uri])
  File "/usr/local/sickrage/var/SickRage/lib/mako/lookup.py", line 341, in _check
    return self._load(template.filename, uri)
  File "/usr/local/sickrage/var/SickRage/lib/mako/lookup.py", line 321, in _load
    **self.template_args)
  File "/usr/local/sickrage/var/SickRage/lib/mako/template.py", line 322, in __init__
    module = self._compile_from_file(path, filename)
  File "/usr/local/sickrage/var/SickRage/lib/mako/template.py", line 379, in _compile_from_file
    module = compat.load_module(self.module_id, path)
  File "/usr/local/sickrage/var/SickRage/lib/mako/compat.py", line 89, in load_module
    return imp.load_source(module_id, path, fp)
  File "/usr/local/sickrage/var/cache/mako/viewlogs.mako.py", line 19, in <module>
    from sickbeard.logger import LOGGING_LEVELS
ImportError: cannot import name LOGGING_LEVELS
 [e31a2e2]
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by SickRage2** [comment]
Thanks for the issue report! Before a real human comes by, please make sure your report has all the below criteria checked

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [ ] Post debug logs, either inline (for smaller logs) or using gist)

Please make sure you also read [how to create an issue](https://github.com/SickRage/sickrage-issues/blob/master/README.md) and followed all of the steps. 

The title should describe your issue. Having "SR not working" or "I get this bug" for 100 issues, isn't really helpful. We will close issues if there isn't enough information.

Sometimes the devs may seem like grunts and respond with short answers. This isn't (always) because the dev hates you, but because he's on mobile or busy fixing bugs. If something isn't clear, please let us know, and this bot may get updated to automatically answer you.

Thanks!

**Comment by fernandog** [comment]
@MrCee if happens again let us know

**Comment by cadatoiva** [comment]
### INFO
Python Version: **2.7.11 (default, Jan  9 2016, 13:05:07) [GCC 4.2.1 Compatible FreeBSD Clang 3.4.1 (tags/RELEASE_34/dot1-final 208032)]**
Operating System: **FreeBSD-10.2-RELEASE-p7-amd64-64bit-ELF**
Locale: unknown
Branch: **master**
Commit: SickRage/SickRage@93536ada05ad3fa9cfb4b18f61787bc8e441f45f
No Log available with ERRORS: 
### ERROR
```
Thread-23 :: Failed doing webui callback: Traceback (most recent call last):
  File "/usr/local/sickrage/sickbeard/webserve.py", line 271, in async_call
    raise HTTPError(404)
  File "/usr/local/sickrage/sickbeard/webserve.py", line 5143, in viewlog
    if match:
  File "/usr/local/sickrage/sickbeard/webserve.py", line 118, in __init__
    class PageTemplate(MakoTemplate):
  File "/usr/local/sickrage/lib/mako/lookup.py", line 256, in get_template
    return self._load(srcfile, uri)
  File "/usr/local/sickrage/lib/mako/lookup.py", line 321, in _load
    **self.template_args)
  File "/usr/local/sickrage/lib/mako/template.py", line 322, in __init__
    module = self._compile_from_file(path, filename)
  File "/usr/local/sickrage/lib/mako/template.py", line 379, in _compile_from_file
    module = compat.load_module(self.module_id, path)
  File "/usr/local/sickrage/lib/mako/compat.py", line 89, in load_module
    return imp.load_source(module_id, path, fp)
  File "/usr/local/sickrage/cache/mako/viewlogs.mako.py", line 19, in <module>
    from sickbeard.logger import LOGGING_LEVELS
ImportError: cannot import name LOGGING_LEVELS
 [93536ad]
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by cadatoiva** [comment]
### INFO
Python Version: **2.7.11 (default, Jan  9 2016, 13:05:07) [GCC 4.2.1 Compatible FreeBSD Clang 3.4.1 (tags/RELEASE_34/dot1-final 208032)]**
Operating System: **FreeBSD-10.2-RELEASE-p7-amd64-64bit-ELF**
Locale: unknown
Branch: **master**
Commit: SickRage/SickRage@93536ada05ad3fa9cfb4b18f61787bc8e441f45f
No Log available with ERRORS: 
### ERROR
```
Thread-42 :: Failed doing webui callback: Traceback (most recent call last):
  File "/usr/local/sickrage/sickbeard/webserve.py", line 271, in async_call
    raise HTTPError(404)
  File "/usr/local/sickrage/sickbeard/webserve.py", line 5143, in viewlog
    if match:
  File "/usr/local/sickrage/sickbeard/webserve.py", line 118, in __init__
    class PageTemplate(MakoTemplate):
  File "/usr/local/sickrage/lib/mako/lookup.py", line 256, in get_template
    return self._load(srcfile, uri)
  File "/usr/local/sickrage/lib/mako/lookup.py", line 321, in _load
    **self.template_args)
  File "/usr/local/sickrage/lib/mako/template.py", line 322, in __init__
    module = self._compile_from_file(path, filename)
  File "/usr/local/sickrage/lib/mako/template.py", line 379, in _compile_from_file
    module = compat.load_module(self.module_id, path)
  File "/usr/local/sickrage/lib/mako/compat.py", line 89, in load_module
    return imp.load_source(module_id, path, fp)
  File "/usr/local/sickrage/cache/mako/viewlogs.mako.py", line 19, in <module>
    from sickbeard.logger import LOGGING_LEVELS
ImportError: cannot import name LOGGING_LEVELS
 [93536ad]
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by cadatoiva** [comment]
### INFO
Python Version: **2.7.11 (default, Jan  9 2016, 13:05:07) [GCC 4.2.1 Compatible FreeBSD Clang 3.4.1 (tags/RELEASE_34/dot1-final 208032)]**
Operating System: **FreeBSD-10.2-RELEASE-p7-amd64-64bit-ELF**
Locale: unknown
Branch: **master**
Commit: SickRage/SickRage@93536ada05ad3fa9cfb4b18f61787bc8e441f45f
No Log available with ERRORS: 
### ERROR
```
Thread-40 :: Failed doing webui callback: Traceback (most recent call last):
  File "/usr/local/sickrage/sickbeard/webserve.py", line 271, in async_call
    raise HTTPError(404)
  File "/usr/local/sickrage/sickbeard/webserve.py", line 5143, in viewlog
    if match:
  File "/usr/local/sickrage/sickbeard/webserve.py", line 118, in __init__
    class PageTemplate(MakoTemplate):
  File "/usr/local/sickrage/lib/mako/lookup.py", line 256, in get_template
    return self._load(srcfile, uri)
  File "/usr/local/sickrage/lib/mako/lookup.py", line 321, in _load
    **self.template_args)
  File "/usr/local/sickrage/lib/mako/template.py", line 322, in __init__
    module = self._compile_from_file(path, filename)
  File "/usr/local/sickrage/lib/mako/template.py", line 379, in _compile_from_file
    module = compat.load_module(self.module_id, path)
  File "/usr/local/sickrage/lib/mako/compat.py", line 89, in load_module
    return imp.load_source(module_id, path, fp)
  File "/usr/local/sickrage/cache/mako/viewlogs.mako.py", line 19, in <module>
    from sickbeard.logger import LOGGING_LEVELS
ImportError: cannot import name LOGGING_LEVELS
 [93536ad]
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by cadatoiva** [comment]
### INFO
Python Version: **2.7.11 (default, Jan  9 2016, 13:05:07) [GCC 4.2.1 Compatible FreeBSD Clang 3.4.1 (tags/RELEASE_34/dot1-final 208032)]**
Operating System: **FreeBSD-10.2-RELEASE-p7-amd64-64bit-ELF**
Locale: unknown
Branch: **master**
Commit: SickRage/SickRage@93536ada05ad3fa9cfb4b18f61787bc8e441f45f
No Log available with ERRORS: 
### ERROR
```
Thread-29 :: Failed doing webui callback: Traceback (most recent call last):
  File "/usr/local/sickrage/sickbeard/webserve.py", line 271, in async_call
    raise HTTPError(404)
  File "/usr/local/sickrage/sickbeard/webserve.py", line 5143, in viewlog
    if match:
  File "/usr/local/sickrage/sickbeard/webserve.py", line 118, in __init__
    class PageTemplate(MakoTemplate):
  File "/usr/local/sickrage/lib/mako/lookup.py", line 256, in get_template
    return self._load(srcfile, uri)
  File "/usr/local/sickrage/lib/mako/lookup.py", line 321, in _load
    **self.template_args)
  File "/usr/local/sickrage/lib/mako/template.py", line 322, in __init__
    module = self._compile_from_file(path, filename)
  File "/usr/local/sickrage/lib/mako/template.py", line 379, in _compile_from_file
    module = compat.load_module(self.module_id, path)
  File "/usr/local/sickrage/lib/mako/compat.py", line 89, in load_module
    return imp.load_source(module_id, path, fp)
  File "/usr/local/sickrage/cache/mako/viewlogs.mako.py", line 19, in <module>
    from sickbeard.logger import LOGGING_LEVELS
ImportError: cannot import name LOGGING_LEVELS
 [93536ad]
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by TechCrazi** [comment]
### INFO
Python Version: **2.7.10 (v2.7.10:15c95b7d81dc, May 23 2015, 09:33:12) [GCC 4.2.1 (Apple Inc. build 5666) (dot 3)]**
Operating System: **Darwin-15.2.0-x86_64-i386-64bit**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@93536ada05ad3fa9cfb4b18f61787bc8e441f45f
No Log available with ERRORS: 
### ERROR
```
Thread-33 :: Failed doing webui callback: Traceback (most recent call last):
  File "/Users/Smit/SickRage/sickbeard/webserve.py", line 271, in async_call
    raise HTTPError(404)
  File "/Users/Smit/SickRage/sickbeard/webserve.py", line 5143, in viewlog
    if match:
  File "/Users/Smit/SickRage/sickbeard/webserve.py", line 118, in __init__
    class PageTemplate(MakoTemplate):
  File "/Users/Smit/SickRage/lib/mako/lookup.py", line 256, in get_template
    return self._load(srcfile, uri)
  File "/Users/Smit/SickRage/lib/mako/lookup.py", line 321, in _load
    **self.template_args)
  File "/Users/Smit/SickRage/lib/mako/template.py", line 322, in __init__
    module = self._compile_from_file(path, filename)
  File "/Users/Smit/SickRage/lib/mako/template.py", line 379, in _compile_from_file
    module = compat.load_module(self.module_id, path)
  File "/Users/Smit/SickRage/lib/mako/compat.py", line 89, in load_module
    return imp.load_source(module_id, path, fp)
  File "/Users/Smit/SickRage/cache/mako/viewlogs.mako.py", line 19, in <module>
    from sickbeard.logger import LOGGING_LEVELS
ImportError: cannot import name LOGGING_LEVELS
 [93536ad]
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by TechCrazi** [comment]
### INFO
Python Version: **2.7.10 (v2.7.10:15c95b7d81dc, May 23 2015, 09:33:12) [GCC 4.2.1 (Apple Inc. build 5666) (dot 3)]**
Operating System: **Darwin-15.2.0-x86_64-i386-64bit**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@93536ada05ad3fa9cfb4b18f61787bc8e441f45f
No Log available with ERRORS: 
### ERROR
```
Thread-47 :: Failed doing webui callback: Traceback (most recent call last):
  File "/Users/Smit/SickRage/sickbeard/webserve.py", line 271, in async_call
    raise HTTPError(404)
  File "/Users/Smit/SickRage/sickbeard/webserve.py", line 5143, in viewlog
    if match:
  File "/Users/Smit/SickRage/sickbeard/webserve.py", line 118, in __init__
    class PageTemplate(MakoTemplate):
  File "/Users/Smit/SickRage/lib/mako/lookup.py", line 256, in get_template
    return self._load(srcfile, uri)
  File "/Users/Smit/SickRage/lib/mako/lookup.py", line 321, in _load
    **self.template_args)
  File "/Users/Smit/SickRage/lib/mako/template.py", line 322, in __init__
    module = self._compile_from_file(path, filename)
  File "/Users/Smit/SickRage/lib/mako/template.py", line 379, in _compile_from_file
    module = compat.load_module(self.module_id, path)
  File "/Users/Smit/SickRage/lib/mako/compat.py", line 89, in load_module
    return imp.load_source(module_id, path, fp)
  File "/Users/Smit/SickRage/cache/mako/viewlogs.mako.py", line 19, in <module>
    from sickbeard.logger import LOGGING_LEVELS
ImportError: cannot import name LOGGING_LEVELS
 [93536ad]
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by TechCrazi** [comment]
### INFO
Python Version: **2.7.10 (v2.7.10:15c95b7d81dc, May 23 2015, 09:33:12) [GCC 4.2.1 (Apple Inc. build 5666) (dot 3)]**
Operating System: **Darwin-15.2.0-x86_64-i386-64bit**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@93536ada05ad3fa9cfb4b18f61787bc8e441f45f
No Log available with ERRORS: 
### ERROR
```
Thread-55 :: Failed doing webui callback: Traceback (most recent call last):
  File "/Users/Smit/SickRage/sickbeard/webserve.py", line 271, in async_call
    raise HTTPError(404)
  File "/Users/Smit/SickRage/sickbeard/webserve.py", line 5143, in viewlog
    if match:
  File "/Users/Smit/SickRage/sickbeard/webserve.py", line 118, in __init__
    class PageTemplate(MakoTemplate):
  File "/Users/Smit/SickRage/lib/mako/lookup.py", line 256, in get_template
    return self._load(srcfile, uri)
  File "/Users/Smit/SickRage/lib/mako/lookup.py", line 321, in _load
    **self.template_args)
  File "/Users/Smit/SickRage/lib/mako/template.py", line 322, in __init__
    module = self._compile_from_file(path, filename)
  File "/Users/Smit/SickRage/lib/mako/template.py", line 379, in _compile_from_file
    module = compat.load_module(self.module_id, path)
  File "/Users/Smit/SickRage/lib/mako/compat.py", line 89, in load_module
    return imp.load_source(module_id, path, fp)
  File "/Users/Smit/SickRage/cache/mako/viewlogs.mako.py", line 19, in <module>
    from sickbeard.logger import LOGGING_LEVELS
ImportError: cannot import name LOGGING_LEVELS
 [93536ad]
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by fernandog** [comment]
@labrys @miigotu so every user will have this once?

**Comment by brse** [comment]
### INFO
Python Version: **2.7.3 (default, Sep  4 2013, 13:54:56) [GCC 4.6.4 20120731 (prerelease)]**
Operating System: **Linux-3.2.40-armv7l-with-glibc2.4**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@abfff93b766d6b8eb81cb2ca4c410b795f5343e5
No Log available with ERRORS: 
### ERROR
```
Thread-41 :: Failed doing webui callback: Traceback (most recent call last):
  File "/mnt/HD/HD_a2/Nas_Prog/sickrage/sickbeard/webserve.py", line 271, in async_call
    raise HTTPError(404)
  File "/mnt/HD/HD_a2/Nas_Prog/sickrage/sickbeard/webserve.py", line 5143, in viewlog
    if match:
  File "/mnt/HD/HD_a2/Nas_Prog/sickrage/sickbeard/webserve.py", line 118, in __init__
    class PageTemplate(MakoTemplate):
  File "/mnt/HD/HD_a2/Nas_Prog/sickrage/lib/mako/lookup.py", line 256, in get_template
    return self._load(srcfile, uri)
  File "/mnt/HD/HD_a2/Nas_Prog/sickrage/lib/mako/lookup.py", line 321, in _load
    **self.template_args)
  File "/mnt/HD/HD_a2/Nas_Prog/sickrage/lib/mako/template.py", line 322, in __init__
    module = self._compile_from_file(path, filename)
  File "/mnt/HD/HD_a2/Nas_Prog/sickrage/lib/mako/template.py", line 379, in _compile_from_file
    module = compat.load_module(self.module_id, path)
  File "/mnt/HD/HD_a2/Nas_Prog/sickrage/lib/mako/compat.py", line 89, in load_module
    return imp.load_source(module_id, path, fp)
  File "/mnt/HD/HD_a2/Nas_Prog/sickrage/cache/mako/viewlogs.mako.py", line 19, in <module>
    from sickbeard.logger import LOGGING_LEVELS
ImportError: cannot import name LOGGING_LEVELS
 [abfff93]
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by brse** [comment]
### INFO
Python Version: **2.7.3 (default, Sep  4 2013, 13:54:56) [GCC 4.6.4 20120731 (prerelease)]**
Operating System: **Linux-3.2.40-armv7l-with-glibc2.4**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@abfff93b766d6b8eb81cb2ca4c410b795f5343e5
No Log available with ERRORS: 
### ERROR
```
Thread-56 :: Failed doing webui callback: Traceback (most recent call last):
  File "/mnt/HD/HD_a2/Nas_Prog/sickrage/sickbeard/webserve.py", line 271, in async_call
    raise HTTPError(404)
  File "/mnt/HD/HD_a2/Nas_Prog/sickrage/sickbeard/webserve.py", line 5143, in viewlog
    if match:
  File "/mnt/HD/HD_a2/Nas_Prog/sickrage/sickbeard/webserve.py", line 118, in __init__
    class PageTemplate(MakoTemplate):
  File "/mnt/HD/HD_a2/Nas_Prog/sickrage/lib/mako/lookup.py", line 256, in get_template
    return self._load(srcfile, uri)
  File "/mnt/HD/HD_a2/Nas_Prog/sickrage/lib/mako/lookup.py", line 321, in _load
    **self.template_args)
  File "/mnt/HD/HD_a2/Nas_Prog/sickrage/lib/mako/template.py", line 322, in __init__
    module = self._compile_from_file(path, filename)
  File "/mnt/HD/HD_a2/Nas_Prog/sickrage/lib/mako/template.py", line 379, in _compile_from_file
    module = compat.load_module(self.module_id, path)
  File "/mnt/HD/HD_a2/Nas_Prog/sickrage/lib/mako/compat.py", line 89, in load_module
    return imp.load_source(module_id, path, fp)
  File "/mnt/HD/HD_a2/Nas_Prog/sickrage/cache/mako/viewlogs.mako.py", line 19, in <module>
    from sickbeard.logger import LOGGING_LEVELS
ImportError: cannot import name LOGGING_LEVELS
 [abfff93]
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by brse** [comment]
### INFO
Python Version: **2.7.3 (default, Sep  4 2013, 13:54:56) [GCC 4.6.4 20120731 (prerelease)]**
Operating System: **Linux-3.2.40-armv7l-with-glibc2.4**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@abfff93b766d6b8eb81cb2ca4c410b795f5343e5
No Log available with ERRORS: 
### ERROR
```
Thread-17 :: Failed doing webui callback: Traceback (most recent call last):
  File "/mnt/HD/HD_a2/Nas_Prog/sickrage/sickbeard/webserve.py", line 271, in async_call
    raise HTTPError(404)
  File "/mnt/HD/HD_a2/Nas_Prog/sickrage/sickbeard/webserve.py", line 5143, in viewlog
    if match:
  File "/mnt/HD/HD_a2/Nas_Prog/sickrage/sickbeard/webserve.py", line 118, in __init__
    class PageTemplate(MakoTemplate):
  File "/mnt/HD/HD_a2/Nas_Prog/sickrage/lib/mako/lookup.py", line 256, in get_template
    return self._load(srcfile, uri)
  File "/mnt/HD/HD_a2/Nas_Prog/sickrage/lib/mako/lookup.py", line 321, in _load
    **self.template_args)
  File "/mnt/HD/HD_a2/Nas_Prog/sickrage/lib/mako/template.py", line 322, in __init__
    module = self._compile_from_file(path, filename)
  File "/mnt/HD/HD_a2/Nas_Prog/sickrage/lib/mako/template.py", line 379, in _compile_from_file
    module = compat.load_module(self.module_id, path)
  File "/mnt/HD/HD_a2/Nas_Prog/sickrage/lib/mako/compat.py", line 89, in load_module
    return imp.load_source(module_id, path, fp)
  File "/mnt/HD/HD_a2/Nas_Prog/sickrage/cache/mako/viewlogs.mako.py", line 19, in <module>
    from sickbeard.logger import LOGGING_LEVELS
ImportError: cannot import name LOGGING_LEVELS
 [abfff93]
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by labrys** [comment]
@fernandog until shutdown and restart, yes.

**Comment by fernandog** [comment]
8000 issues lol. glad I blocked
