### ISSUE TITLE
[APP SUBMITTED]: 'unicode' object has no attribute 'decompose'

### ISSUE THREAD

**Issue by MaDTaZ** [SickRage/sickrage-issues#499]
### INFO
Python Version: **2.7.6 (default, Jun 22 2015, 17:58:13) [GCC 4.8.2]**
Operating System: **Linux-3.13.0-37-generic-x86_64-with-LinuxMint-17.1-rebecca**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@abfff93b766d6b8eb81cb2ca4c410b795f5343e5
Link to Log: https://gist.github.com/cdce0d601c4033d51ddb
### ERROR
```
SEARCHQUEUE-MANUAL-256825 :: [Piratenzb] :: Error while searching Piratenzb, skipping: 'unicode' object has no attribute 'decompose' [abfff93]
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by SickRage2** [comment]
Thanks for the issue report! Before a real human comes by, please make sure your report has all the below criteria checked

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [x] Post debug logs, either inline (for smaller logs) or using gist)

Please make sure you also read [how to create an issue](https://github.com/SickRage/sickrage-issues/blob/master/README.md) and followed all of the steps. 

The title should describe your issue. Having "SR not working" or "I get this bug" for 100 issues, isn't really helpful. We will close issues if there isn't enough information.

Sometimes the devs may seem like grunts and respond with short answers. This isn't (always) because the dev hates you, but because he's on mobile or busy fixing bugs. If something isn't clear, please let us know, and this bot may get updated to automatically answer you.

Thanks!

**Comment by MaDTaZ** [comment]
### INFO
Python Version: **2.7.6 (default, Jun 22 2015, 17:58:13) [GCC 4.8.2]**
Operating System: **Linux-3.13.0-37-generic-x86_64-with-LinuxMint-17.1-rebecca**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@abfff93b766d6b8eb81cb2ca4c410b795f5343e5
Link to Log: https://gist.github.com/eea5db7c304b62e81f24
### ERROR
```
SEARCHQUEUE-MANUAL-256825 :: [NZBID] :: Error while searching NZBID, skipping: 'unicode' object has no attribute 'decompose' [abfff93]
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by MaDTaZ** [comment]
### INFO
Python Version: **2.7.6 (default, Jun 22 2015, 17:58:13) [GCC 4.8.2]**
Operating System: **Linux-3.13.0-37-generic-x86_64-with-LinuxMint-17.1-rebecca**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@abfff93b766d6b8eb81cb2ca4c410b795f5343e5
Link to Log: https://gist.github.com/884893e909b0e7743051
### ERROR
```
SEARCHQUEUE-MANUAL-256825 :: [www.nzbfinder.ws] :: Error while searching www.nzbfinder.ws, skipping: 'unicode' object has no attribute 'decompose' [abfff93]
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by MaDTaZ** [comment]
### INFO
Python Version: **2.7.6 (default, Jun 22 2015, 17:58:13) [GCC 4.8.2]**
Operating System: **Linux-3.13.0-37-generic-x86_64-with-LinuxMint-17.1-rebecca**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@abfff93b766d6b8eb81cb2ca4c410b795f5343e5
Link to Log: https://gist.github.com/359dfdee2fffc589977c
### ERROR
```
SEARCHQUEUE-MANUAL-295759 :: [Piratenzb] :: Error while searching Piratenzb, skipping: 'unicode' object has no attribute 'decompose' [abfff93]
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by MaDTaZ** [comment]
### INFO
Python Version: **2.7.6 (default, Jun 22 2015, 17:58:13) [GCC 4.8.2]**
Operating System: **Linux-3.13.0-37-generic-x86_64-with-LinuxMint-17.1-rebecca**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@abfff93b766d6b8eb81cb2ca4c410b795f5343e5
Link to Log: https://gist.github.com/011b0bb2f86addae7556
### ERROR
```
SEARCHQUEUE-MANUAL-295759 :: [NZBID] :: Error while searching NZBID, skipping: 'unicode' object has no attribute 'decompose' [abfff93]
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by MaDTaZ** [comment]
### INFO
Python Version: **2.7.6 (default, Jun 22 2015, 17:58:13) [GCC 4.8.2]**
Operating System: **Linux-3.13.0-37-generic-x86_64-with-LinuxMint-17.1-rebecca**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@abfff93b766d6b8eb81cb2ca4c410b795f5343e5
Link to Log: https://gist.github.com/1dd9d8872eb02baabba9
### ERROR
```
SEARCHQUEUE-MANUAL-295759 :: [www.nzbfinder.ws] :: Error while searching www.nzbfinder.ws, skipping: 'unicode' object has no attribute 'decompose' [abfff93]
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by rmilyard** [comment]
### INFO
Python Version: **2.7.9 (default, Sep  9 2015, 14:50:03) [GCC 4.2.1 20070831 patched [FreeBSD]]**
Operating System: **FreeBSD-9.1-RELEASE-amd64-64bit-ELF**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@abfff93b766d6b8eb81cb2ca4c410b795f5343e5
Link to Log: https://gist.github.com/b610eaab8399aa28761a
### ERROR
```
SEARCHQUEUE-BACKLOG-166991 :: [nzbplanet] :: Error while searching nzbplanet, skipping: 'unicode' object has no attribute 'decompose' [abfff93]
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by rmilyard** [comment]
### INFO
Python Version: **2.7.9 (default, Sep  9 2015, 14:50:03) [GCC 4.2.1 20070831 patched [FreeBSD]]**
Operating System: **FreeBSD-9.1-RELEASE-amd64-64bit-ELF**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@abfff93b766d6b8eb81cb2ca4c410b795f5343e5
No Log available with ERRORS:
### ERROR
```
SEARCHQUEUE-BACKLOG-72023 :: [nzbplanet] :: Error while searching nzbplanet, skipping: 'unicode' object has no attribute 'decompose' [abfff93]
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by rmilyard** [comment]
### INFO
Python Version: **2.7.9 (default, Sep  9 2015, 14:50:03) [GCC 4.2.1 20070831 patched [FreeBSD]]**
Operating System: **FreeBSD-9.1-RELEASE-amd64-64bit-ELF**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@abfff93b766d6b8eb81cb2ca4c410b795f5343e5
No Log available with ERRORS:
### ERROR
```
SEARCHQUEUE-BACKLOG-166991 :: [nzbplanet] :: Error while searching nzbplanet, skipping: 'unicode' object has no attribute 'decompose' [abfff93]
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by rmilyard** [comment]
### INFO
Python Version: **2.7.9 (default, Sep  9 2015, 14:50:03) [GCC 4.2.1 20070831 patched [FreeBSD]]**
Operating System: **FreeBSD-9.1-RELEASE-amd64-64bit-ELF**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@abfff93b766d6b8eb81cb2ca4c410b795f5343e5
No Log available with ERRORS:
### ERROR
```
SEARCHQUEUE-BACKLOG-248835 :: [nzbplanet] :: Error while searching nzbplanet, skipping: 'unicode' object has no attribute 'decompose' [abfff93]
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by rmilyard** [comment]
### INFO
Python Version: **2.7.9 (default, Sep  9 2015, 14:50:03) [GCC 4.2.1 20070831 patched [FreeBSD]]**
Operating System: **FreeBSD-9.1-RELEASE-amd64-64bit-ELF**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@abfff93b766d6b8eb81cb2ca4c410b795f5343e5
No Log available with ERRORS:
### ERROR
```
SEARCHQUEUE-BACKLOG-121361 :: [nzbplanet] :: Error while searching nzbplanet, skipping: 'unicode' object has no attribute 'decompose' [abfff93]
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by XxUnkn0wnxX** [comment]
### INFO
Python Version: **2.7.11 (default, Dec  5 2015, 14:44:53) [GCC 4.2.1 Compatible Apple LLVM 7.0.0 (clang-700.1.76)]**
Operating System: **Darwin-15.2.0-x86_64-i386-64bit**
Locale: None
Branch: **master**
Commit: SickRage/SickRage@abfff93b766d6b8eb81cb2ca4c410b795f5343e5
Link to Log: https://gist.github.com/d2156431a6ebb82444e2
### ERROR
```
SEARCHQUEUE-MANUAL-73388 :: [NZBNDX] :: Error while searching NZBNDX, skipping: 'unicode' object has no attribute 'decompose' [abfff93]
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by XxUnkn0wnxX** [comment]
### INFO
Python Version: **2.7.11 (default, Dec  5 2015, 14:44:53) [GCC 4.2.1 Compatible Apple LLVM 7.0.0 (clang-700.1.76)]**
Operating System: **Darwin-15.2.0-x86_64-i386-64bit**
Locale: None
Branch: **master**
Commit: SickRage/SickRage@abfff93b766d6b8eb81cb2ca4c410b795f5343e5
No Log available with ERRORS:
### ERROR
```
SEARCHQUEUE-RETRY-295828 :: [NZBNDX] :: Error while searching NZBNDX, skipping: 'unicode' object has no attribute 'decompose' [abfff93]
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by XxUnkn0wnxX** [comment]
### INFO
Python Version: **2.7.11 (default, Dec  5 2015, 14:44:53) [GCC 4.2.1 Compatible Apple LLVM 7.0.0 (clang-700.1.76)]**
Operating System: **Darwin-15.2.0-x86_64-i386-64bit**
Locale: None
Branch: **master**
Commit: SickRage/SickRage@abfff93b766d6b8eb81cb2ca4c410b795f5343e5
No Log available with ERRORS:
### ERROR
```
SEARCHQUEUE-RETRY-295828 :: [NZBid] :: Error while searching NZBid, skipping: 'unicode' object has no attribute 'decompose' [abfff93]
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by XxUnkn0wnxX** [comment]
### INFO
Python Version: **2.7.11 (default, Dec  5 2015, 14:44:53) [GCC 4.2.1 Compatible Apple LLVM 7.0.0 (clang-700.1.76)]**
Operating System: **Darwin-15.2.0-x86_64-i386-64bit**
Locale: None
Branch: **master**
Commit: SickRage/SickRage@abfff93b766d6b8eb81cb2ca4c410b795f5343e5
No Log available with ERRORS:
### ERROR
```
SEARCHQUEUE-RETRY-295828 :: [NZBFinder] :: Error while searching NZBFinder, skipping: 'unicode' object has no attribute 'decompose' [abfff93]
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by XxUnkn0wnxX** [comment]
### INFO
Python Version: **2.7.11 (default, Dec  5 2015, 14:44:53) [GCC 4.2.1 Compatible Apple LLVM 7.0.0 (clang-700.1.76)]**
Operating System: **Darwin-15.2.0-x86_64-i386-64bit**
Locale: None
Branch: **master**
Commit: SickRage/SickRage@abfff93b766d6b8eb81cb2ca4c410b795f5343e5
No Log available with ERRORS:
### ERROR
```
SEARCHQUEUE-RETRY-295828 :: [NZBPlanet] :: Error while searching NZBPlanet, skipping: 'unicode' object has no attribute 'decompose' [abfff93]
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by joakim93** [comment]
### INFO
Python Version: **2.7.9 (default, Sep  9 2015, 14:50:03) [GCC 4.2.1 20070831 patched [FreeBSD]]**
Operating System: **FreeBSD-9.3-RELEASE-p28-amd64-64bit-ELF**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@af9a7fd04d3a80f16cc51ae9aa123fa1b452fd0c
Link to Log: https://gist.github.com/f21ffa722e2c2616a002
### ERROR
```
SEARCHQUEUE-RETRY-281551 :: [Drunkenslug] :: Error while searching Drunkenslug, skipping: 'unicode' object has no attribute 'decompose' [af9a7fd]
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by joakim93** [comment]
### INFO
Python Version: **2.7.9 (default, Sep  9 2015, 14:50:03) [GCC 4.2.1 20070831 patched [FreeBSD]]**
Operating System: **FreeBSD-9.3-RELEASE-p28-amd64-64bit-ELF**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@af9a7fd04d3a80f16cc51ae9aa123fa1b452fd0c
Link to Log: https://gist.github.com/b7aa460b2807b344a346
### ERROR
```
SEARCHQUEUE-BACKLOG-289096 :: [Drunkenslug] :: Error while searching Drunkenslug, skipping: 'unicode' object has no attribute 'decompose' [af9a7fd]
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by joakim93** [comment]
### INFO
Python Version: **2.7.9 (default, Sep  9 2015, 14:50:03) [GCC 4.2.1 20070831 patched [FreeBSD]]**
Operating System: **FreeBSD-9.3-RELEASE-p28-amd64-64bit-ELF**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@af9a7fd04d3a80f16cc51ae9aa123fa1b452fd0c
Link to Log: https://gist.github.com/fbadee2bc22cd3356563
### ERROR
```
SEARCHQUEUE-BACKLOG-295684 :: [Drunkenslug] :: Error while searching Drunkenslug, skipping: 'unicode' object has no attribute 'decompose' [af9a7fd]
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by andrelx** [comment]
### INFO
Python Version: **2.7.10 (default, Jul  8 2015, 08:04:18) [GCC 4.3.6]**
Operating System: **Linux-3.12.6-x86_64-with-glibc2.0**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@af9a7fd04d3a80f16cc51ae9aa123fa1b452fd0c
Link to Log: https://gist.github.com/5db099ef2e203fa91a19
### ERROR
```
SEARCHQUEUE-BACKLOG-248569 :: [NZB.IS] :: Error while searching NZB.IS, skipping: 'unicode' object has no attribute 'decompose' [af9a7fd]
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by andrelx** [comment]
### INFO
Python Version: **2.7.10 (default, Jul  8 2015, 08:04:18) [GCC 4.3.6]**
Operating System: **Linux-3.12.6-x86_64-with-glibc2.0**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@af9a7fd04d3a80f16cc51ae9aa123fa1b452fd0c
No Log available with ERRORS:
### ERROR
```
SEARCHQUEUE-BACKLOG-270633 :: [NZB.IS] :: Error while searching NZB.IS, skipping: 'unicode' object has no attribute 'decompose' [af9a7fd]
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by andrelx** [comment]
### INFO
Python Version: **2.7.10 (default, Jul  8 2015, 08:04:18) [GCC 4.3.6]**
Operating System: **Linux-3.12.6-x86_64-with-glibc2.0**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@af9a7fd04d3a80f16cc51ae9aa123fa1b452fd0c
No Log available with ERRORS:
### ERROR
```
SEARCHQUEUE-BACKLOG-277165 :: [NZB.IS] :: Error while searching NZB.IS, skipping: 'unicode' object has no attribute 'decompose' [af9a7fd]
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by andrelx** [comment]
### INFO
Python Version: **2.7.10 (default, Jul  8 2015, 08:04:18) [GCC 4.3.6]**
Operating System: **Linux-3.12.6-x86_64-with-glibc2.0**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@af9a7fd04d3a80f16cc51ae9aa123fa1b452fd0c
No Log available with ERRORS:
### ERROR
```
SEARCHQUEUE-BACKLOG-271910 :: [NZB.IS] :: Error while searching NZB.IS, skipping: 'unicode' object has no attribute 'decompose' [af9a7fd]
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by andrelx** [comment]
### INFO
Python Version: **2.7.10 (default, Jul  8 2015, 08:04:18) [GCC 4.3.6]**
Operating System: **Linux-3.12.6-x86_64-with-glibc2.0**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@af9a7fd04d3a80f16cc51ae9aa123fa1b452fd0c
No Log available with ERRORS:
### ERROR
```
SEARCHQUEUE-BACKLOG-179871 :: [NZB.IS] :: Error while searching NZB.IS, skipping: 'unicode' object has no attribute 'decompose' [af9a7fd]
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by andrelx** [comment]
### INFO
Python Version: **2.7.10 (default, Jul  8 2015, 08:04:18) [GCC 4.3.6]**
Operating System: **Linux-3.12.6-x86_64-with-glibc2.0**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@af9a7fd04d3a80f16cc51ae9aa123fa1b452fd0c
No Log available with ERRORS:
### ERROR
```
SEARCHQUEUE-BACKLOG-261633 :: [NZB.IS] :: Error while searching NZB.IS, skipping: 'unicode' object has no attribute 'decompose' [af9a7fd]
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by andrelx** [comment]
### INFO
Python Version: **2.7.10 (default, Jul  8 2015, 08:04:18) [GCC 4.3.6]**
Operating System: **Linux-3.12.6-x86_64-with-glibc2.0**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@af9a7fd04d3a80f16cc51ae9aa123fa1b452fd0c
No Log available with ERRORS:
### ERROR
```
SEARCHQUEUE-BACKLOG-270408 :: [NZB.IS] :: Error while searching NZB.IS, skipping: 'unicode' object has no attribute 'decompose' [af9a7fd]
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by andrelx** [comment]
### INFO
Python Version: **2.7.10 (default, Jul  8 2015, 08:04:18) [GCC 4.3.6]**
Operating System: **Linux-3.12.6-x86_64-with-glibc2.0**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@af9a7fd04d3a80f16cc51ae9aa123fa1b452fd0c
No Log available with ERRORS:
### ERROR
```
SEARCHQUEUE-BACKLOG-75450 :: [NZB.IS] :: Error while searching NZB.IS, skipping: 'unicode' object has no attribute 'decompose' [af9a7fd]
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by andrelx** [comment]
### INFO
Python Version: **2.7.10 (default, Jul  8 2015, 08:04:18) [GCC 4.3.6]**
Operating System: **Linux-3.12.6-x86_64-with-glibc2.0**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@af9a7fd04d3a80f16cc51ae9aa123fa1b452fd0c
No Log available with ERRORS:
### ERROR
```
SEARCHQUEUE-BACKLOG-259063 :: [NZB.IS] :: Error while searching NZB.IS, skipping: 'unicode' object has no attribute 'decompose' [af9a7fd]
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by andrelx** [comment]
### INFO
Python Version: **2.7.10 (default, Jul  8 2015, 08:04:18) [GCC 4.3.6]**
Operating System: **Linux-3.12.6-x86_64-with-glibc2.0**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@af9a7fd04d3a80f16cc51ae9aa123fa1b452fd0c
No Log available with ERRORS:
### ERROR
```
SEARCHQUEUE-BACKLOG-261557 :: [NZB.IS] :: Error while searching NZB.IS, skipping: 'unicode' object has no attribute 'decompose' [af9a7fd]
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by andrelx** [comment]
### INFO
Python Version: **2.7.10 (default, Jul  8 2015, 08:04:18) [GCC 4.3.6]**
Operating System: **Linux-3.12.6-x86_64-with-glibc2.0**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@af9a7fd04d3a80f16cc51ae9aa123fa1b452fd0c
No Log available with ERRORS:
### ERROR
```
SEARCHQUEUE-BACKLOG-262980 :: [NZB.IS] :: Error while searching NZB.IS, skipping: 'unicode' object has no attribute 'decompose' [af9a7fd]
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by andrelx** [comment]
### INFO
Python Version: **2.7.10 (default, Jul  8 2015, 08:04:18) [GCC 4.3.6]**
Operating System: **Linux-3.12.6-x86_64-with-glibc2.0**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@af9a7fd04d3a80f16cc51ae9aa123fa1b452fd0c
No Log available with ERRORS:
### ERROR
```
SEARCHQUEUE-BACKLOG-248837 :: [NZB.IS] :: Error while searching NZB.IS, skipping: 'unicode' object has no attribute 'decompose' [af9a7fd]
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by andrelx** [comment]
### INFO
Python Version: **2.7.10 (default, Jul  8 2015, 08:04:18) [GCC 4.3.6]**
Operating System: **Linux-3.12.6-x86_64-with-glibc2.0**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@af9a7fd04d3a80f16cc51ae9aa123fa1b452fd0c
No Log available with ERRORS:
### ERROR
```
SEARCHQUEUE-BACKLOG-255316 :: [NZB.IS] :: Error while searching NZB.IS, skipping: 'unicode' object has no attribute 'decompose' [af9a7fd]
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by andrelx** [comment]
### INFO
Python Version: **2.7.10 (default, Jul  8 2015, 08:04:18) [GCC 4.3.6]**
Operating System: **Linux-3.12.6-x86_64-with-glibc2.0**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@af9a7fd04d3a80f16cc51ae9aa123fa1b452fd0c
No Log available with ERRORS:
### ERROR
```
SEARCHQUEUE-BACKLOG-248742 :: [NZB.IS] :: Error while searching NZB.IS, skipping: 'unicode' object has no attribute 'decompose' [af9a7fd]
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by cbrherms** [comment]
### INFO
Python Version: **2.7.9 (default, Sep  9 2015, 14:50:03) [GCC 4.2.1 20070831 patched [FreeBSD]]**
Operating System: **FreeBSD-9.1-RELEASE-amd64-64bit-ELF**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@af9a7fd04d3a80f16cc51ae9aa123fa1b452fd0c
Link to Log: https://gist.github.com/b6b4afd692a55e0b3c64
### ERROR
```
SEARCHQUEUE-BACKLOG-79824 :: [NZBs.io] :: Error while searching NZBs.io, skipping: 'unicode' object has no attribute 'decompose' [af9a7fd]
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by Ombouwleusden** [comment]
### INFO
Python Version: **2.7.11 (default, Dec 17 2015, 15:58:38) [GCC 4.7.3 20130102 (prerelease)]**
Operating System: **Linux-3.2.40-x86_64-with-glibc2.2.5**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@af9a7fd04d3a80f16cc51ae9aa123fa1b452fd0c
No Log available with ERRORS:
### ERROR
```
SEARCHQUEUE-BACKLOG-283318 :: [nzbid] :: Error while searching nzbid, skipping: 'unicode' object has no attribute 'decompose' [af9a7fd]
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by fernandog** [comment]
@miigotu is this fixed in develop?

**Comment by miigotu** [comment]
yes

**Comment by neoatomic** [comment]
I got this one when i woke up. : 

```
Dev, cur_commit = 09432b7d450e0e8296994e7d35ffbe2314855693
``` 

```
2016-01-18 12:10:35 INFO     SEARCHQUEUE-BACKLOG-81578 :: [nzbplanet.net] :: Performing episode search for Ax Men
2016-01-18 12:10:35 DEBUG    SEARCHQUEUE-BACKLOG-81578 :: [nzbplanet.net] :: Search Mode: Episode
2016-01-18 12:10:35 DEBUG    SEARCHQUEUE-BACKLOG-81578 :: [nzbplanet.net] :: Search string: Ax Men S09E09 
2016-01-18 12:10:35 DEBUG    SEARCHQUEUE-BACKLOG-81578 :: [nzbplanet.net] :: Search URL: http://api.nzbplanet.net/api?apikey=**********&tvdbid=81578&season=9&maxage=2&cat=5040&q=Ax+Men+S09E09&limit=100&t=tvsearch&offset=0&ep=9
2016-01-18 12:10:37 INFO     SEARCHQUEUE-BACKLOG-81578 :: [nzbplanet.net] :: Request limit reached
2016-01-18 12:10:37 ERROR    SEARCHQUEUE-BACKLOG-81578 :: [nzbplanet.net] :: Error while searching nzbplanet.net, skipping: 'unicode' object has no attribute 'decompose' [09432b7]
Traceback (most recent call last):
  File "/volume1/@appstore/sickrage/var/SickRage/sickbeard/search.py", line 494, in searchProviders
    searchResults = curProvider.find_search_results(show, episodes, search_mode, manualSearch, downCurQuality)
  File "/volume1/@appstore/sickrage/var/SickRage/sickrage/providers/GenericProvider.py", line 150, in find_search_results
    items_list += self.search(search_string, ep_obj=episode)
  File "/volume1/@appstore/sickrage/var/SickRage/sickbeard/providers/newznab.py", line 299, in search
    data.decompose()
AttributeError: 'unicode' object has no attribute 'decompose'
2016-01-18 12:10:37 DEBUG    SEARCHQUEUE-BACKLOG-81578 :: [nzbplanet.net] :: Traceback (most recent call last):
  File "/volume1/@appstore/sickrage/var/SickRage/sickbeard/search.py", line 494, in searchProviders
    searchResults = curProvider.find_search_results(show, episodes, search_mode, manualSearch, downCurQuality)
  File "/volume1/@appstore/sickrage/var/SickRage/sickrage/providers/GenericProvider.py", line 150, in find_search_results
    items_list += self.search(search_string, ep_obj=episode)
  File "/volume1/@appstore/sickrage/var/SickRage/sickbeard/providers/newznab.py", line 299, in search
    data.decompose()
AttributeError: 'unicode' object has no attribute 'decompose'
```
