### ISSUE TITLE
[APP SUBMITTED]: HTTP Error 400: Bad Request

### ISSUE THREAD

**Issue by duramato** [SickRage/sickrage-issues#507]
### INFO
Python Version: **2.7.6 (default, Jun 22 2015, 18:00:18) [GCC 4.8.2]**
Operating System: **Linux-3.19.0-43-generic-i686-with-Ubuntu-14.04-trusty**
Locale: UTF-8
Branch: **develop**
Commit: SickRage/SickRage@0b1191512f1f6f973b5bc60f4e6d8649ba367700
Link to Log: https://gist.github.com/2d50cf96e157e2affd51
### ERROR
```
Thread-13 :: Missing parameter(s). [0b11915]
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by SickRage2** [comment]
Thanks for the issue report! Before a real human comes by, please make sure your report has all the below criteria checked

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [x] Post debug logs, either inline (for smaller logs) or using gist)

Please make sure you also read [how to create an issue](https://github.com/SickRage/sickrage-issues/blob/master/README.md) and followed all of the steps. 

The title should describe your issue. Having "SR not working" or "I get this bug" for 100 issues, isn't really helpful. We will close issues if there isn't enough information.

Sometimes the devs may seem like grunts and respond with short answers. This isn't (always) because the dev hates you, but because he's on mobile or busy fixing bugs. If something isn't clear, please let us know, and this bot may get updated to automatically answer you.

Thanks!

**Comment by duramato** [comment]
### INFO
Python Version: **2.7.6 (default, Jun 22 2015, 18:00:18) [GCC 4.8.2]**
Operating System: **Linux-3.19.0-43-generic-i686-with-Ubuntu-14.04-trusty**
Locale: UTF-8
Branch: **develop**
Commit: SickRage/SickRage@0b1191512f1f6f973b5bc60f4e6d8649ba367700
Link to Log: https://gist.github.com/e89d4b644a86a8327816
### ERROR
```
POSTPROCESSER :: Missing parameter(s). [0b11915]
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by duramato** [comment]
@bencer

**Comment by duramato** [comment]
```
AAHTTPError: HTTP Error 400: Bad Request
AA    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
AA  File "/usr/lib/python2.7/urllib2.py", line 531, in http_error_default
AA    result = func(*args)
AA  File "/usr/lib/python2.7/urllib2.py", line 382, in _call_chain
AA    return self._call_chain(*args)
AA  File "/usr/lib/python2.7/urllib2.py", line 448, in error
AA    'http', request, response, code, msg, hdrs)
AA  File "/usr/lib/python2.7/urllib2.py", line 523, in http_response
AA    response = meth(req, response)
AA  File "/usr/lib/python2.7/urllib2.py", line 410, in open
AA    return _opener.open(url, data, timeout)
AA  File "/usr/lib/python2.7/urllib2.py", line 127, in urlopen
AA    urllib2.urlopen(req)
AA  File "/home/home/SickRage/sickbeard/notifiers/telegram.py", line 61, in _sendTelegramMsg
AATraceback (most recent call last):
2016-01-15 16:35:18 ERROR    Thread-46 :: Missing parameter(s). [0b11915]

2016-01-15 16:35:12 DEBUG    Thread-46 :: Telegram in use with API KEY: 153834970:AAFxFuKFUW_DghJomnXSfcq5VyOlM4A3oLk
2016-01-15 16:35:12 DEBUG    Thread-46 :: Sending a Telegram message for This is a test notification from SickRage
```

**Comment by bencer** [comment]
can you please make sure your bot API token and your USERID are valid with this command?
curl -v --data chat_id=YOUR_USER_ID --data-urlencode "text=test" "https://api.telegram.org/botYOUR_BOT_API_TOKEN/sendMessage"

**Comment by fernandog** [comment]
why closed @duramato?

**Comment by duramato** [comment]
The problem was that my name on telegram had a ç in it ,cahnging to c made it work.
Only thing that could be done on sr side would be read the erro message on the api response, feel free to reopen

**Comment by fernandog** [comment]
@miigotu should we test the API token and USERID using JS and not let save if is wrong?

**Comment by Cranium6** [comment]
### INFO
Python Version: **2.7.10 (default, May 23 2015, 09:44:00) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-8-6.2.9200**
Locale: cp1252
Branch: **master**
Commit: SickRage/SickRage@0a1f476a63c552ffd4aae3a9a1e7203ce8707540
No Log available with ERRORS:
### ERROR
```
POSTPROCESSER :: [0a1f476] Missing parameter(s).
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators
