### ISSUE TITLE
rtorrent connection to seedbox no longer works

### ISSUE THREAD

**Issue by thesau** [SickRage/sickrage-issues#515]
Connection to rtorrent on my seedbox has suddenly stopped working (since a few weeks I suspect).

Using sickrage on a synology NAS:
Branch: master
Commit: 5997b76596ce42b261f041d7daa12dc6934e024e
Version: v5.1.2

Not much useful info in the logs:
```
AA
AA>
AAHTTPError: 401 Client Error: Unauthorized for url: https://********.***.seedbox.com//rutorrent/plugins/httprpc/action.php
AA    raise HTTPError(http_error_msg, response=self)
AA  File "/usr/local/sickbeard-custom/var/SickBeard/lib/requests/models.py", line 837, in raise_for_status
AA    response.raise_for_status()
AA  File "/usr/local/sickbeard-custom/var/SickBeard/lib/rtorrent/lib/xmlrpc/requests_transport.py", line 145, in request
AAProtocolError:  The Big Bang Theory - S09E13 - The Empathy Optimization
AA
AA>
AAHTTPError: 401 Client Error: Unauthorized for url: https://********.***.seedbox.com//rutorrent/plugins/httprpc/action.php
AA    raise HTTPError(http_error_msg, response=self)
AA  File "/usr/local/sickbeard-custom/var/SickBeard/lib/requests/models.py", line 837, in raise_for_status
AA    response.raise_for_status()
AA  File "/usr/local/sickbeard-custom/var/SickBeard/lib/rtorrent/lib/xmlrpc/requests_transport.py", line 145, in request
AAProtocolError: 
```

**Comment by SickRage2** [comment]
Thanks for the issue report! Before a real human comes by, please make sure your report has all the below criteria checked

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [x] Post debug logs, either inline (for smaller logs) or using gist)
- [x] Please wrap inline logs inside \`\`\` and \`\`\` for readability

Please make sure you also read [how to create an issue](https://github.com/SickRage/sickrage-issues/blob/master/README.md) and followed all of the steps. 

The title should describe your issue. Having "SR not working" or "I get this bug" for 100 issues, isn't really helpful. We will close issues if there isn't enough information.

Sometimes the devs may seem like grunts and respond with short answers. This isn't (always) because the dev hates you, but because he's on mobile or busy fixing bugs. If something isn't clear, please let us know, and this bot may get updated to automatically answer you.

Thanks!

**Comment by adaur** [comment]
Hi,

Have you checked your credentials?

**Comment by neoatomic** [comment]
`https://********.***.seedbox.com//rutorrent/plugins/httprpc/action.php`
See if you can remove the double `//` from the URL and test again.

**Comment by thesau** [comment]
Yes I re-entered my credentials. 
I noticed the double backslash in the log. Howevet in the settings there is only a single one so I can't remove it.

**Comment by adaur** [comment]
What if you remove this single one?

**Comment by thesau** [comment]
Can't tell what kind of url it makes out of it when I removed that slash:
```
AA
AAUnboundLocalError: local variable 'response' referenced before assignment
AA    response.headers)
AA  File "/usr/local/sickbeard-custom/var/SickBeard/lib/rtorrent/lib/xmlrpc/requests_transport.py", line 150, in request
AA    verbose=self.__verbose
AA  File "/usr/local/python/lib/python2.7/xmlrpclib.py", line 1599, in __request
AA    return self.__send(self.__name, args)
AA  File "/usr/local/python/lib/python2.7/xmlrpclib.py", line 1240, in __call__
AA    self._rpc_methods = self._get_conn().system.listMethods()
AA  File "/usr/local/sickbeard-custom/var/SickBeard/lib/rtorrent/__init__.py", line 150, in _update_rpc_methods
AA    return(self._rpc_methods or self._update_rpc_methods())
AA  File "/usr/local/sickbeard-custom/var/SickBeard/lib/rtorrent/__init__.py", line 161, in _get_rpc_methods
AA    assert "system.client_version" in self._get_rpc_methods(
AA  File "/usr/local/sickbeard-custom/var/SickBeard/lib/rtorrent/__init__.py", line 122, in _verify_conn
AA    self._verify_conn()
AA  File "/usr/local/sickbeard-custom/var/SickBeard/lib/rtorrent/__init__.py", line 83, in __init__
AA    self.auth = RTorrent(self.host, self.username, self.password, True, tp_kwargs=tp_kwargs)
AA  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/clients/rtorrent_client.py", line 49, in _get_auth
AA    if not self._get_auth():
AA  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/clients/generic.py", line 177, in sendTORRENT
AA    dlResult = client.sendTORRENT(result)
AA  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/search.py", line 140, in snatchEpisode
AA    self.success = search.snatchEpisode(searchResult[0])
AA  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/search_queue.py", line 184, in run
2016-01-17 23:43:59 DEBUG    SEARCHQUEUE-MANUAL-80379 :: [Torrentz] :: Traceback (most recent call last):
2016-01-17 23:43:59 DEBUG    SEARCHQUEUE-MANUAL-80379 :: [Torrentz] :: Calling rTorrent Client
2016-01-17 23:43:58 INFO     SEARCHQUEUE-MANUAL-80379 :: [Torrentz] :: Downloading The.Big.Bang.Theory.S06E03.HDTV.x264.LOL from Torrentz
```

**Comment by miigotu** [comment]
Installing rtorrent and working a bit on the rtorrent client now. Will see if it is broken and if I can improve it some.

**Comment by thesau** [comment]
Thanks mate! It was working just fine until about early/mid December, if that helps? I was on the SickrageTV branch back then. Still broken in that branch last week when I switched.

**Comment by neoatomic** [comment]
Also try to use `http` instead of `https` for testing. Just to exclude any ssl related issues.
