### ISSUE TITLE
[APP SUBMITTED]: 401 {u'documentation_url': u'https://developer.github.com/v3', u'message': u'Bad credentials'}

### ISSUE THREAD

**Issue by udochrist** [SickRage/sickrage-issues#56]
### INFO
Python Version: **2.7.10 (default, Jun  3 2015, 20:43:13) [GCC 4.7.3 20130102 (prerelease)]**
Operating System: **Linux-3.10.35-x86_64-with-glibc2.2.5**
Locale: unknown
Branch: **master**
Commit: SickRage/SickRage@6cdb5420378f7ae944e087cc1e4272fccdb7fc41
Link to Log: https://gist.github.com/6e97b752f8e4abe5ad61
### ERROR
```
Thread-59 :: Traceback (most recent call last):
  File "/volume1/@appstore/sickrage/var/SickRage/sickbeard/logger.py", line 249, in submit_errors
    gist = gh.get_user().create_gist(True, {"sickrage.log": InputFileContent(paste_data)})
  File "/usr/local/sickrage/var/SickRage/lib/github/AuthenticatedUser.py", line 473, in create_gist
    input=post_parameters
  File "/usr/local/sickrage/var/SickRage/lib/github/Requester.py", line 171, in requestJsonAndCheck
    return self.__check(*self.requestJson(verb, url, parameters, headers, input, cnx))
  File "/usr/local/sickrage/var/SickRage/lib/github/Requester.py", line 179, in __check
    raise self.__createException(status, responseHeaders, output)
BadCredentialsException: 401 {u'documentation_url': u'https://developer.github.com/v3', u'message': u'Bad credentials'}

```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by duramato** [comment]
Wrong Github Login
