### ISSUE TITLE
[Dev] fatal: No names found, cannot describe anything. sickbeard-custom

### ISSUE THREAD

**Issue by neoatomic** [SickRage/sickrage-issues#561]
As i needed to update the wiki, i did a install with the Synocommunity's sickbear-custom package.
However came across an issue.
When i view the Help & info page i get `Version: fatal: No names found, cannot describe anything.` instead of a version number. And this was on a clean, and out of the box install.
However the Synocommunity's Sickrage package doesn't have this, and shows correctly the version number.

Looking at the log, SR gives me a SSL error. (yes on the Syno...) However i have a feeling that this might not be a real one, and more a code issue. 

```

2016-01-20 23:09:50 ERROR    Uncaught exception
Traceback (most recent call last):
  File "/usr/local/sickbeard-custom/var/SickBeard/lib/tornado/http1connection.py", line 693, in _server_request_loop
    ret = yield conn.read_response(request_delegate)
  File "/usr/local/sickbeard-custom/var/SickBeard/lib/tornado/gen.py", line 870, in run
    value = future.result()
  File "/usr/local/sickbeard-custom/var/SickBeard/lib/tornado/concurrent.py", line 215, in result
    raise_exc_info(self._exc_info)
  File "/usr/local/sickbeard-custom/var/SickBeard/lib/tornado/gen.py", line 876, in run
    yielded = self.gen.throw(*exc_info)
  File "/usr/local/sickbeard-custom/var/SickBeard/lib/tornado/http1connection.py", line 168, in _read_message
    quiet_exceptions=iostream.StreamClosedError)
  File "/usr/local/sickbeard-custom/var/SickBeard/lib/tornado/gen.py", line 870, in run
    value = future.result()
  File "/usr/local/sickbeard-custom/var/SickBeard/lib/tornado/concurrent.py", line 215, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 3, in raise_exc_info
SSLError: [SSL: TLSV1_ALERT_UNKNOWN_CA] tlsv1 alert unknown ca (_ssl.c:1751)

```

```
2016-01-20 23:29:10 ERROR    Thread-33 :: git fetch origin returned : error: cannot lock ref 'refs/remotes/origin/develop': ref refs/remotes/origin/develop is at 1d70b7e45a4806f7e0876f5ea2089e1fbd56a6a6 but expected f2dd6ac0451805764cfe33e6adc757d61ab27985
From https://github.com/SiCKRAGE/SickRage
 ! f2dd6ac..1d70b7e  develop    -> origin/develop  (unable to update local ref) [f2dd6ac]
None
2016-01-20 23:29:10 WARNING  Thread-33 :: Unable to contact github, can't check for update [f2dd6ac]
```

![11](https://cloud.githubusercontent.com/assets/7928052/12466132/83a69328-bfd2-11e5-888c-4b30830f66c3.png)

```
Python 2.7.11

System installed modules:
bcrypt==2.0.0
cffi==1.3.1
Cheetah==2.4.4
cryptography==1.1.2
enum34==1.1.1
idna==2.0
ipaddress==1.0.15
lxml==3.5.0
M2Crypto==0.22.3
MarkupSafe==0.23
msgpack-python==0.4.6
Pillow==3.0.0
PocketSphinx==0.8
psutil==3.3.0
pyalsa==1.0.29
pyasn1==0.1.9
PyAudio==0.2.9
pycparser==2.14
pycrypto==2.6.1
pycurl==7.19.5.3
pymongo==3.2
pyOpenSSL==0.15.1
PyYAML==3.11
pyzmq==15.1.0
six==1.10.0
SphinxBase==0.8
SQLAlchemy==1.0.10
Twisted==15.5.0
uWSGI==2.0.11.2
virtualenv==13.1.2
wheel==0.26.0
yenc==0.4.0
zope.interface==4.1.3
```

**Comment by SickRage2** [comment]
Thanks for the issue report! Before a real human comes by, please make sure your report has all the below criteria checked

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [x] Post debug logs, either inline (for smaller logs) or using gist)
- [x] Please wrap inline logs inside \`\`\` and \`\`\` for readability

Please make sure you also read [how to create an issue](https://github.com/SickRage/sickrage-issues/blob/master/README.md) and followed all of the steps. 

The title should describe your issue. Having "SR not working" or "I get this bug" for 100 issues, isn't really helpful. We will close issues if there isn't enough information.

Sometimes the devs may seem like grunts and respond with short answers. This isn't (always) because the dev hates you, but because he's on mobile or busy fixing bugs. If something isn't clear, please let us know, and this bot may get updated to automatically answer you.

Thanks!

**Comment by miigotu** [comment]
The ca certs are out of date. The SickRage package had some fixes for this.

**Comment by neoatomic** [comment]
That would explain the ssl error.
If we advice users to use the sickbeard-custom package we should see if we can get this fixed on Synocommunity/package then. Otherwise this will be generating support tickets. :(
