### ISSUE TITLE
[APP SUBMITTED]: 411

### ISSUE THREAD

**Issue by udochrist** [SickRage/sickrage-issues#57]
### INFO
Python Version: **2.7.10 (default, Jun  3 2015, 20:43:13) [GCC 4.7.3 20130102 (prerelease)]**
Operating System: **Linux-3.10.35-x86_64-with-glibc2.2.5**
Locale: unknown
Branch: **master**
Commit: SickRage/SickRage@6cdb5420378f7ae944e087cc1e4272fccdb7fc41
Link to Log: https://gist.github.com/4e7a8c103adfbe47f06a
### ERROR
```
Thread-48 :: Failed doing webui callback: Traceback (most recent call last):
  File "/volume1/@appstore/sickrage/var/SickRage/sickbeard/webserve.py", line 263, in async_call
    result = function(**kwargs)
  File "/volume1/@appstore/sickrage/var/SickRage/sickbeard/webserve.py", line 1959, in getManualSearchStatus
    episodes += getEpisodes(searchThread, searchstatus)
  File "/volume1/@appstore/sickrage/var/SickRage/sickbeard/webserve.py", line 1938, in getEpisodes
    'status': statusStrings[epObj.status],
  File "/volume1/@appstore/sickrage/var/SickRage/sickbeard/numdict.py", line 44, in __getitem__
    return self.__class__.__missing__(self, key)
  File "/volume1/@appstore/sickrage/var/SickRage/sickbeard/common.py", line 549, in __missing__
    raise KeyError(key)  # ... so the key is invalid
KeyError: 411

```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by fernandog** [comment]
@labrys related to your PR?

**Comment by miigotu** [comment]
This has already been fixed, or the key is really invalid, not sure which.
