### ISSUE TITLE
Error In Logs

### ISSUE THREAD

**Issue by Vodka2014** [SickRage/sickrage-issues#590]
Hi All

I have been getting this today in my logs.

Branch: master
Commit: 66fa37c556784fa3b41a06bb3043bd854d165c10
Version: 2016.01.20-1
Python Version:	2.7.11 (default, Dec 17 2015, 15:58:38) [GCC 4.7.3 20130102 (prerelease)]

```
2016-01-22 02:49:04 SEARCHQUEUE-BACKLOG-95491 :: [NZB.su] :: Traceback (most recent call last):
  File "/volume5/@appstore/sickrage/var/SickRage/sickbeard/helpers.py", line 1442, in getURL
    resp = session.get(url, timeout=timeout, allow_redirects=True, verify=session.verify)
  File "/usr/local/sickrage/var/SickRage/lib/requests/sessions.py", line 480, in get
    return self.request('GET', url, **kwargs)
  File "/usr/local/sickrage/var/SickRage/lib/requests/sessions.py", line 468, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/sickrage/var/SickRage/lib/requests/sessions.py", line 576, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/sickrage/var/SickRage/lib/requests/adapters.py", line 376, in send
    timeout=timeout
  File "/usr/local/sickrage/var/SickRage/lib/requests/packages/urllib3/connectionpool.py", line 559, in urlopen
    body=body, headers=headers)
  File "/usr/local/sickrage/var/SickRage/lib/requests/packages/urllib3/connectionpool.py", line 376, in _make_request
    httplib_response = conn.getresponse(buffering=True)
  File "/usr/local/python/lib/python2.7/httplib.py", line 1136, in getresponse
    response.begin()
  File "/usr/local/python/lib/python2.7/httplib.py", line 453, in begin
    version, status, reason = self._read_status()
  File "/usr/local/python/lib/python2.7/httplib.py", line 409, in _read_status
    line = self.fp.readline(_MAXLINE + 1)
  File "/usr/local/python/lib/python2.7/socket.py", line 480, in readline
    data = self._sock.recv(self._rbufsize)
  File "/usr/local/sickrage/var/SickRage/lib/requests/packages/urllib3/contrib/pyopenssl.py", line 196, in recv
    return self.recv(*args, **kwargs)
  File "/usr/local/sickrage/var/SickRage/lib/requests/packages/urllib3/contrib/pyopenssl.py", line 179, in recv
    data = self.connection.recv(*args, **kwargs)
  File "/usr/local/python/lib/python2.7/site-packages/OpenSSL/SSL.py", line 1320, in recv
    self._raise_ssl_error(self._ssl, result)
  File "/usr/local/python/lib/python2.7/site-packages/OpenSSL/SSL.py", line 1178, in _raise_ssl_error
    raise SysCallError(errno, errorcode.get(errno))
SysCallError: (104, 'ECONNRESET')
 [66fa37c]
```

**Comment by SickRage2** [comment]
Thanks for the issue report! Before a real human comes by, please make sure your report has all the below criteria checked

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [ ] Post debug logs, either inline (for smaller logs) or using gist)

Please make sure you also read [how to create an issue](https://github.com/SickRage/sickrage-issues/blob/master/README.md) and followed all of the steps. 

The title should describe your issue. Having "SR not working" or "I get this bug" for 100 issues, isn't really helpful. We will close issues if there isn't enough information.

Sometimes the devs may seem like grunts and respond with short answers. This isn't (always) because the dev hates you, but because he's on mobile or busy fixing bugs. If something isn't clear, please let us know, and this bot may get updated to automatically answer you.

Thanks!

**Comment by fernandog** [comment]
@miigotu can we do in helpers.py ?

```
from OpenSSL.SSL import SysCallError
.....
except SysCallError:
logger.log("......, logger.WARNING)
```

**Comment by neoatomic** [comment]
Al-trough this is an SSL error i think the url is probbebly not correct for nzb.su. I think its changed to api.nzb.su recently.?

**Comment by duramato** [comment]
Yup they are refusing api calls anywhere other than api.nzb.su

**Comment by miigotu** [comment]
Fix your url.

**Comment by Vodka2014** [comment]
URL has changed and i am getting files from it.

**Comment by Vodka2014** [comment]
http://api.nzb.su/ does not work but this does https://api.nzb.su/

**Comment by miigotu** [comment]
no shit

**Comment by Vodka2014** [comment]
So then why am i getting the errors ?

**Comment by duramato** [comment]
@Vodka2014 You get errors becouse you need to change the url :/

**Comment by Vodka2014** [comment]
I did change the URL this is the point i am making.

**Comment by duramato** [comment]
You will need to contact them then, this isnt a SR issue 
It might also be an issue on your internet connection

**Comment by Vodka2014** [comment]
Sure will do thanks
