### ISSUE TITLE
[APP SUBMITTED]: 'NoneType' object has no attribute 'encode'

### ISSUE THREAD

**Issue by raistlin2912** [SickRage/sickrage-issues#60]
### INFO
Python Version: **2.7.3 (default, Mar 13 2014, 11:03:55) [GCC 4.7.2]**
Operating System: **Linux-3.2.0-4-amd64-x86_64-with-debian-7.9**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@6752769ac0828a51191f18f48bd6a47c47fb6998
Link to Log: https://gist.github.com/cac224438759d8e0db1b
### ERROR
```
Thread-14 :: Failed doing webui callback: Traceback (most recent call last):
  File "/opt/sickrage/sickbeard/webserve.py", line 263, in async_call
    result = function(**kwargs)
  File "/opt/sickrage/sickbeard/webserve.py", line 1042, in testPushbullet
    result = notifiers.pushbullet_notifier.test_notify(api)
  File "/opt/sickrage/sickbeard/notifiers/pushbullet.py", line 44, in test_notify
    return self._sendPushbullet(pushbullet_api, event=self.TEST_EVENT, message="Testing Pushbullet settings from SickRage")
  File "/opt/sickrage/sickbeard/notifiers/pushbullet.py", line 87, in _sendPushbullet
    }) if event else None
AttributeError: 'NoneType' object has no attribute 'encode'

```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by raistlin2912** [comment]
### INFO
Python Version: **2.7.3 (default, Mar 13 2014, 11:03:55) [GCC 4.7.2]**
Operating System: **Linux-3.2.0-4-amd64-x86_64-with-debian-7.9**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@6752769ac0828a51191f18f48bd6a47c47fb6998
Link to Log: https://gist.github.com/731ddd7ca34283e3d35b
### ERROR
```
Thread-39 :: Failed doing webui callback: Traceback (most recent call last):
  File "/opt/sickrage/sickbeard/webserve.py", line 263, in async_call
    result = function(**kwargs)
  File "/opt/sickrage/sickbeard/webserve.py", line 1042, in testPushbullet
    result = notifiers.pushbullet_notifier.test_notify(api)
  File "/opt/sickrage/sickbeard/notifiers/pushbullet.py", line 44, in test_notify
    return self._sendPushbullet(pushbullet_api, event=self.TEST_EVENT, message="Testing Pushbullet settings from SickRage")
  File "/opt/sickrage/sickbeard/notifiers/pushbullet.py", line 87, in _sendPushbullet
    }) if event else None
AttributeError: 'NoneType' object has no attribute 'encode'

```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by raistlin2912** [comment]
### INFO
Python Version: **2.7.3 (default, Mar 13 2014, 11:03:55) [GCC 4.7.2]**
Operating System: **Linux-3.2.0-4-amd64-x86_64-with-debian-7.9**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@6752769ac0828a51191f18f48bd6a47c47fb6998
Link to Log: https://gist.github.com/3c65274175c74622bff1
### ERROR
```
Thread-21 :: Failed doing webui callback: Traceback (most recent call last):
  File "/opt/sickrage/sickbeard/webserve.py", line 263, in async_call
    result = function(**kwargs)
  File "/opt/sickrage/sickbeard/webserve.py", line 1042, in testPushbullet
    result = notifiers.pushbullet_notifier.test_notify(api)
  File "/opt/sickrage/sickbeard/notifiers/pushbullet.py", line 44, in test_notify
    return self._sendPushbullet(pushbullet_api, event=self.TEST_EVENT, message="Testing Pushbullet settings from SickRage")
  File "/opt/sickrage/sickbeard/notifiers/pushbullet.py", line 87, in _sendPushbullet
    }) if event else None
AttributeError: 'NoneType' object has no attribute 'encode'

```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by tonyp1983** [comment]
### INFO
Python Version: **2.7.9 (default, Sep  9 2015, 14:50:03) [GCC 4.2.1 20070831 patched [FreeBSD]]**
Operating System: **FreeBSD-9.1-RELEASE-amd64-64bit-ELF**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@c575707408313497ee391e761f0164fe574a3c6f
Link to Log: https://gist.github.com/1bfe1f2568bb3237be59
### ERROR
```
Thread-51 :: Failed doing webui callback: Traceback (most recent call last):
  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/sickbeard/webserve.py", line 265, in async_call
    result = function(**kwargs)
  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/sickbeard/webserve.py", line 1073, in testPushbullet
    result = notifiers.pushbullet_notifier.test_notify(api)
  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/sickbeard/notifiers/pushbullet.py", line 44, in test_notify
    return self._sendPushbullet(pushbullet_api, event=self.TEST_EVENT, message="Testing Pushbullet settings from SickRage")
  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/sickbeard/notifiers/pushbullet.py", line 85, in _sendPushbullet
    'device_iden': pushbullet_device.encode('utf-8'),
AttributeError: 'NoneType' object has no attribute 'encode'

```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by utdrmac** [comment]
Just cloned a fresh, first-time, install. Attempted to test out PushBullet support. Got this error:

Branch: master
Commit: 66fa37c556784fa3b41a06bb3043bd854d165c10
Version: 2016.01.20-1
Python Version:	2.7.3 (default, Mar 13 2014, 11:03:55) [GCC 4.7.2]

```
2016-01-22 23:10:16 Thread-15 :: Failed doing webui callback: Traceback (most recent call last):
  File "/apps/sickrage/sickbeard/webserve.py", line 281, in async_call
    result = function(**kwargs)
  File "/apps/sickrage/sickbeard/webserve.py", line 1104, in testPushbullet
    result = notifiers.pushbullet_notifier.test_notify(api)
  File "/apps/sickrage/sickbeard/notifiers/pushbullet.py", line 46, in test_notify
    return self._sendPushbullet(pushbullet_api, event=self.TEST_EVENT, message="Testing Pushbullet settings from SickRage")
  File "/apps/sickrage/sickbeard/notifiers/pushbullet.py", line 91, in _sendPushbullet
    'device_iden': pushbullet_device.encode('utf-8'),
AttributeError: 'NoneType' object has no attribute 'encode'
 [66fa37c]
```

**Comment by miigotu** [comment]
Try selecting the device you want to send to in the notifier settings before clicking test.

**Comment by utdrmac** [comment]
@miigotu I did select my device for the test last night when it failed. Seems gremlins are real. Woke up this morning and clicked test again, this time it succeeded.

**Comment by porkchop34** [comment]
### INFO
Python Version: **2.7.11 (v2.7.11:6d1b6a68f775, Dec  5 2015, 20:40:30) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-7-6.1.7601-SP1**
Locale: cp1252
Branch: **master**
Commit: SickRage/SickRage@7a94dd094c2861d54f500c39af5fb2cdb856dfdc
No Log available with ERRORS:
### ERROR
```
Thread-33 :: Failed doing webui callback: Traceback (most recent call last):
  File "C:\SickRage\sickbeard\webserve.py", line 283, in async_call
    result = function(**kwargs)
  File "C:\SickRage\sickbeard\webserve.py", line 1106, in testPushbullet
    result = notifiers.pushbullet_notifier.test_notify(api)
  File "C:\SickRage\sickbeard\notifiers\pushbullet.py", line 46, in test_notify
    return self._sendPushbullet(pushbullet_api, event=self.TEST_EVENT, message="Testing Pushbullet settings from SickRage")
  File "C:\SickRage\sickbeard\notifiers\pushbullet.py", line 91, in _sendPushbullet
    'device_iden': pushbullet_device.encode('utf-8'),
AttributeError: 'NoneType' object has no attribute 'encode'
 [7a94dd0]
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by Atmannen** [comment]
### INFO
Python Version: **2.7.11 (default, Dec 17 2015, 15:58:38) [GCC 4.7.3 20130102 (prerelease)]**
Operating System: **Linux-3.10.35-x86_64-with-glibc2.2.5**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@e44f3ea56ed7150bbc18e3312f0eb1442ef724bf
No Log available with ERRORS:
### ERROR
```
Thread-13 :: Failed doing webui callback: Traceback (most recent call last):
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/webserve.py", line 283, in async_call
    result = function(**kwargs)
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/webserve.py", line 1106, in testPushbullet
    result = notifiers.pushbullet_notifier.test_notify(api)
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/notifiers/pushbullet.py", line 46, in test_notify
    return self._sendPushbullet(pushbullet_api, event=self.TEST_EVENT, message="Testing Pushbullet settings from SickRage")
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/notifiers/pushbullet.py", line 91, in _sendPushbullet
    'device_iden': pushbullet_device.encode('utf-8'),
AttributeError: 'NoneType' object has no attribute 'encode'
 [e44f3ea]
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators
