### ISSUE TITLE
[APP SUBMITTED]: 500 {u'documentation_url': u'https://developer.github.com/v3/gists/#create-a-gist', u'message': u'Server Error'}

### ISSUE THREAD

**Issue by megabitus98** [SickRage/sickrage-issues#607]
### INFO
Python Version: **2.7.11 (v2.7.11:6d1b6a68f775, Dec  5 2015, 20:40:30) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-10-10.0.10586**
Locale: cp1252
Branch: **master**
Commit: SickRage/SickRage@66fa37c556784fa3b41a06bb3043bd854d165c10
No Log available with ERRORS:
### ERROR
```
Thread-54 :: Traceback (most recent call last):
  File "J:\SickRage\sickbeard\logger.py", line 293, in submit_errors
    gist = git.get_user().create_gist(True, {'sickrage.log': InputFileContent(paste_data)})
  File "J:\SickRage\lib\github\AuthenticatedUser.py", line 473, in create_gist
    input=post_parameters
  File "J:\SickRage\lib\github\Requester.py", line 171, in requestJsonAndCheck
    return self.__check(*self.requestJson(verb, url, parameters, headers, input, cnx))
  File "J:\SickRage\lib\github\Requester.py", line 179, in __check
    raise self.__createException(status, responseHeaders, output)
GithubException: 500 {u'documentation_url': u'https://developer.github.com/v3/gists/#create-a-gist', u'message': u'Server Error'}
 [66fa37c]
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by SickRage2** [comment]
Thanks for the issue report! Before a real human comes by, please make sure your report has all the below criteria checked

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [ ] Post debug logs, either inline (for smaller logs) or using gist)

Please make sure you also read [how to create an issue](https://github.com/SickRage/sickrage-issues/blob/master/README.md) and followed all of the steps. 

The title should describe your issue. Having "SR not working" or "I get this bug" for 100 issues, isn't really helpful. We will close issues if there isn't enough information.

Sometimes the devs may seem like grunts and respond with short answers. This isn't (always) because the dev hates you, but because he's on mobile or busy fixing bugs. If something isn't clear, please let us know, and this bot may get updated to automatically answer you.

Thanks!

**Comment by miigotu** [comment]
Server error. Sorry we cant control github servers =P

**Comment by megabitus98** [comment]
Oh, ok thanks but I got that error when i tries to submit these 
```
2016-01-23 09:45:33 FINDSUBTITLES :: Unable to find subtitles for Heavy Object S01E07. Error: charmap : E:\Animes\Heavy Object\Season 01\Heavy Object - S01E07 - The War of the Ant and the Grasshopper ã€œThe War to Capture the Oceania Military Power â… Iã€œ - 1080p HDTV.mkv : error 96 : error 97 : character maps to  [3f5939e]
2016-01-23 09:45:32 FINDSUBTITLES :: Unable to find subtitles for Heavy Object S01E13. Error: charmap : E:\Animes\Heavy Object\Season 01\Heavy Object - S01E13 - In a Calvary Battle, You Must Break Their Foothold ï½žAmazon City All-Out War Iï½ž - 1080p HDTV.mkv : error 108 : error 109 : character maps to  [3f5939e]
```

**Comment by miigotu** [comment]
@medariox clues?

**Comment by medariox** [comment]
@megabitus98 
Which subtitles provider(s) are you using? Can you please post your debug logs with the above error?

**Comment by megabitus98** [comment]
@medariox Here is the [sickrage.log](http://pastebin.com/YeUGQfsc), and I'm using all the subtitle providers except Legendastv, also have accounts for Addic7ed and Opensubtitles, if it changes anything. Not sure if the logs are debug logs.

**Comment by medariox** [comment]
@megabitus98 
That's indeed what causes the error.
I still don't know if it is a SR or subliminal problem, will try out a few things tomorrow and will see what can be done about it.

**Comment by medariox** [comment]
@megabitus98 
So, the problem here is that the episode you are searching the subtitle for contains this character ```～```, which looks like a normal tilde ```~```, but actually is a big tilde. The big tilde is quite rare and is not contained in the character encoding you have set (cp1252). What I'd suggest you do, is replacing the big tilde with the normal one, that should solve the issue. There is no need to disable all the anime subtitles really.

**Comment by megabitus98** [comment]
@medariox 
Thanks, I didn't need the subtitles for anime's anyway. It never founded a subtitle for them, but still thanks for helping!
