### ISSUE TITLE
>= v5.0 incompatible with Synology sickbeard-custom

### ISSUE THREAD

**Issue by marcofranssen** [SickRage/sickrage-issues#612]
Is there any plan to bring back a Sickbeard package for Synology. The sickbeard package has disappeared from the package center.

When using the Sickbeard-custom package it only works with the latest v4.0 release. Since the release v5.0 it doesn't work anymore.

I really hope there will soon be a new SickRage package for synology.

**Comment by SickRage2** [comment]
Thanks for the issue report! Before a real human comes by, please make sure your report has all the below criteria checked

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [ ] Post debug logs, either inline (for smaller logs) or using gist)

Please make sure you also read [how to create an issue](https://github.com/SickRage/sickrage-issues/blob/master/README.md) and followed all of the steps. 

The title should describe your issue. Having "SR not working" or "I get this bug" for 100 issues, isn't really helpful. We will close issues if there isn't enough information.

Sometimes the devs may seem like grunts and respond with short answers. This isn't (always) because the dev hates you, but because he's on mobile or busy fixing bugs. If something isn't clear, please let us know, and this bot may get updated to automatically answer you.

Thanks!

**Comment by OmgImAlexis** [comment]
@marcofranssen this is Sickrage so I'm pretty sure you should be looking for the SickRage package, not the SickBeard one but I could be wrong.

@miigotu

**Comment by marcofranssen** [comment]
Oh I know that, but that package is not available anymore on Synology. That is why I'm asking to have a new SickRage package compatible with the latest releases. Currently I'm using the Sickbeard-custom package as a workarround with SickRage v4 release from december last year.

**Comment by miigotu** [comment]
@marcofranssen if the synocommunity guys will allow it. They have been somewhat errr difficult.

**Comment by labrys** [comment]
@marcofranssen The SickBeard-custom works with current versions as long as you are using this repository and not the old SiCKRAGETV repository.

**Comment by neoatomic** [comment]
Two days back i installed Sickrage using the sickbeard-custom package myself, and its working fine.
Just make sure you are using the new Repo URL. `https://github.com/SickRage/SickRage.git`

But there are some reports that the Synocommunity's sickbeard-custom package isn't working on the new DSM 6.0 Beta. But we are looking into that.

**Comment by marcofranssen** [comment]
I'm using this repo, but it breaks on any commit newer than this one `#2eaf3fb`.

So it did a git reset --hard to this commit to make it work.

Any commit later gives the following when starting on the synology.

```bash
DiskStation> /var/packages/sickbeard-custom/scripts/start-stop-status start                                        
Starting SickBeard Custom ...                                                                                        
Traceback (most recent call last):                                                                                   
  File "/usr/local/sickbeard-custom/var/SickBeard/SickBeard.py", line 66, in <module>                                
    import sickbeard                                                                                                 
  File "/volume1/@appstore/sickbeard-custom/var/SickRage/sickbeard/__init__.py", line 36, in <module>                
    from sickbeard import metadata                                                                                   
  File "/volume1/@appstore/sickbeard-custom/var/SickRage/sickbeard/metadata/__init__.py", line 22, in <module>       
    from sickbeard.metadata import kodi, kodi_12plus, mediabrowser, ps3, wdtv, tivo, mede8er, generic, helpers       
  File "/volume1/@appstore/sickbeard-custom/var/SickRage/sickbeard/metadata/kodi.py", line 23, in <module>           
    from sickbeard.metadata import generic                                                                           
  File "/volume1/@appstore/sickbeard-custom/var/SickRage/sickbeard/metadata/generic.py", line 32, in <module>        
    from sickbeard import helpers                                                                                    
  File "/volume1/@appstore/sickbeard-custom/var/SickRage/sickbeard/helpers.py", line 51, in <module>                 
    from sickbeard import logger, classes                                                                            
  File "/volume1/@appstore/sickbeard-custom/var/SickRage/sickbeard/logger.py", line 36, in <module>                  
    from sickbeard import classes                                                                                    
  File "/volume1/@appstore/sickbeard-custom/var/SickRage/sickbeard/classes.py", line 29, in <module>                 
    from sickbeard.common import USER_AGENT, Quality                                                                 
  File "/volume1/@appstore/sickbeard-custom/var/SickRage/sickbeard/common.py", line 49, in <module>                  
    UA_POOL = UserAgent()                                                                                            
  File "/usr/local/sickbeard-custom/var/SickBeard/lib/fake_useragent/fake.py", line 10, in __init__                  
    self.data = load_cached()                                                                                        
  File "/usr/local/sickbeard-custom/var/SickBeard/lib/fake_useragent/utils.py", line 140, in load_cached             
    update()                                                                                                         
  File "/usr/local/sickbeard-custom/var/SickBeard/lib/fake_useragent/utils.py", line 135, in update                  
    write(load())                                                                                                    
  File "/usr/local/sickbeard-custom/var/SickBeard/lib/fake_useragent/utils.py", line 108, in write                   
    f = open(settings.DB, 'w+')                                                                                      
IOError: [Errno 13] Permission denied: u'/volume1/@appstore/sickbeard-custom/var/SickRage/lib/fake_useragent/ua.json'
```

Before there was a Sickrage package for the synology. However an automatic update of SickrageTV broak by Sickrage install, so I decided to remove the package and reinstall it. That was the point when I figured out the Sickrage package wasn't available anymore.

Then I struggeled a lot to get this repo working with Sickbeard-custom by resetting the master branch to the above mentioned commit.

I really hope there will be a new Sickrage package for Synology soon, that works with the HEAD of master branch. @neoatomic I really wonder what is your current commit, and how you made it work?

**Comment by neoatomic** [comment]
@marcofranssen I will do a fresh install later today on my Syno, Just to verify its indeed working correctly.

**Comment by neoatomic** [comment]
As promised i did remove my own installation and did a fresh one to test functionality.
First i removed all packages, including Git & Python. Final result, it installed flawlessly and with no issues at all...

But you write that you did manual Git commands, that's not something i would advice with a Syno.
The thing is that the Git package (from the synocommunity) is installed in a special way, and its easy to messes up your install if you don't do it correctly.
This error in your logs seems to indicate just that `OError: [Errno 13] Permission denied` I saw a similar error last summer, and that was because of the usage of the original git package form Synology and running it with the wrong account. Both are a bad thing...

The only time the sickbeard-custom package was having problems installing was with the new DSM 6.0 Beta as reported here https://github.com/SickRage/sickrage-issues/issues/587 ... 


![1](https://cloud.githubusercontent.com/assets/7928052/12537286/9d834b1a-c2bb-11e5-8506-30a87e47dc3f.png)
![2](https://cloud.githubusercontent.com/assets/7928052/12537287/9d84b1e4-c2bb-11e5-8a5d-44778d8b5211.png)
![3](https://cloud.githubusercontent.com/assets/7928052/12537285/9d8287ca-c2bb-11e5-8bbd-eaffaf487256.png)
![4](https://cloud.githubusercontent.com/assets/7928052/12537288/9d8527f0-c2bb-11e5-8c47-393a85d9bdbc.png)

**Comment by labrys** [comment]
@neoatomic He isn't getting the user agent file from www.w3schools.com to create lib/fake_useragent/ua.json.  He is probably behind a firewall.

**Comment by duramato** [comment]
Should we edit the lib to use a gist?
Seeing this problem happening alot of times now..

**Comment by labrys** [comment]
@duramato I think we should include a ua.json in our build, and try..except the UserAgent() call.  If it fails copy in our cached ua.json instead.

**Comment by labrys** [comment]
For now i'm removing the ua.json from the .gitignore and pushing a ua.json in the libs directory.  In the future we can see about falling back to pulling from sickrage.github.io or something.

**Comment by labrys** [comment]
@marcofranssen Can you switch to the develop branch and update to the latest version to see if this is fixed for you?

**Comment by miigotu** [comment]
@marcofranssen You should be able to just update and use current master now, I cherry-picked #832 to master.

**Comment by marcofranssen** [comment]
Sorry I couldn't test on develop yesterday. Wasn't at home so unable to test. However I do want to report back that the lastest master runs fine again after a fresh install. Thanks for the support and fix @miigotu .
