### ISSUE TITLE
http and https loop.

### ISSUE THREAD

**Issue by neoatomic** [SickRage/sickrage-issues#622]
@miigotu @labrys  Just for your info. : 

Today i was testing sickrage by installing it on my Syno. However i came across an issue.
When i installed SR it was using `http`. But my backup had `https` set in the config.ini.
So when i restored the backup and restarted, it got changed to `https`.
However i still had the browser open, but forgot to change the url from `http` to `https` and just did a refresh of the page. 
That SR didn't like, and went into a loop filling the log with the below errors.

Clearly this is a user error on my part, but i'm wondering if we can prevent that from happening.
maybe by auto-redirecting the url from http to https, of showing a 404 error page etc.

```
2016-01-24 16:10:49 DEBUG    FINDSUBTITLES :: Subtitle search for South Park S19E02 delayed for 20 days, 5 hours, 43 minutes
2016-01-24 16:10:49 ERROR    Uncaught exception
Traceback (most recent call last):
  File "/usr/local/sickbeard-custom/var/SickBeard/lib/tornado/http1connection.py", line 693, in _server_request_loop
    ret = yield conn.read_response(request_delegate)
  File "/usr/local/sickbeard-custom/var/SickBeard/lib/tornado/gen.py", line 870, in run
    value = future.result()
  File "/usr/local/sickbeard-custom/var/SickBeard/lib/tornado/concurrent.py", line 215, in result
    raise_exc_info(self._exc_info)
  File "/usr/local/sickbeard-custom/var/SickBeard/lib/tornado/gen.py", line 876, in run
    yielded = self.gen.throw(*exc_info)
  File "/usr/local/sickbeard-custom/var/SickBeard/lib/tornado/http1connection.py", line 168, in _read_message
    quiet_exceptions=iostream.StreamClosedError)
  File "/usr/local/sickbeard-custom/var/SickBeard/lib/tornado/gen.py", line 870, in run
    value = future.result()
  File "/usr/local/sickbeard-custom/var/SickBeard/lib/tornado/concurrent.py", line 215, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 3, in raise_exc_info
SSLError: [SSL: HTTP_REQUEST] http request (_ssl.c:590)
2016-01-24 16:10:49 DEBUG    FINDSUBTITLES :: Subtitle search for South Park S19E01 delayed for 20 days, 5 hours, 43 minutes
2016-01-24 16:10:49 WARNING  SSL Error on 19 ('192.168.2.13', 61552): [SSL: HTTP_REQUEST] http request (_ssl.c:590) 
```

**Comment by SickRage2** [comment]
Thanks for the issue report! Before a real human comes by, please make sure your report has all the below criteria checked

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [x] Post debug logs, either inline (for smaller logs) or using gist)
- [x] Please wrap inline logs inside \`\`\` and \`\`\` for readability

Please make sure you also read [how to create an issue](https://github.com/SickRage/sickrage-issues/blob/master/README.md) and followed all of the steps. 

The title should describe your issue. Having "SR not working" or "I get this bug" for 100 issues, isn't really helpful. We will close issues if there isn't enough information.

Sometimes the devs may seem like grunts and respond with short answers. This isn't (always) because the dev hates you, but because he's on mobile or busy fixing bugs. If something isn't clear, please let us know, and this bot may get updated to automatically answer you.

Thanks!
