### ISSUE TITLE
[APP SUBMITTED]: <MatchTree: root=.ZiLLA.There's.a.Whole.Slew.of.Ladies.with.Bad.Things.to.Say.About.th> is not in list

### ISSUE THREAD

**Issue by labrys** [SickRage/sickrage-issues#630]
### INFO
Python Version: **2.7.11 (v2.7.11:6d1b6a68f775, Dec  5 2015, 20:32:19) [MSC v.1500 32 bit (Intel)]**
Operating System: **Windows-10-10.0.10240**
Locale: cp1252
Branch: **hotfix-issue-620**
Commit: SickRage/SickRage@031ac8ee3ffa296790b9925ae27d6678a6a3b3cb
No Log available with ERRORS:

Here's the [LOG](https://gist.github.com/labrys/85f43b119d0e6fd94e85)

### ERROR
```
FINDSUBTITLES :: Traceback (most recent call last):
  File "H:\usr\local\sickrage\sickbeard\subtitles.py", line 177, in download_subtitles
    matches = subtitle.get_matches(video, hearing_impaired=sickbeard.SUBTITLES_HEARING_IMPAIRED)
  File "H:\usr\local\sickrage\lib\subliminal\providers\opensubtitles.py", line 69, in get_matches
    matches |= guess_matches(video, guess_episode_info(self.movie_release_name + '.mkv'))
  File "H:\usr\local\sickrage\lib\guessit\__init__.py", line 370, in guess_episode_info
    return guess_file_info(filename, info=info, options=options, type='episode', **kwargs)
  File "H:\usr\local\sickrage\lib\guessit\__init__.py", line 302, in guess_file_info
    result.append(_guess_filename(filename, options, **kwargs))
  File "H:\usr\local\sickrage\lib\guessit\__init__.py", line 114, in _guess_filename
    mtree = _build_filename_mtree(filename, options=options, **kwargs)
  File "H:\usr\local\sickrage\lib\guessit\__init__.py", line 127, in _build_filename_mtree
    mtree = IterativeMatcher(filename, options=merged_options, **kwargs)
  File "H:\usr\local\sickrage\lib\guessit\matcher.py", line 120, in __init__
    self._process(transformer, False)
  File "H:\usr\local\sickrage\lib\guessit\matcher.py", line 138, in _process
    transformer.process(self.match_tree, self.options)
  File "H:\usr\local\sickrage\lib\guessit\transfo\guess_release_group.py", line 223, in process
    GuessFinder(self.guess_release_group, None, self.log, options).process_nodes(mtree.unidentified_leaves())
  File "H:\usr\local\sickrage\lib\guessit\matcher.py", line 227, in process_nodes
    self.process_node(node)
  File "H:\usr\local\sickrage\lib\guessit\matcher.py", line 286, in process_node
    self.process_node(node, partial_span=relative_span, skip_nodes=next_skip_nodes)
  File "H:\usr\local\sickrage\lib\guessit\matcher.py", line 241, in process_node
    matcher_result = self.guess_func(string, node, self.options)
  File "H:\usr\local\sickrage\lib\guessit\transfo\guess_release_group.py", line 175, in guess_release_group
    if self.validate_node(leaf, node, True):
  File "H:\usr\local\sickrage\lib\guessit\transfo\guess_release_group.py", line 143, in validate_node
    if not self.validate_next_leaves(node):
  File "H:\usr\local\sickrage\lib\guessit\transfo\guess_release_group.py", line 126, in validate_next_leaves
    next_leaf = node.root.next_leaf(node)
  File "H:\usr\local\sickrage\lib\guessit\matchtree.py", line 318, in next_leaf
    return self._other_leaf(leaf, +1)
  File "H:\usr\local\sickrage\lib\guessit\matchtree.py", line 322, in _other_leaf
    index = leaves.index(leaf) + offset
ValueError: <MatchTree: root=.ZiLLA.There's.a.Whole.Slew.of.Ladies.with.Bad.Things.to.Say.About.th> is not in list
 [be60487]
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by SickRage2** [comment]
Thanks for the issue report! Before a real human comes by, please make sure your report has all the below criteria checked

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [ ] Post debug logs, either inline (for smaller logs) or using gist)

Please make sure you also read [how to create an issue](https://github.com/SickRage/sickrage-issues/blob/master/README.md) and followed all of the steps. 

The title should describe your issue. Having "SR not working" or "I get this bug" for 100 issues, isn't really helpful. We will close issues if there isn't enough information.

Sometimes the devs may seem like grunts and respond with short answers. This isn't (always) because the dev hates you, but because he's on mobile or busy fixing bugs. If something isn't clear, please let us know, and this bot may get updated to automatically answer you.

Thanks!

**Comment by labrys** [comment]
@medariox This is the error I was talking about.  And it must be something to do with upstream, as that string is nowhere in my downloads, nor library.  Confirmed with grep.

**Comment by medariox** [comment]
Crash fixed here https://github.com/SickRage/SickRage/pull/840 and reported upstream.
