### ISSUE TITLE
HTTPError: HTTP 404: Not Found after updating to 9.3.3

### ISSUE THREAD

**Issue by frozn00** [SickRage/sickrage-issues#658]
I have searched for this but I haven't found an answer and I was hoping someone here could help me.  I updated sickrage the other day using the UPDATE feature in freenas and I am not getting:

```
Traceback (most recent call last):
  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/lib/tornado/web.py", line 1390, in _execute
    result = self.prepare()
  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/lib/tornado/web.py", line 2103, in prepare
    raise HTTPError(self._status_code)
HTTPError: HTTP 404: Not Found
```
Evidently SickRage still is working because it downloaded  something last night.  I know this because I get e-mails when it downloads something.  When I try to access the web interface I get the message above.  I have tried downgrading to 9.3.2, 9.3.1, and 9.3.0 but the message still remains.  I was asked to come here for support and I hope one of you can help me.  Thanks!

**Comment by SickRage2** [comment]
Thanks for the issue report! Before a real human comes by, please make sure your report has all the below criteria checked

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [ ] Post debug logs, either inline (for smaller logs) or using gist)

Please make sure you also read [how to create an issue](https://github.com/SickRage/sickrage-issues/blob/master/README.md) and followed all of the steps. 

The title should describe your issue. Having "SR not working" or "I get this bug" for 100 issues, isn't really helpful. We will close issues if there isn't enough information.

Sometimes the devs may seem like grunts and respond with short answers. This isn't (always) because the dev hates you, but because he's on mobile or busy fixing bugs. If something isn't clear, please let us know, and this bot may get updated to automatically answer you.

Thanks!

**Comment by labrys** [comment]
@frozn00 First of all are you sure you are on this SickRage repository and not the old SiCKRAGETV?

Please post your commit hash.  Since you can't access the web interface it can be found in your config.ini file.

**Comment by frozn00** [comment]
git_remote_url = https://github.com/SickRage/SickRage.git
cur_commit_hash = ""
cur_commit_branch = ""
config_version = 7
encryption_version = 2

**Comment by labrys** [comment]
@frozn00 Have you tried shutting down and restarting sickrage?  Sometimes errors such as this can occur during an update do to files in use being changed as part of the update.

**Comment by frozn00** [comment]
I have numerous times.  I have also restarted the entire freenas.

**Comment by frozn00** [comment]
@labrys I'm not trying to rush you but I would love to figure out what is causing this.  Is there anything I can check on my end to figure out what is causing this?  Thank you for your help.

**Comment by labrys** [comment]
@frozn00 I haven't been able to reproduce this but I am not running on a freenas and don't have one available to test.  However, if you could enable debug logs and post a complete log, it would help a lot.

**Comment by frozn00** [comment]
In the config.ini?  I will set debug = 0 to debug = 1 if that will help.

**Comment by labrys** [comment]
That will do it :)

**Comment by frozn00** [comment]
Thanks.  I've enabled debugging...started and stopped the service and I'm looking around trying to find the log folder but I can't see to find it.  My guess is it will be inside the jail directory or is it somewhere else?

**Comment by labrys** [comment]
default is in sickrage/logs folder but not sure if thats where freenas puts it

**Comment by frozn00** [comment]
I found a sickrage.log in /jails/sabnzbd_1/var/db/sickrage/Logs.  I see a  SHOWQUEUE-REFRESH, DAILYSEARCHER, SEARCHQUEUE-DAILY-SEARCH, EVENT-QUEUE etc.  What should I be looking for in identifying the error?

**Comment by neoatomic** [comment]
Looks like those are missing from the config. : 
 
cur_commit_hash = ""
cur_commit_branch = ""

However that would not explain why you get the error and cant access the GUI.
It sounds to me that you updated the old Freenas package that was still pointing to the old Repo with the new Freenas package that uses the new Repo. And it seems there something went wrong...

Probably the quickest solution would be removal of the old package and reinstall the latest Freenas package and start fresh.

**Comment by frozn00** [comment]
I have deleted the plugin from the "Plugins" "Installed" location and sickrage is no longer visiable.  I would then upload the pbi file into my current jail and I am having the same problem.  Are you suggesting that I do something different as a way of deleting the plugin?

**Comment by neoatomic** [comment]
Did you maybe restore your old backup or sickbeard.db & config.ini.? Dont do that as it clearly is missing information.

The only other issue i recall regarding freenas was a conflict between IPv4 & IPv6. Think it was like enabled in the freenas itself but not in the jail.? Or the other way around. maybe that's why you are unable to open the GUI.

**Comment by frozn00** [comment]
I didn't do any restore of any backup.  Problems began when I ran the update feature in Freenas and I have had the http error ever since.  I really don't know what to do at this point.  The freenas forum suggested I come here for help but maybe I can go back over there and ask.

**Comment by neoatomic** [comment]
Well if you do a fresh/clean install, than all should work/start.
As it clearly doesn't in your case, its more likely an issue with your Freenas or setup.
But what exactly is hard for me to say, as i dont use a Freenas myself. :(

**Comment by frozn00** [comment]
Thanks.  Does the git_remote_url = https://github.com/SickRage/SickRage.git mean I am on the correct repo?

**Comment by josh4trunks** [comment]
@frozn00 you are still having the same problem when reuploading the plugin because the old data-directory is still at /var/db/sickrage. If you want to start fresh with sickrage you can delete that directory.

Yes, your program files are on the correct repo, but something about your data-directory isn't compatible with the new repo.

**Comment by frozn00** [comment]
@josh4trunks Thanks Josh, that did indeed work.  Is there any way I can restore the shows, config and the rest of what was setup or do I have to start fresh?  I did make a copy of the sickrage directory before I deleted the directory (config.ini, sickbeard.db) etc.

**Comment by duramato** [comment]
@frozn00 If you copy the config.ini and sickbeard.db you should get your shows and settings back

**Comment by frozn00** [comment]
@duramato I haven't been able to just straight copy the config.ini and sickbeard.db and make it work.  I am getting the same error when I do so.  Is there a way to look at the config.ini and the sickbeard.db to determine what version those two files will run on.  Meaning...Do I need to install the 9.3.0, 9.3.1, 9.3.2, or 9.3.3 pbi to try and salvage this?

**Comment by neoatomic** [comment]
@frozn00 If those files are giving you errors, then start fresh. Its not worth the risk of having issues again in the near future. Just invest the extra minutes to have it setup solidly.
