### ISSUE TITLE
Remove show gives 404 error

### ISSUE THREAD

**Issue by papampi** [SickRage/sickrage-issues#666]
```
SickRage Version:	Branch: master
Commit: 3f0efd1338faf8796fd355bada4f546ec1cb5ed6
Version: 2016.01.23-1
Python Version:	2.7.11 (default, Jan 9 2016, 16:55:40) [GCC 4.8.5]
SSL Version:	OpenSSL 1.0.2e 3 Dec 2015
Locale:	None.None
 	 
 	 
User:	admin
Program Directory:	/share/CACHEDEV1_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage
Configuration File:	/share/CACHEDEV1_DATA/.qpkg/SickBeard-TVRage/config/config.ini
Database:	/share/CACHEDEV1_DATA/.qpkg/SickBeard-TVRage/config/sickbeard.db
Cache Directory:	/share/CACHEDEV1_DATA/.qpkg/SickBeard-TVRage/config/cache
Log Directory:	/share/CACHEDEV1_DATA/.qpkg/SickBeard-TVRage/config/Logs
Arguments:	['--daemon', '--datadir', '/share/CACHEDEV1_DATA/.qpkg/SickBeard-TVRage/config', '--pidfile', '/tmp/SickBeard-TVRage.pid']
```

remove show error log : 
```
2016-01-26 12:23:48 Thread-68 :: Failed doing webui callback: Traceback (most recent call last):
  File "/share/CACHEDEV1_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/sickbeard/webserve.py", line 282, in async_call
    result = function(**kwargs)
  File "/share/CACHEDEV1_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/sickbeard/webserve.py", line 1596, in deleteShow
    error, show = Show.delete(show, full)
  File "/share/CACHEDEV1_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/sickrage/show/Show.py", line 51, in delete
    sickbeard.showQueueScheduler.action.removeShow(show, bool(remove_files))
  File "/share/CACHEDEV1_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/sickbeard/show_queue.py", line 173, in removeShow
    if all([item, item.show, item != self.currentItem, show.indexerid == item.show.indexerid]):
AttributeError: 'NoneType' object has no attribute 'indexerid'
 [3f0efd1]
```

remove show web page output :
```
Oops
You have reached this page by accident, please check the url.
```

**Comment by SickRage2** [comment]
Thanks for the issue report! Before a real human comes by, please make sure your report has all the below criteria checked

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [ ] Post debug logs, either inline (for smaller logs) or using gist)

Please make sure you also read [how to create an issue](https://github.com/SickRage/sickrage-issues/blob/master/README.md) and followed all of the steps. 

The title should describe your issue. Having "SR not working" or "I get this bug" for 100 issues, isn't really helpful. We will close issues if there isn't enough information.

Sometimes the devs may seem like grunts and respond with short answers. This isn't (always) because the dev hates you, but because he's on mobile or busy fixing bugs. If something isn't clear, please let us know, and this bot may get updated to automatically answer you.

Thanks!

**Comment by papampi** [comment]
seems like there has been another ticket for this issue as well :+1: 
https://github.com/SickRage/sickrage-issues/issues/625

**Comment by neoatomic** [comment]
@papampi Can you add the info and log there.? Than we have all in 1 place.
