### ISSUE TITLE
Windows locale leads to invalid encoding settings

### ISSUE THREAD

**Issue by matansh** [SickRage/sickrage-issues#685]
I am getting these errors ever since I migrated to the new sickrage repo but no matter how hard I try I cannot understand how to change sickrage's locale settings!
I tried manually editing the config.ini file but it has nothing remotely close to encoding or locale in it..
Any kind of help would be appreciated.

### INFO
Python Version: **2.7.11 (v2.7.11:6d1b6a68f775, Dec  5 2015, 20:32:19) [MSC v.1500 32 bit (Intel)]**
Operating System: **Windows-7-6.1.7601-SP1**
Locale: cp1255
Branch: **master**
Commit: SickRage/SickRage@3f0efd1338faf8796fd355bada4f546ec1cb5ed6

### ERROR
```
2016-01-27 15:11:06 WARNING  FINDSUBTITLES :: An error occurred while encoding 'D:\TV\Hannibal\Hannibal.S01E01.Apéritif.mkv' with your current locale. Rename the file or try a different locale. Error: charmap : D:\TV\Hannibal\Hannibal.S01E01.Apֳ©ritif.mkv : error 33 : error 34 : character maps to  [589ade6]
2016-01-27 15:11:05 WARNING  FINDSUBTITLES :: An error occurred while encoding 'D:\TV\Hannibal\Hannibal.S01E04.Œuf.mkv' with your current locale. Rename the file or try a different locale. Error: charmap : D:\TV\Hannibal\Hannibal.S01E04.ֵ’uf.mkv : error 31 : error 32 : character maps to  [589ade6]
2016-01-27 15:11:05 WARNING  FINDSUBTITLES :: An error occurred while encoding 'D:\TV\Hannibal\Hannibal.S01E06.Entrée.avi' with your current locale. Rename the file or try a different locale. Error: charmap : D:\TV\Hannibal\Hannibal.S01E06.Entrֳ©e.avi : error 35 : error 36 : character maps to  [589ade6]
2016-01-27 15:11:05 WARNING  FINDSUBTITLES :: An error occurred while encoding 'D:\TV\Hannibal\Hannibal.S01E11.Rôti.avi' with your current locale. Rename the file or try a different locale. Error: charmap : D:\TV\Hannibal\Hannibal.S01E11.Rֳ´ti.avi : error 32 : error 33 : character maps to  [589ade6]
2016-01-27 15:11:05 WARNING  FINDSUBTITLES :: An error occurred while encoding 'D:\TV\Hannibal\Hannibal.S01E12.Relevés.avi' with your current locale. Rename the file or try a different locale. Error: charmap : D:\TV\Hannibal\Hannibal.S01E12.Relevֳ©s.avi : error 36 : error 37 : character maps to  [589ade6]
```

**Comment by SickRage2** [comment]
Thanks for the issue report! Before a real human comes by, please make sure your report has all the below criteria checked

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [x] Post debug logs, either inline (for smaller logs) or using gist)
- [x] Please wrap inline logs inside \`\`\` and \`\`\` for readability

Please make sure you also read [how to create an issue](https://github.com/SickRage/sickrage-issues/blob/master/README.md) and followed all of the steps. 

The title should describe your issue. Having "SR not working" or "I get this bug" for 100 issues, isn't really helpful. We will close issues if there isn't enough information.

Sometimes the devs may seem like grunts and respond with short answers. This isn't (always) because the dev hates you, but because he's on mobile or busy fixing bugs. If something isn't clear, please let us know, and this bot may get updated to automatically answer you.

Thanks!

**Comment by labrys** [comment]
@matansh You can't change locale on Windows.  It's a known python bug.

**Comment by fernandog** [comment]
Did you use SickRage windows installer?

Run before run SR: chcp 65001

**Comment by labrys** [comment]
@fernandog That doesnt work.  As I said, you can't change locale on Windows.

**Comment by matansh** [comment]
Sickrage has a windows installer? i'm just clicking (more like adding to windows startup) the SickBeard.py file.
Any chance to force UTF-8? just point me to the appropriate file + line and i'll implement the needed lines of code.
BTW if changing is impossible then maybe "hard coding" it to use UTF on windows can help out?

**Comment by duramato** [comment]
@matansh yeah the isntaller is on the site sickrage.github.io

**Comment by medariox** [comment]
@matansh 
The problem here is that you are using cp1255 (Windows Hebrew), which does not contain characters like ```é``` for example. If [this](http://windows.microsoft.com/en-us/windows/change-system-locale#1TC=windows-7) doesn't help, I'm afraid we will have to force fallback to UTF-8 for Windows users, or something like that. You can still rename the files that are causing the errors tho.

**Comment by fernandog** [comment]
Why chcp 65001 wont work? It changes to UTF-8

Identifier:
65001

.NET Name
utf-8

Additional information:
Unicode (UTF-8)

https://msdn.microsoft.com/en-us/library/windows/desktop/dd317756(v=vs.85).aspx


@matansh did you try?

**Comment by matansh** [comment]
@fernandog i stated off running the command you gave and then the SickBeard.py file via the same command line window, i got-
```
C:\SickRage\SickRage>chcp 65001
Active code page: 65001

C:\SickRage\SickRage>SickBeard.py
Unable to find C:\SickRage\SickRage\config.ini, all settings will be default!
```

And the locale is now "en_US.cp1252"

Does this mean it worked?

**Comment by fernandog** [comment]
Hit find subtitles for hannibal and see if works

**Comment by matansh** [comment]
Didn't work :(
And now in my "server status" screen the "Subtitles Finder" scheduler says "alive = false" and has no "next run"

````
2016-01-28 18:11:40 SHOWQUEUE-SUBTITLE :: Traceback (most recent call last):
  File "C:\SickRage\SickRage\sickbeard\tv.py", line 1160, in download_subtitles
    episode.download_subtitles(force=force)
  File "C:\SickRage\SickRage\sickbeard\tv.py", line 1464, in download_subtitles
    self.subtitles, new_subtitles = subtitles.download_subtitles(subtitles_info)
  File "C:\SickRage\SickRage\sickbeard\subtitles.py", line 148, in download_subtitles
    video_path = subtitles_info['location'].encode(sickbeard.SYS_ENCODING)
  File "C:\SickRage\Python\lib\encodings\cp1255.py", line 12, in encode
    return codecs.charmap_encode(input,errors,encoding_table)
UnicodeEncodeError: 'charmap' codec can't encode character u'\xe9' in position 33: character maps to 
 [f568d15]
2016-01-28 17:40:23 SHOWQUEUE-REFRESH :: 259063: Could not refresh subtitles [f568d15]
````

**Comment by medariox** [comment]
@matansh 
Did you go back to master branch? You have to be on develop branch to have the warning (and no crash) instead of the error you get now.

**Comment by matansh** [comment]
Just wanted to update everyone that i tried multiple solutions, some from this thread and some from the web. nothing really helps so i just manually edited the file names.
In my opinion, forcing UTF-8 on windows users is a really good idea, ultimately we can just download subtitles by ourselves (and even episodes) but the promise of an automated process is what brought all of us here :)

Thanks for the help!

**Comment by labrys** [comment]
@matansh You can't force UTF-8, it breaks on Windows.  It's *supposed* to work but doesn't actually since you can't switch to `cp65001`.  The safest bet is actually to fall back through encodings to 'ascii`-replace.  But that can mangle filenames more than some users would care for.  The filesystem itself is 'UTF-16LE' for NTFS and also iirc exFAT.  But since `UTF-16` default is `UTF-16BE` when endian-ness is unknown, assuming that `UTF-16` is little-endian can cause issues.  Welcome to the wonderful world of encoding.

**Comment by fernandog** [comment]
@matansh best solution for now change SR rename patter to not incluse episode name
