### ISSUE TITLE
[APP SUBMITTED]: failedDownloads() got an unexpected keyword argument '039'

### ISSUE THREAD

**Issue by andevellicus** [SickRage/sickrage-issues#692]
### INFO
Python Version: **2.7.9 (default, Mar  1 2015, 12:57:24) [GCC 4.9.2]**
Operating System: **Linux-3.16.0-4-amd64-x86_64-with-debian-8.3**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@f568d1515557f854042511d7bfee3ae070c864bd
No Log available with ERRORS:
### ERROR
```
Thread-33 :: Failed doing webui callback: Traceback (most recent call last):
  File "/opt/sickrage/sickbeard/webserve.py", line 282, in async_call
    result = function(**kwargs)
TypeError: failedDownloads() got an unexpected keyword argument '039'
 [f568d15]
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by SickRage2** [comment]
Thanks for the issue report! Before a real human comes by, please make sure your report has all the below criteria checked

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [ ] Post debug logs, either inline (for smaller logs) or using gist)

Please make sure you also read [how to create an issue](https://github.com/SickRage/sickrage-issues/blob/master/README.md) and followed all of the steps. 

The title should describe your issue. Having "SR not working" or "I get this bug" for 100 issues, isn't really helpful. We will close issues if there isn't enough information.

Sometimes the devs may seem like grunts and respond with short answers. This isn't (always) because the dev hates you, but because he's on mobile or busy fixing bugs. If something isn't clear, please let us know, and this bot may get updated to automatically answer you.

Thanks!

**Comment by andevellicus** [comment]
### INFO
Python Version: **2.7.9 (default, Mar  1 2015, 12:57:24) [GCC 4.9.2]**
Operating System: **Linux-3.16.0-4-amd64-x86_64-with-debian-8.3**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@f568d1515557f854042511d7bfee3ae070c864bd
No Log available with ERRORS:
### ERROR
```
Thread-31 :: Failed doing webui callback: Traceback (most recent call last):
  File "/opt/sickrage/sickbeard/webserve.py", line 282, in async_call
    result = function(**kwargs)
TypeError: failedDownloads() got an unexpected keyword argument '039'
 [f568d15]
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by andevellicus** [comment]
This occurred when I was using the "Failed Downloads" page to clear my list of failed downloads. I believe it happened because one of the file names contained:

"e&039;s"

I suspect that either "&" or ";" represent illegal characters.

**Comment by miigotu** [comment]
Fixed in develop
