### ISSUE TITLE
[APP SUBMITTED]: 'NoneType' object has no attribute 'replace'

### ISSUE THREAD

**Issue by nitedevil** [SickRage/sickrage-issues#693]
### INFO
Python Version: **2.7.10 (default, May 23 2015, 09:44:00) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-8-6.2.9200**
Locale: cp1252
Branch: **master**
Commit: SickRage/SickRage@f568d1515557f854042511d7bfee3ae070c864bd
No Log available with ERRORS:
### ERROR
```
SEARCHQUEUE-BACKLOG-72268 :: [TransmitTheNet] :: Failed parsing provider. Traceback: Traceback (most recent call last):
  File "C:\SickRage\sickbeard\providers\transmitthenet.py", line 140, in search
    title = title.replace("[", "").replace("]", "").replace("/ ", "")
AttributeError: 'NoneType' object has no attribute 'replace'
 [f568d15]
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by nitedevil** [comment]
### INFO
Python Version: **2.7.10 (default, May 23 2015, 09:44:00) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-8-6.2.9200**
Locale: cp1252
Branch: **master**
Commit: SickRage/SickRage@f568d1515557f854042511d7bfee3ae070c864bd
No Log available with ERRORS:
### ERROR
```
SEARCHQUEUE-BACKLOG-278125 :: [TransmitTheNet] :: Failed parsing provider. Traceback: Traceback (most recent call last):
  File "C:\SickRage\sickbeard\providers\transmitthenet.py", line 140, in search
    title = title.replace("[", "").replace("]", "").replace("/ ", "")
AttributeError: 'NoneType' object has no attribute 'replace'
 [f568d15]
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by SickRage2** [comment]
Thanks for the issue report! Before a real human comes by, please make sure your report has all the below criteria checked

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [ ] Post debug logs, either inline (for smaller logs) or using gist)

Please make sure you also read [how to create an issue](https://github.com/SickRage/sickrage-issues/blob/master/README.md) and followed all of the steps. 

The title should describe your issue. Having "SR not working" or "I get this bug" for 100 issues, isn't really helpful. We will close issues if there isn't enough information.

Sometimes the devs may seem like grunts and respond with short answers. This isn't (always) because the dev hates you, but because he's on mobile or busy fixing bugs. If something isn't clear, please let us know, and this bot may get updated to automatically answer you.

Thanks!

**Comment by nitedevil** [comment]
### INFO
Python Version: **2.7.10 (default, May 23 2015, 09:44:00) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-8-6.2.9200**
Locale: cp1252
Branch: **master**
Commit: SickRage/SickRage@f568d1515557f854042511d7bfee3ae070c864bd
No Log available with ERRORS:
### ERROR
```
SEARCHQUEUE-DAILY-SEARCH :: [TransmitTheNet] :: Failed parsing provider. Traceback: Traceback (most recent call last):
  File "C:\SickRage\sickbeard\providers\transmitthenet.py", line 140, in search
    title = title.replace("[", "").replace("]", "").replace("/ ", "")
AttributeError: 'NoneType' object has no attribute 'replace'
 [f568d15]
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by nitedevil** [comment]
### INFO
Python Version: **2.7.10 (default, May 23 2015, 09:44:00) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-8-6.2.9200**
Locale: cp1252
Branch: **master**
Commit: SickRage/SickRage@f568d1515557f854042511d7bfee3ae070c864bd
No Log available with ERRORS:
### ERROR
```
SEARCHQUEUE-BACKLOG-73388 :: [TransmitTheNet] :: Failed parsing provider. Traceback: Traceback (most recent call last):
  File "C:\SickRage\sickbeard\providers\transmitthenet.py", line 140, in search
    title = title.replace("[", "").replace("]", "").replace("/ ", "")
AttributeError: 'NoneType' object has no attribute 'replace'
 [f568d15]
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by nitedevil** [comment]
### INFO
Python Version: **2.7.10 (default, May 23 2015, 09:44:00) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-8-6.2.9200**
Locale: cp1252
Branch: **master**
Commit: SickRage/SickRage@f568d1515557f854042511d7bfee3ae070c864bd
No Log available with ERRORS:
### ERROR
```
SEARCHQUEUE-BACKLOG-75216 :: [TransmitTheNet] :: Failed parsing provider. Traceback: Traceback (most recent call last):
  File "C:\SickRage\sickbeard\providers\transmitthenet.py", line 140, in search
    title = title.replace("[", "").replace("]", "").replace("/ ", "")
AttributeError: 'NoneType' object has no attribute 'replace'
 [f568d15]
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by nitedevil** [comment]
### INFO
Python Version: **2.7.10 (default, May 23 2015, 09:44:00) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-8-6.2.9200**
Locale: cp1252
Branch: **master**
Commit: SickRage/SickRage@f568d1515557f854042511d7bfee3ae070c864bd
No Log available with ERRORS:
### ERROR
```
SEARCHQUEUE-BACKLOG-253695 :: [TransmitTheNet] :: Failed parsing provider. Traceback: Traceback (most recent call last):
  File "C:\SickRage\sickbeard\providers\transmitthenet.py", line 140, in search
    title = title.replace("[", "").replace("]", "").replace("/ ", "")
AttributeError: 'NoneType' object has no attribute 'replace'
 [f568d15]
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by nitedevil** [comment]
### INFO
Python Version: **2.7.10 (default, May 23 2015, 09:44:00) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-8-6.2.9200**
Locale: cp1252
Branch: **master**
Commit: SickRage/SickRage@f568d1515557f854042511d7bfee3ae070c864bd
No Log available with ERRORS:
### ERROR
```
SEARCHQUEUE-BACKLOG-134241 :: [TransmitTheNet] :: Failed parsing provider. Traceback: Traceback (most recent call last):
  File "C:\SickRage\sickbeard\providers\transmitthenet.py", line 140, in search
    title = title.replace("[", "").replace("]", "").replace("/ ", "")
AttributeError: 'NoneType' object has no attribute 'replace'
 [f568d15]
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by duramato** [comment]
@nitedevil Do you have logs? It may have been an ocasional occorance as i also got 1 error..

**Comment by FWoelffel** [comment]
### INFO
Python Version: **2.7.9 (default, Sep  9 2015, 14:50:03) [GCC 4.2.1 20070831 patched [FreeBSD]]**
Operating System: **FreeBSD-9.1-RELEASE-amd64-64bit-ELF**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@f568d1515557f854042511d7bfee3ae070c864bd
No Log available with ERRORS:
### ERROR
```
SEARCHQUEUE-DAILY-SEARCH :: [TransmitTheNet] :: Failed parsing provider. Traceback: Traceback (most recent call last):
  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/sickbeard/providers/transmitthenet.py", line 140, in search
    title = title.replace("[", "").replace("]", "").replace("/ ", "")
AttributeError: 'NoneType' object has no attribute 'replace'
 [f568d15]
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by FWoelffel** [comment]
### INFO
Python Version: **2.7.9 (default, Sep  9 2015, 14:50:03) [GCC 4.2.1 20070831 patched [FreeBSD]]**
Operating System: **FreeBSD-9.1-RELEASE-amd64-64bit-ELF**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@f568d1515557f854042511d7bfee3ae070c864bd
No Log available with ERRORS:
### ERROR
```
SEARCHQUEUE-BACKLOG-80379 :: [TransmitTheNet] :: Failed parsing provider. Traceback: Traceback (most recent call last):
  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/sickbeard/providers/transmitthenet.py", line 140, in search
    title = title.replace("[", "").replace("]", "").replace("/ ", "")
AttributeError: 'NoneType' object has no attribute 'replace'
 [f568d15]
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators
