### ISSUE TITLE
[APP SUBMITTED]: savePostProcessing() got an unexpected keyword argument 'tIvo_data'

### ISSUE THREAD

**Issue by smntsn** [SickRage/sickrage-issues#694]
### INFO
Python Version: **2.7.9 (default, Mar  8 2015, 00:52:26) [GCC 4.9.2]**
Operating System: **Linux-4.1.13-v7+-armv7l-with-debian-8.0**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@f568d1515557f854042511d7bfee3ae070c864bd
No Log available with ERRORS:
### ERROR
```
Thread-37 :: Failed doing webui callback: Traceback (most recent call last):
  File "/opt/sickrage/sickbeard/webserve.py", line 282, in async_call
    result = function(**kwargs)
TypeError: savePostProcessing() got an unexpected keyword argument 'tIvo_data'
 [f568d15]
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by SickRage2** [comment]
Thanks for the issue report! Before a real human comes by, please make sure your report has all the below criteria checked

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [ ] Post debug logs, either inline (for smaller logs) or using gist)

Please make sure you also read [how to create an issue](https://github.com/SickRage/sickrage-issues/blob/master/README.md) and followed all of the steps. 

The title should describe your issue. Having "SR not working" or "I get this bug" for 100 issues, isn't really helpful. We will close issues if there isn't enough information.

Sometimes the devs may seem like grunts and respond with short answers. This isn't (always) because the dev hates you, but because he's on mobile or busy fixing bugs. If something isn't clear, please let us know, and this bot may get updated to automatically answer you.

Thanks!

**Comment by smntsn** [comment]
### INFO
Python Version: **2.7.9 (default, Mar  8 2015, 00:52:26) [GCC 4.9.2]**
Operating System: **Linux-4.1.13-v7+-armv7l-with-debian-8.0**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@f568d1515557f854042511d7bfee3ae070c864bd
No Log available with ERRORS:
### ERROR
```
Thread-36 :: Failed doing webui callback: Traceback (most recent call last):
  File "/opt/sickrage/sickbeard/webserve.py", line 282, in async_call
    result = function(**kwargs)
TypeError: savePostProcessing() got an unexpected keyword argument 'tIvo_data'
 [f568d15]
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by fernandog** [comment]
@smntsn can you reproduce again the error ?

 send a print of all values in the settings that cause this error

**Comment by miigotu** [comment]
@smntsn where does the string tIvo_data come from? Its not in the source, so either it is part of one of your inputted data or you have a modified gui

**Comment by smntsn** [comment]
@fernandog 
In settings(gear logo) > 
"post processing" page all checkboxes 
"Episode Naming" & "Metadata"  tabs, all check boxes not working. (Not saving and generating same error "tIvo_data")

@miigotu 
I think this problem occoured in "Metadata" configuration page when I selected "KODI 12+" and TIVO metadata options. 

When I manually edit "/opt/sickrage/config.ini" file everything works. But web interface can't write to config.ini because of "tIvo_data" error. But It can write in other pages when I press SAVE or SAVE ALL buttons .
Other settings in web interface saves values with no problem. The problem is only in "Settings(Gear logo)">Post Processing page & Episode Naming page & Metadata Page.

I can easily reproduce error by checking a random checkbox in Settings>Post Processing page and Metadata & Episode Naming tabs. 

Example:
```
2016-01-30 20:06:27 Thread-57 :: Failed doing webui callback: Traceback (most recent call last):
  File "/opt/sickrage/sickbeard/webserve.py", line 282, in async_call
    result = function(**kwargs)
TypeError: savePostProcessing() got an unexpected keyword argument 'tIvo_data'
 [f568d15]
2016-01-30 19:55:17 Thread-31 :: Failed doing webui callback: Traceback (most recent call last):
  File "/opt/sickrage/sickbeard/webserve.py", line 282, in async_call
    result = function(**kwargs)
TypeError: savePostProcessing() got an unexpected keyword argument 'tIvo_data'
 [f568d15]
2016-01-30 19:54:53 Thread-30 :: Failed doing webui callback: Traceback (most recent call last):
  File "/opt/sickrage/sickbeard/webserve.py", line 282, in async_call
    result = function(**kwargs)
TypeError: savePostProcessing() got an unexpected keyword argument 'tIvo_data'
 [f568d15]
2016-01-30 19:54:26 Thread-45 :: Failed doing webui callback: Traceback (most recent call last):
  File "/opt/sickrage/sickbeard/webserve.py", line 282, in async_call
    result = function(**kwargs)
TypeError: savePostProcessing() got an unexpected keyword argument 'tIvo_data'
 [f568d15]
```

**Comment by labrys** [comment]
@smntsn What @miigotu is saying is that the string `tIvo_data` doesn't appear anywhere in the SickRage source code, so if that error is occurring it is due to something external to SickRage itself passing incorrect information.  What platform are you running on?  Are you using any form of custom user interface (e.g. something like ShowsRage)?  Please include more from the log as well next time including lines above and below the error.

**Comment by miigotu** [comment]
I need the input data you are giving SR that causes it, is the string somthuing&tIvo_data or blah>tIvo_data or what?

**Comment by fernandog** [comment]
@smntsn send a screenshot of the PP page/tabs so we can see all values in all input fields/checkboxes etc
