### ISSUE TITLE
sickrage broke my python install

### ISSUE THREAD

**Issue by wpmccormick** [SickRage/sickrage-issues#712]
I switched over from the other repo and all it's problems, at first I thought everything was fine. Then I see that my plexmediaserver won't run. Then I see that nzbget won't run. It seems that somehow my python install is broken:

root@pvr:/usr/local/PlexMediaServer # ./start.sh
Traceback (most recent call last):
  File "bundles-release/Framework.bundle-dist/Contents/Resources/Versions/2/Python/bootstrap.py", line 13, in <module>
  File "bundles-release/Framework.bundle-dist/Contents/Resources/Versions/2/Python/subsystem/__init__.py", line 7, in <module>
  File "bundles-release/Framework.bundle-dist/Contents/Resources/Versions/2/Python/subsystem/ospathfix.py", line 2, in <module>
  File "/usr/local/PlexMediaServer-0.9.12.19.1537-f38ac80/Resources/Python/lib/python2.7/shutil.py", line 12, in <module>
    import collections
  File "/usr/local/PlexMediaServer-0.9.12.19.1537-f38ac80/Resources/Python/lib/python2.7/collections.py", line 8, in <module>
    from _collections import deque, defaultdict
ImportError: Shared object "libpython2.7.so" not found, required by "_collections.so"

What happened? How do I fix this?

**Comment by SickRage2** [comment]
Thanks for the issue report! Before a real human comes by, please make sure your report has all the below criteria checked

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [ ] Post debug logs, either inline (for smaller logs) or using gist)

Please make sure you also read [how to create an issue](https://github.com/SickRage/sickrage-issues/blob/master/README.md) and followed all of the steps. 

The title should describe your issue. Having "SR not working" or "I get this bug" for 100 issues, isn't really helpful. We will close issues if there isn't enough information.

Sometimes the devs may seem like grunts and respond with short answers. This isn't (always) because the dev hates you, but because he's on mobile or busy fixing bugs. If something isn't clear, please let us know, and this bot may get updated to automatically answer you.

Thanks!

**Comment by neoatomic** [comment]
Sickrage doesn't touch Python at all. 
The issue is probbebly the old Repo that wracked/messed up your device/install. 
And sadly you are not the first one that gets to experience that... 

I would try to remove/reinstall Plex & Python, and hope you can fix it that way.
(Also check our Wiki, there are guides to install Sickrage etc from scratch.)
