### ISSUE TITLE
[APP SUBMITTED]: 404 {u'documentation_url': u'https://developer.github.com/v3/gists/#create-a-gist', u'message': u'Not Found'}

### ISSUE THREAD

**Issue by darkwinternight** [SickRage/sickrage-issues#715]
### INFO
Python Version: **2.7.11 (default, Dec 17 2015, 15:58:38) [GCC 4.7.3 20130102 (prerelease)]**
Operating System: **Linux-3.10.77-x86_64-with-glibc2.2.5**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@f568d1515557f854042511d7bfee3ae070c864bd
No Log available with ERRORS:
### ERROR
```
Thread-57 :: Traceback (most recent call last):
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/logger.py", line 293, in submit_errors
    gist = git.get_user().create_gist(True, {'sickrage.log': InputFileContent(paste_data)})
  File "/usr/local/sickbeard-custom/var/SickBeard/lib/github/AuthenticatedUser.py", line 473, in create_gist
    input=post_parameters
  File "/usr/local/sickbeard-custom/var/SickBeard/lib/github/Requester.py", line 171, in requestJsonAndCheck
    return self.__check(*self.requestJson(verb, url, parameters, headers, input, cnx))
  File "/usr/local/sickbeard-custom/var/SickBeard/lib/github/Requester.py", line 179, in __check
    raise self.__createException(status, responseHeaders, output)
UnknownObjectException: 404 {u'documentation_url': u'https://developer.github.com/v3/gists/#create-a-gist', u'message': u'Not Found'}
 [f568d15]
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by SickRage2** [comment]
Thanks for the issue report! Before a real human comes by, please make sure your report has all the below criteria checked

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [ ] Post debug logs, either inline (for smaller logs) or using gist)

Please make sure you also read [how to create an issue](https://github.com/SickRage/sickrage-issues/blob/master/README.md) and followed all of the steps. 

The title should describe your issue. Having "SR not working" or "I get this bug" for 100 issues, isn't really helpful. We will close issues if there isn't enough information.

Sometimes the devs may seem like grunts and respond with short answers. This isn't (always) because the dev hates you, but because he's on mobile or busy fixing bugs. If something isn't clear, please let us know, and this bot may get updated to automatically answer you.

Thanks!
