### ISSUE TITLE
Subtitle UnicodeDecodeError

### ISSUE THREAD

**Issue by labrys** [SickRage/sickrage-issues#721]
>SickRage Version:	Branch: subs-no-ek
Commit: 6c0c91d30ec1b948bd657d28133f96273dcbf097
Version: v5.1.2
 Operating System:	Windows-10-10.0.10240
 Python Version:	2.7.11 (v2.7.11:6d1b6a68f775, Dec 5 2015, 20:32:19) [MSC v.1500 32 bit (Intel)]
 SSL Version:	OpenSSL 1.0.2d 9 Jul 2015
 Locale:	en_US.cp1252

Got the following traceback during normally scheduled run:

```
2016-01-31 09:37:51 INFO     POSTPROCESSER :: Error occurred when downloading subtitles for: Sealab 2021 [2000]\Season 02\Sealab 2021 - S02E03 - Swimming in Oblivion.mp4
2016-01-31 09:37:51 ERROR    POSTPROCESSER :: Traceback (most recent call last):
  File "sickrage\sickbeard\subtitles.py", line 188, in download_subtitles
    min_score=user_score, only_one=not sickbeard.SUBTITLES_MULTI)
  File "sickrage\lib\subliminal\api.py", line 267, in download_best_subtitles
    for s in subtitles], key=operator.itemgetter(1), reverse=True)
  File "sickrage\lib\subliminal\providers\opensubtitles.py", line 69, in get_matches
    matches |= guess_matches(video, guessit(self.movie_release_name, {'type': 'episode'}))
  File "sickrage\lib\guessit\api.py", line 29, in guessit
    return default_api.guessit(string, options)
  File "sickrage\lib\guessit\api.py", line 80, in guessit
    match.value = match.value.decode("utf-8")
  File "python27\lib\encodings\utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
UnicodeDecodeError: 'utf8' codec can't decode byte 0xa0 in position 6: invalid start byte
 [6c0c91d]
```

And the following warning from the post processor:
```
2016-01-31 09:37:50 POSTPROCESSER :: An error occurred while getting a subtitle match for: Sealab 2021 [2000]\Season 02\Sealab 2021 - S02E03 - Swimming in Oblivion.mp4. Error: utf8 : Glups  ! Apparition d'un faux Goku  !! : error 6 : error 7 : invalid start byte [6c0c91d]
```
I would assume this is an upstream issue as `Glups  ! Apparition d'un faux Goku  !!` is the French translation of the movie title [`Dragonball: Egad! A Goku Imposter!`](www.imdb.com/title/tt0838671/), which, as you can see, was not part of the original search query.

**Comment by SickRage2** [comment]
Thanks for the issue report! Before a real human comes by, please make sure your report has all the below criteria checked

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [x] Post debug logs, either inline (for smaller logs) or using gist)
- [x] Please wrap inline logs inside \`\`\` and \`\`\` for readability

Please make sure you also read [how to create an issue](https://github.com/SickRage/sickrage-issues/blob/master/README.md) and followed all of the steps. 

The title should describe your issue. Having "SR not working" or "I get this bug" for 100 issues, isn't really helpful. We will close issues if there isn't enough information.

Sometimes the devs may seem like grunts and respond with short answers. This isn't (always) because the dev hates you, but because he's on mobile or busy fixing bugs. If something isn't clear, please let us know, and this bot may get updated to automatically answer you.

Thanks!

**Comment by labrys** [comment]
@medariox This is using your `subs-no-ek` branch rebased on current dev.

**Comment by medariox** [comment]
@labrys 
What a weird error. Do you even have that show in your library? Definitely looks like an upstream issue, probably guessit.

PS: Thanks for trying out the branch :+1:

**Comment by labrys** [comment]
No the movie is definitely not in the library.
