### ISSUE TITLE
Eps not downloading via nzb. Object has no attribute errno 

### ISSUE THREAD

**Issue by udochrist** [SickRage/sickrage-issues#724]
This is logged as info after the search seems to have found eps for d/l. The are not downloaded.
Sorry for the formatting. Copy paste and edit is a pita from an iPad on github.

Branch: master
Commit: 5195b784b76916a2acfe21c1fffd12f837ce0e93
Version: 2016.01.31-1

```logs```

2016-01-31 18:28:40 DEBUG    SEARCHQUEUE-BACKLOG-303291 :: [NZB.su] :: Last update was too soon, using old cache: 2016-01-31 18:21:12. Updated less then 30 minutes ago
2016-01-31 18:28:40 DEBUG    SEARCHQUEUE-BACKLOG-303291 :: [DOGnzb] :: Last update was too soon, using old cache: 2016-01-31 18:21:01. Updated less then 30 minutes ago
2016-01-31 18:28:40 DEBUG    SEARCHQUEUE-BACKLOG-303291 :: Internal name cache for Schwarzesmarken set to: [ schwarzesmarken ]
2016-01-31 18:28:40 INFO     SEARCHQUEUE-BACKLOG-303291 :: Beginning backlog search for: [Schwarzesmarken]
AA
AAAttributeError: 'exceptions.AssertionError' object has no attribute 'errno'
AA    if e.errno != errno.ECONNRESET:
AA  File "/volume1/@appstore/sickrage/var/SickRage/sickbeard/search.py", line 519, in searchProviders
AA    searchResult = search.searchProviders(self.show, self.segment, False)
AA  File "/volume1/@appstore/sickrage/var/SickRage/sickbeard/search_queue.py", line 222, in run
2016-01-31 18:28:39 DEBUG    SEARCHQUEUE-BACKLOG-295222 :: [NZB.su] :: Traceback (most recent call last):
2016-01-31 18:28:37 DEBUG    SEARCHQUEUE-BACKLOG-295222 :: [NZB.su] :: Search URL: https://api.nzb.su/api?apikey=**********&tvdbid=295222&season=1&maxage=2240&cat=5070%2C5080%2C5040%2C5030&limit=100&t=tvsearch&offset=0&ep=1
2016-01-31 18:28:37 DEBUG    SEARCHQUEUE-BACKLOG-295222 :: [NZB.su] :: Search string: Gate: Jieitai Kanochi Nite, Kaku Tatakaeri 01 
2016-01-31 18:28:37 DEBUG    SEARCHQUEUE-BACKLOG-295222 :: [NZB.su] :: Search Mode: Episode
2016-01-31 18:28:34 DEBUG    SEARCHQUEUE-BACKLOG-295222 :: [NZB.su] :: Search URL: https://api.nzb.su/api?apikey=**********&tvdbid=295222&season=1&maxage=2240&cat=5070%2C5080%2C5040%2C5030&limit=100&t=tvsearch&offset=0&ep=2

**Comment by SickRage2** [comment]
Thanks for the issue report! Before a real human comes by, please make sure your report has all the below criteria checked

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [x] Post debug logs, either inline (for smaller logs) or using gist)
- [ ] Please wrap inline logs inside \`\`\` and \`\`\` for readability

Please make sure you also read [how to create an issue](https://github.com/SickRage/sickrage-issues/blob/master/README.md) and followed all of the steps. 

The title should describe your issue. Having "SR not working" or "I get this bug" for 100 issues, isn't really helpful. We will close issues if there isn't enough information.

Sometimes the devs may seem like grunts and respond with short answers. This isn't (always) because the dev hates you, but because he's on mobile or busy fixing bugs. If something isn't clear, please let us know, and this bot may get updated to automatically answer you.

Thanks!

**Comment by neoatomic** [comment]
@udochrist The problem is that NZB.su doesn't support searching with the tvdbid like : `&tvdbid=295222`.
All Major indexers support that but it seems nzb.su hasn't implemented that yet. Not sure why they dont support it, as it also reduces api call's by about 3 times. 
It only effects the backlog search, so just disable that for now on the nzb.su settings, and you should be fine.

We are currently considering how we should handle those outdated indexers, you can follow that here. : https://github.com/SickRage/sickrage-issues/issues/667

**Comment by udochrist** [comment]
Done. Thanks for your fast help. 
 Nevertheless failing with missing attribute errno still seems to be an error. Besides that error log level  would be appropriate in that case

**Comment by fernandog** [comment]
@miigotu the issue we talked about in IRC. @duramato have this too
