### ISSUE TITLE
[APP SUBMITTED]: Old quality does not match new: SD DVD != 720p HDTV : Bleach S15E14 330 720p.DVDRip.x264.AAC

### ISSUE THREAD

**Issue by Gumbyohson** [SickRage/sickrage-issues#744]
### INFO
Python Version: **2.7.11 (v2.7.11:6d1b6a68f775, Dec  5 2015, 20:32:19) [MSC v.1500 32 bit (Intel)]**
Operating System: **Windows-10-10.0.10586**
Locale: cp1252
Branch: **master**
Commit: SickRage/SickRage@3dd13c33887e3e09d706646f007d92678b0697c0
No Log available with ERRORS:
### ERROR
```
Thread-38 :: Failed doing webui callback: Traceback (most recent call last):
  File "C:\Users\Plex\Downloads\Download applications\SickRage2\sickbeard\webserve.py", line 285, in async_call
    result = function(**kwargs)
  File "C:\Users\Plex\Downloads\Download applications\SickRage2\sickbeard\webserve.py", line 2281, in processEpisode
    is_priority=argToBool(is_priority), delete_on=argToBool(delete_on), failed=argToBool(failed), proc_type=type
  File "C:\Users\Plex\Downloads\Download applications\SickRage2\sickbeard\processTV.py", line 222, in processDir
    process_media(path, [video], nzbName, process_method, force, is_priority, result)
  File "C:\Users\Plex\Downloads\Download applications\SickRage2\sickbeard\processTV.py", line 544, in process_media
    result.result = processor.process()
  File "C:\Users\Plex\Downloads\Download applications\SickRage2\sickbeard\postProcessor.py", line 939, in process
    (show, season, episodes, quality, version) = self._find_info()
  File "C:\Users\Plex\Downloads\Download applications\SickRage2\sickbeard\postProcessor.py", line 662, in _find_info
    (cur_show, cur_season, cur_episodes, cur_quality, cur_version) = cur_attempt()
  File "C:\Users\Plex\Downloads\Download applications\SickRage2\sickbeard\postProcessor.py", line 646, in <lambda>
    lambda: self._analyze_name(self.file_name),
  File "C:\Users\Plex\Downloads\Download applications\SickRage2\sickbeard\postProcessor.py", line 580, in _analyze_name
    parse_result = np.parse(name)
  File "C:\Users\Plex\Downloads\Download applications\SickRage2\sickbeard\name_parser\parser.py", line 421, in parse
    file_name_result = self._parse_string(base_file_name)
  File "C:\Users\Plex\Downloads\Download applications\SickRage2\sickbeard\name_parser\parser.py", line 211, in _parse_string
    bestResult.quality = common.Quality.nameQuality(name, bestResult.show.is_anime)
  File "C:\Users\Plex\Downloads\Download applications\SickRage2\sickbeard\common.py", line 279, in nameQuality
    quality = Quality.sceneQuality(name, anime)
  File "C:\Users\Plex\Downloads\Download applications\SickRage2\sickbeard\common.py", line 455, in sceneQuality
    assert old == result, 'Old quality does not match new: %s != %s : %s' % (Quality.qualityStrings[old], Quality.qualityStrings[result], name)
AssertionError: Old quality does not match new: SD DVD != 720p HDTV : Bleach S15E14 330 720p.DVDRip.x264.AAC
 [3dd13c3]
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by SickRage2** [comment]
Thanks for the issue report! Before a real human comes by, please make sure your report has all the below criteria checked

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [ ] Post debug logs, either inline (for smaller logs) or using gist)

Please make sure you also read [how to create an issue](https://github.com/SickRage/sickrage-issues/blob/master/README.md) and followed all of the steps. 

The title should describe your issue. Having "SR not working" or "I get this bug" for 100 issues, isn't really helpful. We will close issues if there isn't enough information.

Sometimes the devs may seem like grunts and respond with short answers. This isn't (always) because the dev hates you, but because he's on mobile or busy fixing bugs. If something isn't clear, please let us know, and this bot may get updated to automatically answer you.

Thanks!

**Comment by Gumbyohson** [comment]
### INFO
Python Version: **2.7.11 (v2.7.11:6d1b6a68f775, Dec  5 2015, 20:32:19) [MSC v.1500 32 bit (Intel)]**
Operating System: **Windows-10-10.0.10586**
Locale: cp1252
Branch: **master**
Commit: SickRage/SickRage@3dd13c33887e3e09d706646f007d92678b0697c0
No Log available with ERRORS:
### ERROR
```
POSTPROCESSER :: Exception generated in thread POSTPROCESSER: Old quality does not match new: SD DVD != 720p HDTV : Bleach S15E14 330 720p.DVDRip.x264.AAC [3dd13c3]
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by Gumbyohson** [comment]
### INFO
Python Version: **2.7.11 (v2.7.11:6d1b6a68f775, Dec  5 2015, 20:32:19) [MSC v.1500 32 bit (Intel)]**
Operating System: **Windows-10-10.0.10586**
Locale: cp1252
Branch: **master**
Commit: SickRage/SickRage@3dd13c33887e3e09d706646f007d92678b0697c0
No Log available with ERRORS:
### ERROR
```
Thread-26 :: Failed doing webui callback: Traceback (most recent call last):
  File "C:\Users\Plex\Downloads\Download applications\SickRage2\sickbeard\webserve.py", line 285, in async_call
    result = function(**kwargs)
  File "C:\Users\Plex\Downloads\Download applications\SickRage2\sickbeard\webserve.py", line 2281, in processEpisode
    is_priority=argToBool(is_priority), delete_on=argToBool(delete_on), failed=argToBool(failed), proc_type=type
  File "C:\Users\Plex\Downloads\Download applications\SickRage2\sickbeard\processTV.py", line 222, in processDir
    process_media(path, [video], nzbName, process_method, force, is_priority, result)
  File "C:\Users\Plex\Downloads\Download applications\SickRage2\sickbeard\processTV.py", line 544, in process_media
    result.result = processor.process()
  File "C:\Users\Plex\Downloads\Download applications\SickRage2\sickbeard\postProcessor.py", line 939, in process
    (show, season, episodes, quality, version) = self._find_info()
  File "C:\Users\Plex\Downloads\Download applications\SickRage2\sickbeard\postProcessor.py", line 662, in _find_info
    (cur_show, cur_season, cur_episodes, cur_quality, cur_version) = cur_attempt()
  File "C:\Users\Plex\Downloads\Download applications\SickRage2\sickbeard\postProcessor.py", line 646, in <lambda>
    lambda: self._analyze_name(self.file_name),
  File "C:\Users\Plex\Downloads\Download applications\SickRage2\sickbeard\postProcessor.py", line 580, in _analyze_name
    parse_result = np.parse(name)
  File "C:\Users\Plex\Downloads\Download applications\SickRage2\sickbeard\name_parser\parser.py", line 421, in parse
    file_name_result = self._parse_string(base_file_name)
  File "C:\Users\Plex\Downloads\Download applications\SickRage2\sickbeard\name_parser\parser.py", line 211, in _parse_string
    bestResult.quality = common.Quality.nameQuality(name, bestResult.show.is_anime)
  File "C:\Users\Plex\Downloads\Download applications\SickRage2\sickbeard\common.py", line 279, in nameQuality
    quality = Quality.sceneQuality(name, anime)
  File "C:\Users\Plex\Downloads\Download applications\SickRage2\sickbeard\common.py", line 455, in sceneQuality
    assert old == result, 'Old quality does not match new: %s != %s : %s' % (Quality.qualityStrings[old], Quality.qualityStrings[result], name)
AssertionError: Old quality does not match new: SD DVD != 720p HDTV : Bleach S15E14 330 720p.DVDRip.x264.AAC
 [3dd13c3]
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by Gumbyohson** [comment]
### INFO
Python Version: **2.7.11 (v2.7.11:6d1b6a68f775, Dec  5 2015, 20:32:19) [MSC v.1500 32 bit (Intel)]**
Operating System: **Windows-10-10.0.10586**
Locale: cp1252
Branch: **master**
Commit: SickRage/SickRage@3dd13c33887e3e09d706646f007d92678b0697c0
No Log available with ERRORS:
### ERROR
```
Thread-32 :: Failed doing webui callback: Traceback (most recent call last):
  File "C:\Users\Plex\Downloads\Download applications\SickRage2\sickbeard\webserve.py", line 285, in async_call
    result = function(**kwargs)
  File "C:\Users\Plex\Downloads\Download applications\SickRage2\sickbeard\webserve.py", line 2281, in processEpisode
    is_priority=argToBool(is_priority), delete_on=argToBool(delete_on), failed=argToBool(failed), proc_type=type
  File "C:\Users\Plex\Downloads\Download applications\SickRage2\sickbeard\processTV.py", line 222, in processDir
    process_media(path, [video], nzbName, process_method, force, is_priority, result)
  File "C:\Users\Plex\Downloads\Download applications\SickRage2\sickbeard\processTV.py", line 544, in process_media
    result.result = processor.process()
  File "C:\Users\Plex\Downloads\Download applications\SickRage2\sickbeard\postProcessor.py", line 939, in process
    (show, season, episodes, quality, version) = self._find_info()
  File "C:\Users\Plex\Downloads\Download applications\SickRage2\sickbeard\postProcessor.py", line 662, in _find_info
    (cur_show, cur_season, cur_episodes, cur_quality, cur_version) = cur_attempt()
  File "C:\Users\Plex\Downloads\Download applications\SickRage2\sickbeard\postProcessor.py", line 646, in <lambda>
    lambda: self._analyze_name(self.file_name),
  File "C:\Users\Plex\Downloads\Download applications\SickRage2\sickbeard\postProcessor.py", line 580, in _analyze_name
    parse_result = np.parse(name)
  File "C:\Users\Plex\Downloads\Download applications\SickRage2\sickbeard\name_parser\parser.py", line 421, in parse
    file_name_result = self._parse_string(base_file_name)
  File "C:\Users\Plex\Downloads\Download applications\SickRage2\sickbeard\name_parser\parser.py", line 211, in _parse_string
    bestResult.quality = common.Quality.nameQuality(name, bestResult.show.is_anime)
  File "C:\Users\Plex\Downloads\Download applications\SickRage2\sickbeard\common.py", line 279, in nameQuality
    quality = Quality.sceneQuality(name, anime)
  File "C:\Users\Plex\Downloads\Download applications\SickRage2\sickbeard\common.py", line 455, in sceneQuality
    assert old == result, 'Old quality does not match new: %s != %s : %s' % (Quality.qualityStrings[old], Quality.qualityStrings[result], name)
AssertionError: Old quality does not match new: SD DVD != 720p HDTV : Bleach S15E14 330 720p.DVDRip.x264.AAC
 [3dd13c3]
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by Gumbyohson** [comment]
### INFO
Python Version: **2.7.11 (v2.7.11:6d1b6a68f775, Dec  5 2015, 20:32:19) [MSC v.1500 32 bit (Intel)]**
Operating System: **Windows-10-10.0.10586**
Locale: cp1252
Branch: **master**
Commit: SickRage/SickRage@3dd13c33887e3e09d706646f007d92678b0697c0
No Log available with ERRORS:
### ERROR
```
Thread-24 :: Failed doing webui callback: Traceback (most recent call last):
  File "C:\Users\Plex\Downloads\Download applications\SickRage2\sickbeard\webserve.py", line 285, in async_call
    result = function(**kwargs)
  File "C:\Users\Plex\Downloads\Download applications\SickRage2\sickbeard\webserve.py", line 2281, in processEpisode
    is_priority=argToBool(is_priority), delete_on=argToBool(delete_on), failed=argToBool(failed), proc_type=type
  File "C:\Users\Plex\Downloads\Download applications\SickRage2\sickbeard\processTV.py", line 222, in processDir
    process_media(path, [video], nzbName, process_method, force, is_priority, result)
  File "C:\Users\Plex\Downloads\Download applications\SickRage2\sickbeard\processTV.py", line 544, in process_media
    result.result = processor.process()
  File "C:\Users\Plex\Downloads\Download applications\SickRage2\sickbeard\postProcessor.py", line 939, in process
    (show, season, episodes, quality, version) = self._find_info()
  File "C:\Users\Plex\Downloads\Download applications\SickRage2\sickbeard\postProcessor.py", line 662, in _find_info
    (cur_show, cur_season, cur_episodes, cur_quality, cur_version) = cur_attempt()
  File "C:\Users\Plex\Downloads\Download applications\SickRage2\sickbeard\postProcessor.py", line 646, in <lambda>
    lambda: self._analyze_name(self.file_name),
  File "C:\Users\Plex\Downloads\Download applications\SickRage2\sickbeard\postProcessor.py", line 580, in _analyze_name
    parse_result = np.parse(name)
  File "C:\Users\Plex\Downloads\Download applications\SickRage2\sickbeard\name_parser\parser.py", line 421, in parse
    file_name_result = self._parse_string(base_file_name)
  File "C:\Users\Plex\Downloads\Download applications\SickRage2\sickbeard\name_parser\parser.py", line 211, in _parse_string
    bestResult.quality = common.Quality.nameQuality(name, bestResult.show.is_anime)
  File "C:\Users\Plex\Downloads\Download applications\SickRage2\sickbeard\common.py", line 279, in nameQuality
    quality = Quality.sceneQuality(name, anime)
  File "C:\Users\Plex\Downloads\Download applications\SickRage2\sickbeard\common.py", line 455, in sceneQuality
    assert old == result, 'Old quality does not match new: %s != %s : %s' % (Quality.qualityStrings[old], Quality.qualityStrings[result], name)
AssertionError: Old quality does not match new: SD DVD != 720p HDTV : Bleach S15E14 330 720p.DVDRip.x264.AAC
 [3dd13c3]
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by labrys** [comment]
@Gumbyohson This is just a validation method for a new quality system we have implemented.  It will be removed in the next couple of days.

**Comment by Gumbyohson** [comment]
Hey Guys,

Don't know if this email works or is monitored but whenever I'm manually
postprocessing i'm getting a 404 page.
Not sure if this is related.

thanks,

Gumby

**Comment by labrys** [comment]
Expand the information for the 404 and see if there is details for it.  If there is, and the traceback is for the same error, then it would be the same cause.  Another way to check, or if no additional details are listed on the 404 page, would be to clear all errors/warnings, manual post process and check the error/warning log for information regarding the error that occurred.

**Comment by Gumbyohson** [comment]
### INFO
Python Version: **2.7.11 (v2.7.11:6d1b6a68f775, Dec  5 2015, 20:32:19) [MSC v.1500 32 bit (Intel)]**
Operating System: **Windows-10-10.0.10586**
Locale: cp1252
Branch: **develop**
Commit: SickRage/SickRage@1cd527b25a5df4d5c0415f22ed464b5447f41a9d
No Log available with ERRORS:
### ERROR
```
Thread-25 :: Failed doing webui callback: Traceback (most recent call last):
  File "C:\Users\Plex\Downloads\Download applications\SickRage2\sickbeard\webserve.py", line 285, in async_call
    result = function(**kwargs)
  File "C:\Users\Plex\Downloads\Download applications\SickRage2\sickbeard\webserve.py", line 2452, in processEpisode
    is_priority=argToBool(is_priority), delete_on=argToBool(delete_on), failed=argToBool(failed), proc_type=type
  File "C:\Users\Plex\Downloads\Download applications\SickRage2\sickbeard\processTV.py", line 222, in processDir
    process_media(path, [video], nzbName, process_method, force, is_priority, result)
  File "C:\Users\Plex\Downloads\Download applications\SickRage2\sickbeard\processTV.py", line 544, in process_media
    result.result = processor.process()
  File "C:\Users\Plex\Downloads\Download applications\SickRage2\sickbeard\postProcessor.py", line 939, in process
    (show, season, episodes, quality, version) = self._find_info()
  File "C:\Users\Plex\Downloads\Download applications\SickRage2\sickbeard\postProcessor.py", line 662, in _find_info
    (cur_show, cur_season, cur_episodes, cur_quality, cur_version) = cur_attempt()
  File "C:\Users\Plex\Downloads\Download applications\SickRage2\sickbeard\postProcessor.py", line 646, in <lambda>
    lambda: self._analyze_name(self.file_name),
  File "C:\Users\Plex\Downloads\Download applications\SickRage2\sickbeard\postProcessor.py", line 580, in _analyze_name
    parse_result = np.parse(name)
  File "C:\Users\Plex\Downloads\Download applications\SickRage2\sickbeard\name_parser\parser.py", line 421, in parse
    file_name_result = self._parse_string(base_file_name)
  File "C:\Users\Plex\Downloads\Download applications\SickRage2\sickbeard\name_parser\parser.py", line 211, in _parse_string
    bestResult.quality = common.Quality.nameQuality(name, bestResult.show.is_anime)
  File "C:\Users\Plex\Downloads\Download applications\SickRage2\sickbeard\common.py", line 279, in nameQuality
    quality = Quality.sceneQuality(name, anime)
  File "C:\Users\Plex\Downloads\Download applications\SickRage2\sickbeard\common.py", line 455, in sceneQuality
    assert old == result, 'Old quality does not match new: %s != %s : %s' % (Quality.qualityStrings[old], Quality.qualityStrings[result], name)
AssertionError: Old quality does not match new: SD DVD != 720p HDTV : Bleach S15E14 330 720p.DVDRip.x264.AAC
 [1cd527b]
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by duramato** [comment]
`720p.DVDRip`  oO what kind of dvd is that? The old HDDVD ? lol

**Comment by labrys** [comment]
@duramato It's improperly labeled.  

It's either a mislabeled `BluRay`/`HD-DVD` or its a standard `DVD` that was either labeled by the horizontal, not vertical, resolution (480p = 720x480; 720p=1280x720) or DVD ripped at 720p, a higher resolution than the actual media, and thus crap.

The old system classed this as SD DVD, the current thinks it is 720p HDTV,  this is the types of reasons we are doing this assert.  This *should be* `UNKNOWN`

**Comment by Gumbyohson** [comment]
Hey all,

I might also note that whenever this happens postprocessing stops and can't
get past this file.

Thanks,

Gumby

**Comment by labrys** [comment]
@Gumbyohson thanks for the info.

**Comment by labrys** [comment]
@Gumbyohson and just to be clear, was the 404 error and the traceback the same thing?  If not was it the 404 that prevents the PP or the traceback?

**Comment by Gumbyohson** [comment]
Yes the 404 was related to the incorrect recognition of the quality and
prevented PP.
