### ISSUE TITLE
ERROR POST PROCESSING

### ISSUE THREAD

**Issue by luigose** [SickRage/sickrage-issues#780]
HELP ME PLEASE;;

QNAP TVS 463
```
2016-02-05 20:43:00 Thread-55 :: Failed doing webui callback: Traceback (most recent call last):
  File "/share/CACHEDEV1_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/sickbeard/webserve.py", line 285, in async_call
    result = function(**kwargs)
  File "/share/CACHEDEV1_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/sickbeard/webserve.py", line 2281, in processEpisode
    is_priority=argToBool(is_priority), delete_on=argToBool(delete_on), failed=argToBool(failed), proc_type=type
  File "/share/CACHEDEV1_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/sickbeard/processTV.py", line 265, in processDir
    process_media(processPath, videoFiles, nzbName, process_method, force, is_priority, result)
  File "/share/CACHEDEV1_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/sickbeard/processTV.py", line 544, in process_media
    result.result = processor.process()
  File "/share/CACHEDEV1_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/sickbeard/postProcessor.py", line 1009, in process
    if not helpers.isFileLocked(self.file_path, False):
  File "/share/CACHEDEV1_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/sickbeard/helpers.py", line 1700, in isFileLocked
    f = io.open(checkfile, 'rb')
UnicodeEncodeError: 'ascii' codec can't encode character u'\xf1' in position 112: ordinal not in range(128)
 [5d51b16]
```

**Comment by SickRage2** [comment]
Thanks for the issue report! Before a real human comes by, please make sure your report has all the below criteria checked

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [ ] Post debug logs, either inline (for smaller logs) or using gist)

Please make sure you also read [how to create an issue](https://github.com/SickRage/sickrage-issues/blob/master/README.md) and followed all of the steps. 

The title should describe your issue. Having "SR not working" or "I get this bug" for 100 issues, isn't really helpful. We will close issues if there isn't enough information.

Sometimes the devs may seem like grunts and respond with short answers. This isn't (always) because the dev hates you, but because he's on mobile or busy fixing bugs. If something isn't clear, please let us know, and this bot may get updated to automatically answer you.

Thanks!

**Comment by duramato** [comment]
What about you giving the info the bot requested?

**Comment by luigose** [comment]
2016-02-05 20:57:50 Thread-15 :: Failed doing webui callback: Traceback (most recent call last):
  File "/share/CACHEDEV1_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/sickbeard/webserve.py", line 285, in async_call
    result = function(**kwargs)
  File "/share/CACHEDEV1_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/sickbeard/webserve.py", line 2281, in processEpisode
    is_priority=argToBool(is_priority), delete_on=argToBool(delete_on), failed=argToBool(failed), proc_type=type
  File "/share/CACHEDEV1_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/sickbeard/processTV.py", line 265, in processDir
    process_media(processPath, videoFiles, nzbName, process_method, force, is_priority, result)
  File "/share/CACHEDEV1_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/sickbeard/processTV.py", line 544, in process_media
    result.result = processor.process()
  File "/share/CACHEDEV1_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/sickbeard/postProcessor.py", line 1009, in process
    if not helpers.isFileLocked(self.file_path, False):
  File "/share/CACHEDEV1_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/sickbeard/helpers.py", line 1700, in isFileLocked
    f = io.open(checkfile, 'rb')
UnicodeEncodeError: 'ascii' codec can't encode character u'\xf1' in position 115: ordinal not in range(128)
 [5d51b16]
2016-02-05 20:56:59 POSTPROCESSER :: Exception generated in thread POSTPROCESSER: ascii : /share/CACHEDEV1_DATA/Download/transmission/completed/The Blacklist - Temporada 3 [HDTV 720p][Cap.309][AC3 5.1 Español Castellano]/The Blacklist 720p 3x09 [www.newpct1.com].mkv : error 115 : error 116 : ordinal not in range(128) [5d51b16]

**Comment by duramato** [comment]
```
Include basic information: Branch/Commit,locale , OS, What you did, What happened, What you expected
Enable debug logging (be sure to disable after the bug is fixed)
Post debug logs, either inline (for smaller logs) or using gist)
```

**Comment by luigose** [comment]
SickRage Version:	Branch: master
Commit: 5d51b1687edf252958317c8cbb110069d7b207b3
Version: 2016.01.31-1
 Operating System:	Linux-3.12.6-x86_64-with-glibc2.2.5
 Python Version:	2.7.11 (default, Jan 9 2016, 16:55:40) [GCC 4.8.5]
 SSL Version:	OpenSSL 1.0.2e 3 Dec 2015
 Locale:	None.None

the problem maybe locale??

**Comment by duramato** [comment]
It is you need to set it to UTF-8 but i dont know how its done on a QNAP , @neoatomic ?

**Comment by luigose** [comment]
how fix locale:none.none?

**Comment by neoatomic** [comment]
@luigose Best to ask on the QNAP forums, as i sadly are not familiar with QNAP's...
http://forum.qnap.com/viewtopic.php?f=223&t=118366#p525730

But it is indeed a locale issue as the `ñ` isn't recognized correctly. So if you remove that the PP should work fine for now.

**Comment by medariox** [comment]
Fixed in develop.
