### ISSUE TITLE
Schedule not show today shows 

### ISSUE THREAD

**Issue by jms05** [SickRage/sickrage-issues#787]
On schedule page it shows every coming shows but not show today shows, i'm running on OMV NAS

**Comment by SickRage2** [comment]
Thanks for the issue report! Before a real human comes by, please make sure your report has all the below criteria checked

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [ ] Post debug logs, either inline (for smaller logs) or using gist)

Please make sure you also read [how to create an issue](https://github.com/SickRage/sickrage-issues/blob/master/README.md) and followed all of the steps. 

The title should describe your issue. Having "SR not working" or "I get this bug" for 100 issues, isn't really helpful. We will close issues if there isn't enough information.

Sometimes the devs may seem like grunts and respond with short answers. This isn't (always) because the dev hates you, but because he's on mobile or busy fixing bugs. If something isn't clear, please let us know, and this bot may get updated to automatically answer you.

Thanks!

**Comment by neoatomic** [comment]
@jms05 I just tested by adding a show that airs today, but all is working fine. : 


![2](https://cloud.githubusercontent.com/assets/7928052/12873181/3105310e-cdb7-11e5-8581-6958589a0b70.png)
![3](https://cloud.githubusercontent.com/assets/7928052/12873182/3125007e-cdb7-11e5-8ece-19194009ea61.png)


@miigotu However i got a error while switching between the schedule layouts.
The show i added `Trapped (2015)` doesn't seem to have a timezone (showed me 0:00).
As the traceback is talking that it needs 2 arguments instead of 1 (given) , i'm thinking there might be something missing related to the timezone.?


```
2016-02-07 16:17:44 ERROR    Thread-47 :: Failed doing webui callback: Traceback (most recent call last):
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/webserve.py", line 283, in async_call
    result = function(**kwargs)
TypeError: setScheduleLayout() takes exactly 2 arguments (1 given)
 [02badb0]
Traceback (most recent call last):
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/webserve.py", line 283, in async_call
    result = function(**kwargs)
TypeError: setScheduleLayout() takes exactly 2 arguments (1 given)
2016-02-07 16:17:44 DEBUG    TORNADO :: Failed doing webui request "setScheduleLayout": Traceback (most recent call last):
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/webserve.py", line 268, in get
    results = yield self.async_call(method)
  File "/usr/local/sickbeard-custom/var/SickBeard/lib/tornado/gen.py", line 870, in run
    value = future.result()
  File "/usr/local/sickbeard-custom/var/SickBeard/lib/concurrent/futures/_base.py", line 400, in result
    return self.__get_result()
  File "/usr/local/sickbeard-custom/var/SickBeard/lib/concurrent/futures/_base.py", line 359, in __get_result
    reraise(self._exception, self._traceback)
  File "/usr/local/sickbeard-custom/var/SickBeard/lib/concurrent/futures/_compat.py", line 107, in reraise
    exec('raise exc_type, exc_value, traceback', {}, locals_)
  File "/usr/local/sickbeard-custom/var/SickBeard/lib/concurrent/futures/thread.py", line 61, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/webserve.py", line 283, in async_call
    result = function(**kwargs)
TypeError: setScheduleLayout() takes exactly 2 arguments (1 given)
```

**Comment by miigotu** [comment]
@neoatomic I cant reproduce that setScheduleLayout problem either, and I checked the code, it always has a value.

**Comment by jms05** [comment]
i dont have any show that goes on today, but i try add the one you added and says air date was yesterday

**Comment by neoatomic** [comment]
@jms05 It has to do with the timezone. A show can air today for you, but for someone in Australia it would be Yesterday.

**Comment by jms05** [comment]
@neoatomic 
today i have shows that go on as you see on my Sunday screenshot bot in today's one nothing shows.
![capture](https://cloud.githubusercontent.com/assets/9093746/12929596/8b50a412-cf6b-11e5-910c-7fb337b7fa74.PNG)
![capture2](https://cloud.githubusercontent.com/assets/9093746/12929597/8b56da12-cf6b-11e5-8114-b4e9835ba724.PNG)

**Comment by neoatomic** [comment]
Check your hardware clock / system time / network time. Maybe one of those isn't correct and causing this strange issue.

It seems to be working fine for me. Its just past midnight here, and Schedule is showing correctly today's shows that air.

Maybe @fernandog could do a quick check as he is in another time zone.

![1](https://cloud.githubusercontent.com/assets/7928052/12934682/b837a23a-cf90-11e5-9803-e597eab92acc.png)

**Comment by jms05** [comment]
problem solved :)
change the timezone to network it was on local as @neoatomic  said something about timezone and system time e remember to check this setting.
