### ISSUE TITLE
[APP SUBMITTED]: 'exceptions.AttributeError' object has no attribute 'errno'

### ISSUE THREAD

**Issue by kriznik** [SickRage/sickrage-issues#788]
### INFO
Python Version: **2.7.9 (default, Mar 24 2015, 00:42:24) [GCC 4.1.3 20070929 (prerelease) (Ubuntu 4.1.2-16ubuntu2)]**
Operating System: **Linux-3.4.6-x86_64-with-glibc2.4**
Locale: None
Branch: **master**
Commit: SickRage/SickRage@5d51b1687edf252958317c8cbb110069d7b207b3
Link to Log: https://gist.github.com/67f4317ab84b810b458b
### ERROR
```
SEARCHQUEUE-DAILY-SEARCH :: [KickAssTorrents] :: Failed parsing provider. Traceback: 'Traceback (most recent call last):\n  File "/share/CACHEDEV1_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/sickbeard/providers/kat.py", line 91, in search\n    data = self.get_url(search_url)\n  File "/share/CACHEDEV1_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/sickrage/providers/GenericProvider.py", line 353, in get_url\n    session=self.session, json=json, need_bytes=need_bytes)\n  File "/share/CACHEDEV1_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/sickbeard/helpers.py", line 1468, in getURL\n    if e.errno != errno.ECONNRESET:\nAttributeError: \'exceptions.AttributeError\' object has no attribute \'errno\'\n' [5d51b16]
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by SickRage2** [comment]
Thanks for the issue report! Before a real human comes by, please make sure your report has all the below criteria checked

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [x] Post debug logs, either inline (for smaller logs) or using gist)

Please make sure you also read [how to create an issue](https://github.com/SickRage/sickrage-issues/blob/master/README.md) and followed all of the steps. 

The title should describe your issue. Having "SR not working" or "I get this bug" for 100 issues, isn't really helpful. We will close issues if there isn't enough information.

Sometimes the devs may seem like grunts and respond with short answers. This isn't (always) because the dev hates you, but because he's on mobile or busy fixing bugs. If something isn't clear, please let us know, and this bot may get updated to automatically answer you.

Thanks!

**Comment by kriznik** [comment]
### INFO
Python Version: **2.7.9 (default, Mar 24 2015, 00:42:24) [GCC 4.1.3 20070929 (prerelease) (Ubuntu 4.1.2-16ubuntu2)]**
Operating System: **Linux-3.4.6-x86_64-with-glibc2.4**
Locale: None
Branch: **master**
Commit: SickRage/SickRage@5d51b1687edf252958317c8cbb110069d7b207b3
Link to Log: https://gist.github.com/6ef15cfffed887d7887e
### ERROR
```
SEARCHQUEUE-BACKLOG-262980 :: [KickAssTorrents] :: Failed parsing provider. Traceback: 'Traceback (most recent call last):\n  File "/share/CACHEDEV1_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/sickbeard/providers/kat.py", line 91, in search\n    data = self.get_url(search_url)\n  File "/share/CACHEDEV1_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/sickrage/providers/GenericProvider.py", line 353, in get_url\n    session=self.session, json=json, need_bytes=need_bytes)\n  File "/share/CACHEDEV1_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/sickbeard/helpers.py", line 1468, in getURL\n    if e.errno != errno.ECONNRESET:\nAttributeError: \'exceptions.AttributeError\' object has no attribute \'errno\'\n' [5d51b16]
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by kriznik** [comment]
### INFO
Python Version: **2.7.9 (default, Mar 24 2015, 00:42:24) [GCC 4.1.3 20070929 (prerelease) (Ubuntu 4.1.2-16ubuntu2)]**
Operating System: **Linux-3.4.6-x86_64-with-glibc2.4**
Locale: None
Branch: **master**
Commit: SickRage/SickRage@5d51b1687edf252958317c8cbb110069d7b207b3
Link to Log: https://gist.github.com/bf7ec51714f7e97c17fb
### ERROR
```
SEARCHQUEUE-BACKLOG-78107 :: [KickAssTorrents] :: Failed parsing provider. Traceback: 'Traceback (most recent call last):\n  File "/share/CACHEDEV1_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/sickbeard/providers/kat.py", line 91, in search\n    data = self.get_url(search_url)\n  File "/share/CACHEDEV1_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/sickrage/providers/GenericProvider.py", line 353, in get_url\n    session=self.session, json=json, need_bytes=need_bytes)\n  File "/share/CACHEDEV1_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/sickbeard/helpers.py", line 1468, in getURL\n    if e.errno != errno.ECONNRESET:\nAttributeError: \'exceptions.AttributeError\' object has no attribute \'errno\'\n' [5d51b16]
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by kriznik** [comment]
### INFO
Python Version: **2.7.9 (default, Mar 24 2015, 00:42:24) [GCC 4.1.3 20070929 (prerelease) (Ubuntu 4.1.2-16ubuntu2)]**
Operating System: **Linux-3.4.6-x86_64-with-glibc2.4**
Locale: None
Branch: **master**
Commit: SickRage/SickRage@5d51b1687edf252958317c8cbb110069d7b207b3
Link to Log: https://gist.github.com/5b4bb571f3755d09193e
### ERROR
```
SEARCHQUEUE-BACKLOG-74372 :: [KickAssTorrents] :: Failed parsing provider. Traceback: 'Traceback (most recent call last):\n  File "/share/CACHEDEV1_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/sickbeard/providers/kat.py", line 91, in search\n    data = self.get_url(search_url)\n  File "/share/CACHEDEV1_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/sickrage/providers/GenericProvider.py", line 353, in get_url\n    session=self.session, json=json, need_bytes=need_bytes)\n  File "/share/CACHEDEV1_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/sickbeard/helpers.py", line 1468, in getURL\n    if e.errno != errno.ECONNRESET:\nAttributeError: \'exceptions.AttributeError\' object has no attribute \'errno\'\n' [5d51b16]
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by kriznik** [comment]
### INFO
Python Version: **2.7.9 (default, Mar 24 2015, 00:42:24) [GCC 4.1.3 20070929 (prerelease) (Ubuntu 4.1.2-16ubuntu2)]**
Operating System: **Linux-3.4.6-x86_64-with-glibc2.4**
Locale: None
Branch: **master**
Commit: SickRage/SickRage@5d51b1687edf252958317c8cbb110069d7b207b3
Link to Log: https://gist.github.com/f05a08413e83038201ab
### ERROR
```
SEARCHQUEUE-BACKLOG-118421 :: [KickAssTorrents] :: Failed parsing provider. Traceback: 'Traceback (most recent call last):\n  File "/share/CACHEDEV1_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/sickbeard/providers/kat.py", line 91, in search\n    data = self.get_url(search_url)\n  File "/share/CACHEDEV1_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/sickrage/providers/GenericProvider.py", line 353, in get_url\n    session=self.session, json=json, need_bytes=need_bytes)\n  File "/share/CACHEDEV1_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/sickbeard/helpers.py", line 1468, in getURL\n    if e.errno != errno.ECONNRESET:\nAttributeError: \'exceptions.AttributeError\' object has no attribute \'errno\'\n' [5d51b16]
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by kriznik** [comment]
### INFO
Python Version: **2.7.9 (default, Mar 24 2015, 00:42:24) [GCC 4.1.3 20070929 (prerelease) (Ubuntu 4.1.2-16ubuntu2)]**
Operating System: **Linux-3.4.6-x86_64-with-glibc2.4**
Locale: None
Branch: **master**
Commit: SickRage/SickRage@5d51b1687edf252958317c8cbb110069d7b207b3
Link to Log: https://gist.github.com/6258e6897f6f627bfe21
### ERROR
```
SEARCHQUEUE-BACKLOG-262447 :: [KickAssTorrents] :: Failed parsing provider. Traceback: 'Traceback (most recent call last):\n  File "/share/CACHEDEV1_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/sickbeard/providers/kat.py", line 91, in search\n    data = self.get_url(search_url)\n  File "/share/CACHEDEV1_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/sickrage/providers/GenericProvider.py", line 353, in get_url\n    session=self.session, json=json, need_bytes=need_bytes)\n  File "/share/CACHEDEV1_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/sickbeard/helpers.py", line 1468, in getURL\n    if e.errno != errno.ECONNRESET:\nAttributeError: \'exceptions.AttributeError\' object has no attribute \'errno\'\n' [5d51b16]
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by kriznik** [comment]
### INFO
Python Version: **2.7.9 (default, Mar 24 2015, 00:42:24) [GCC 4.1.3 20070929 (prerelease) (Ubuntu 4.1.2-16ubuntu2)]**
Operating System: **Linux-3.4.6-x86_64-with-glibc2.4**
Locale: None
Branch: **master**
Commit: SickRage/SickRage@5d51b1687edf252958317c8cbb110069d7b207b3
Link to Log: https://gist.github.com/21fae89b0d70e2d0c1e1
### ERROR
```
SEARCHQUEUE-BACKLOG-79222 :: [KickAssTorrents] :: Failed parsing provider. Traceback: 'Traceback (most recent call last):\n  File "/share/CACHEDEV1_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/sickbeard/providers/kat.py", line 91, in search\n    data = self.get_url(search_url)\n  File "/share/CACHEDEV1_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/sickrage/providers/GenericProvider.py", line 353, in get_url\n    session=self.session, json=json, need_bytes=need_bytes)\n  File "/share/CACHEDEV1_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/sickbeard/helpers.py", line 1468, in getURL\n    if e.errno != errno.ECONNRESET:\nAttributeError: \'exceptions.AttributeError\' object has no attribute \'errno\'\n' [5d51b16]
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by kriznik** [comment]
### INFO
Python Version: **2.7.9 (default, Mar 24 2015, 00:42:24) [GCC 4.1.3 20070929 (prerelease) (Ubuntu 4.1.2-16ubuntu2)]**
Operating System: **Linux-3.4.6-x86_64-with-glibc2.4**
Locale: None
Branch: **master**
Commit: SickRage/SickRage@5d51b1687edf252958317c8cbb110069d7b207b3
Link to Log: https://gist.github.com/ed7ec69cf099b653bba5
### ERROR
```
SEARCHQUEUE-BACKLOG-269643 :: [KickAssTorrents] :: Failed parsing provider. Traceback: 'Traceback (most recent call last):\n  File "/share/CACHEDEV1_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/sickbeard/providers/kat.py", line 91, in search\n    data = self.get_url(search_url)\n  File "/share/CACHEDEV1_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/sickrage/providers/GenericProvider.py", line 353, in get_url\n    session=self.session, json=json, need_bytes=need_bytes)\n  File "/share/CACHEDEV1_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/sickbeard/helpers.py", line 1468, in getURL\n    if e.errno != errno.ECONNRESET:\nAttributeError: \'exceptions.AttributeError\' object has no attribute \'errno\'\n' [5d51b16]
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by kriznik** [comment]
### INFO
Python Version: **2.7.9 (default, Mar 24 2015, 00:42:24) [GCC 4.1.3 20070929 (prerelease) (Ubuntu 4.1.2-16ubuntu2)]**
Operating System: **Linux-3.4.6-x86_64-with-glibc2.4**
Locale: None
Branch: **master**
Commit: SickRage/SickRage@5d51b1687edf252958317c8cbb110069d7b207b3
Link to Log: https://gist.github.com/2695ad6674f03b456da6
### ERROR
```
SEARCHQUEUE-BACKLOG-84190 :: [KickAssTorrents] :: Failed parsing provider. Traceback: 'Traceback (most recent call last):\n  File "/share/CACHEDEV1_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/sickbeard/providers/kat.py", line 91, in search\n    data = self.get_url(search_url)\n  File "/share/CACHEDEV1_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/sickrage/providers/GenericProvider.py", line 353, in get_url\n    session=self.session, json=json, need_bytes=need_bytes)\n  File "/share/CACHEDEV1_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/sickbeard/helpers.py", line 1468, in getURL\n    if e.errno != errno.ECONNRESET:\nAttributeError: \'exceptions.AttributeError\' object has no attribute \'errno\'\n' [5d51b16]
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by kriznik** [comment]
### INFO
Python Version: **2.7.9 (default, Mar 24 2015, 00:42:24) [GCC 4.1.3 20070929 (prerelease) (Ubuntu 4.1.2-16ubuntu2)]**
Operating System: **Linux-3.4.6-x86_64-with-glibc2.4**
Locale: None
Branch: **master**
Commit: SickRage/SickRage@5d51b1687edf252958317c8cbb110069d7b207b3
Link to Log: https://gist.github.com/34b0736aa6b4f63dcf17
### ERROR
```
SEARCHQUEUE-BACKLOG-72227 :: [KickAssTorrents] :: Failed parsing provider. Traceback: 'Traceback (most recent call last):\n  File "/share/CACHEDEV1_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/sickbeard/providers/kat.py", line 91, in search\n    data = self.get_url(search_url)\n  File "/share/CACHEDEV1_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/sickrage/providers/GenericProvider.py", line 353, in get_url\n    session=self.session, json=json, need_bytes=need_bytes)\n  File "/share/CACHEDEV1_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/sickbeard/helpers.py", line 1468, in getURL\n    if e.errno != errno.ECONNRESET:\nAttributeError: \'exceptions.AttributeError\' object has no attribute \'errno\'\n' [5d51b16]
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by kriznik** [comment]
### INFO
Python Version: **2.7.9 (default, Mar 24 2015, 00:42:24) [GCC 4.1.3 20070929 (prerelease) (Ubuntu 4.1.2-16ubuntu2)]**
Operating System: **Linux-3.4.6-x86_64-with-glibc2.4**
Locale: None
Branch: **master**
Commit: SickRage/SickRage@5d51b1687edf252958317c8cbb110069d7b207b3
Link to Log: https://gist.github.com/045e59c0a660ca1fc8f7
### ERROR
```
SEARCHQUEUE-BACKLOG-81189 :: [KickAssTorrents] :: Failed parsing provider. Traceback: 'Traceback (most recent call last):\n  File "/share/CACHEDEV1_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/sickbeard/providers/kat.py", line 91, in search\n    data = self.get_url(search_url)\n  File "/share/CACHEDEV1_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/sickrage/providers/GenericProvider.py", line 353, in get_url\n    session=self.session, json=json, need_bytes=need_bytes)\n  File "/share/CACHEDEV1_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/sickbeard/helpers.py", line 1468, in getURL\n    if e.errno != errno.ECONNRESET:\nAttributeError: \'exceptions.AttributeError\' object has no attribute \'errno\'\n' [5d51b16]
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by kriznik** [comment]
### INFO
Python Version: **2.7.9 (default, Mar 24 2015, 00:42:24) [GCC 4.1.3 20070929 (prerelease) (Ubuntu 4.1.2-16ubuntu2)]**
Operating System: **Linux-3.4.6-x86_64-with-glibc2.4**
Locale: None
Branch: **master**
Commit: SickRage/SickRage@5d51b1687edf252958317c8cbb110069d7b207b3
Link to Log: https://gist.github.com/8485a6c6e937df18f9fd
### ERROR
```
SEARCHQUEUE-BACKLOG-79216 :: [KickAssTorrents] :: Failed parsing provider. Traceback: 'Traceback (most recent call last):\n  File "/share/CACHEDEV1_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/sickbeard/providers/kat.py", line 91, in search\n    data = self.get_url(search_url)\n  File "/share/CACHEDEV1_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/sickrage/providers/GenericProvider.py", line 353, in get_url\n    session=self.session, json=json, need_bytes=need_bytes)\n  File "/share/CACHEDEV1_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/sickbeard/helpers.py", line 1468, in getURL\n    if e.errno != errno.ECONNRESET:\nAttributeError: \'exceptions.AttributeError\' object has no attribute \'errno\'\n' [5d51b16]
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by neoatomic** [comment]
@kriznik Same as https://github.com/SickRage/sickrage-issues/issues/805

**Comment by samtheeagle** [comment]
### INFO
Python Version: **2.7.3 (default, Jun 22 2016, 03:14:32) [GCC 4.6.3]**
Operating System: **Linux-4.4.36-v7+-armv7l-with-debian-7.11**
Locale: None
Branch: **master**
Commit: SickRage/SickRage@3dd13c33887e3e09d706646f007d92678b0697c0
No Log available with ERRORS:
### ERROR
```
FINDPROPERS :: [Rarbg] :: Exception generated in thread FINDPROPERS :: [Rarbg]: 'exceptions.AttributeError' object has no attribute 'errno' [3dd13c3]
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators
