### ISSUE TITLE
AttributeError: 'SourceUpdateManager' object has no attribute 'list_remote_branches'

### ISSUE THREAD

**Issue by RackerJack** [SickRage/sickrage-issues#789]
Branch: 7.0.2 
centos 6.7 python2.7
What i did: tried to enter the settings
What happened: big ugly error
full log: http://pastebin.com/z1UN4brL
in browser error: http://pastebin.com/DdttEJTF
```
23:05:20 DEBUG::WEB::Failed doing webui callback [/config/general/]: Traceback (most recent call last):
  File "/srv/opt/sickrage-5051/sickrage/core/webserver/views.py", line 112, in async_call
    **{k: ''.join(v) if isinstance(v, list) else v for k, v in recursive_unicode(kwargs.items())}))
  File "/srv/opt/sickrage-5051/sickrage/core/webserver/views.py", line 3680, in index
    submenu=self.ConfigMenu())
  File "/srv/opt/sickrage-5051/sickrage/core/webserver/views.py", line 192, in render
    return self.render_string(template_name, **kwargs)
  File "/srv/opt/sickrage-5051/sickrage/core/webserver/views.py", line 186, in render_string
    return self.mako_lookup.get_template(template_name).render_unicode(**template_kwargs)
  File "/home/transmission/.local/lib/python2.7/site-packages/mako/template.py", line 454, in render_unicode
    as_unicode=True)
  File "/home/transmission/.local/lib/python2.7/site-packages/mako/runtime.py", line 829, in _render
    **_kwargs_for_callable(callable_, data))
  File "/home/transmission/.local/lib/python2.7/site-packages/mako/runtime.py", line 864, in _render_context
    _exec_template(inherit, lclcontext, args=args, kwargs=kwargs)
  File "/home/transmission/.local/lib/python2.7/site-packages/mako/runtime.py", line 890, in _exec_template
    callable_(context, *args, **kwargs)
  File "/srv/opt/sickrage-5051/cache/mako/layouts/main.mako.py", line 480, in render_body
    context['self'].content(**pageargs)
  File "/srv/opt/sickrage-5051/cache/mako/config_general.mako.py", line 330, in render_content
    gh_branch = sickrage.srCore.VERSIONUPDATER.list_remote_branches
  File "/srv/opt/sickrage-5051/sickrage/core/version_updater.py", line 267, in list_remote_branches
    return self.updater.list_remote_branches
AttributeError: 'SourceUpdateManager' object has no attribute 'list_remote_branches'
```

**Comment by SickRage2** [comment]
Thanks for the issue report! Before a real human comes by, please make sure your report has all the below criteria checked

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [x] Post debug logs, either inline (for smaller logs) or using gist)

Please make sure you also read [how to create an issue](https://github.com/SickRage/sickrage-issues/blob/master/README.md) and followed all of the steps. 

The title should describe your issue. Having "SR not working" or "I get this bug" for 100 issues, isn't really helpful. We will close issues if there isn't enough information.

Sometimes the devs may seem like grunts and respond with short answers. This isn't (always) because the dev hates you, but because he's on mobile or busy fixing bugs. If something isn't clear, please let us know, and this bot may get updated to automatically answer you.

Thanks!

**Comment by neoatomic** [comment]
@RackerJack You are still on the old repo. Thats why stuff isn't working...
