### ISSUE TITLE
[APP SUBMITTED]: (22, 'Invalid argument')

### ISSUE THREAD

**Issue by habskilla** [SickRage/sickrage-issues#790]
### INFO
Python Version: **2.7.11 (v2.7.11:6d1b6a68f775, Dec  5 2015, 20:40:30) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-8.1-6.3.9600**
Locale: cp1252
Branch: **master**
Commit: SickRage/SickRage@5d51b1687edf252958317c8cbb110069d7b207b3
No Log available with ERRORS:
### ERROR
```
Thread-39 :: Failed doing webui callback: Traceback (most recent call last):
  File "C:\SickRage2\sickbeard\webserve.py", line 285, in async_call
    result = function(**kwargs)
  File "C:\SickRage2\sickbeard\webserve.py", line 2281, in processEpisode
    is_priority=argToBool(is_priority), delete_on=argToBool(delete_on), failed=argToBool(failed), proc_type=type
  File "C:\SickRage2\sickbeard\processTV.py", line 265, in processDir
    process_media(processPath, videoFiles, nzbName, process_method, force, is_priority, result)
  File "C:\SickRage2\sickbeard\processTV.py", line 544, in process_media
    result.result = processor.process()
  File "C:\SickRage2\sickbeard\postProcessor.py", line 1172, in process
    cur_ep.airdateModifyStamp()
  File "C:\SickRage2\sickbeard\tv.py", line 2550, in airdateModifyStamp
    airdatetime = airdatetime.astimezone(network_timezones.sb_timezone)
  File "C:\SickRage2\lib\dateutil\tz.py", line 115, in utcoffset
    if self._isdst(dt):
  File "C:\SickRage2\lib\dateutil\tz.py", line 159, in _isdst
    return time.localtime(timestamp+time.timezone).tm_isdst
ValueError: (22, 'Invalid argument')
 [5d51b16]
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by SickRage2** [comment]
Thanks for the issue report! Before a real human comes by, please make sure your report has all the below criteria checked

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [ ] Post debug logs, either inline (for smaller logs) or using gist)

Please make sure you also read [how to create an issue](https://github.com/SickRage/sickrage-issues/blob/master/README.md) and followed all of the steps. 

The title should describe your issue. Having "SR not working" or "I get this bug" for 100 issues, isn't really helpful. We will close issues if there isn't enough information.

Sometimes the devs may seem like grunts and respond with short answers. This isn't (always) because the dev hates you, but because he's on mobile or busy fixing bugs. If something isn't clear, please let us know, and this bot may get updated to automatically answer you.

Thanks!

**Comment by neoatomic** [comment]
@habskilla Seems to be a time related issue.
Do you have the setting `Change File Date` enabled under the Post-processing section.?

**Comment by habskilla** [comment]
Yes.  I will uncheck that option.

**Comment by labrys** [comment]
@habskilla @neoatomic this is an upstream dateutil bug thats been reported. Although there is a workaround for it.

**Comment by neoatomic** [comment]
Ok, Than we will have to wait until they fix it there before we can solve it on Sickrage. :)
