### ISSUE TITLE
ImportError: No module named urllib3.contrib after fresh install on Synology using Sickbeard Custom

### ISSUE THREAD

**Issue by mpretz** [SickRage/sickrage-issues#794]
Went to update sickrage last night and update crashed and burned. Trying to reinstall fresh with no luck. No python packages were updated or changed.

MediaServer> /var/packages/sickbeard-custom/scripts/start-stop-status start
Starting SickBeard Custom ...
Traceback (most recent call last):
  File "/usr/local/sickbeard-custom/var/SickBeard/SickBeard.py", line 24, in <module>
    import sickrage
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickrage/__init__.py", line 31, in <module>
    from requirements import install_pip, install_requirements
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickrage/requirements/__init__.py", line 27, in <module>
    import urllib3.contrib
ImportError: No module named urllib3.contrib

**Comment by SickRage2** [comment]
Thanks for the issue report! Before a real human comes by, please make sure your report has all the below criteria checked

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [ ] Post debug logs, either inline (for smaller logs) or using gist)

Please make sure you also read [how to create an issue](https://github.com/SickRage/sickrage-issues/blob/master/README.md) and followed all of the steps. 

The title should describe your issue. Having "SR not working" or "I get this bug" for 100 issues, isn't really helpful. We will close issues if there isn't enough information.

Sometimes the devs may seem like grunts and respond with short answers. This isn't (always) because the dev hates you, but because he's on mobile or busy fixing bugs. If something isn't clear, please let us know, and this bot may get updated to automatically answer you.

Thanks!

**Comment by neoatomic** [comment]
@mpretz You are still on the old repo, that's why stuff isn't working... : 
`from requirements import install_pip, install_requirements`

Reinstall with this git URL, and you will be up and running again. : 
`git://github.com/SickRage/SickRage.git`
