### ISSUE TITLE
[APP SUBMITTED]: 'data-filesize'

### ISSUE THREAD

**Issue by FWoelffel** [SickRage/sickrage-issues#795]
### INFO
Python Version: **2.7.9 (default, Sep  9 2015, 14:50:03) [GCC 4.2.1 20070831 patched [FreeBSD]]**
Operating System: **FreeBSD-9.1-RELEASE-amd64-64bit-ELF**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@3288b895982fa1e296f41a15e0d548504dd7de39
No Log available with ERRORS:
### ERROR
```
SEARCHQUEUE-DAILY-SEARCH :: [TransmitTheNet] :: Failed parsing provider. Traceback: Traceback (most recent call last):
  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/sickbeard/providers/transmitthenet.py", line 168, in search
    torrent_size = temp_anchor['data-filesize']
  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/lib/bs4/element.py", line 958, in __getitem__
    return self.attrs[key]
KeyError: 'data-filesize'
 [3288b89]
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by SickRage2** [comment]
Thanks for the issue report! Before a real human comes by, please make sure your report has all the below criteria checked

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [ ] Post debug logs, either inline (for smaller logs) or using gist)

Please make sure you also read [how to create an issue](https://github.com/SickRage/sickrage-issues/blob/master/README.md) and followed all of the steps. 

The title should describe your issue. Having "SR not working" or "I get this bug" for 100 issues, isn't really helpful. We will close issues if there isn't enough information.

Sometimes the devs may seem like grunts and respond with short answers. This isn't (always) because the dev hates you, but because he's on mobile or busy fixing bugs. If something isn't clear, please let us know, and this bot may get updated to automatically answer you.

Thanks!

**Comment by duramato** [comment]
### INFO
Python Version: **2.7.6 (default, Jun 22 2015, 18:00:18) [GCC 4.8.2]**
Operating System: **Linux-3.19.0-49-generic-i686-with-Ubuntu-14.04-trusty**
Locale: UTF-8
Branch: **develop**
Commit: SickRage/SickRage@4e5af57d85fe84ab497823e171336fa89887a66b
No Log available with ERRORS:
### ERROR
```
SEARCHQUEUE-DAILY-SEARCH :: [TransmitTheNet] :: Failed parsing provider. Traceback: Traceback (most recent call last):
  File "/home/home/SickRage/sickbeard/providers/transmitthenet.py", line 168, in search
    torrent_size = temp_anchor['data-filesize']
  File "/home/home/SickRage/lib/bs4/element.py", line 958, in __getitem__
    return self.attrs[key]
KeyError: 'data-filesize'
 [4e5af57]
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by miigotu** [comment]
they moved it, will need to rewrite this provider later

**Comment by duramato** [comment]
### INFO
Python Version: **2.7.6 (default, Jun 22 2015, 18:00:18) [GCC 4.8.2]**
Operating System: **Linux-3.19.0-49-generic-i686-with-Ubuntu-14.04-trusty**
Locale: UTF-8
Branch: **develop**
Commit: SickRage/SickRage@93181f873fbb85019533d65a860496f284d0abbc
No Log available with ERRORS:
### ERROR
```
SEARCHQUEUE-DAILY-SEARCH :: [TransmitTheNet] :: Failed parsing provider. Traceback: Traceback (most recent call last):
  File "/home/home/SickRage/sickbeard/providers/transmitthenet.py", line 168, in search
    torrent_size = temp_anchor['data-filesize']
  File "/home/home/SickRage/lib/bs4/element.py", line 958, in __getitem__
    return self.attrs[key]
KeyError: 'data-filesize'
 [93181f8]
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by porkchop34** [comment]
### INFO
Python Version: **2.7.11 (v2.7.11:6d1b6a68f775, Dec  5 2015, 20:40:30) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-7-6.1.7601-SP1**
Locale: cp1252
Branch: **master**
Commit: SickRage/SickRage@7a94dd094c2861d54f500c39af5fb2cdb856dfdc
No Log available with ERRORS:
### ERROR
```
SEARCHQUEUE-MANUAL-268592 :: [TransmitTheNet] :: Failed parsing provider. Traceback: Traceback (most recent call last):
  File "C:\SickRage\sickbeard\providers\transmitthenet.py", line 169, in search
    torrent_size = temp_anchor['data-filesize']
  File "C:\SickRage\lib\bs4\element.py", line 958, in __getitem__
    return self.attrs[key]
KeyError: 'data-filesize'
 [7a94dd0]
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by porkchop34** [comment]
### INFO
Python Version: **2.7.11 (v2.7.11:6d1b6a68f775, Dec  5 2015, 20:40:30) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-7-6.1.7601-SP1**
Locale: cp1252
Branch: **master**
Commit: SickRage/SickRage@7a94dd094c2861d54f500c39af5fb2cdb856dfdc
No Log available with ERRORS:
### ERROR
```
SEARCHQUEUE-MANUAL-269586 :: [TransmitTheNet] :: Failed parsing provider. Traceback: Traceback (most recent call last):
  File "C:\SickRage\sickbeard\providers\transmitthenet.py", line 169, in search
    torrent_size = temp_anchor['data-filesize']
  File "C:\SickRage\lib\bs4\element.py", line 958, in __getitem__
    return self.attrs[key]
KeyError: 'data-filesize'
 [7a94dd0]
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by porkchop34** [comment]
### INFO
Python Version: **2.7.11 (v2.7.11:6d1b6a68f775, Dec  5 2015, 20:40:30) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-7-6.1.7601-SP1**
Locale: cp1252
Branch: **master**
Commit: SickRage/SickRage@7a94dd094c2861d54f500c39af5fb2cdb856dfdc
No Log available with ERRORS:
### ERROR
```
SEARCHQUEUE-BACKLOG-208111 :: [TransmitTheNet] :: Failed parsing provider. Traceback: Traceback (most recent call last):
  File "C:\SickRage\sickbeard\providers\transmitthenet.py", line 169, in search
    torrent_size = temp_anchor['data-filesize']
  File "C:\SickRage\lib\bs4\element.py", line 958, in __getitem__
    return self.attrs[key]
KeyError: 'data-filesize'
 [7a94dd0]
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by porkchop34** [comment]
### INFO
Python Version: **2.7.11 (v2.7.11:6d1b6a68f775, Dec  5 2015, 20:40:30) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-7-6.1.7601-SP1**
Locale: cp1252
Branch: **master**
Commit: SickRage/SickRage@7a94dd094c2861d54f500c39af5fb2cdb856dfdc
No Log available with ERRORS:
### ERROR
```
SEARCHQUEUE-BACKLOG-220411 :: [TransmitTheNet] :: Failed parsing provider. Traceback: Traceback (most recent call last):
  File "C:\SickRage\sickbeard\providers\transmitthenet.py", line 169, in search
    torrent_size = temp_anchor['data-filesize']
  File "C:\SickRage\lib\bs4\element.py", line 958, in __getitem__
    return self.attrs[key]
KeyError: 'data-filesize'
 [7a94dd0]
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by porkchop34** [comment]
### INFO
Python Version: **2.7.11 (v2.7.11:6d1b6a68f775, Dec  5 2015, 20:40:30) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-7-6.1.7601-SP1**
Locale: cp1252
Branch: **master**
Commit: SickRage/SickRage@7a94dd094c2861d54f500c39af5fb2cdb856dfdc
No Log available with ERRORS:
### ERROR
```
SEARCHQUEUE-BACKLOG-278339 :: [TransmitTheNet] :: Failed parsing provider. Traceback: Traceback (most recent call last):
  File "C:\SickRage\sickbeard\providers\transmitthenet.py", line 169, in search
    torrent_size = temp_anchor['data-filesize']
  File "C:\SickRage\lib\bs4\element.py", line 958, in __getitem__
    return self.attrs[key]
KeyError: 'data-filesize'
 [7a94dd0]
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by porkchop34** [comment]
### INFO
Python Version: **2.7.11 (v2.7.11:6d1b6a68f775, Dec  5 2015, 20:40:30) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-7-6.1.7601-SP1**
Locale: cp1252
Branch: **master**
Commit: SickRage/SickRage@7a94dd094c2861d54f500c39af5fb2cdb856dfdc
No Log available with ERRORS:
### ERROR
```
SEARCHQUEUE-BACKLOG-77811 :: [TransmitTheNet] :: Failed parsing provider. Traceback: Traceback (most recent call last):
  File "C:\SickRage\sickbeard\providers\transmitthenet.py", line 169, in search
    torrent_size = temp_anchor['data-filesize']
  File "C:\SickRage\lib\bs4\element.py", line 958, in __getitem__
    return self.attrs[key]
KeyError: 'data-filesize'
 [7a94dd0]
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by porkchop34** [comment]
### INFO
Python Version: **2.7.11 (v2.7.11:6d1b6a68f775, Dec  5 2015, 20:40:30) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-7-6.1.7601-SP1**
Locale: cp1252
Branch: **master**
Commit: SickRage/SickRage@7a94dd094c2861d54f500c39af5fb2cdb856dfdc
No Log available with ERRORS:
### ERROR
```
SEARCHQUEUE-BACKLOG-123581 :: [TransmitTheNet] :: Failed parsing provider. Traceback: Traceback (most recent call last):
  File "C:\SickRage\sickbeard\providers\transmitthenet.py", line 169, in search
    torrent_size = temp_anchor['data-filesize']
  File "C:\SickRage\lib\bs4\element.py", line 958, in __getitem__
    return self.attrs[key]
KeyError: 'data-filesize'
 [7a94dd0]
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by porkchop34** [comment]
### INFO
Python Version: **2.7.11 (v2.7.11:6d1b6a68f775, Dec  5 2015, 20:40:30) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-7-6.1.7601-SP1**
Locale: cp1252
Branch: **master**
Commit: SickRage/SickRage@7a94dd094c2861d54f500c39af5fb2cdb856dfdc
No Log available with ERRORS:
### ERROR
```
SEARCHQUEUE-BACKLOG-80270 :: [TransmitTheNet] :: Failed parsing provider. Traceback: Traceback (most recent call last):
  File "C:\SickRage\sickbeard\providers\transmitthenet.py", line 169, in search
    torrent_size = temp_anchor['data-filesize']
  File "C:\SickRage\lib\bs4\element.py", line 958, in __getitem__
    return self.attrs[key]
KeyError: 'data-filesize'
 [7a94dd0]
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by porkchop34** [comment]
### INFO
Python Version: **2.7.11 (v2.7.11:6d1b6a68f775, Dec  5 2015, 20:40:30) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-7-6.1.7601-SP1**
Locale: cp1252
Branch: **master**
Commit: SickRage/SickRage@7a94dd094c2861d54f500c39af5fb2cdb856dfdc
No Log available with ERRORS:
### ERROR
```
SEARCHQUEUE-BACKLOG-269586 :: [TransmitTheNet] :: Failed parsing provider. Traceback: Traceback (most recent call last):
  File "C:\SickRage\sickbeard\providers\transmitthenet.py", line 169, in search
    torrent_size = temp_anchor['data-filesize']
  File "C:\SickRage\lib\bs4\element.py", line 958, in __getitem__
    return self.attrs[key]
KeyError: 'data-filesize'
 [7a94dd0]
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by porkchop34** [comment]
### INFO
Python Version: **2.7.11 (v2.7.11:6d1b6a68f775, Dec  5 2015, 20:40:30) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-7-6.1.7601-SP1**
Locale: cp1252
Branch: **master**
Commit: SickRage/SickRage@7a94dd094c2861d54f500c39af5fb2cdb856dfdc
No Log available with ERRORS:
### ERROR
```
SEARCHQUEUE-BACKLOG-81189 :: [TransmitTheNet] :: Failed parsing provider. Traceback: Traceback (most recent call last):
  File "C:\SickRage\sickbeard\providers\transmitthenet.py", line 169, in search
    torrent_size = temp_anchor['data-filesize']
  File "C:\SickRage\lib\bs4\element.py", line 958, in __getitem__
    return self.attrs[key]
KeyError: 'data-filesize'
 [7a94dd0]
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by porkchop34** [comment]
### INFO
Python Version: **2.7.11 (v2.7.11:6d1b6a68f775, Dec  5 2015, 20:40:30) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-7-6.1.7601-SP1**
Locale: cp1252
Branch: **master**
Commit: SickRage/SickRage@7a94dd094c2861d54f500c39af5fb2cdb856dfdc
No Log available with ERRORS:
### ERROR
```
SEARCHQUEUE-BACKLOG-249361 :: [TransmitTheNet] :: Failed parsing provider. Traceback: Traceback (most recent call last):
  File "C:\SickRage\sickbeard\providers\transmitthenet.py", line 169, in search
    torrent_size = temp_anchor['data-filesize']
  File "C:\SickRage\lib\bs4\element.py", line 958, in __getitem__
    return self.attrs[key]
KeyError: 'data-filesize'
 [7a94dd0]
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by porkchop34** [comment]
### INFO
Python Version: **2.7.11 (v2.7.11:6d1b6a68f775, Dec  5 2015, 20:40:30) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-7-6.1.7601-SP1**
Locale: cp1252
Branch: **master**
Commit: SickRage/SickRage@7a94dd094c2861d54f500c39af5fb2cdb856dfdc
No Log available with ERRORS:
### ERROR
```
SEARCHQUEUE-BACKLOG-84947 :: [TransmitTheNet] :: Failed parsing provider. Traceback: Traceback (most recent call last):
  File "C:\SickRage\sickbeard\providers\transmitthenet.py", line 169, in search
    torrent_size = temp_anchor['data-filesize']
  File "C:\SickRage\lib\bs4\element.py", line 958, in __getitem__
    return self.attrs[key]
KeyError: 'data-filesize'
 [7a94dd0]
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by porkchop34** [comment]
### INFO
Python Version: **2.7.11 (v2.7.11:6d1b6a68f775, Dec  5 2015, 20:40:30) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-7-6.1.7601-SP1**
Locale: cp1252
Branch: **master**
Commit: SickRage/SickRage@7a94dd094c2861d54f500c39af5fb2cdb856dfdc
No Log available with ERRORS:
### ERROR
```
SEARCHQUEUE-BACKLOG-80379 :: [TransmitTheNet] :: Failed parsing provider. Traceback: Traceback (most recent call last):
  File "C:\SickRage\sickbeard\providers\transmitthenet.py", line 169, in search
    torrent_size = temp_anchor['data-filesize']
  File "C:\SickRage\lib\bs4\element.py", line 958, in __getitem__
    return self.attrs[key]
KeyError: 'data-filesize'
 [7a94dd0]
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by porkchop34** [comment]
### INFO
Python Version: **2.7.11 (v2.7.11:6d1b6a68f775, Dec  5 2015, 20:40:30) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-7-6.1.7601-SP1**
Locale: cp1252
Branch: **master**
Commit: SickRage/SickRage@7a94dd094c2861d54f500c39af5fb2cdb856dfdc
No Log available with ERRORS:
### ERROR
```
SEARCHQUEUE-BACKLOG-254203 :: [TransmitTheNet] :: Failed parsing provider. Traceback: Traceback (most recent call last):
  File "C:\SickRage\sickbeard\providers\transmitthenet.py", line 169, in search
    torrent_size = temp_anchor['data-filesize']
  File "C:\SickRage\lib\bs4\element.py", line 958, in __getitem__
    return self.attrs[key]
KeyError: 'data-filesize'
 [7a94dd0]
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by porkchop34** [comment]
### INFO
Python Version: **2.7.11 (v2.7.11:6d1b6a68f775, Dec  5 2015, 20:40:30) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-7-6.1.7601-SP1**
Locale: cp1252
Branch: **master**
Commit: SickRage/SickRage@7a94dd094c2861d54f500c39af5fb2cdb856dfdc
No Log available with ERRORS:
### ERROR
```
SEARCHQUEUE-BACKLOG-274603 :: [TransmitTheNet] :: Failed parsing provider. Traceback: Traceback (most recent call last):
  File "C:\SickRage\sickbeard\providers\transmitthenet.py", line 169, in search
    torrent_size = temp_anchor['data-filesize']
  File "C:\SickRage\lib\bs4\element.py", line 958, in __getitem__
    return self.attrs[key]
KeyError: 'data-filesize'
 [7a94dd0]
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by porkchop34** [comment]
### INFO
Python Version: **2.7.11 (v2.7.11:6d1b6a68f775, Dec  5 2015, 20:40:30) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-7-6.1.7601-SP1**
Locale: cp1252
Branch: **master**
Commit: SickRage/SickRage@7a94dd094c2861d54f500c39af5fb2cdb856dfdc
No Log available with ERRORS:
### ERROR
```
SEARCHQUEUE-DAILY-SEARCH :: [TransmitTheNet] :: Failed parsing provider. Traceback: Traceback (most recent call last):
  File "C:\SickRage\sickbeard\providers\transmitthenet.py", line 169, in search
    torrent_size = temp_anchor['data-filesize']
  File "C:\SickRage\lib\bs4\element.py", line 958, in __getitem__
    return self.attrs[key]
KeyError: 'data-filesize'
 [7a94dd0]
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by porkchop34** [comment]
### INFO
Python Version: **2.7.11 (v2.7.11:6d1b6a68f775, Dec  5 2015, 20:40:30) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-7-6.1.7601-SP1**
Locale: cp1252
Branch: **master**
Commit: SickRage/SickRage@7a94dd094c2861d54f500c39af5fb2cdb856dfdc
No Log available with ERRORS:
### ERROR
```
SEARCHQUEUE-MANUAL-295743 :: [TransmitTheNet] :: Failed parsing provider. Traceback: Traceback (most recent call last):
  File "C:\SickRage\sickbeard\providers\transmitthenet.py", line 169, in search
    torrent_size = temp_anchor['data-filesize']
  File "C:\SickRage\lib\bs4\element.py", line 958, in __getitem__
    return self.attrs[key]
KeyError: 'data-filesize'
 [7a94dd0]
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by porkchop34** [comment]
### INFO
Python Version: **2.7.11 (v2.7.11:6d1b6a68f775, Dec  5 2015, 20:40:30) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-7-6.1.7601-SP1**
Locale: cp1252
Branch: **master**
Commit: SickRage/SickRage@7a94dd094c2861d54f500c39af5fb2cdb856dfdc
No Log available with ERRORS:
### ERROR
```
SEARCHQUEUE-MANUAL-77398 :: [TransmitTheNet] :: Failed parsing provider. Traceback: Traceback (most recent call last):
  File "C:\SickRage\sickbeard\providers\transmitthenet.py", line 169, in search
    torrent_size = temp_anchor['data-filesize']
  File "C:\SickRage\lib\bs4\element.py", line 958, in __getitem__
    return self.attrs[key]
KeyError: 'data-filesize'
 [7a94dd0]
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by porkchop34** [comment]
### INFO
Python Version: **2.7.11 (v2.7.11:6d1b6a68f775, Dec  5 2015, 20:40:30) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-7-6.1.7601-SP1**
Locale: cp1252
Branch: **master**
Commit: SickRage/SickRage@7a94dd094c2861d54f500c39af5fb2cdb856dfdc
No Log available with ERRORS:
### ERROR
```
SEARCHQUEUE-BACKLOG-208111 :: [TransmitTheNet] :: Failed parsing provider. Traceback: Traceback (most recent call last):
  File "C:\SickRage\sickbeard\providers\transmitthenet.py", line 169, in search
    torrent_size = temp_anchor['data-filesize']
  File "C:\SickRage\lib\bs4\element.py", line 958, in __getitem__
    return self.attrs[key]
KeyError: 'data-filesize'
 [7a94dd0]
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by porkchop34** [comment]
Sorry for the spam and apologies as I am a new user.

The item is marked as fixed however I have no update prompt within SickRage and the issue is still there.

**Comment by duramato** [comment]
@porkchop34 its fixed on dev you will have to wait for it to be merged to master

**Comment by porkchop34** [comment]
Ok cool thanks for the reply. Final question is there any timeline on when that will happen?
