### ISSUE TITLE
POSTPROCESSER :: Exception generated in thread POSTPROCESSER: Old quality does not match new: 1080p BluRay != 1080p HDTV 

### ISSUE THREAD

**Issue by Fumler** [SickRage/sickrage-issues#803]
Updated to latest sickrage commit today (was 300 commits behind), and now my postprocesser dies after running.

Error is: 2016-02-08 18:28:12 POSTPROCESSER :: Exception generated in thread POSTPROCESSER: Old quality does not match new: 1080p BluRay != 1080p HDTV : [UTW]_Fate_stay_night_Unlimited_Blade_Works_-_09_[BD][h264-1080p][FLAC][B20AAB33] [cdf22bf]

That show was downloaded months ago and it is whining about it now.

**Comment by SickRage2** [comment]
Thanks for the issue report! Before a real human comes by, please make sure your report has all the below criteria checked

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [ ] Post debug logs, either inline (for smaller logs) or using gist)

Please make sure you also read [how to create an issue](https://github.com/SickRage/sickrage-issues/blob/master/README.md) and followed all of the steps. 

The title should describe your issue. Having "SR not working" or "I get this bug" for 100 issues, isn't really helpful. We will close issues if there isn't enough information.

Sometimes the devs may seem like grunts and respond with short answers. This isn't (always) because the dev hates you, but because he's on mobile or busy fixing bugs. If something isn't clear, please let us know, and this bot may get updated to automatically answer you.

Thanks!

**Comment by neoatomic** [comment]
@Fumler Cant imagine that PP dies from just that error...

Could you post a full log and the version information etc. form the help & info page.?

Meanwhile what you can try to shutdown SR and remove the cache.db and restart.

**Comment by labrys** [comment]
@Fumler This is a validation method in place for some upcoming quality changes.  Once some final tweaks are made the validation method will be removed.  It should not, however, be killing the PP.  After following @neoatomic's suggestion let us know if it still kills the thread, if so then we can fast-track these tweaks.

**Comment by Fumler** [comment]
@labrys updated sickrage just now, pp still dies.

```
2016-02-09 20:58:46 DEBUG    POSTPROCESSER :: 'Traceback (most recent call last):\n  File "/home/fredrik/.sickrage/sickbeard/scheduler.py", line 106, in run\n    self.action.run(self.force)\n  File "/home/fredrik/.sickrage/sickbeard/auto_postprocessor.py", line 56, in run\n    processTV.processDir(sickbeard.TV_DOWNLOAD_DIR, force=force)\n  File "/home/fredrik/.sickrage/sickbeard/processTV.py", line 237, in processDir\n    for curDir in [x for x in dirs if validateDir(path, x, nzbNameOriginal, failed, result)]:\n  File "/home/fredrik/.sickrage/sickbeard/processTV.py", line 379, in validateDir\n    NameParser().parse(video, cache_result=False)\n  File "/home/fredrik/.sickrage/sickbeard/name_parser/parser.py", line 423, in parse\n    file_name_result = self._parse_string(base_file_name)\n  File "/home/fredrik/.sickrage/sickbeard/name_parser/parser.py", line 212, in _parse_string\n    bestResult.quality = common.Quality.nameQuality(name, bestResult.show.is_anime)\n  File "/home/fredrik/.sickrage/sickbeard/common.py", line 279, in nameQuality\n    quality = Quality.sceneQuality(name, anime)\n  File "/home/fredrik/.sickrage/sickbeard/common.py", line 455, in sceneQuality\n    assert old == result, \'Old quality does not match new: %s != %s : %s\' % (Quality.qualityStrings[old], Quality.qualityStrings[result], name)\nAssertionError: Old quality does not match new: 1080p BluRay != 1080p HDTV : [UTW]_Fate_stay_night_Unlimited_Blade_Works_-_09_[BD][h264-1080p][FLAC][B20AAB33]\n'
AAAssertionError: Old quality does not match new: 1080p BluRay != 1080p HDTV : [UTW]_Fate_stay_night_Unlimited_Blade_Works_-_09_[BD][h264-1080p][FLAC][B20AAB33]
AA    assert old == result, 'Old quality does not match new: %s != %s : %s' % (Quality.qualityStrings[old], Quality.qualityStrings[result], name)
AA  File "/home/fredrik/.sickrage/sickbeard/common.py", line 455, in sceneQuality
AA    quality = Quality.sceneQuality(name, anime)
AA  File "/home/fredrik/.sickrage/sickbeard/common.py", line 279, in nameQuality
AA    bestResult.quality = common.Quality.nameQuality(name, bestResult.show.is_anime)
AA  File "/home/fredrik/.sickrage/sickbeard/name_parser/parser.py", line 212, in _parse_string
AA    file_name_result = self._parse_string(base_file_name)
AA  File "/home/fredrik/.sickrage/sickbeard/name_parser/parser.py", line 423, in parse
AA    NameParser().parse(video, cache_result=False)
AA  File "/home/fredrik/.sickrage/sickbeard/processTV.py", line 379, in validateDir
AA    for curDir in [x for x in dirs if validateDir(path, x, nzbNameOriginal, failed, result)]:
AA  File "/home/fredrik/.sickrage/sickbeard/processTV.py", line 237, in processDir
AA    processTV.processDir(sickbeard.TV_DOWNLOAD_DIR, force=force)
AA  File "/home/fredrik/.sickrage/sickbeard/auto_postprocessor.py", line 56, in run
AA    self.action.run(self.force)
AA  File "/home/fredrik/.sickrage/sickbeard/scheduler.py", line 106, in run
AATraceback (most recent call last):

2016-02-09 20:58:46 ERROR    POSTPROCESSER :: Exception generated in thread POSTPROCESSER: Old quality does not match new: 1080p BluRay != 1080p HDTV : [UTW]_Fate_stay_night_Unlimited_Blade_Works_-_09_[BD][h264-1080p][FLAC][B20AAB33] [7a94dd0]

2016-02-09 20:58:46 DEBUG    POSTPROCESSER :: Processing folder Fate.Stay.Night.Unlimited.Blade.Works.S01.1080p.BluRay.FLAC2.0.x264-Hi10P-UTW
```

Deleted cache.db and restarted, same error (note this file has already been moved to correct folders etc ages ago by sickrage).

```
SickRage Info:	Branch: master
Commit: 7a94dd094c2861d54f500c39af5fb2cdb856dfdc
Version: 2016.02.09-2
 Python Version:	2.7.6 (default, Jun 22 2015, 17:58:13) [GCC 4.8.2]
 SSL Version:	OpenSSL 1.0.1f 6 Jan 2014
 OS:	Linux-3.13.0-44-generic-x86_64-with-Ubuntu-14.04-trusty
 Locale:	None.None
```

**Comment by labrys** [comment]
@Fumler Those tweaks aren't in yet, but thanks for the feedback I'll fast-track those tweaks and get them out soon.
