### ISSUE TITLE
[APP SUBMITTED]: [Error 2] The system cannot find the file specified: u"C:\\uTorrent\\Finished Downloading\\It's Always Sunny in Philadelphia\\Season 4\\It's Always Sunny in Philadelphia S04 E10.avi"

### ISSUE THREAD

**Issue by raygunxd** [SickRage/sickrage-issues#807]
### INFO
Python Version: **2.7.10 (default, May 23 2015, 09:44:00) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-2012Server-6.2.9200**
Locale: cp1252
Branch: **master**
Commit: SickRage/SickRage@cdf22bfe1cf70b90c32932a6b9326b6d3b8f7e63
No Log available with ERRORS:
### ERROR
```
Thread-22 :: Failed doing webui callback: Traceback (most recent call last):
  File "C:\SickRage\sickbeard\webserve.py", line 283, in async_call
    result = function(**kwargs)
  File "C:\SickRage\sickbeard\webserve.py", line 2279, in processEpisode
    is_priority=argToBool(is_priority), delete_on=argToBool(delete_on), failed=argToBool(failed), proc_type=type
  File "C:\SickRage\sickbeard\processTV.py", line 265, in processDir
    process_media(processPath, videoFiles, nzbName, process_method, force, is_priority, result)
  File "C:\SickRage\sickbeard\processTV.py", line 544, in process_media
    result.result = processor.process()
  File "C:\SickRage\sickbeard\postProcessor.py", line 974, in process
    existing_file_status = self._checkForExistingFile(ep_obj.location)
  File "C:\SickRage\sickbeard\postProcessor.py", line 135, in _checkForExistingFile
    if ek(os.path.getsize, existing_file) > ek(os.path.getsize, self.file_path):
  File "C:\SickRage\sickrage\helper\encoding.py", line 38, in ek
    result = function(*args, **kwargs)
  File "C:\Python27\lib\genericpath.py", line 57, in getsize
    return os.stat(filename).st_size
WindowsError: [Error 2] The system cannot find the file specified: u"C:\\uTorrent\\Finished Downloading\\It's Always Sunny in Philadelphia\\Season 4\\It's Always Sunny in Philadelphia S04 E10.avi"
 [cdf22bf]
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by SickRage2** [comment]
Thanks for the issue report! Before a real human comes by, please make sure your report has all the below criteria checked

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [ ] Post debug logs, either inline (for smaller logs) or using gist)

Please make sure you also read [how to create an issue](https://github.com/SickRage/sickrage-issues/blob/master/README.md) and followed all of the steps. 

The title should describe your issue. Having "SR not working" or "I get this bug" for 100 issues, isn't really helpful. We will close issues if there isn't enough information.

Sometimes the devs may seem like grunts and respond with short answers. This isn't (always) because the dev hates you, but because he's on mobile or busy fixing bugs. If something isn't clear, please let us know, and this bot may get updated to automatically answer you.

Thanks!

**Comment by miigotu** [comment]
You need to increase the time between post processor runs. These sort of errors when you run 2 instances of the post processor at the same time.

**Comment by NicholasMatthew** [comment]
I had a similar problem, and in that time the only solution i found was using long path tool. It really works.
