### ISSUE TITLE
[APP SUBMITTED]: Old quality does not match new: 720p BluRay != 720p HDTV : [mudabone] Chu-Bra!! - 06 [BD 720p H264-AAC][EB50EA76]

### ISSUE THREAD

**Issue by ShadoDragon** [SickRage/sickrage-issues#808]
### INFO
Python Version: **2.7.6 (default, Jun 22 2015, 17:58:13) [GCC 4.8.2]**
Operating System: **Linux-3.13.0-76-generic-x86_64-with-Ubuntu-14.04-trusty**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@cdf22bfe1cf70b90c32932a6b9326b6d3b8f7e63
No Log available with ERRORS:
### ERROR
```
Thread-53 :: Failed doing webui callback: Traceback (most recent call last):
  File "/opt/sickrage/sickbeard/webserve.py", line 283, in async_call
    result = function(**kwargs)
  File "/opt/sickrage/sickbeard/webserve.py", line 2279, in processEpisode
    is_priority=argToBool(is_priority), delete_on=argToBool(delete_on), failed=argToBool(failed), proc_type=type
  File "/opt/sickrage/sickbeard/processTV.py", line 222, in processDir
    process_media(path, [video], nzbName, process_method, force, is_priority, result)
  File "/opt/sickrage/sickbeard/processTV.py", line 544, in process_media
    result.result = processor.process()
  File "/opt/sickrage/sickbeard/postProcessor.py", line 939, in process
    (show, season, episodes, quality, version) = self._find_info()
  File "/opt/sickrage/sickbeard/postProcessor.py", line 662, in _find_info
    (cur_show, cur_season, cur_episodes, cur_quality, cur_version) = cur_attempt()
  File "/opt/sickrage/sickbeard/postProcessor.py", line 646, in <lambda>
    lambda: self._analyze_name(self.file_name),
  File "/opt/sickrage/sickbeard/postProcessor.py", line 580, in _analyze_name
    parse_result = np.parse(name)
  File "/opt/sickrage/sickbeard/name_parser/parser.py", line 421, in parse
    file_name_result = self._parse_string(base_file_name)
  File "/opt/sickrage/sickbeard/name_parser/parser.py", line 211, in _parse_string
    bestResult.quality = common.Quality.nameQuality(name, bestResult.show.is_anime)
  File "/opt/sickrage/sickbeard/common.py", line 279, in nameQuality
    quality = Quality.sceneQuality(name, anime)
  File "/opt/sickrage/sickbeard/common.py", line 455, in sceneQuality
    assert old == result, 'Old quality does not match new: %s != %s : %s' % (Quality.qualityStrings[old], Quality.qualityStrings[result], name)
AssertionError: Old quality does not match new: 720p BluRay != 720p HDTV : [mudabone] Chu-Bra!! - 06 [BD 720p H264-AAC][EB50EA76]
 [cdf22bf]
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by SickRage2** [comment]
Thanks for the issue report! Before a real human comes by, please make sure your report has all the below criteria checked

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [ ] Post debug logs, either inline (for smaller logs) or using gist)

Please make sure you also read [how to create an issue](https://github.com/SickRage/sickrage-issues/blob/master/README.md) and followed all of the steps. 

The title should describe your issue. Having "SR not working" or "I get this bug" for 100 issues, isn't really helpful. We will close issues if there isn't enough information.

Sometimes the devs may seem like grunts and respond with short answers. This isn't (always) because the dev hates you, but because he's on mobile or busy fixing bugs. If something isn't clear, please let us know, and this bot may get updated to automatically answer you.

Thanks!

**Comment by labrys** [comment]
This is a validation method for some new quality settings.  It will be removed shortly when some tweaks are finalized.  Thanks for the issue report.
duplicate #796
