### ISSUE TITLE
installed Sickrage and it doesn't open web browser unable to connect 

### ISSUE THREAD

**Issue by Sven137** [SickRage/sickrage-issues#817]
The web browser opens but cannot connect, webpage unavailable

Starting SiCKRAGE ...
23:54:13 INFO::MAIN::New API generated
Launching b2ro3:54:16 IwserN winFO::TORNADO::SiCKRAGE STARTED :: VERSION:[7.0.22] CONFIG:[C:\Udowsers\Paul\.sickrage\config.ini]
URL:[http://10.0.0.20:8081/]
ERROR:apscheduler.executors.default:Job "SHOWUPDATER (trigger: interval[1:00:00], next run at: 2016-02-10 00:54:16 SAST)" raised an exception
Traceback (most recent call last):
  File "C:\Users\Paul\AppData\Roaming\Python\Python27\site-packages\apscheduler\executors\base.py", line 112, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "C:\Users\Paul\Desktop\New folder\sickrage\core\updaters\show_updater.py", line 44, in run
    update_datetime = datetime.datetime.now()
AttributeError: type object 'datetime.datetime' has no attribute 'datetime'
00:04:16 INFO::NAMECACHE::Checking for SiCKRAGE scene exception updates for theTVDB
00:04:17 INFO::NAMECACHE::Checking for XEM scene exception updates for theTVDB
00:04:19 INFO::NAMECACHE::Checking for scene exception updates for AniDB

any help would be appreciated

Python 2.7
​Windows 10

**Comment by SickRage2** [comment]
Thanks for the issue report! Before a real human comes by, please make sure your report has all the below criteria checked

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [ ] Post debug logs, either inline (for smaller logs) or using gist)

Please make sure you also read [how to create an issue](https://github.com/SickRage/sickrage-issues/blob/master/README.md) and followed all of the steps. 

The title should describe your issue. Having "SR not working" or "I get this bug" for 100 issues, isn't really helpful. We will close issues if there isn't enough information.

Sometimes the devs may seem like grunts and respond with short answers. This isn't (always) because the dev hates you, but because he's on mobile or busy fixing bugs. If something isn't clear, please let us know, and this bot may get updated to automatically answer you.

Thanks!

**Comment by duramato** [comment]
Include basic information: Branch/Commit, OS, What you did, What happened, What you expected

**Comment by Sven137** [comment]
Its fixed .. put it in the root
