### ISSUE TITLE
No IMDB module error + cant add a new series

### ISSUE THREAD

**Issue by vanticar** [SickRage/sickrage-issues#819]
Hi again sorry to ask but been having quite a few issues of late, mainly loading and the only provider that seems to work is kickass now (rarbg and showRSS do not yet were my preferred). As kickass works not really been an issue until I now want to add a new series. Also news and changelog option from menu give the error 'The was a problem connecting to github, please refresh and try again' - you may want to change 'the' to 'there' lol

### This is my error log:-

2016-02-10 07:56:34 Error loading TMDb info: list index out of range
2016-02-10 07:56:34 Error loading IMDb info: No module named imdb
2016-02-10 07:54:15 Error trying to add show: 'NoneType' object has no attribute 'location'

### This is my log entries:-

2016-02-10 07:56:34 ERROR::SHOWQUEUE-UPDATE::Error loading IMDb info: No module named imdb

IndexError: list index out of range

    self.tmdbid = tmdbsimple.Search().tv(query=self.name)['results'][0]['id']

  File "C:\SickRage\sickrage\core\tv\show\__init__.py", line 988, in loadTMDbInfo

    self.show.loadTMDbInfo()

  File "C:\SickRage\sickrage\core\queues\show.py", line 603, in run

Traceback (most recent call last):

2016-02-10 07:56:34 ERROR::SHOWQUEUE-UPDATE::Error loading TMDb info: list index out of range

2016-02-10 07:54:15 ERROR::SHOWQUEUE-ADD::Error trying to add show: 'NoneType' object has no attribute 'location'

2016-02-10 07:54:14 INFO::SHOWQUEUE-ADD::295685: Unable to find the show in the database
2016-02-10 07:54:13 INFO::SHOWQUEUE-ADD::theTVDB: {u'useZip': True, u'apikey': u'F9C450E78D99172E', 'cache': u'C:\\SickRage\\cache\\indexers\\theTVDB', u'language': u'en', u'apitoken': u''}
2016-02-10 07:54:13 INFO::SHOWQUEUE-ADD::Starting to add show C:\-=NEW=-\Lucifer

### Here is my version info

Configuration
SR Version:	BRANCH: (master) / COMMIT: (19c425a5b858e326ae671b8fdfc330d7c9b25e6e) 
SR Type:	git 
SR User:	Hal
SR Locale:	('en_GB', 'cp1252')
SR Config:	C:\SickRage\config.ini
SR Database:	C:\SickRage\sickrage.db
SR Cache Dir:	C:\SickRage\cache
SR Log Dir:	C:\SickRage\Logs
SR Arguments:	[]
Python Version:	2.7.9 (default, Dec 10 2014, 12:28:03) [MSC v.1500 64 bit (AMD64)]

thanks in advance! hope you can help and as always i appreciate all you do

**Comment by SickRage2** [comment]
Thanks for the issue report! Before a real human comes by, please make sure your report has all the below criteria checked

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [ ] Post debug logs, either inline (for smaller logs) or using gist)

Please make sure you also read [how to create an issue](https://github.com/SickRage/sickrage-issues/blob/master/README.md) and followed all of the steps. 

The title should describe your issue. Having "SR not working" or "I get this bug" for 100 issues, isn't really helpful. We will close issues if there isn't enough information.

Sometimes the devs may seem like grunts and respond with short answers. This isn't (always) because the dev hates you, but because he's on mobile or busy fixing bugs. If something isn't clear, please let us know, and this bot may get updated to automatically answer you.

Thanks!

**Comment by neoatomic** [comment]
@vanticar You are still on the old repository. Thats why stuff isn't working...

Remove the old installation and do a fresh install with the windows installer. That will get you up and running again without errors and working indexers.

https://github.com/VinceVal/SickRageInstaller/releases/tag/v0.5
