### ISSUE TITLE
[APP SUBMITTED]: Old quality does not match new: 720p BluRay != 720p HDTV : [Commie] Ao Haru Ride - 01 [BD 720p AAC]

### ISSUE THREAD

**Issue by Riceak** [SickRage/sickrage-issues#840]
### INFO
Python Version: **2.7.11rc1 (v2.7.11rc1:82dd9545bd93, Nov 21 2015, 23:25:27) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-7-6.1.7601-SP1**
Locale: cp1252
Branch: **master**
Commit: SickRage/SickRage@4f3207fa6ab2db95f11a86bc7305ccef45523ecb
No Log available with ERRORS:
### ERROR
```
Thread-32 :: Failed doing webui callback: Traceback (most recent call last):
  File "C:\SickRage\sickbeard\webserve.py", line 283, in async_call
    result = function(**kwargs)
  File "C:\SickRage\sickbeard\webserve.py", line 2279, in processEpisode
    is_priority=argToBool(is_priority), delete_on=argToBool(delete_on), failed=argToBool(failed), proc_type=type
  File "C:\SickRage\sickbeard\processTV.py", line 229, in processDir
    process_media(path, [video], nzbName, process_method, force, is_priority, result)
  File "C:\SickRage\sickbeard\processTV.py", line 554, in process_media
    result.result = processor.process()
  File "C:\SickRage\sickbeard\postProcessor.py", line 942, in process
    (show, season, episodes, quality, version) = self._find_info()
  File "C:\SickRage\sickbeard\postProcessor.py", line 665, in _find_info
    cur_show, cur_season, cur_episodes, cur_quality, cur_version = cur_attempt()
  File "C:\SickRage\sickbeard\postProcessor.py", line 649, in <lambda>
    lambda: self._analyze_name(self.file_name),
  File "C:\SickRage\sickbeard\postProcessor.py", line 580, in _analyze_name
    parse_result = NameParser(True, tryIndexers=True).parse(name)
  File "C:\SickRage\sickbeard\name_parser\parser.py", line 423, in parse
    file_name_result = self._parse_string(base_file_name)
  File "C:\SickRage\sickbeard\name_parser\parser.py", line 212, in _parse_string
    bestResult.quality = common.Quality.nameQuality(name, bestResult.show.is_anime)
  File "C:\SickRage\sickbeard\common.py", line 279, in nameQuality
    quality = Quality.sceneQuality(name, anime)
  File "C:\SickRage\sickbeard\common.py", line 455, in sceneQuality
    assert old == result, 'Old quality does not match new: %s != %s : %s' % (Quality.qualityStrings[old], Quality.qualityStrings[result], name)
AssertionError: Old quality does not match new: 720p BluRay != 720p HDTV : [Commie] Ao Haru Ride - 01 [BD 720p AAC]
 [4f3207f]
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by SickRage2** [comment]
Thanks for the issue report! Before a real human comes by, please make sure your report has all the below criteria checked

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [ ] Post debug logs, either inline (for smaller logs) or using gist)

Please make sure you also read [how to create an issue](https://github.com/SickRage/sickrage-issues/blob/master/README.md) and followed all of the steps. 

The title should describe your issue. Having "SR not working" or "I get this bug" for 100 issues, isn't really helpful. We will close issues if there isn't enough information.

Sometimes the devs may seem like grunts and respond with short answers. This isn't (always) because the dev hates you, but because he's on mobile or busy fixing bugs. If something isn't clear, please let us know, and this bot may get updated to automatically answer you.

Thanks!

**Comment by labrys** [comment]
Duplicate. This is a validation method for a new quality system.
