### ISSUE TITLE
[APP SUBMITTED]: cannot concatenate 'str' and 'NoneType' objects

### ISSUE THREAD

**Issue by rcocchiararo** [SickRage/sickrage-issues#857]
### INFO
Python Version: **2.7.10 (default, May 23 2015, 09:40:32) [MSC v.1500 32 bit (Intel)]**
Operating System: **Windows-8-6.2.9200**
Locale: cp1252
Branch: ****
Commit: SickRage/SickRage@f568d1515557f854042511d7bfee3ae070c864bd
No Log available with ERRORS:
### ERROR
```
Thread-22 :: Failed doing webui callback: Traceback (most recent call last):
  File "C:\SickRage\SickRage\sickbeard\webserve.py", line 282, in async_call
    result = function(**kwargs)
  File "C:\SickRage\SickRage\sickbeard\webserve.py", line 3787, in index
    sr_version = updater.get_cur_version()
  File "C:\SickRage\SickRage\sickbeard\versionChecker.py", line 377, in get_cur_version
    return self._run_git(self._git_path, "describe --abbrev=0 " + self._cur_commit_hash)[0]
TypeError: cannot concatenate 'str' and 'NoneType' objects
 [f568d15]
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by SickRage2** [comment]
Thanks for the issue report! Before a real human comes by, please make sure your report has all the below criteria checked

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [ ] Post debug logs, either inline (for smaller logs) or using gist

Please make sure you also read [how to create an issue](https://github.com/SickRage/sickrage-issues/blob/master/README.md) and followed all of the steps. 

The title should describe your issue. Having "SR not working" or "I get this bug" for 100 issues, isn't really helpful. We will close issues if there isn't enough information.

Sometimes the devs may seem like grunts and respond with short answers. This isn't (always) because the dev hates you, but because he's on mobile or busy fixing bugs. If something isn't clear, please let us know, and this bot may get updated to automatically answer you.

Thanks!

**Comment by neoatomic** [comment]
@rcocchiararo You are missing the branch and commit hash. 
See : https://github.com/SickRage/sickrage-issues/issues/720#issuecomment-177496926
