### ISSUE TITLE
Delete TV from list

### ISSUE THREAD

**Issue by alienx2** [SickRage/sickrage-issues#874]
**Branch:** Master
**Commit hash:** can't find version or commit in sickrage. it did updated yesterday.
**OS:** Linux-2.6.22.19-mips-with-glibc2.0
**python version:**  2.7.11 (default, Jan 9 2016, 19:23:54) [GCC 4.8.5]
**What you did:** was delete tv show from list.
**What happened:** It said: "Oops You have reached this page by accident, please check the url." then didnt remove tv show from list even also didnt delete files.

**ERROR LOG:**
```
2016-02-13 05:50:03 Thread-33 :: Failed doing webui callback: Traceback (most recent call last):
  File "/tmp/mnt/TOSHIBA/entware/etc/sickrage/sickbeard/webserve.py", line 283, in async_call
    result = function(**kwargs)
  File "/tmp/mnt/TOSHIBA/entware/etc/sickrage/sickbeard/webserve.py", line 1599, in deleteShow
    error, show = Show.delete(show, full)
  File "/tmp/mnt/TOSHIBA/entware/etc/sickrage/sickrage/show/Show.py", line 51, in delete
    sickbeard.showQueueScheduler.action.removeShow(show, bool(remove_files))
  File "/tmp/mnt/TOSHIBA/entware/etc/sickrage/sickbeard/show_queue.py", line 174, in removeShow
    if all([item, item.show, item != self.currentItem, show.indexerid == item.show.indexerid]):
AttributeError: 'NoneType' object has no attribute 'indexerid'
 [e44f3ea]
2016-02-13 05:48:33 Thread-53 :: Failed doing webui callback: Traceback (most recent call last):
  File "/tmp/mnt/TOSHIBA/entware/etc/sickrage/sickbeard/webserve.py", line 283, in async_call
    result = function(**kwargs)
  File "/tmp/mnt/TOSHIBA/entware/etc/sickrage/sickbeard/webserve.py", line 1599, in deleteShow
    error, show = Show.delete(show, full)
  File "/tmp/mnt/TOSHIBA/entware/etc/sickrage/sickrage/show/Show.py", line 51, in delete
    sickbeard.showQueueScheduler.action.removeShow(show, bool(remove_files))
  File "/tmp/mnt/TOSHIBA/entware/etc/sickrage/sickbeard/show_queue.py", line 174, in removeShow
    if all([item, item.show, item != self.currentItem, show.indexerid == item.show.indexerid]):
AttributeError: 'NoneType' object has no attribute 'indexerid'
 [e44f3ea]
```

**Comment by SickRage2** [comment]
Thanks for the issue report! Before a real human comes by, please make sure your report has all the below criteria checked

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [ ] Post debug logs, either inline (for smaller logs) or using gist

Please make sure you also read [how to create an issue](https://github.com/SickRage/sickrage-issues/blob/master/README.md) and followed all of the steps. 

The title should describe your issue. Having "SR not working" or "I get this bug" for 100 issues, isn't really helpful. We will close issues if there isn't enough information.

Sometimes the devs may seem like grunts and respond with short answers. This isn't (always) because the dev hates you, but because he's on mobile or busy fixing bugs. If something isn't clear, please let us know, and this bot may get updated to automatically answer you.

Thanks!
