### ISSUE TITLE
[APP SUBMITTED]: invalid literal for int() with base 10: '5.8'

### ISSUE THREAD

**Issue by SirApokalypse** [SickRage/sickrage-issues#892]
### INFO
Python Version: **2.7.11 (default, Dec 17 2015, 15:58:38) [GCC 4.7.3 20130102 (prerelease)]**
Operating System: **Linux-3.10.35-x86_64-with-glibc2.2.5**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@e44f3ea56ed7150bbc18e3312f0eb1442ef724bf
No Log available with ERRORS:
### ERROR
```
Thread-30 :: Failed doing webui callback: Traceback (most recent call last):
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/webserve.py", line 283, in async_call
    result = function(**kwargs)
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/webserve.py", line 4128, in saveSearch
    sickbeard.save_config()
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/__init__.py", line 1637, in save_config
    new_config['General']['log_size'] = int(LOG_SIZE)
ValueError: invalid literal for int() with base 10: '5.8'
 [e44f3ea]
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by SickRage2** [comment]
Thanks for the issue report! Before a real human comes by, please make sure your report has all the below criteria checked

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [ ] Post debug logs, either inline (for smaller logs) or using gist

Please make sure you also read [how to create an issue](https://github.com/SickRage/sickrage-issues/blob/master/README.md) and followed all of the steps. 

The title should describe your issue. Having "SR not working" or "I get this bug" for 100 issues, isn't really helpful. We will close issues if there isn't enough information.

Sometimes the devs may seem like grunts and respond with short answers. This isn't (always) because the dev hates you, but because he's on mobile or busy fixing bugs. If something isn't clear, please let us know, and this bot may get updated to automatically answer you.

Thanks!

**Comment by SirApokalypse** [comment]
### INFO
Python Version: **2.7.11 (default, Dec 17 2015, 15:58:38) [GCC 4.7.3 20130102 (prerelease)]**
Operating System: **Linux-3.10.35-x86_64-with-glibc2.2.5**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@e44f3ea56ed7150bbc18e3312f0eb1442ef724bf
No Log available with ERRORS:
### ERROR
```
Thread-61 :: Failed doing webui callback: Traceback (most recent call last):
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/webserve.py", line 283, in async_call
    result = function(**kwargs)
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/webserve.py", line 4128, in saveSearch
    sickbeard.save_config()
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/__init__.py", line 1637, in save_config
    new_config['General']['log_size'] = int(LOG_SIZE)
ValueError: invalid literal for int() with base 10: '5.8'
 [e44f3ea]
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by SirApokalypse** [comment]
### INFO
Python Version: **2.7.11 (default, Dec 17 2015, 15:58:38) [GCC 4.7.3 20130102 (prerelease)]**
Operating System: **Linux-3.10.35-x86_64-with-glibc2.2.5**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@e44f3ea56ed7150bbc18e3312f0eb1442ef724bf
No Log available with ERRORS:
### ERROR
```
Thread-25 :: Failed doing webui callback: Traceback (most recent call last):
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/webserve.py", line 283, in async_call
    result = function(**kwargs)
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/webserve.py", line 3959, in saveGeneral
    sickbeard.save_config()
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/__init__.py", line 1637, in save_config
    new_config['General']['log_size'] = int(LOG_SIZE)
ValueError: invalid literal for int() with base 10: '5.8'
 [e44f3ea]
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by SirApokalypse** [comment]
### INFO
Python Version: **2.7.11 (default, Dec 17 2015, 15:58:38) [GCC 4.7.3 20130102 (prerelease)]**
Operating System: **Linux-3.10.35-x86_64-with-glibc2.2.5**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@e44f3ea56ed7150bbc18e3312f0eb1442ef724bf
No Log available with ERRORS:
### ERROR
```
Thread-34 :: Failed doing webui callback: Traceback (most recent call last):
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/webserve.py", line 283, in async_call
    result = function(**kwargs)
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/webserve.py", line 3959, in saveGeneral
    sickbeard.save_config()
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/__init__.py", line 1637, in save_config
    new_config['General']['log_size'] = int(LOG_SIZE)
ValueError: invalid literal for int() with base 10: '5.8'
 [e44f3ea]
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by fernandog** [comment]
@miigotu dont allow float in log size in UI ?
