### ISSUE TITLE
[APP SUBMITTED]: 'NoneType' object has no attribute 'request'

### ISSUE THREAD

**Issue by duramato** [SickRage/sickrage-issues#902]
### INFO
Python Version: **2.7.6 (default, Jun 22 2015, 18:00:18) [GCC 4.8.2]**
Operating System: **Linux-3.19.0-49-generic-i686-with-Ubuntu-14.04-trusty**
Locale: None
Branch: **develop**
Commit: SickRage/SickRage@27006feec78c14b2b3dce50baa093421b26899af
No Log available with ERRORS:
### ERROR
```
Thread-16 :: Failed doing webui callback: Traceback (most recent call last):
  File "/home/home/SickRage/sickbeard/webserve.py", line 283, in async_call
    result = function(**kwargs)
  File "/home/home/SickRage/sickbeard/webserve.py", line 4423, in getNewznabCategories
    success, tv_categories, error = tempProvider.get_newznab_categories()
  File "/home/home/SickRage/sickbeard/providers/newznab.py", line 140, in get_newznab_categories
    data = self.get_url(url)
  File "/home/home/SickRage/sickrage/providers/GenericProvider.py", line 350, in get_url
    logger.log(u'URL: {url}'.format(url=resp.request.url), logger.DEBUG)
AttributeError: 'NoneType' object has no attribute 'request'
 [27006fe]
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by SickRage2** [comment]
Thanks for the issue report! Before a real human comes by, please make sure your report has all the below criteria checked

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [ ] Post debug logs, either inline (for smaller logs) or using gist

Please make sure you also read [how to create an issue](https://github.com/SickRage/sickrage-issues/blob/master/README.md) and followed all of the steps. 

The title should describe your issue. Having "SR not working" or "I get this bug" for 100 issues, isn't really helpful. We will close issues if there isn't enough information.

Sometimes the devs may seem like grunts and respond with short answers. This isn't (always) because the dev hates you, but because he's on mobile or busy fixing bugs. If something isn't clear, please let us know, and this bot may get updated to automatically answer you.

Thanks!

**Comment by duramato** [comment]
### INFO
Python Version: **2.7.6 (default, Jun 22 2015, 18:00:18) [GCC 4.8.2]**
Operating System: **Linux-3.19.0-49-generic-i686-with-Ubuntu-14.04-trusty**
Locale: None
Branch: **develop**
Commit: SickRage/SickRage@27006feec78c14b2b3dce50baa093421b26899af
No Log available with ERRORS:
### ERROR
```
Thread-40 :: Failed doing webui callback: Traceback (most recent call last):
  File "/home/home/SickRage/sickbeard/webserve.py", line 283, in async_call
    result = function(**kwargs)
  File "/home/home/SickRage/sickbeard/webserve.py", line 4423, in getNewznabCategories
    success, tv_categories, error = tempProvider.get_newznab_categories()
  File "/home/home/SickRage/sickbeard/providers/newznab.py", line 140, in get_newznab_categories
    data = self.get_url(url)
  File "/home/home/SickRage/sickrage/providers/GenericProvider.py", line 350, in get_url
    logger.log(u'URL: {url}'.format(url=resp.request.url), logger.DEBUG)
AttributeError: 'NoneType' object has no attribute 'request'
 [27006fe]
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by duramato** [comment]
### INFO
Python Version: **2.7.6 (default, Jun 22 2015, 18:00:18) [GCC 4.8.2]**
Operating System: **Linux-3.19.0-49-generic-i686-with-Ubuntu-14.04-trusty**
Locale: None
Branch: **develop**
Commit: SickRage/SickRage@27006feec78c14b2b3dce50baa093421b26899af
No Log available with ERRORS:
### ERROR
```
Thread-26 :: Failed doing webui callback: Traceback (most recent call last):
  File "/home/home/SickRage/sickbeard/webserve.py", line 283, in async_call
    result = function(**kwargs)
  File "/home/home/SickRage/sickbeard/webserve.py", line 4423, in getNewznabCategories
    success, tv_categories, error = tempProvider.get_newznab_categories()
  File "/home/home/SickRage/sickbeard/providers/newznab.py", line 140, in get_newznab_categories
    data = self.get_url(url)
  File "/home/home/SickRage/sickrage/providers/GenericProvider.py", line 350, in get_url
    logger.log(u'URL: {url}'.format(url=resp.request.url), logger.DEBUG)
AttributeError: 'NoneType' object has no attribute 'request'
 [27006fe]
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by duramato** [comment]
### INFO
Python Version: **2.7.6 (default, Jun 22 2015, 18:00:18) [GCC 4.8.2]**
Operating System: **Linux-3.19.0-49-generic-i686-with-Ubuntu-14.04-trusty**
Locale: None
Branch: **develop**
Commit: SickRage/SickRage@27006feec78c14b2b3dce50baa093421b26899af
No Log available with ERRORS:
### ERROR
```
Thread-15 :: Failed doing webui callback: Traceback (most recent call last):
  File "/home/home/SickRage/sickbeard/webserve.py", line 283, in async_call
    result = function(**kwargs)
  File "/home/home/SickRage/sickbeard/webserve.py", line 4423, in getNewznabCategories
    success, tv_categories, error = tempProvider.get_newznab_categories()
  File "/home/home/SickRage/sickbeard/providers/newznab.py", line 140, in get_newznab_categories
    data = self.get_url(url)
  File "/home/home/SickRage/sickrage/providers/GenericProvider.py", line 350, in get_url
    logger.log(u'URL: {url}'.format(url=resp.request.url), logger.DEBUG)
AttributeError: 'NoneType' object has no attribute 'request'
 [27006fe]
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by duramato** [comment]
### INFO
Python Version: **2.7.6 (default, Jun 22 2015, 18:00:18) [GCC 4.8.2]**
Operating System: **Linux-3.19.0-49-generic-i686-with-Ubuntu-14.04-trusty**
Locale: None
Branch: **develop**
Commit: SickRage/SickRage@27006feec78c14b2b3dce50baa093421b26899af
Link to Log: https://gist.github.com/9538892e4c409c71a95c
### ERROR
```
SEARCHQUEUE-DAILY-SEARCH :: [BitSnoop] :: Failed parsing provider. Traceback: 'Traceback (most recent call last):\n  File "/home/home/SickRage/sickbeard/providers/bitsnoop.py", line 70, in search\n    data = self.get_url(search_url)\n  File "/home/home/SickRage/sickrage/providers/GenericProvider.py", line 350, in get_url\n    logger.log(u\'URL: {url}\'.format(url=resp.request.url), logger.DEBUG)\nAttributeError: \'NoneType\' object has no attribute \'request\'\n' [27006fe]
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators
