### ISSUE TITLE
Reverse Proxy - Text only GUI

### ISSUE THREAD

**Issue by mattpulpfree** [SickRage/sickrage-issues#998]
So i'm trying to get reverse proxy working with sickrage and IIS, i'm able to get it to load by navigating to mydomain.com/sickrage but it's only text, no images. I found https://github.com/SickRage/sickrage-issues/issues/742 and followed all the steps outlined and nothing worked. Opened up the developer console and it's not able to access SOME javascripts and css files it seems.

IIS Settings
-Virtual directory pointing to C:\sickrage\GUI\slick labeled home
-URL rewrite pointing to 127.0.0.1:8081/home

![rvprxy](https://cloud.githubusercontent.com/assets/9369715/13096476/5587484e-d4df-11e5-936d-8a45b2d6ab4b.PNG)

SickRage Configuration:
 SickRage Version:	Branch: master
Commit: 1b0a6a5a6cc665fcdc4cf69f5b67d4a07add1522
Version: 2016.02.16-1
 Python Version:	2.7.11 (v2.7.11:6d1b6a68f775, Dec 5 2015, 20:40:30) [MSC v.1500 64 bit (AMD64)]
 SSL Version:	OpenSSL 1.0.2d 9 Jul 2015
 OS:	Windows-10-10.0.10586
 Locale:	en_US.cp1252

https://gist.github.com/mattpulpfree/9fcaa6dbe18d412b8df6

**Comment by SickRage2** [comment]
Thanks for the issue report! Before a real human comes by, please make sure your report has all the below criteria checked

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [ ] Post debug logs, either inline (for smaller logs) or using gist

Please make sure you also read [how to create an issue](https://github.com/SickRage/sickrage-issues/blob/master/README.md) and followed all of the steps. 

The title should describe your issue. Having "SR not working" or "I get this bug" for 100 issues, isn't really helpful. We will close issues if there isn't enough information.

Sometimes the devs may seem like grunts and respond with short answers. This isn't (always) because the dev hates you, but because he's on mobile or busy fixing bugs. If something isn't clear, please let us know, and this bot may get updated to automatically answer you.

Thanks!

**Comment by OmgImAlexis** [comment]
You need to point the rewrite to `127.0.0.1:8081` without the `/home`.

**Comment by mattpulpfree** [comment]
That gives me a 404 not found page, interesting enough it changes from mydomain.com/sickrage to mydomain.com/schedule (which is my default starting page now). but when i put in 127.0.0.1:8081/schedule for the rewrite, it brings up just text.

Just so we're clear, I'm trying to reverse proxy 127.0.0.1:8081 -> mydomain.com/sickrage .

**Comment by OmgImAlexis** [comment]
You'll need to set `sickrage` as a webroot inside of SickRage as it expects it to be at the root of the domain. After that it'll work fine.

Just shutdown SickRage, edit the config.ini and set `web_root = ""`.

**Comment by mattpulpfree** [comment]
Alright did that, made sure the rewrite was 127.0.0.1:8081 and it gave me this

Traceback (most recent call last):
  File "C:\SickRage\lib\tornado\web.py", line 1390, in _execute
    result = self.prepare()
  File "C:\SickRage\lib\tornado\web.py", line 2103, in prepare
    raise HTTPError(self._status_code)
HTTPError: HTTP 404: Not Found

but if i change it to 127.0.0.1:8081/sickrage i get the text only gui.

**Comment by OmgImAlexis** [comment]
So you can load `http://127.0.0.1:8081/sickrage`? Have you also tried just opening one of those links to see if it's a caching issue?

**Comment by mattpulpfree** [comment]
http://127.0.0.1:8081/sickrage loads text only with those failed to load errors in the developer console.

by opening one of those links you mean copying the url for the files into chrome? It just brings me to a text only page but with "Oops You have reached this page by accident, please check the url." on it.

**Comment by OmgImAlexis** [comment]
If `http://127.0.0.1:8081/sickrage` isn't working then it's either a caching issue or something else. That's nothing todo with the proxy.
Did you also set `handle_reverse_proxy = 1`?

http://www.htpcguides.com/configure-sickrage-reverse-proxy-nginx/

**Comment by mattpulpfree** [comment]
Sorry I stated that wrong! I meant mydomain.com/sickrage
127.0.0.1:8081/sickrage works properly still. and handle_reverse_proxy = 1 is set.

**Comment by mattpulpfree** [comment]
I'm thinking it has something to do with the re-write in IIS, when I go into to look at the developers console in chrome, it's saying it can't find certain files and then when I browse to them in chrome it gives me a sickrage - 404 page. but when using 127.0.0.1 or localhost, it's the same address only replacing mydomain.com with 127.0.0.1 or local host.

so. Browsing to http://127.0.0.1:8081/sickrage/images/imdb.png gives me the imdb.png no problem, but browsing to http://mydomain.com/sickrage/images/imdb.png gives me the "oops" 404 sickrage page.


Another odd thing I noticed in the developer console when trying to get mydomain.com/sickrage to work is that some image/png's are loading fine while about 6 aren't and it's showing them trying to read as text/html instead of image files like the rest of them.
![img files](https://cloud.githubusercontent.com/assets/9369715/13115475/8e0ffff2-d55d-11e5-9322-3bd1fc2832ad.PNG)
so it's loading the tv shows banners and stuff just fine.


it's also showing that none of the css or js files are being found / loaded it seems?

**Comment by mattpulpfree** [comment]
I was able to find a guide on how to get nginx (thanks for that link to htpcguides.com!) setup for reverse proxy on windows. Still unsure as to why IIS doesn't like it but at least I got it working now!

**Comment by OmgImAlexis** [comment]
Sounds like it's caching or rewriting issues with IIS.

I'm closing this now and marking as `wontfix`.

**Comment by mattpulpfree** [comment]
Thanks for all the help though!
